;;; Native link recognition from admitted POO rules, without language policy.
(import (only-in ./line-structure-objects
                 text-line? text-line-token text-line-inline-link
                 inline-link-opening inline-link-separator inline-link-closing
                 inline-link-node inline-link-target-token
                 inline-link-description-token inline-link-trivia-token)
        (only-in ./source-pattern-funs source-pattern-at? source-pattern-end))
(import (only-in ./source-event-scope-funs source-event-name))
(export source-inline-link-initial source-inline-link-scan-forms source-inline-link-open-condition)
(def (admit-link rule)
  (unless (and (text-line? rule) (text-line-inline-link rule))
    (error "native link requires a declared inline-link rule" rule))
  (text-line-inline-link rule))
(def (source-inline-link-initial rule scope)
  (admit-link rule)
  (map (lambda (binding) (list (source-event-name scope (car binding)) (cadr binding)))
       '((inline-open #f) (inline-has-separator #f) (inline-failed #f)
         (inline-open-at 0) (inline-target-start 0) (inline-separator-at 0))))
(def (source-inline-link-open-condition scope)
  `(state ,(source-event-name scope 'inline-open)))
(def (source-inline-link-scan-forms rule scope
          description-helper: (helper #f) parameters: (parameters '())
          description-node: (node #f) literal-description?: (literal? #f)
          invalid-target: (invalid-target 'recover-span)
          index: (index-name #f) cursor: (cursor-name #f))
  (source-inline-link-initial rule scope)
  (def (name role) (source-event-name scope role))
  (let* ((link (admit-link rule))
         (index `(line-index ,index-name)) (cursor `(state-offset ,cursor-name))
         (opening (inline-link-opening link)) (separator (inline-link-separator link))
         (closing (inline-link-closing link)) (trivia (inline-link-trivia-token link))
         (target (inline-link-target-token link))
         (description (inline-link-description-token link))
         (separator-end (source-pattern-end `(state-offset ,(name 'inline-separator-at)) separator))
         (close-end (source-pattern-end index closing)))
    (unless (and (symbol? index-name) (symbol? cursor-name) (boolean? literal?)
                 (memq invalid-target '(recover-span recover-region))
                 (or (not node) (symbol? node)) (or (not helper) (symbol? helper))
                 (list? parameters) (andmap symbol? parameters)
                 (let loop ((rest parameters) (seen '()))
                   (or (null? rest)
                       (and (not (memq (car rest) seen))
                            (loop (cdr rest) (cons (car rest) seen)))))
                 (or helper (null? parameters)))
      (error "invalid native inline description binding" helper parameters node))
    (def description-forms
      (let (content
            (if (or literal? (not helper))
              `(token ,description ,separator-end ,index)
              `(call-source-helper ,helper ,separator-end ,index
                ,@(if (null? parameters) '()
                    (list (map (lambda (name) `(state ,name)) parameters))))))
        (if (and node (not literal?))
          `((start-node ,node) ,content (finish-node)) (list content))))
    (def events
      `((token ,(text-line-token rule) ,cursor (state-offset ,(name 'inline-open-at)))
        (start-node ,(inline-link-node link))
        (token ,trivia (state-offset ,(name 'inline-open-at)) (state-offset ,(name 'inline-target-start)))
        (if (state ,(name 'inline-has-separator))
            ((token ,target (state-offset ,(name 'inline-target-start)) (state-offset ,(name 'inline-separator-at)))
             (token ,trivia (state-offset ,(name 'inline-separator-at)) ,separator-end)
             ,@description-forms)
            ((token ,target (state-offset ,(name 'inline-target-start)) ,index)))
        (token ,trivia ,index ,close-end) (finish-node)
        (set-uint ,cursor-name (offset ,close-end)) (set-bool ,(name 'inline-open) (bool #f))))
    (def (commit until)
      `((if (offset-less? (state-offset ,(name 'inline-target-start)) ,until)
            ,events ,(if (eq? invalid-target 'recover-region)
                       `((set-bool ,(name 'inline-failed) (bool #t)))
                       `((set-bool ,(name 'inline-open) (bool #f)))))))
    `((if (offset-less? ,index ,cursor) ()
          ((if (and (not (state ,(name 'inline-failed))) (not (state ,(name 'inline-open))))
               ((if ,(source-pattern-at? index opening)
                    ((set-bool ,(name 'inline-open) (bool #t))
                     (set-bool ,(name 'inline-has-separator) (bool #f))
                     (set-uint ,(name 'inline-open-at) (offset ,index))
                     (set-uint ,(name 'inline-target-start) (offset ,(source-pattern-end index opening)))) ()))
               ((if (offset-less? ,index (state-offset ,(name 'inline-target-start))) ()
                    ((if (and (state ,(name 'inline-open)) ,(source-pattern-at? index closing))
                    ((if (state ,(name 'inline-has-separator))
                         ,(commit `(state-offset ,(name 'inline-separator-at))) ,(commit index)))
                    ((if (and (state ,(name 'inline-open)) (not (state ,(name 'inline-has-separator)))
                              ,(source-pattern-at? index separator))
                         ((set-bool ,(name 'inline-has-separator) (bool #t))
                          (set-uint ,(name 'inline-separator-at) (offset ,index))) ()))))))))))))
