;;; Native link recognition from admitted POO rules, without language policy.
(import (only-in ./line-structure-objects
                 text-line? text-line-token text-line-inline-link
                 inline-link-opening inline-link-separator inline-link-closing
                 inline-link-node inline-link-target-token
                 inline-link-description-token inline-link-trivia-token)
        (only-in ./source-pattern-funs source-pattern-at? source-pattern-end))
(export source-inline-link-initial source-inline-link-scan-forms)
(def (admit-link rule)
  (unless (and (text-line? rule) (text-line-inline-link rule))
    (error "native link requires a declared inline-link rule" rule))
  (text-line-inline-link rule))
(def (source-inline-link-initial rule)
  (admit-link rule)
  '((inline-open #f) (inline-has-separator #f) (inline-failed #f)
    (inline-open-at 0) (inline-target-start 0) (inline-separator-at 0)))
(def (source-inline-link-scan-forms rule
          description-helper: (helper #f) parameters: (parameters '())
          description-node: (node #f) literal-description?: (literal? #f)
          invalid-target: (invalid-target 'recover-span)
          index: (index-name 'inline-byte-index) cursor: (cursor-name 'inline-cursor))
  (let* ((link (admit-link rule))
         (index `(line-index ,index-name)) (cursor `(state-offset ,cursor-name))
         (opening (inline-link-opening link)) (separator (inline-link-separator link))
         (closing (inline-link-closing link)) (trivia (inline-link-trivia-token link))
         (target (inline-link-target-token link))
         (description (inline-link-description-token link))
         (separator-end (source-pattern-end '(state-offset inline-separator-at) separator))
         (close-end (source-pattern-end index closing)))
    (unless (and (symbol? index-name) (symbol? cursor-name) (boolean? literal?)
                 (memq invalid-target '(recover-span recover-region))
                 (or (not node) (symbol? node)) (or (not helper) (symbol? helper))
                 (list? parameters) (andmap symbol? parameters)
                 (let loop ((rest parameters) (seen '()))
                   (or (null? rest)
                       (and (not (memq (car rest) seen))
                            (loop (cdr rest) (cons (car rest) seen)))))
                 (or helper (null? parameters)))
      (error "invalid native inline description binding" helper parameters node))
    (def description-forms
      (let (content
            (if (or literal? (not helper))
              `(token ,description ,separator-end ,index)
              `(call-source-helper ,helper ,separator-end ,index
                ,@(if (null? parameters) '()
                    (list (map (lambda (name) `(state ,name)) parameters))))))
        (if (and node (not literal?))
          `((start-node ,node) ,content (finish-node)) (list content))))
    (def events
      `((token ,(text-line-token rule) ,cursor (state-offset inline-open-at))
        (start-node ,(inline-link-node link))
        (token ,trivia (state-offset inline-open-at) (state-offset inline-target-start))
        (if (state inline-has-separator)
            ((token ,target (state-offset inline-target-start) (state-offset inline-separator-at))
             (token ,trivia (state-offset inline-separator-at) ,separator-end)
             ,@description-forms)
            ((token ,target (state-offset inline-target-start) ,index)))
        (token ,trivia ,index ,close-end) (finish-node)
        (set-uint ,cursor-name (offset ,close-end)) (set-bool inline-open (bool #f))))
    (def (commit until)
      `((if (offset-less? (state-offset inline-target-start) ,until)
            ,events ,(if (eq? invalid-target 'recover-region)
                       '((set-bool inline-failed (bool #t)))
                       '((set-bool inline-open (bool #f)))))))
    `((if (offset-less? ,index ,cursor) ()
          ((if (and (not (state inline-failed)) (not (state inline-open)))
               ((if ,(source-pattern-at? index opening)
                    ((set-bool inline-open (bool #t))
                     (set-bool inline-has-separator (bool #f))
                     (set-uint inline-open-at (offset ,index))
                     (set-uint inline-target-start (offset ,(source-pattern-end index opening)))) ()))
               ((if (offset-less? ,index (state-offset inline-target-start)) ()
                    ((if (and (state inline-open) ,(source-pattern-at? index closing))
                    ((if (state inline-has-separator)
                         ,(commit '(state-offset inline-separator-at)) ,(commit index)))
                    ((if (and (state inline-open) (not (state inline-has-separator))
                              ,(source-pattern-at? index separator))
                         ((set-bool inline-has-separator (bool #t))
                          (set-uint inline-separator-at (offset ,index))) ()))))))))))))
