;;; Native list ownership from admitted POO declarations and explicit scopes.
(import (only-in ./line-structure-objects
                 list-line? list-line-unordered-markers list-line-ordered
                 list-line-tab-width list-line-list-node list-line-item-node
                 list-line-bullet-token list-line-trivia-token)
        (only-in ./source-event-scope-funs source-event-name)
        (only-in ./line-event-funs source-paragraph-initial
                 source-paragraph-span-forms source-paragraph-close-form))
(export source-list-initial source-list-scan-form source-list-present-condition
        source-list-ordered-condition source-list-active-condition
        source-list-first-blank-condition source-list-continuation-condition
        source-list-content-offset source-list-item-open-forms
        source-list-paragraph-span-forms source-list-paragraph-close-form
        source-list-close-forms source-list-first-blank-forms source-list-reset-blank-form)
(def (admit-list rule)
  (unless (list-line? rule) (error "unadmitted native list rule" rule))
  rule)
(def (source-list-initial rule scope text)
  (admit-list rule)
  (append
    (map (lambda (binding) (list (source-event-name scope (car binding)) (cadr binding)))
         '((list-frames (uint-stack)) (list-present #f) (list-ordered #f)
           (list-column 0) (list-bullet-start 0) (list-bullet-end 0)
           (list-content-start 0) (list-blank-count 0)))
    (source-paragraph-initial text scope pending-blank?: #f)))
(def (source-list-scan-form rule scope)
  (admit-list rule)
  `(scan-list-marker ,(list-line-unordered-markers rule) ,(list-line-ordered rule)
                     ,(list-line-tab-width rule)
                     ,@(map (lambda (role) (source-event-name scope role))
                            '(list-present list-column list-ordered
                              list-bullet-start list-bullet-end list-content-start))))
(def (source-list-present-condition scope)
  `(state ,(source-event-name scope 'list-present)))
(def (source-list-ordered-condition scope)
  `(state ,(source-event-name scope 'list-ordered)))
(def (source-list-active-condition scope)
  `(stack-nonempty? ,(source-event-name scope 'list-frames)))
(def (source-list-first-blank-condition scope)
  `(uint-equal? (state ,(source-event-name scope 'list-blank-count)) (uint 0)))
(def (source-list-continuation-condition rule scope)
  (admit-list rule)
  `(uint-greater? (line-indent-column ,(list-line-tab-width rule))
                  (uint-divide (stack-top ,(source-event-name scope 'list-frames)) (uint 2))))
(def (source-list-content-offset scope)
  `(state-offset ,(source-event-name scope 'list-content-start)))
(def (source-list-reset-blank-form scope)
  `(set-uint ,(source-event-name scope 'list-blank-count) (uint 0)))
(def (source-list-paragraph-span-forms text scope from until)
  (source-paragraph-span-forms text scope from until))
(def (source-list-paragraph-close-form text scope (helper #f) (parameters '()) (reset? #t))
  (source-paragraph-close-form text scope helper parameters reset? pending-blank?: #f))
(def (source-list-close-forms text scope (helper #f) (parameters '()) (reset? #t))
  `(,(source-list-paragraph-close-form text scope helper parameters reset?)
    (close-all-frames ,(source-event-name scope 'list-frames) 2)
    ,@(if reset? (list (source-list-reset-blank-form scope)) '())))
(def (source-list-first-blank-forms rule text scope (helper #f) (parameters '()))
  (admit-list rule)
  `(,(source-list-paragraph-close-form text scope helper parameters)
    (token ,(list-line-trivia-token rule) start end)
    (set-uint ,(source-event-name scope 'list-blank-count) (uint 1))))
(def (source-list-item-open-forms rule scope ordered? bullet-span: (span 'marker))
  (admit-list rule)
  (unless (and (boolean? ordered?) (memq span '(marker with-separator)))
    (error "invalid native list item policy" ordered? span))
  (let* ((frames (source-event-name scope 'list-frames))
         (column `(state ,(source-event-name scope 'list-column)))
         (top `(uint-divide (stack-top ,frames) (uint 2)))
         (base `(uint-multiply ,column (uint 2)))
         (frame (if ordered? `(uint-add ,base (uint 1)) base))
         (from `(state-offset ,(source-event-name scope 'list-bullet-start)))
         (marker-end `(state-offset ,(source-event-name scope 'list-bullet-end)))
         (content (source-list-content-offset scope))
         (trivia (list-line-trivia-token rule)))
    `((close-frames-while ,frames
        (or (uint-greater? ,top ,column)
            (and (uint-equal? ,top ,column)
                 (uint-not-equal? (stack-top ,frames) ,frame))) 2)
      (if (and ,(source-list-active-condition scope) (uint-equal? ,top ,column))
          ((finish-node))
          ((start-node ,(list-line-list-node rule)) (push-frame ,frames ,frame)))
      (start-node ,(list-line-item-node rule))
      (token ,trivia start ,from)
      (token ,(list-line-bullet-token rule) ,from
             ,(if (eq? span 'with-separator) content marker-end))
      ,@(if (eq? span 'marker) `((token ,trivia ,marker-end ,content)) '()))))
