;;; Admitted POO boundary queries and parent bindings; no raw form callbacks.
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. element?)
        (only-in ./line-structure-objects heading-line? block-line?))
(export SourceBoundaryQuery SourceBoundaryParent source-boundary-query? source-boundary-parent?)
(def (ascii? text)
  (and (string? text)
       (andmap (lambda (ch) (<= 1 (char->integer ch) 127)) (string->list text))))
(def (slots? value names)
  (and (object? value) (andmap (lambda (name) (.slot? value name)) names)))
(def (query-shape? value)
  (and (slots? value '(kind mode heading block opening closing suffix terminator indent heading-bound case-insensitive))
       (eq? (.ref value 'kind) 'source-boundary-query)
       (heading-line? (.ref value 'heading))
       (andmap (lambda (name) (boolean? (.ref value name))) '(indent heading-bound case-insensitive))
       (case (.ref value 'mode)
         ((fixed) (block-line? (.ref value 'block)))
         ((named)
          (and (ascii? (.ref value 'opening)) (> (string-length (.ref value 'opening)) 0)
               (ascii? (.ref value 'closing)) (> (string-length (.ref value 'closing)) 0)
               (ascii? (.ref value 'suffix))
               (or (not (.ref value 'terminator))
                   (and (ascii? (.ref value 'terminator))
                        (= (string-length (.ref value 'terminator)) 1)))))
         (else #f))))
(def (parent-shape? value)
  (and (slots? value '(kind id closing name-start name-end suffix case-insensitive))
       (eq? (.ref value 'kind) 'source-boundary-parent)
       (integer? (.ref value 'id)) (> (.ref value 'id) 0)
       (ascii? (.ref value 'closing)) (> (string-length (.ref value 'closing)) 0)
       (ascii? (.ref value 'suffix)) (boolean? (.ref value 'case-insensitive))
       (or (and (not (.ref value 'name-start)) (not (.ref value 'name-end))
                (string=? (.ref value 'suffix) "")
                (.ref value 'case-insensitive))
           (and (symbol? (.ref value 'name-start)) (symbol? (.ref value 'name-end))))))
(define-type (SourceBoundaryQuery @ Type.) .element?: query-shape?)
(define-type (SourceBoundaryParent @ Type.) .element?: parent-shape?)
(def (source-boundary-query? value) (element? SourceBoundaryQuery value))
(def (source-boundary-parent? value) (element? SourceBoundaryParent value))
