;;; -*- Gerbil -*-
;;; Stable public facade for language implementations.
;;; Internal source-admission and fixture layout remains private under src/.

(import (only-in ./src/language-support/antlr4-source
                 +antlr4-source-schema+
                 antlr4-rule?
                 antlr4-rule-name
                 antlr4-rule-kind
                 antlr4-rule-fragment?
                 antlr4-rule-expression
                 antlr4-rule-references
                 antlr4-source?
                 antlr4-source-language
                 antlr4-source-version
                 antlr4-source-commit
                 antlr4-source-digest
                 antlr4-source-name
                 antlr4-source-options
                 antlr4-source-rules
                 antlr4-source-parser-rules
                 antlr4-source-lexer-rules
                 antlr4-source-rule
                 antlr4-source-parser-grammar-rules
                 antlr4-source-parser-syntax-kinds
                 antlr4-source-parser-literals
                 antlr4-source-declaration-sources
                 antlr4-source->datum
                 antlr4-source-from-datum
                 parse-antlr4-source
                 parse-antlr4-source/expected)
        (only-in ./src/language-support/fixture
                 defsyntax-fixture
                 defsyntax-corpus
                 syntax-fixture?
                 syntax-fixture-id
                 syntax-fixture-language
                 syntax-fixture-version
                 syntax-fixture-contract
                 syntax-fixture-source-digest
                 syntax-fixture-source
                 syntax-fixture-expected-status
                 syntax-fixture-root-kind
                 syntax-fixture-required-kinds)
        (only-in ./src/language-support/grammar-source
                 defsyntax-iso-bnf-source
                 defsyntax-antlr4-source
                 deflanguage-antlr4-grammar
                 deflanguage-iso-bnf-grammar)
        (only-in ./src/language-support/iso-bnf
                 +iso-bnf-source-schema+
                 +iso-bnf-rule-overlay-schema+
                 iso-bnf-production?
                 iso-bnf-production-name
                 iso-bnf-production-expression
                 iso-bnf-production-ast
                 iso-bnf-production-line
                 iso-bnf-production-references
                 iso-bnf-source?
                 iso-bnf-source-language
                 iso-bnf-source-version
                 iso-bnf-source-commit
                 iso-bnf-source-digest
                 iso-bnf-source-productions
                 iso-bnf-source-production
                 iso-bnf-source-grammar-rules
                 iso-bnf-source-grammar-rules/overrides
                 iso-bnf-source-syntax-kinds
                 iso-bnf-source-literals
                 iso-bnf-source-declaration-sources
                 iso-bnf-source-declaration-sources/overrides
                 parse-iso-bnf-source
                 parse-iso-bnf-source/expected))
(export +antlr4-source-schema+
        +iso-bnf-source-schema+
        +iso-bnf-rule-overlay-schema+
        antlr4-rule?
        antlr4-rule-name
        antlr4-rule-kind
        antlr4-rule-fragment?
        antlr4-rule-expression
        antlr4-rule-references
        antlr4-source?
        antlr4-source-language
        antlr4-source-version
        antlr4-source-commit
        antlr4-source-digest
        antlr4-source-name
        antlr4-source-options
        antlr4-source-rules
        antlr4-source-parser-rules
        antlr4-source-lexer-rules
        antlr4-source-rule
        antlr4-source-parser-grammar-rules
        antlr4-source-parser-syntax-kinds
        antlr4-source-parser-literals
        antlr4-source-declaration-sources
        antlr4-source->datum
        antlr4-source-from-datum
        parse-antlr4-source
        parse-antlr4-source/expected
        iso-bnf-production?
        iso-bnf-production-name
        iso-bnf-production-expression
        iso-bnf-production-ast
        iso-bnf-production-line
        iso-bnf-production-references
        iso-bnf-source?
        iso-bnf-source-language
        iso-bnf-source-version
        iso-bnf-source-commit
        iso-bnf-source-digest
        iso-bnf-source-productions
        iso-bnf-source-production
        iso-bnf-source-grammar-rules
        iso-bnf-source-grammar-rules/overrides
        iso-bnf-source-syntax-kinds
        iso-bnf-source-literals
        iso-bnf-source-declaration-sources
        iso-bnf-source-declaration-sources/overrides
        parse-iso-bnf-source
        parse-iso-bnf-source/expected
        defsyntax-iso-bnf-source
        defsyntax-antlr4-source
        deflanguage-antlr4-grammar
        deflanguage-iso-bnf-grammar
        defsyntax-fixture
        defsyntax-corpus
        syntax-fixture?
        syntax-fixture-id
        syntax-fixture-language
        syntax-fixture-version
        syntax-fixture-contract
        syntax-fixture-source-digest
        syntax-fixture-source
        syntax-fixture-expected-status
        syntax-fixture-root-kind
        syntax-fixture-required-kinds)
