#!/usr/bin/env gxi
;;; Native qualification entry; declarations own process contracts.
(displayln "QUALIFICATION-START") (force-output)
(import :gerbil-parser/tools/qualification/process :gerbil-parser/tools/qualification/products :gerbil-parser/tools/qualification/plans :gerbil-parser/tools/qualification/performance)
(def (run-process-cli arguments)
  (let loop ((arguments arguments) (budget 60) (idle #f) (log #f) (receipts '()))
    (unless (pair? arguments) (error "missing qualification command"))
    (let (flag (car arguments))
      (cond
       ((equal? flag "--")
        (unless log (error "missing --log"))
        (let (result (run-observed-process (cdr arguments) log timeout: budget idle-timeout: idle))
          (let (missing (filter (lambda (pattern)
                                 (not (receipt-present? pattern (utf8->string (process-result-output result))))) receipts))
            (displayln "PROCESS-RESULT elapsed=" (process-result-elapsed result) " exit=" (process-result-status result)
                       " reason=" (process-result-reason result) " missing=" missing) (force-output)
            (exit (cond ((member (process-result-reason result) '(total-timeout idle-timeout)) 124)
                        ((or (process-result-reason result) (pair? missing) (not (zero? (process-result-status result)))) 1)
                        (else 0))))))
       ((member flag '("--timeout" "--idle-timeout" "--log" "--require"))
        (unless (pair? (cdr arguments)) (error "missing option value" flag))
        (let (value (cadr arguments))
          (cond ((equal? flag "--timeout") (loop (cddr arguments) (string->number value) idle log receipts))
                ((equal? flag "--idle-timeout") (loop (cddr arguments) budget (string->number value) log receipts))
                ((equal? flag "--log") (loop (cddr arguments) budget idle value receipts))
                (else (loop (cddr arguments) budget idle log (cons value receipts))))))
       ((equal? flag "--full-output") (loop (cdr arguments) budget idle log receipts))
       (else (error "unknown process contract option" flag))))))

(def (local-cli arguments)
 (let loop ((rest arguments) (suites '()) (prepared? #f) (root ".gerbil") (logs ".data/local-native") (jobs (min 4 (##core-count))))
  (if (null? rest)
   (qualify-local! (if (null? suites) '("rust" "gql" "ffi" "aot") (reverse suites)) prepared? root logs jobs)
   (cond
    ((equal? (car rest) "--prepared-diagnostics") (loop (cdr rest) suites #t root logs jobs))
    ((member (car rest) '("--suite" "--gerbil-path" "--log-dir" "--jobs"))
     (unless (pair? (cdr rest)) (error "missing local option value" (car rest)))
     (let (value (cadr rest))
      (cond ((equal? (car rest) "--suite") (loop (cddr rest) (if (member value suites) suites (cons value suites)) prepared? root logs jobs))
            ((equal? (car rest) "--gerbil-path") (loop (cddr rest) suites prepared? value logs jobs))
            ((equal? (car rest) "--log-dir") (loop (cddr rest) suites prepared? root value jobs))
            (else (loop (cddr rest) suites prepared? root logs (string->number value))))))
    (else (error "unknown local option" (car rest)))))))

(def (performance-cli arguments)
 (let loop ((rest arguments) (selected '()) (budget 120) (logs ".data/performance-source") (continue? #f) (list? #f))
  (if (null? rest)
   (let (names (if (null? selected) (map car performance-suites) (reverse selected)))
    (if list? (for-each (lambda (name) (displayln name ": " (cdr (or (assoc name performance-suites) (error "unknown suite" name))))) names)
     (qualify-performance! names budget logs continue?)))
   (cond
    ((equal? (car rest) "--continue-on-failure") (loop (cdr rest) selected budget logs #t list?))
    ((equal? (car rest) "--list") (loop (cdr rest) selected budget logs continue? #t))
    ((member (car rest) '("--suite" "--timeout" "--log-dir"))
     (unless (pair? (cdr rest)) (error "missing performance option value" (car rest)))
     (let (value (cadr rest))
      (cond ((equal? (car rest) "--suite") (loop (cddr rest) (cons value selected) budget logs continue? list?))
            ((equal? (car rest) "--timeout") (loop (cddr rest) selected (string->number value) logs continue? list?))
            (else (loop (cddr rest) selected budget value continue? list?)))))
    (else (error "unknown performance option" (car rest)))))))

(def (main mode . arguments)
 (cond
  ((equal? mode "run") (run-process-cli arguments))
  ((equal? mode "alignment") (unless (null? arguments) (error "alignment takes no arguments")) (qualify-language-alignment!))
  ((equal? mode "compiled-event-fold") (apply qualify-event-fold! arguments))
  ((equal? mode "performance") (performance-cli arguments))
  ((equal? mode "local") (local-cli arguments))
  ((equal? mode "host") (unless (null? arguments) (error "host takes no arguments")) (qualify-runtime-host!))
  ((equal? mode "shared-library")
   (let loop ((rest arguments) (output #f) (modules '()))
    (if (null? rest)
     (begin (unless output (error "missing --output")) (build-language-library! output (reverse modules)))
     (begin
      (unless (pair? (cdr rest)) (error "missing shared-library option value"))
      (cond ((equal? (car rest) "--output") (loop (cddr rest) (cadr rest) modules))
            ((equal? (car rest) "--language-module") (loop (cddr rest) output (cons (cadr rest) modules)))
            (else (error "unknown shared-library option" (car rest))))))))
  (else (error "unknown qualification profile" mode)))
 (exit 0))
