;;; Native qualification of process-owning test entries.
(displayln "PROCESS-QUALIFICATION-START") (force-output)
(load "t/fixtures/tla-sany-differential/preload.ss")
(prefer-compiled-interfaces!)
(call-with-compiled-interface-trace
 (lambda () (eval '(import :gerbil-parser/tools/qualification/process))))

(import :gerbil-parser/tools/qualification/process)

(defstruct process-case (name arguments exit marker budget idle) transparent: #t)

(def (qualification-cases profile)
  (cond
   ((equal? profile "conformance")
    (map (lambda (row)
           (process-case (car row)
             ["gxi" "scripts/tests/conformance-runner-test.ss" (car row)]
             (cadr row) (caddr row) 10 5))
         '(("success" 0 "CONFORMANCE-CONTROL-OK success")
           ("duplicate" 70 "duplicate conformance Suite")
           ("failure" 1 "negative control")
           ("timeout" 70 "CONFORMANCE-GROUP-TIMEOUT timeout"))))
   ((equal? profile "workers")
    (setenv "GERBIL_TEST_CORES" "2")
    (map (lambda (row)
           (process-case (car row)
             (append ["gxi" "t/fixtures/tla-sany-differential/test-suite.ss"]
               (map (lambda (name)
                      (string-append "t/fixtures/tla-sany-differential/" name ".ss"))
                    (cadr row)))
             (caddr row) (cadddr row) 30 #f))
         '(("shared-runtime" ("worker-left" "worker-right") 0 #f)
           ("runtime-affinity" ("affinity-left" "affinity-right") 0 #f)
           ("failure-propagation" ("worker-failure") nonzero #f)
           ("silence-watchdog" ("worker-timeout") 70 #f)
           ("duplicate-ownership" ("worker-left" "worker-left") nonzero #f)
           ("reexport-ownership" ("worker-reexport") nonzero #f)
           ("suite-object-ownership" ("worker-suite-alias") 70 "duplicate test Suite object"))))
   ((equal? profile "research")
    (let (binary (path-expand "bin/gerbil-parser-conformance" (getenv "GERBIL_PATH")))
      (cons (process-case "semantic" [binary "semantic"] 0
                           "CONFORMANCE-SEMANTIC-OK groups=" 240 5)
        (map (lambda (name) (process-case name [binary name] 0 #f 10 5))
             '("concise-runtime" "history" "native-poo-runtime" "provenance"
               "all-language-benchmark")))))
   (else (error "unknown process qualification profile" profile))))

(def (qualify-process! case directory)
 (let* ((name (process-case-name case))
        (result (run-observed-process (process-case-arguments case)
                  (path-expand (string-append name ".log") directory)
                  timeout: (process-case-budget case) idle-timeout: (process-case-idle case)
                  error-output?: #f))
        (status (process-result-status result)) (expected (process-case-exit case)))
  (unless (and (not (process-result-reason result))
               (if (eq? expected 'nonzero) (> status 0) (= status expected)))
   (error "unexpected process exit" name status (process-result-reason result)))
  (let (marker (process-case-marker case))
   (when (and marker (not (string-contains (utf8->string (process-result-output result)) marker)))
    (error "missing process receipt" name marker)))
  status))

(def (main profile . arguments)
  (let* ((cases (qualification-cases profile))
         (directory (if (pair? arguments) (car arguments)
                        (string-append ".data/" profile "-controls")))
         (prefix (cond ((equal? profile "conformance") "CONFORMANCE-CONTROL-OK ")
                       ((equal? profile "workers") "WORKER-CONTROL-OK ")
                       (else "RESEARCH-CONTROL-OK "))))
    (create-directory* directory)
    (call-with-output-file (path-expand "exits.tsv" directory)
      (lambda (exits)
        (for-each (lambda (case)
                    (let (status (qualify-process! case directory))
                      (display (process-case-name case) exits) (display "\t" exits)
                      (display status exits) (newline exits)
                      (force-output exits)
                      (displayln prefix (process-case-name case)) (force-output))) cases)))
    (when (equal? profile "research")
      (displayln "DSL-RESEARCH-CLOSURE-OK: all child processes exited 0"))
    (displayln "OK") (force-output)
    (exit 0)))
