;;; Common closed recognition/context/construction identity, without compiler imports.
(import (only-in ./identity sha256-text))
(export +contextual-parser-ir-schema+ contextual-ir-ref contextual-ir-copy
        make-contextual-parser-ir contextual-parser-ir-valid?)
(def +contextual-parser-ir-schema+ "gerbil-parser.contextual-parser-ir.v2")
(def (rows? datum)
  (and (list? datum) (andmap (lambda (row) (and (pair? row) (symbol? (car row)))) datum)))
(def (contextual-ir-ref ir key)
  (let (row (and (rows? ir) (assq key ir))) (and row (cdr row))))
(def (fields? datum required optional)
  (and (rows? datum)
       (andmap (lambda (key) (assq key datum)) required)
       (let loop ((rest datum) (seen '()))
         (or (null? rest)
             (let (key (caar rest))
               (and (memq key (append required optional)) (not (memq key seen))
                    (loop (cdr rest) (cons key seen))))))))
(def (contextual-ir-copy value)
  (cond ((pair? value) (cons (contextual-ir-copy (car value)) (contextual-ir-copy (cdr value))))
        ((vector? value) (list->vector (map contextual-ir-copy (vector->list value))))
        ((string? value) (string-copy value)) (else value)))
(def (closed? value)
  (cond ((pair? value) (and (closed? (car value)) (closed? (cdr value))))
        ((vector? value) (andmap closed? (vector->list value)))
        (else (or (null? value) (boolean? value) (symbol? value) (string? value)
                  (char? value) (exact-integer? value)))))
(def (canonical value) (call-with-output-string (lambda (port) (write value port))))
(def (shape? body)
  (and (fields? body '(schema recognition scanner context construction root-kind)
                      '(digest base-grammar-digest parser-ir-digest))
       (closed? body)
       (let* ((recognition (contextual-ir-ref body 'recognition))
              (construction (contextual-ir-ref body 'construction))
              (root (contextual-ir-ref body 'root-kind))
              (kinds (contextual-ir-ref construction 'syntax-kinds))
              (dialect (contextual-ir-ref recognition 'dialect)))
         (and (equal? (contextual-ir-ref body 'schema) +contextual-parser-ir-schema+)
              (fields? recognition '(dialect program) '())
              (memq dialect '(lr command lines))
              (contextual-ir-ref recognition 'program)
              (rows? (contextual-ir-ref body 'context))
              (fields? construction '(syntax-kinds terminals projections) '())
              (symbol? root) (list? kinds)
              (andmap (lambda (row) (and (list? row) (>= (length row) 2)
                                         (symbol? (car row)) (symbol? (cadr row)))) kinds)
              (list? (contextual-ir-ref construction 'terminals))
              (list? (contextual-ir-ref construction 'projections))
              (let (row (assq root kinds)) (and row (memq (cadr row) '(node result))))
              (if (eq? dialect 'lr)
                (and (string? (contextual-ir-ref body 'base-grammar-digest))
                     (string? (contextual-ir-ref body 'parser-ir-digest)))
                (not (or (assq 'base-grammar-digest body) (assq 'parser-ir-digest body))))))))
(def (make-contextual-parser-ir recognition scanner context construction root (binding '()))
  (let (body (contextual-ir-copy
              (append (list (cons 'schema +contextual-parser-ir-schema+)
                            (cons 'recognition recognition) (cons 'scanner scanner)
                            (cons 'context context) (cons 'construction construction)
                            (cons 'root-kind root)) binding)))
    (unless (shape? body) (error "invalid contextual recognition/context/construction product"))
    (append body (list (cons 'digest (sha256-text (canonical body)))))))
(def (contextual-parser-ir-valid? ir)
  (and (list? ir) (shape? ir)
       (= (length (filter (lambda (row) (eq? (car row) 'digest)) ir)) 1)
       (equal? (contextual-ir-ref ir 'digest)
               (sha256-text (canonical (filter (lambda (row) (not (eq? (car row) 'digest))) ir))))))
