;;; -*- Gerbil -*-
;;; Engine-owned persistent event instructions. No mutable instruction buffer
;;; is exposed. Semantic frames share bodies; token instructions reuse tokens.
(import (only-in ./token token? token-start token-end))
(export event-program-value? event-program-value-kind event-program-value-start
        event-program-value-end event-program-value-code
        event-program-token event-program-append event-program-append/avl event-program-relocate
        event-program-field event-program-node-value event-program-fragment-value
        event-program-walk event-program-walk/inline
        event-program-sequence? event-program-sequence-arity
        event-program-sequence-start event-program-sequence-end
        event-program-sequence-field? event-program-sequence-for-each
        event-program-sequence-height
        event-program-value-body)

(defstruct event-code-branch (left right start end height))
(defstruct event-code-view (code delta))
(defstruct event-code-append (prefix blocks tail start end height))
(defstruct event-code-chunk (items start end))
(defstruct event-field-frame (name start end body))
(defstruct event-program-value (kind start end body))

;; A value is itself its node/boundary instruction: no duplicate opcode packet.
(def (event-program-value-code value) value)
(def (event-program-token token) token)
(def +event-chunk-capacity+ 16)
;;; Only bounded leaf blocks may be copied. Persistent AVL join copies the
;;; logarithmic boundary path, retaining every untouched subtree and block.
(def (event-block-width code)
  (cond ((event-code-chunk? code) (vector-length (event-code-chunk-items code)))
        ((or (event-code-branch? code) (event-code-append? code)) (+ +event-chunk-capacity+ 1))
        ((event-code-view? code)
         (if (= (event-program-sequence-arity code) 1) 1 (+ +event-chunk-capacity+ 1)))
        (else 1)))
(def (event-block-join left right)
  (let* ((left-width (event-block-width left)) (right-width (event-block-width right))
         (items (make-vector (+ left-width right-width))))
    (def (copy-block code width offset)
      (if (event-code-chunk? code)
        (let (source (event-code-chunk-items code))
          (let loop ((i 0))
            (when (< i width)
              (vector-set! items (+ offset i) (vector-ref source i))
              (loop (+ i 1)))))
        (vector-set! items offset code)))
    (copy-block left left-width 0)
    (copy-block right right-width left-width)
    (make-event-code-chunk items (event-program-sequence-start left 0)
                                (event-program-sequence-end right 0))))
(def (event-rope-height code)
  ;; Semantic nodes, fields and position views are opaque rope leaves. Their
  ;; bodies retain their own balanced storage and depth fallback independently.
  (if (event-code-branch? code) (event-code-branch-height code) 0))
(def (event-program-sequence-height code)
  (if (event-code-append? code) (event-code-append-height code)
    (event-rope-height code)))
(def (event-branch left right)
  (make-event-code-branch left right (event-program-sequence-start left 0)
    (event-program-sequence-end right 0)
    (+ 1 (max (event-rope-height left) (event-rope-height right)))))
(def (event-balance left right)
  (let ((left-height (event-rope-height left))
        (right-height (event-rope-height right)))
    (cond
     ((> left-height (+ right-height 1))
      (let ((a (event-code-branch-left left)) (b (event-code-branch-right left)))
        (if (>= (event-rope-height a) (event-rope-height b))
          (event-branch a (event-branch b right))
          (event-branch (event-branch a (event-code-branch-left b))
                        (event-branch (event-code-branch-right b) right)))))
     ((> right-height (+ left-height 1))
      (let ((b (event-code-branch-left right)) (c (event-code-branch-right right)))
        (if (>= (event-rope-height c) (event-rope-height b))
          (event-branch (event-branch left b) c)
          (event-branch (event-branch left (event-code-branch-left b))
                        (event-branch (event-code-branch-right b) c)))))
     (else (event-branch left right)))))
(def (event-rope-join left right)
  (let ((left-height (event-rope-height left))
        (right-height (event-rope-height right)))
    (cond
     ((> left-height (+ right-height 1))
      (event-balance (event-code-branch-left left)
                     (event-rope-join (event-code-branch-right left) right)))
     ((> right-height (+ left-height 1))
      (event-balance (event-rope-join left (event-code-branch-left right))
                     (event-code-branch-right right)))
     ((and (= left-height 0) (= right-height 0)
           (<= (+ (event-block-width left) (event-block-width right)) +event-chunk-capacity+))
      (event-block-join left right))
     (else (event-branch left right)))))
(def (event-program-append/avl left right)
  (cond ((or (not left) (null? left)) right)
        ((or (not right) (null? right)) left)
        (else (event-rope-join left right))))
;;; Equal-rank complete leaf blocks form binary digits, newest first.
;;; Carry merges share their operands. Along a linear append chain the total
;;; carry count is linear; repeated branches from one old root may cost log N.
(def (event-append-block blocks block)
  (if (and (pair? blocks) (= (event-rope-height (car blocks)) (event-rope-height block)))
    (event-append-block (cdr blocks) (event-branch (car blocks) block))
    (cons block blocks)))
(def (event-snoc left right)
  (cond
   ((event-code-append? left)
    (let* ((tail (event-code-append-tail left))
           (full? (= (event-block-width tail) +event-chunk-capacity+))
           (blocks (if full? (event-append-block (event-code-append-blocks left) tail)
                     (event-code-append-blocks left)))
           (next-tail (if full? right (event-block-join tail right)))
           (height (max (event-code-append-height left)
                        (if full? (+ 1 (event-rope-height (car blocks))) 1))))
      (make-event-code-append (event-code-append-prefix left) blocks next-tail
        (event-code-append-start left) (event-program-sequence-end right 0) height)))
   ((or (= (event-program-sequence-arity left) 1)
        (and (event-code-chunk? left) (< (event-block-width left) +event-chunk-capacity+)))
    ;; Small grammar actions retain one leaf block, with no empty envelope.
    (event-block-join left right))
   ((event-code-chunk? left)
    (make-event-code-append #f (list left) right
      (event-code-chunk-start left) (event-program-sequence-end right 0) 1))
   (else
    (make-event-code-append left '() right
      (event-program-sequence-start left 0) (event-program-sequence-end right 0)
      (+ 1 (event-program-sequence-height left))))))
(def (event-append-tree code)
  ;; Normalize only at multi-sequence concat: newest/smallest blocks first.
  ;; Increasing ranks make the carry/join work telescope along the end path.
  ;; Prefixes are already AVL ropes; singleton append never nests envelopes.
  (if (event-code-append? code)
    (let (tree (event-code-append-tail code))
      (for-each (lambda (block) (set! tree (event-rope-join block tree)))
                (event-code-append-blocks code))
      (let (prefix (event-code-append-prefix code))
        (if prefix (event-rope-join prefix tree) tree)))
    code))
(def (event-program-append left right)
  (cond ((or (not left) (null? left)) right)
        ((or (not right) (null? right)) left)
        ((= (event-program-sequence-arity right) 1) (event-snoc left right))
        (else (event-rope-join (event-append-tree left) (event-append-tree right)))))
(def (event-program-relocate code delta (moved? #t))
  (cond ((not code) #f) ((not moved?) code)
        ((event-code-view? code)
         (make-event-code-view (event-code-view-code code)
                               (+ delta (event-code-view-delta code))))
        (else (make-event-code-view code delta))))
(def (event-program-field name start end body)
  (make-event-field-frame name start end body))
(def (event-program-node-value kind start end body)
  (make-event-program-value kind start end body))
(def (event-program-fragment-value start end body)
  ;; Flush final trivia before an enclosing field close. Bare tokens do not
  ;; carry this boundary, preserving the original field/trivia order.
  (make-event-program-value #f start end body))

;;; The same DAG is the LR semantic sequence. Node/boundary values and tokens
;;; are opaque semantic leaves; field frames freeze their label. Bounds on an
;;; append branch are computed once instead of walking its children at actions.
(def (event-program-sequence? value)
  (or (not value) (event-program-value? value) (token? value)
      (event-field-frame? value) (event-code-branch? value) (event-code-view? value)
      (event-code-chunk? value) (event-code-append? value)))
(def (event-program-sequence-arity value)
  (cond ((not value) 0)
        ((event-code-view? value) (event-program-sequence-arity (event-code-view-code value)))
        ((or (event-code-branch? value) (event-code-chunk? value) (event-code-append? value)) 2) (else 1)))
(def (event-program-sequence-bound value default-offset end?)
  (cond
   ((not value) default-offset)
   ((event-code-view? value)
    (+ (event-code-view-delta value)
       (event-program-sequence-bound (event-code-view-code value) default-offset end?)))
   ((event-code-append? value)
    ((if end? event-code-append-end event-code-append-start) value))
   ((event-code-chunk? value)
    ((if end? event-code-chunk-end event-code-chunk-start) value))
   ((event-code-branch? value)
    ((if end? event-code-branch-end event-code-branch-start) value))
   ((event-field-frame? value)
    ((if end? event-field-frame-end event-field-frame-start) value))
   ((event-program-value? value)
    ((if end? event-program-value-end event-program-value-start) value))
   ((token? value) ((if end? token-end token-start) value))
   (else (error "invalid event semantic sequence"))))
(def (event-program-sequence-start value default-offset)
  (event-program-sequence-bound value default-offset #f))
(def (event-program-sequence-end value default-offset)
  (event-program-sequence-bound value default-offset #t))
(def (event-program-sequence-field? value)
  (if (event-code-view? value)
    (event-program-sequence-field? (event-code-view-code value))
    (event-field-frame? value)))

;;; This visitor is the explicit materialization boundary, not a reduction.
;;; Preserve relocation provenance even when its summed offset is zero.
(def (event-program-sequence-for-each visit sequence)
  (let loop ((current sequence) (delta 0) (moved? #f) (pending '()))
    (cond
     ((event-code-view? current)
      (loop (event-code-view-code current) (+ delta (event-code-view-delta current)) #t pending))
     ((event-code-append? current)
      (let (frames (cons (vector (event-code-append-tail current) delta moved?) pending))
        (for-each (lambda (block) (set! frames (cons (vector block delta moved?) frames)))
                  (event-code-append-blocks current))
        (loop (event-code-append-prefix current) delta moved? frames)))
     ((event-code-branch? current)
      (loop (event-code-branch-left current) delta moved?
        (cons (vector (event-code-branch-right current) delta moved?) pending)))
     ((event-code-chunk? current)
      (loop (vector-ref (event-code-chunk-items current) 0) delta moved?
        (cons (vector current delta moved? 1) pending)))
     (else
      (when current
        (let unwrap ((value (if (event-field-frame? current) (event-field-frame-body current) current))
                     (delta delta) (moved? moved?))
          (if (event-code-view? value)
            (unwrap (event-code-view-code value) (+ delta (event-code-view-delta value)) #t)
            (visit (and (event-field-frame? current) (event-field-frame-name current)) value delta moved?))))
      (unless (null? pending)
        (let* ((frame (car pending)) (code (vector-ref frame 0)))
          (if (and (= (vector-length frame) 4) (event-code-chunk? code))
            (let* ((items (event-code-chunk-items code)) (i (vector-ref frame 3))
                   (last? (= (+ i 1) (vector-length items))))
              (unless last? (vector-set! frame 3 (+ i 1)))
              (loop (vector-ref items i) (vector-ref frame 1) (vector-ref frame 2)
                    (if last? (cdr pending) pending)))
            (loop code (vector-ref frame 1) (vector-ref frame 2) (cdr pending)))))))))

;;; Execute the instruction DAG with an explicit continuation stack. No flat
;;; intermediate tape or translated token objects are allocated. Position views
;;; retain moved provenance even when repeated translations cancel to zero.
;;; One traversal template specializes both inspection and publication. Ordinary
;;; depth uses native call frames; explicit continuations handle deep subgraphs.
;;; An opening node may return consumer state, retained only until its footer.
(defsyntax (event-program-walk/inline stx)
  (syntax-case stx (lambda)
    ((_ (lambda (op name offset shift moved context) effect ...) initial-code)
     #'(let ()
         (def (iterative initial delta moved?)
           (let loop ((code initial) (finish? #f) (delta delta) (moved? moved?)
                      (state #f) (pending '()))
             (cond
              ((not code)
               (unless (null? pending)
                 (let* ((frame (car pending)) (next (vector-ref frame 0)))
                   (if (and (event-code-chunk? next) (integer? (vector-ref frame 1)))
                     (let* ((items (event-code-chunk-items next)) (i (vector-ref frame 1))
                            (last? (= (+ i 1) (vector-length items))))
                       (unless last? (vector-set! frame 1 (+ i 1)))
                       (loop (vector-ref items i) #f (vector-ref frame 2) (vector-ref frame 3)
                             #f (if last? (cdr pending) pending)))
                     (loop next (vector-ref frame 1) (vector-ref frame 2) (vector-ref frame 3)
                           (if (= (vector-length frame) 5) (vector-ref frame 4) #f)
                           (cdr pending))))))
              (finish?
               (cond
                ((event-program-value? code)
                 (if (event-program-value-kind code)
                   ((lambda (op name offset shift moved context) effect ...) 'close-node (event-program-value-kind code) (event-program-value-end code) delta moved? state)
                   ((lambda (op name offset shift moved context) effect ...) 'boundary #f (event-program-value-end code) delta moved? #f)))
                ((event-field-frame? code)
                 ((lambda (op name offset shift moved context) effect ...) 'close-field (event-field-frame-name code) (event-field-frame-end code) delta moved? #f))
                (else (error "invalid event continuation")))
               (loop #f #f delta moved? #f pending))
              ((event-code-view? code)
               (loop (event-code-view-code code) #f (+ delta (event-code-view-delta code)) #t #f pending))
              ((event-code-append? code)
               (let (frames (cons (vector (event-code-append-tail code) #f delta moved?) pending))
                 (for-each (lambda (block) (set! frames (cons (vector block #f delta moved?) frames)))
                           (event-code-append-blocks code))
                 (loop (event-code-append-prefix code) #f delta moved? #f frames)))
            ((event-code-branch? code)
               (loop (event-code-branch-left code) #f delta moved? #f
                     (cons (vector (event-code-branch-right code) #f delta moved?) pending)))
              ((event-code-chunk? code)
               (loop (vector-ref (event-code-chunk-items code) 0) #f delta moved? #f
                     (cons (vector code 1 delta moved?) pending)))
              ((event-program-value? code)
               (let (node-state (and (event-program-value-kind code)
                                 ((lambda (op name offset shift moved context) effect ...) 'open-node (event-program-value-kind code)
                                   (event-program-value-start code) delta moved? #f)))
                 (loop (event-program-value-body code) #f delta moved? #f
                       (cons (vector code #t delta moved? node-state) pending))))
              ((event-field-frame? code)
               ((lambda (op name offset shift moved context) effect ...) 'open-field (event-field-frame-name code) (event-field-frame-start code) delta moved? #f)
               (loop (event-field-frame-body code) #f delta moved? #f
                     (cons (vector code #t delta moved? #f) pending)))
              ((token? code)
               ((lambda (op name offset shift moved context) effect ...) 'token code (token-start code) delta moved? #f)
               (loop #f #f delta moved? #f pending))
              (else (error "invalid event instruction")))))
         (def (walk code delta moved? depth)
           (cond
            ((not code) (void))
            ((>= depth 64) (iterative code delta moved?))
            ((event-program-value? code)
             (let* ((kind (event-program-value-kind code))
                    (node-state (and kind ((lambda (op name offset shift moved context) effect ...) 'open-node kind (event-program-value-start code) delta moved? #f))))
               (walk (event-program-value-body code) delta moved? (+ depth 1))
               (if kind
                 ((lambda (op name offset shift moved context) effect ...) 'close-node kind (event-program-value-end code) delta moved? node-state)
                 ((lambda (op name offset shift moved context) effect ...) 'boundary #f (event-program-value-end code) delta moved? #f))))
            ((event-field-frame? code)
             ((lambda (op name offset shift moved context) effect ...) 'open-field (event-field-frame-name code) (event-field-frame-start code) delta moved? #f)
             (walk (event-field-frame-body code) delta moved? (+ depth 1))
             ((lambda (op name offset shift moved context) effect ...) 'close-field (event-field-frame-name code) (event-field-frame-end code) delta moved? #f))
            ((token? code) ((lambda (op name offset shift moved context) effect ...) 'token code (token-start code) delta moved? #f))
            ((event-code-view? code)
             (walk (event-code-view-code code) (+ delta (event-code-view-delta code)) #t (+ depth 1)))
            ((event-code-chunk? code)
             (let* ((items (event-code-chunk-items code)) (n (vector-length items)))
               (let loop ((i 0))
                 (when (< i n)
                   (walk (vector-ref items i) delta moved? (+ depth 1))
                   (loop (+ i 1))))))
            ((event-code-append? code)
             (walk (event-code-append-prefix code) delta moved? (+ depth 1))
             (for-each (lambda (block) (walk block delta moved? (+ depth 1)))
                       (reverse (event-code-append-blocks code)))
             (walk (event-code-append-tail code) delta moved? (+ depth 1)))
            ((event-code-branch? code)
             (walk (event-code-branch-left code) delta moved? (+ depth 1))
             (walk (event-code-branch-right code) delta moved? (+ depth 1)))
            (else (error "invalid event instruction"))))
         (walk initial-code 0 #f 0)))))
(def (event-program-walk visit code)
  (event-program-walk/inline
   (lambda (operation name offset delta moved? state)
     (visit operation name offset delta moved?)) code))
