;;; Immutable source preparation for closed lexical capture opcodes.
(export prepare-lexical-source-plan call-with-lexical-source scan-header-delimiter scan-header-data)
(defstruct lexical-source-context (owner source headers))
(def current-lexical-source-context (make-parameter #f))
(def (prepare-lexical-source-plan rules)
 (let visit ((expressions (map cadr rules)) (headers '()))
  (if (null? expressions) (reverse headers)
   (let (expression (car expressions))
    (case (car expression)
     ((header-delimiter header-data)
      (let (capture (list (string-copy (cadr expression)) (caddr expression)))
       (visit (cdr expressions) (if (member capture headers) headers (cons capture headers)))))
     ((choice) (visit (append (cdr expression) (cdr expressions)) headers))
     ((precedence) (visit (cons (caddr expression) (cdr expressions)) headers))
     (else (visit (cdr expressions) headers)))))))
(def (call-with-lexical-source plan source thunk)
 (if (null? plan) (thunk)
  (let (current (current-lexical-source-context))
   (if (and current (eq? plan (lexical-source-context-owner current))
                  (eq? source (lexical-source-context-source current)))
    (thunk)
    (let (prepared (make-lexical-source-context plan source
            (map (lambda (capture)
              (cons capture (validate-header-base source (car capture) (cadr capture)))) plan)))
     (parameterize ((current-lexical-source-context prepared)) (thunk)))))))
(def (header-delimiter-base source prefix count)
 (let (context (current-lexical-source-context))
  (if (and context (eq? source (lexical-source-context-source context)))
   (let loop ((rows (lexical-source-context-headers context)))
    (if (null? rows) (validate-header-base source prefix count)
     (let* ((row (car rows)) (capture (car row)))
      (if (and (equal? prefix (car capture)) (= count (cadr capture)))
       (cdr row) (loop (cdr rows))))))
   (validate-header-base source prefix count))))

;;; Header-derived delimiter rules are closed data, independent of language.
;;; Compare directly in the source: no delimiter list, substring or hash table.
;;; A bounded header contains distinct non-alphabetic, non-numeric characters.
(def (validate-header-base source prefix count)
  (let (base (string-length prefix))
    (and (<= (+ base count) (string-length source)) (string-prefix? prefix source)
         (let loop ((index 0))
           (if (= index count) base
             (let (character (string-ref source (+ base index)))
               (and (not (char-alphabetic? character)) (not (char-numeric? character))
                    (let unique ((previous 0))
                      (or (= previous index)
                          (and (not (char=? character (string-ref source (+ base previous))))
                               (unique (+ previous 1)))))
                    (loop (+ index 1)))))))))
(def (scan-header-delimiter source start prefix count index)
  (and (exact-integer? start) (<= 0 start) (< start (string-length source))
       (let (base (header-delimiter-base source prefix count))
         (and base (char=? (string-ref source start) (string-ref source (+ base index)))
              (+ start 1)))))
(def (scan-header-data source start prefix count stops)
  (and (exact-integer? start) (<= 0 start) (< start (string-length source))
       (let (base (header-delimiter-base source prefix count))
         (and base
              (let loop ((end start))
                (if (and (< end (string-length source))
                         (let (character (string-ref source end))
                           (and (let stop ((index 0))
                                  (or (= index (string-length stops))
                                      (and (not (char=? character (string-ref stops index)))
                                           (stop (+ index 1)))))
                                (let delimiter ((index 0))
                                  (or (= index count)
                                      (and (not (char=? character (string-ref source (+ base index))))
                                           (delimiter (+ index 1))))))))
                  (loop (+ end 1)) (and (> end start) end)))))))

