;;; Prepared module framing. Repeated borders are indexed as intervals, not suffix scans.
(export prepare-module-source scan-prepared-module-source)
(defstruct module-source-index (source expression headers events))
(def (prefix-at? source at text)
 (and (<= (+ at (string-length text)) (string-length source))
  (let loop ((i 0))
   (or (= i (string-length text))
       (and (char=? (string-ref source (+ at i)) (string-ref text i)) (loop (+ i 1)))))))
(def (run-end source at accept?)
 (let loop ((at at))
  (if (and (< at (string-length source)) (accept? (string-ref source at))) (loop (+ at 1)) at)))
(def (name-end source at extra)
 (let loop ((end at) (seen? #f))
  (if (and (< end (string-length source))
           (let (ch (string-ref source end))
            (or (char-alphabetic? ch) (char-numeric? ch) (char=? ch extra))))
   (loop (+ end 1) (or seen? (char-alphabetic? (string-ref source end))
                            (char=? (string-ref source end) extra)))
   (and seen? end))))
(def (header-tail-end source at border word extra)
 (let (word-at (run-end source at char-whitespace?))
  (and (prefix-at? source word-at word)
   (let* ((name-at (run-end source (+ word-at (string-length word)) char-whitespace?))
          (name-stop (name-end source name-at extra)))
    (and name-stop
     (let (close-at (run-end source name-stop char-whitespace?))
      (and (prefix-at? source close-at border)
           (run-end source close-at (cut char=? <> (string-ref border 0))))))))))
(def (module-header-intervals source border word extra)
 (let ((ch (string-ref border 0)) (width (string-length border)) (size (string-length source)))
  (let loop ((at 0) (rows '()))
   (if (= at size) (list->vector (reverse rows))
    (if (char=? (string-ref source at) ch)
     (let* ((end (run-end source at (cut char=? <> ch)))
            (stop (and (>= (- end at) width) (header-tail-end source end border word extra))))
      (loop end (if stop (cons (vector at (- end width) stop) rows) rows)))
     (loop (+ at 1) rows))))))
(def (skip-block source at open close)
 (let loop ((at (+ at (string-length open))) (depth 1))
  (cond ((>= at (string-length source)) at)
        ((prefix-at? source at open) (loop (+ at (string-length open)) (+ depth 1)))
        ((prefix-at? source at close)
         (if (= depth 1) (+ at (string-length close)) (loop (+ at (string-length close)) (- depth 1))))
        (else (loop (+ at 1) depth)))))
(def (skip-string source at)
 (let loop ((at (+ at 1)))
  (cond ((>= at (string-length source)) at)
        ((char=? (string-ref source at) #\") (+ at 1))
        ((char=? (string-ref source at) #\\) (loop (+ at 2)))
        (else (loop (+ at 1))))))
(def (module-depth-events source headers end-border open close comment)
 (let loop ((at 0) (cursor 0) (depth 0) (rows '()))
  (cond
   ((>= at (string-length source)) (list->vector (reverse rows)))
   ((and (< cursor (vector-length headers)) (> at (vector-ref (vector-ref headers cursor) 1)))
    (loop at (+ cursor 1) depth rows))
   ((prefix-at? source at open) (loop (skip-block source at open close) cursor depth rows))
   ((char=? (string-ref source at) #\") (loop (skip-string source at) cursor depth rows))
   ((prefix-at? source at comment)
    (loop (run-end source at (lambda (ch) (not (char=? ch #\newline)))) cursor depth rows))
   ((and (< cursor (vector-length headers)) (>= at (vector-ref (vector-ref headers cursor) 0)))
    (loop (vector-ref (vector-ref headers cursor) 2) cursor (+ depth 1) (cons (vector at (+ depth 1)) rows)))
   ((prefix-at? source at end-border)
    (loop (run-end source at (cut char=? <> (string-ref end-border 0))) cursor (- depth 1)
          (cons (vector at (- depth 1)) rows)))
   (else (loop (+ at 1) cursor depth rows)))))
(def (prepare-module-source source expression)
 (match expression
  (['module-text border word end-border open close comment extra]
   (let (headers (module-header-intervals source border word (string-ref extra 0)))
    (make-module-source-index source expression headers
     (module-depth-events source headers end-border open close comment))))))
(def (lower-bound rows before?)
 (let loop ((lo 0) (hi (vector-length rows)))
  (if (= lo hi) lo
   (let (mid (quotient (+ lo hi) 2))
    (if (before? (vector-ref rows mid)) (loop (+ mid 1) hi) (loop lo mid))))))
(def (scan-prepared-module-source index start)
 (let* ((source (module-source-index-source index)) (size (string-length source))
        (end-border (list-ref (module-source-index-expression index) 3)))
  (and (exact-integer? start) (<= 0 start) (< start size)
   (or (= start 0)
    (let* ((prior (let loop ((at (- start 1)))
                   (if (and (>= at 0) (char-whitespace? (string-ref source at))) (loop (- at 1)) at)))
           (border-at (- (+ prior 1) (string-length end-border)))
           (events (module-source-index-events index))
           (event (lower-bound events (lambda (row) (< (vector-ref row 0) start)))))
     (and (>= border-at 0) (prefix-at? source border-at end-border)
          (= (if (zero? event) 0 (vector-ref (vector-ref events (- event 1)) 1)) 0))))
   (let* ((headers (module-source-index-headers index))
          (next (lower-bound headers (lambda (row) (< (vector-ref row 1) start))))
          (end (if (= next (vector-length headers)) size
                 (max start (vector-ref (vector-ref headers next) 0)))))
    (and (> end start) end)))))
