;;; Closed record selectors and POO recipes; no language-specific projection code.
(import (only-in :clan/poo/object .o .cc .ref .slot? object?)
        (only-in :clan/poo/mop define-type validate)
        (only-in :core/types PooFlowContract. poo-flow-classification-evidence)
        (only-in ../language/descriptor language-grammar? language-grammar-machine)
        (only-in ../compiler/machine parser-machine-grammar-digest)
        (only-in ./lexical-source scan-header-delimiter)
        (only-in ./artifact parse-artifact-valid? parse-artifact-success? parse-artifact-roundtrip parse-artifact-ref))
(export RecordProjection. RecordProjectionContract bind-record-projection deflanguage-projection)
(def (selector? value count (depth 0))
  (and (< depth 64) (list? value) (pair? value)
       (case (car value)
         ((text) (and (= (length value) 2) (string? (cadr value))))
         ((record) (and (= (length value) 3) (string? (cadr value)) (positive? (string-length (cadr value)))
                        (exact-integer? (caddr value)) (<= 0 (caddr value))))
         ((split) (and (= (length value) 4) (selector? (cadr value) count (+ depth 1))
                       (exact-integer? (caddr value)) (<= 0 (caddr value)) (< (caddr value) count)
                       (exact-integer? (cadddr value)) (<= 0 (cadddr value))))
         ((concat list) (and (pair? (cdr value))
                            (andmap (lambda (child) (selector? child count (+ depth 1))) (cdr value))))
         (else #f))))
(def (unique-columns? rows)
  (let loop ((remaining rows) (names '(sourceDigest grammarDigest)))
    (or (null? remaining)
        (and (pair? (car remaining)) (symbol? (caar remaining))
             (not (memq (caar remaining) names))
             (loop (cdr remaining) (cons (caar remaining) names))))))
(def (projection-shape? value)
  (with-catch (lambda (_) #f)
    (lambda ()
      (and (object? value)
           (andmap (lambda (slot) (.slot? value slot)) '(descriptor prefix delimiter-count expectations constants columns metadata))
           (language-grammar? (.ref value 'descriptor)) (object? (.ref value 'metadata))
           (string? (.ref value 'prefix)) (positive? (string-length (.ref value 'prefix)))
           (exact-integer? (.ref value 'delimiter-count)) (<= 1 (.ref value 'delimiter-count) 32)
           (list? (.ref value 'constants)) (list? (.ref value 'columns)) (list? (.ref value 'expectations))
           (unique-columns? (append (.ref value 'constants) (.ref value 'columns)))
           (andmap (lambda (row) (and (list? row) (= (length row) 2)
                                      (selector? (car row) (.ref value 'delimiter-count))
                                      (or (string? (cadr row)) (list? (cadr row))))) (.ref value 'expectations))
           (andmap (lambda (row) (and (pair? row) (symbol? (car row))
                                      (selector? (cdr row) (.ref value 'delimiter-count)))) (.ref value 'columns))
           (andmap (lambda (row) (or (string? (cdr row)) (symbol? (cdr row)) (number? (cdr row)) (boolean? (cdr row))))
                   (.ref value 'constants))))))
(define-type (RecordProjectionContract @ PooFlowContract.)
  identity: 'gerbil-parser/record-projection
  .classify: (lambda (candidate context)
               (let (accepted? (projection-shape? candidate))
                 (poo-flow-classification-evidence 'gerbil-parser/record-projection candidate accepted?
                  (if accepted? '() '((expected gerbil-parser/record-projection))) context))))
(def RecordProjection.
  (.o descriptor: #f prefix: #f delimiter-count: #f expectations: '() constants: '() columns: '() metadata: (.o)))
(def (split-text text delimiter)
  (let (limit (string-length text))
    (let loop ((start 0) (at 0) (parts '()))
      (cond ((= at limit) (reverse (cons (substring text start at) parts)))
            ((char=? (string-ref text at) delimiter)
             (loop (+ at 1) (+ at 1) (cons (substring text start at) parts)))
            (else (loop start (+ at 1) parts))))))
(def (record-lines source)
  (let (limit (string-length source))
    (let loop ((start 0) (at 0) (rows '()))
      (if (or (= at limit) (memv (string-ref source at) '(#\return #\newline)))
        (let (next-rows (if (= start at) rows (cons (substring source start at) rows)))
          (if (= at limit) (reverse next-rows) (loop (+ at 1) (+ at 1) next-rows)))
        (loop start (+ at 1) rows)))))
(def (required-item items index)
  (let loop ((remaining items) (at index))
    (cond ((null? remaining) (error "record selector has no required item" index))
          ((zero? at) (car remaining))
          (else (loop (cdr remaining) (- at 1))))))
(def (copy-data value)
  (cond ((pair? value) (cons (copy-data (car value)) (copy-data (cdr value))))
        ((string? value) (string-copy value)) (else value)))
(def (bind-record-projection descriptor prototype)
  (let (candidate (.cc prototype 'descriptor descriptor))
    (validate RecordProjectionContract candidate)
    (let ((digest (parser-machine-grammar-digest (language-grammar-machine descriptor)))
          (prefix (string-copy (.ref candidate 'prefix))) (count (.ref candidate 'delimiter-count))
          (expectations (copy-data (.ref candidate 'expectations)))
          (constants (copy-data (.ref candidate 'constants))) (columns (copy-data (.ref candidate 'columns))))
      (lambda (artifact)
        (unless (and (parse-artifact-valid? artifact) (parse-artifact-success? artifact)
                     (equal? (parse-artifact-ref artifact 'grammarDigest) digest))
          (error "record projection requires its own accepted artifact"))
        (let* ((source (parse-artifact-roundtrip artifact)) (base (string-length prefix)))
          (unless (scan-header-delimiter source base prefix count 0)
            (error "record projection header violates its recipe"))
          (let ((delimiters (substring source base (+ base count)))
                (records (map (lambda (line) (split-text line (string-ref source base))) (record-lines source))))
            (def (evaluate expression)
              (case (car expression)
                ((text) (cadr expression))
                ((record) (let (row (find (lambda (row) (equal? (car row) (cadr expression))) records))
                            (unless row (error "record projection has no required record" (cadr expression)))
                            (required-item row (caddr expression))))
                ((split) (required-item (split-text (evaluate (cadr expression)) (string-ref delimiters (caddr expression)))
                                        (cadddr expression)))
                ((concat) (apply string-append (map evaluate (cdr expression))))
                ((list) (map evaluate (cdr expression)))))
            (for-each (lambda (row) (unless (equal? (evaluate (car row)) (cadr row))
                                     (error "record projection does not admit this message" row))) expectations)
            (append (list (cons 'sourceDigest (parse-artifact-ref artifact 'sourceDigest))
                          (cons 'grammarDigest digest)) constants
                    (map (lambda (row) (cons (car row) (evaluate (cdr row)))) columns))))))))
(defrules deflanguage-projection (grammar strategy)
  ((_ binding (grammar descriptor) (strategy prototype))
   (def binding (bind-record-projection descriptor prototype))))
