;;; Closed source recipes share the source engine protocol; no language imports.
(import (only-in ../language/command-profile compile-command-profile admit-command-plan command-plan-recipe command-plan-kind)
        (only-in :clan/poo/object .o .ref .slot?)
        (only-in ../language/source-strategy SourceStrategy. declare-source-strategy-provider make-source-engine)
        (only-in ./region-scanner region-plan? region-plan-specification prepare-region-plan)
        (only-in ../language/part-profile compile-part-profile part-plan-recipe admit-part-plan)
        (only-in ../language/scanner-profile compile-scanner-profile)
        (only-in ./contextual-scanner prepare-contextual-scanner-plan)
        (only-in ./shell-parser make-shell-parser)
        (only-in ./source-scanner make-source-scanner make-contextual-source-scanner source-scanner-tokens)
        (only-in ./recognition make-recognition-child)
        (only-in ../language/result-profile ResultProfile. compile-result-profile result-plan-recipe result-plan-node result-plan-token)
        (only-in ./token token-start token-end)
        (only-in ./artifact make-success-parse-artifact make-failure-parse-artifact))
(export ShellSourceStrategy. LineSourceStrategy.)
;;; Shape classification is separate from semantic compilation. The compiler
;;; admits each plan once and uses that same owned plan for identity and runtime.
(def (shell-source-admit? candidate)
  (and (andmap (lambda (slot) (.slot? candidate slot))
               '(regions scanner parts results commands))
       (region-plan? (.ref candidate 'regions))))
(def (compile-shell-source candidate)
  (let* ((results (compile-result-profile (.ref candidate 'results)))
         (regions (prepare-region-plan (region-plan-specification (.ref candidate 'regions))))
         (scanner-ir (compile-scanner-profile (.ref candidate 'scanner)))
         (commands (admit-command-plan (compile-command-profile (.ref candidate 'commands)) results (.ref candidate 'scanner)))
         (parts (admit-part-plan (compile-part-profile (.ref candidate 'parts)) results regions))
         (plan (prepare-contextual-scanner-plan scanner-ir)))
    (def (factory source) (make-contextual-source-scanner plan source 'source))
    (def (scan source) (source-scanner-tokens (factory source) 'command))
    (let-values (((parse receipt) (make-shell-parser regions results parts commands)))
      (values
        (list (region-plan-specification regions) scanner-ir
              (result-plan-recipe results) (part-plan-recipe parts)
              (command-plan-recipe commands))
        (make-source-engine scan factory parse receipt results (command-plan-kind commands 'BashFile))))))
(def +shell-source-provider+
  (declare-source-strategy-provider 'shell shell-source-admit? compile-shell-source))
(def ShellSourceStrategy.
  (.o (:: self SourceStrategy.) provider: +shell-source-provider+ regions: #f scanner: #f results: #f parts: #f commands: #f))
(def (line-source-admit? candidate)
  (and (andmap (lambda (slot) (.slot? candidate slot)) '(root-kind token-kind required-prefix))
       (symbol? (.ref candidate 'root-kind)) (symbol? (.ref candidate 'token-kind))
       (string? (.ref candidate 'required-prefix))
       (.slot? candidate 'results)))
(def (compile-line-source candidate)
  (let ((root-kind (.ref candidate 'root-kind)) (token-kind (.ref candidate 'token-kind))
        (prefix (string-copy (.ref candidate 'required-prefix)))
        (results (compile-result-profile (.ref candidate 'results))))
    (def (factory source)
      (make-source-scanner source #f
       (lambda (text start context _mode)
         (let (limit (string-length text))
           (if (= start limit) (values #f start context)
             (let loop ((end start))
               (if (or (= end limit) (char=? (string-ref text end) #\newline))
                 (values token-kind (if (= end limit) end (+ end 1)) context)
                 (loop (+ end 1)))))))))
    (def (scan source) (map (lambda (token) (result-plan-token results token))
                           (source-scanner-tokens (factory source) 'lines)))
    (def (parse source scanner digest)
      (let (tokens (scanner source))
        (if (and (<= (string-length prefix) (string-length source))
                 (equal? prefix (substring source 0 (string-length prefix))))
          (make-success-parse-artifact digest source tokens
           (result-plan-node results root-kind 0
            (if (null? tokens) 0 (token-end (last tokens)))
            (map (lambda (token) (make-recognition-child 'line token)) tokens)) (lambda (_) #f))
          (make-failure-parse-artifact digest source tokens
           '((schema . "gerbil-parser.diagnostic.v1") (code . "SOURCE-PREFIX")
             (reasonKind . parse-rejected) (failureKind . source-rejected)
             (message . "source does not match its declared prefix") (byteOffset . 0))))))
    (values (list root-kind token-kind prefix (result-plan-recipe results))
            (make-source-engine scan factory parse #f results root-kind))))
(def +line-source-provider+
  (declare-source-strategy-provider 'lines line-source-admit? compile-line-source))
(def LineSourceStrategy.
  (.o (:: self SourceStrategy.) provider: +line-source-provider+
      root-kind: 'SourceFile token-kind: 'Line required-prefix: ""
      (results (.o (:: result ResultProfile.)
                   nodes: (list (list (.ref self 'root-kind) '(line)))
                   tokens: (list (.ref self 'token-kind))))))
