;;; -*- Gerbil -*-
;;; Persistent measured token/mode sequence. Only fresh chunks are mutable
;;; while being built; published nodes and chunk backing vectors never mutate.
(import (only-in ./token make-token token-kind token-lexeme token-start token-end))
(export source-index-count source-index-height source-index-start source-index-end
        source-index-shift source-index-concat source-index-slice source-index->lists
        source-index-audit source-index-storage
        make-source-index-builder source-index-builder-token! source-index-builder-shared!
        source-index-builder-finish source-index-builder-fresh source-index-builder-shared
        source-index-builder-chunks source-index-builder-mode-chunks
        make-source-index-cursor source-index-cursor-copy source-index-cursor-token
        source-index-cursor-mode source-index-cursor-rank source-index-cursor-next!
        source-index-cursor-seek!)
(def +chunk-size+ 64)
(defstruct source-leaf (tokens modes begin count bytes chars start end))
(defstruct source-branch (left right count bytes chars start end height))
(defstruct source-view (base delta))
(def (source-index-count tree)
  (cond ((not tree) 0) ((source-view? tree) (source-index-count (source-view-base tree)))
        ((source-leaf? tree) (source-leaf-count tree)) (else (source-branch-count tree))))
(def (source-index-height tree)
  (cond ((not tree) 0) ((source-view? tree) (source-index-height (source-view-base tree)))
        ((source-leaf? tree) 1) (else (source-branch-height tree))))
(def (source-index-start tree)
  (cond ((source-view? tree) (+ (source-view-delta tree) (source-index-start (source-view-base tree))))
        ((source-leaf? tree) (source-leaf-start tree)) (else (source-branch-start tree))))
(def (source-index-end tree)
  (cond ((source-view? tree) (+ (source-view-delta tree) (source-index-end (source-view-base tree))))
        ((source-leaf? tree) (source-leaf-end tree)) (else (source-branch-end tree))))
(def (tree-chars tree)
  (cond ((not tree) 0) ((source-view? tree) (tree-chars (source-view-base tree)))
        ((source-leaf? tree) (source-leaf-chars tree)) (else (source-branch-chars tree))))
(def (tree-bytes tree)
  (if tree (- (source-index-end tree) (source-index-start tree)) 0))
(def (source-index-shift tree delta)
  (cond ((or (not tree) (zero? delta)) tree)
        ((source-view? tree)
         (source-index-shift (source-view-base tree) (+ delta (source-view-delta tree))))
        (else (make-source-view tree delta))))
(def (branch-parts tree)
  (if (source-view? tree)
    (let-values (((left right) (branch-parts (source-view-base tree))))
      (values (source-index-shift left (source-view-delta tree))
              (source-index-shift right (source-view-delta tree))))
    (values (source-branch-left tree) (source-branch-right tree))))
(def (branch left right)
  (unless (= (source-index-end left) (source-index-start right))
    (error "source index join has a byte gap"))
  (make-source-branch left right (+ (source-index-count left) (source-index-count right))
                      (+ (tree-bytes left) (tree-bytes right)) (+ (tree-chars left) (tree-chars right))
                      (source-index-start left) (source-index-end right)
                      (+ 1 (max (source-index-height left) (source-index-height right)))))
(def (balance left right)
  (cond
   ((> (source-index-height left) (+ (source-index-height right) 1))
    (let-values (((a b) (branch-parts left)))
      (if (>= (source-index-height a) (source-index-height b))
        (branch a (branch b right))
        (let-values (((c d) (branch-parts b))) (branch (branch a c) (branch d right))))))
   ((> (source-index-height right) (+ (source-index-height left) 1))
    (let-values (((a b) (branch-parts right)))
      (if (>= (source-index-height b) (source-index-height a))
        (branch (branch left a) b)
        (let-values (((c d) (branch-parts a))) (branch (branch left c) (branch d b))))))
   (else (branch left right))))
(def (source-index-concat left right)
  (cond ((not left) right) ((not right) left)
        ((> (source-index-height left) (+ (source-index-height right) 1))
         (let-values (((a b) (branch-parts left))) (balance a (source-index-concat b right))))
        ((> (source-index-height right) (+ (source-index-height left) 1))
         (let-values (((a b) (branch-parts right))) (balance (source-index-concat left a) b)))
        (else (branch left right))))
(def (leaf tokens modes begin count)
  (let ((start (token-start (vector-ref tokens begin)))
        (end (token-end (vector-ref tokens (+ begin count -1)))))
    (make-source-leaf tokens modes begin count (- end start)
      (let loop ((at begin) (chars 0))
        (if (= at (+ begin count)) chars
          (loop (+ at 1) (+ chars (string-length (token-lexeme (vector-ref tokens at))))))) start end)))
(def (split tree count)
  (cond ((zero? count) (values #f tree))
        ((= count (source-index-count tree)) (values tree #f))
        ((source-view? tree)
         (let-values (((a b) (split (source-view-base tree) count)))
           (values (source-index-shift a (source-view-delta tree))
                   (source-index-shift b (source-view-delta tree)))))
        ((source-leaf? tree)
         (values (leaf (source-leaf-tokens tree) (source-leaf-modes tree) (source-leaf-begin tree) count)
                 (leaf (source-leaf-tokens tree) (source-leaf-modes tree)
                       (+ (source-leaf-begin tree) count) (- (source-leaf-count tree) count))))
        (else
         (let-values (((a b) (branch-parts tree)))
           (let (left-count (source-index-count a))
             (if (< count left-count)
               (let-values (((x y) (split a count))) (values x (source-index-concat y b)))
               (let-values (((x y) (split b (- count left-count))))
                 (values (source-index-concat a x) y))))))))
(def (source-index-slice tree start count)
  (unless (and (integer? start) (integer? count) (>= start 0) (>= count 0)
               (<= (+ start count) (source-index-count tree)))
    (error "invalid source index slice" start count))
  (let-values (((prefix tail) (split tree start)))
    (let-values (((middle suffix) (split tail count))) middle)))

;;; A cursor descends once, then iterates inside immutable chunks. Its copied
;;; state is a certificate trial; rejecting that trial never consumes the owner.
(defstruct source-cursor (root pending leaf offset limit delta rank cache))
(def (cursor-install! cursor tree rank delta pending)
  (cond ((not tree) (set! (source-cursor-leaf cursor) #f) (set! (source-cursor-pending cursor) pending))
        ((source-view? tree)
         (cursor-install! cursor (source-view-base tree) rank (+ delta (source-view-delta tree)) pending))
        ((source-leaf? tree)
         (set! (source-cursor-leaf cursor) tree)
         (set! (source-cursor-offset cursor) (+ (source-leaf-begin tree) rank))
         (set! (source-cursor-limit cursor) (+ (source-leaf-begin tree) (source-leaf-count tree)))
         (set! (source-cursor-delta cursor) delta) (set! (source-cursor-pending cursor) pending))
        (else
         (let ((left (source-branch-left tree)) (right (source-branch-right tree)))
           (if (< rank (source-index-count left))
             (cursor-install! cursor left rank delta (cons (cons right delta) pending))
             (cursor-install! cursor right (- rank (source-index-count left)) delta pending))))))
(def (make-source-index-cursor tree (rank 0))
  (unless (<= 0 rank (source-index-count tree)) (error "invalid source cursor rank" rank))
  (let (cursor (make-source-cursor tree '() #f 0 0 0 rank #f))
    (unless (= rank (source-index-count tree)) (cursor-install! cursor tree rank 0 '())) cursor))
(def source-index-cursor-rank source-cursor-rank)
(def (source-index-cursor-copy cursor)
  (make-source-cursor (source-cursor-root cursor) (source-cursor-pending cursor)
    (source-cursor-leaf cursor) (source-cursor-offset cursor) (source-cursor-limit cursor)
    (source-cursor-delta cursor) (source-cursor-rank cursor) (source-cursor-cache cursor)))
(def (source-index-cursor-token cursor)
  (and (source-cursor-leaf cursor)
       (or (source-cursor-cache cursor)
           (let* ((raw (vector-ref (source-leaf-tokens (source-cursor-leaf cursor)) (source-cursor-offset cursor)))
                  (delta (source-cursor-delta cursor))
                  (token (if (zero? delta) raw
                           (make-token (token-kind raw) (token-lexeme raw)
                                       (+ delta (token-start raw)) (+ delta (token-end raw))))))
             (set! (source-cursor-cache cursor) token) token))))
(def (source-index-cursor-mode cursor)
  (and (source-cursor-leaf cursor)
       (vector-ref (source-leaf-modes (source-cursor-leaf cursor)) (source-cursor-offset cursor))))
(def (source-index-cursor-next! cursor)
  (when (source-cursor-leaf cursor)
    (set! (source-cursor-cache cursor) #f)
    (set! (source-cursor-rank cursor) (+ (source-cursor-rank cursor) 1))
    (set! (source-cursor-offset cursor) (+ (source-cursor-offset cursor) 1))
    (when (= (source-cursor-offset cursor) (source-cursor-limit cursor))
      (if (null? (source-cursor-pending cursor)) (set! (source-cursor-leaf cursor) #f)
        (let (next (car (source-cursor-pending cursor)))
          (cursor-install! cursor (car next) 0 (cdr next) (cdr (source-cursor-pending cursor))))))))
(def (byte-rank tree byte)
  (cond ((not tree) 0)
        ((<= byte (source-index-start tree)) 0)
        ((>= byte (source-index-end tree)) (source-index-count tree))
        ((source-view? tree) (byte-rank (source-view-base tree) (- byte (source-view-delta tree))))
        ((source-leaf? tree)
         (let loop ((at 0))
           (if (or (= at (source-leaf-count tree))
                   (>= (token-start (vector-ref (source-leaf-tokens tree) (+ at (source-leaf-begin tree)))) byte)) at
             (loop (+ at 1)))))
        (else
         (let ((a (source-branch-left tree)) (b (source-branch-right tree)))
           (if (< byte (source-index-end a)) (byte-rank a byte)
             (+ (source-index-count a) (byte-rank b byte)))))))
(def (source-index-cursor-seek! cursor byte)
  (let (current (source-index-cursor-token cursor))
    (unless (or (not current) (>= (token-start current) byte))
      (if (< byte (+ (source-cursor-delta cursor) (source-leaf-end (source-cursor-leaf cursor))))
        ;; Recognition and boundary scanning stay near the current chunk.
        ;; Advancing there preserves locality instead of searching from root
        ;; and rescanning the same leaf prefix for every declaration boundary.
        (let advance ()
          (when (< (+ (source-cursor-delta cursor)
                      (token-start (vector-ref (source-leaf-tokens (source-cursor-leaf cursor))
                                               (source-cursor-offset cursor)))) byte)
            (source-index-cursor-next! cursor)
            (when (source-cursor-leaf cursor) (advance))))
        (let (rank (byte-rank (source-cursor-root cursor) byte))
          (set! (source-cursor-rank cursor) rank) (set! (source-cursor-cache cursor) #f)
          (if (= rank (source-index-count (source-cursor-root cursor)))
            (begin (set! (source-cursor-leaf cursor) #f) (set! (source-cursor-pending cursor) '()))
            (cursor-install! cursor (source-cursor-root cursor) rank 0 '())))))))

(def (relabel tree patches)
  ;; Patches are sorted ranks relative to this tree. Copy one bounded mode
  ;; vector per touched leaf; token backing storage is always retained.
  (cond ((null? patches) (values tree 0))
        ((source-view? tree)
         (let-values (((base chunks) (relabel (source-view-base tree) patches)))
           (values (source-index-shift base (source-view-delta tree)) chunks)))
        ((source-leaf? tree)
         (let (modes (vector-copy (source-leaf-modes tree)))
           (for-each (lambda (patch) (vector-set! modes (+ (source-leaf-begin tree) (car patch)) (cdr patch))) patches)
           (values (make-source-leaf (source-leaf-tokens tree) modes (source-leaf-begin tree)
                     (source-leaf-count tree) (source-leaf-bytes tree) (source-leaf-chars tree)
                     (source-leaf-start tree) (source-leaf-end tree)) 1)))
        (else
         (let* ((a (source-branch-left tree)) (b (source-branch-right tree)) (count (source-index-count a)))
           (let divide ((rest patches) (left '()))
             (if (and (pair? rest) (< (caar rest) count))
               (divide (cdr rest) (cons (car rest) left))
               (let-values (((x xc) (relabel a (reverse left)))
                            ((y yc) (relabel b (map (lambda (patch) (cons (- (car patch) count) (cdr patch))) rest))))
                 (values (branch x y) (+ xc yc)))))))))

;;; A request builder coalesces adjacent origins before slicing old trees.
;;; It never owns a previous snapshot after finish: only reachable tree pieces
;;; survive. Caller observers report scanner results or certified source spans.
(defstruct source-builder (root tokens modes buffered origin fresh shared chunks mode-chunks))
(def (make-source-index-builder (prefix #f))
  (make-source-builder prefix '() '() 0 #f 0 (source-index-count prefix) 0 0))
(def source-index-builder-fresh source-builder-fresh)
(def source-index-builder-shared source-builder-shared)
(def source-index-builder-chunks source-builder-chunks)
(def source-index-builder-mode-chunks source-builder-mode-chunks)
(def (flush-fresh! builder)
  (when (positive? (source-builder-buffered builder))
    (let ((tokens (list->vector (reverse (source-builder-tokens builder))))
          (modes (list->vector (reverse (source-builder-modes builder)))))
      (set! (source-builder-root builder)
            (source-index-concat (source-builder-root builder) (leaf tokens modes 0 (vector-length tokens))))
      (set! (source-builder-chunks builder) (+ (source-builder-chunks builder) 1)))
    (set! (source-builder-tokens builder) '()) (set! (source-builder-modes builder) '())
    (set! (source-builder-buffered builder) 0)))
(def (flush-origin! builder)
  (let (origin (source-builder-origin builder))
    (when origin
      (let-values (((piece chunks)
                    (relabel (source-index-slice (vector-ref origin 0) (vector-ref origin 1) (vector-ref origin 2))
                             (reverse (vector-ref origin 4)))))
        (set! (source-builder-root builder)
          (source-index-concat (source-builder-root builder) (source-index-shift piece (vector-ref origin 3))))
        (set! (source-builder-mode-chunks builder) (+ (source-builder-mode-chunks builder) chunks)))
      (set! (source-builder-origin builder) #f))))
(def (source-index-builder-token! builder token mode)
  (unless (and (positive? (- (token-end token) (token-start token))) (integer? mode) (>= mode 0))
    (error "invalid source index token/mode"))
  (flush-origin! builder)
  (when (pair? (source-builder-tokens builder))
    (unless (= (token-end (car (source-builder-tokens builder))) (token-start token))
      (error "source index fresh chunk has a byte gap")))
  (set! (source-builder-tokens builder) (cons token (source-builder-tokens builder)))
  (set! (source-builder-modes builder) (cons mode (source-builder-modes builder)))
  (set! (source-builder-buffered builder) (+ (source-builder-buffered builder) 1))
  (set! (source-builder-fresh builder) (+ (source-builder-fresh builder) 1))
  (when (= (source-builder-buffered builder) +chunk-size+) (flush-fresh! builder)))
(def (source-index-builder-shared! builder tree start count delta (mode #f))
  (unless (and (<= 0 start) (<= 0 count) (<= (+ start count) (source-index-count tree)))
    (error "invalid shared source span"))
  (when mode
    (unless (and (= count 1) (integer? mode) (>= mode 0)) (error "invalid shared source mode override")))
  (when (positive? count)
    (flush-fresh! builder)
    (let (origin (source-builder-origin builder))
      (if (and origin (eq? tree (vector-ref origin 0)) (= delta (vector-ref origin 3))
               (= start (+ (vector-ref origin 1) (vector-ref origin 2))))
        (begin
          (when mode (vector-set! origin 4 (cons (cons (vector-ref origin 2) mode) (vector-ref origin 4))))
          (vector-set! origin 2 (+ (vector-ref origin 2) count)))
        (begin (flush-origin! builder) (set! (source-builder-origin builder) (vector tree start count delta (if mode (list (cons 0 mode)) '()))))))
    (set! (source-builder-shared builder) (+ (source-builder-shared builder) count))))
(def (source-index-builder-finish builder)
  (flush-fresh! builder) (flush-origin! builder) (source-builder-root builder))
(def (source-index->lists tree)
  (let loop ((cursor (make-source-index-cursor tree)) (tokens '()) (modes '()))
    (let (token (source-index-cursor-token cursor))
      (if (not token) (values (reverse tokens) (reverse modes))
        (let (mode (source-index-cursor-mode cursor))
          (source-index-cursor-next! cursor) (loop cursor (cons token tokens) (cons mode modes)))))))
;;; Debug/audit operations deliberately traverse the tree; never used to update it.
(def (source-index-storage tree)
  (cond ((not tree) '()) ((source-view? tree) (source-index-storage (source-view-base tree)))
        ((source-leaf? tree) (list (source-leaf-tokens tree)))
        (else (append (source-index-storage (source-branch-left tree)) (source-index-storage (source-branch-right tree))))))
(def (source-index-audit tree)
  (cond ((not tree) #t)
        ((source-view? tree)
         (and (not (source-view? (source-view-base tree))) (not (zero? (source-view-delta tree)))
              (source-index-audit (source-view-base tree))))
        ((source-leaf? tree)
         (and (<= 1 (source-leaf-count tree) +chunk-size+)
              (= (source-leaf-bytes tree) (- (source-leaf-end tree) (source-leaf-start tree)))
              (let loop ((at (source-leaf-begin tree)) (end (source-leaf-start tree)) (chars 0))
                (if (= at (+ (source-leaf-begin tree) (source-leaf-count tree)))
                  (and (= end (source-leaf-end tree)) (= chars (source-leaf-chars tree)))
                  (let ((token (vector-ref (source-leaf-tokens tree) at))
                        (mode (vector-ref (source-leaf-modes tree) at)))
                    (and (= end (token-start token)) (< end (token-end token)) (integer? mode) (>= mode 0)
                         (loop (+ at 1) (token-end token) (+ chars (string-length (token-lexeme token))))))))))
        (else
         (let ((a (source-branch-left tree)) (b (source-branch-right tree)))
           (and (source-index-audit a) (source-index-audit b)
                (<= (abs (- (source-index-height a) (source-index-height b))) 1)
                (= (source-branch-height tree) (+ 1 (max (source-index-height a) (source-index-height b))))
                (= (source-branch-count tree) (+ (source-index-count a) (source-index-count b)))
                (= (source-index-end a) (source-index-start b))
                (= (source-branch-start tree) (source-index-start a)) (= (source-branch-end tree) (source-index-end b))
                (= (source-branch-bytes tree) (+ (tree-bytes a) (tree-bytes b)))
                (= (source-branch-chars tree) (+ (tree-chars a) (tree-chars b))))))))
