// @generated by t/generate-scheme-whitespace-class.ss; do not edit.
// Source authority: pinned native Scheme char-whitespace? class.
const RANGES: &[(u32, u32)] = &[
    (0x9, 0xd),
    (0x20, 0x20),
    (0x85, 0x85),
    (0xa0, 0xa0),
    (0x1680, 0x1680),
    (0x2000, 0x200a),
    (0x2028, 0x2029),
    (0x202f, 0x202f),
    (0x205f, 0x205f),
    (0x3000, 0x3000),
];

pub(super) fn is_scheme_whitespace(character: char) -> bool {
    let code = character as u32;
    let index = RANGES.partition_point(|&(start, _)| start <= code);
    index > 0 && code <= RANGES[index - 1].1
}
