#!/usr/bin/env gxi
;;; Canonical Scheme producer supplies Rust ABI conformance bytes, not reports.
(import "records"
        :std/encoding/json
        (only-in :gerbil-parser/t/fixtures/tla-sany-differential/exit-child-process test-child-process-exit!)
        (only-in :gerbil-parser/src/ffi/language-artifact-codec
                 bind-native-language native-parse-binary-payload native-descriptor-payload))
(def (emit-bytes port bytes)
  (display "&[" port)
  (for-each (lambda (byte) (display byte port) (display "," port)) (u8vector->list bytes))
  (display "]" port))
(def (main output)
  (let* ((language (bind-native-language records-language-grammar))
         (contextual (bind-native-language records-language-grammar records-contextual-product))
         (descriptor (string->json (native-descriptor-payload language) (JSONReadOptions object-as-hash: #t)))
         (sources (list "" "α=1\n" "a = 1\r\nb=\"β\"\n" "name=value" "a="
                        (string-append "a=1" (string (integer->char 0)) "!"))))
    (call-with-output-file output
      (lambda (port)
        (display "// @generated by the Scheme GPA1 producer; do not edit.\n" port)
        (display "pub const FIELD_COUNT: usize = " port)
        (display (length (hash-get descriptor "fields")) port)
        (display ";\npub static CASES: &[(&[u8], &[u8])] = &[\n" port)
        (for-each (lambda (source)
                    (display "(" port) (emit-bytes port (string->utf8 source))
                    (display "," port) (emit-bytes port (native-parse-binary-payload language source))
                    (display "),\n" port)) sources)
        (display "];\npub static CONTEXTUAL_CASES: &[(&[u8], &[u8])] = &[\n" port)
        (for-each (lambda (source)
                    (display "(" port) (emit-bytes port (string->utf8 source))
                    (display "," port) (emit-bytes port (native-parse-binary-payload contextual source))
                    (display "),\n" port)) sources)
        (display "];\n" port))))
  (displayln "NATIVE-ARTIFACT-GENERATED") (force-output)
  (test-child-process-exit! 0))
