// @generated by gerbil-parser/src/compiler/rust-rowan.ss
// Source authority: canonical Grammar IR v1; do not edit.

use gerbil_parser_rowan::{
    ActionEntry, GotoEntry, KindCategory, KindSpec, LanguageSpec, LexicalExpr, LexicalRule,
    Operand, OperandAction, ParserAction, Production, Reduction, Symbol, Terminal, TerminalSpec,
};

static KINDS: &[KindSpec] = &[
    KindSpec {
        name: "SourceFile",
        category: KindCategory::Node,
    },
    KindSpec {
        name: "String",
        category: KindCategory::Token,
    },
    KindSpec {
        name: "Name",
        category: KindCategory::Token,
    },
    KindSpec {
        name: "Unknown",
        category: KindCategory::Token,
    },
];

static TERMINALS: &[TerminalSpec] = &[
    TerminalSpec {
        name: "string",
        syntax_kind: 1,
    },
    TerminalSpec {
        name: "name",
        syntax_kind: 2,
    },
    TerminalSpec {
        name: "unknown",
        syntax_kind: 3,
    },
];

static LEXICAL_RULES: &[LexicalRule] = &[
    LexicalRule {
        terminal: "string",
        expression: LexicalExpr::QuotedStringProfile {
            delimiter: "'",
            escapes: "`'\\/fnrt",
            unicode_width: 4,
        },
        precedence: 0,
        extra: false,
    },
    LexicalRule {
        terminal: "name",
        expression: LexicalExpr::QuotedStringProfile {
            delimiter: "`",
            escapes: "`'\\/fnrt",
            unicode_width: 4,
        },
        precedence: 0,
        extra: false,
    },
    LexicalRule {
        terminal: "unknown",
        expression: LexicalExpr::Fallback,
        precedence: 0,
        extra: false,
    },
];

static ACTION_0: &[ActionEntry] = &[
    ActionEntry {
        terminal: Terminal::Token("string"),
        action: ParserAction::Shift(2),
    },
    ActionEntry {
        terminal: Terminal::Token("name"),
        action: ParserAction::Shift(3),
    },
];
static ACTION_1: &[ActionEntry] = &[ActionEntry {
    terminal: Terminal::Eof,
    action: ParserAction::Accept,
}];
static ACTION_2: &[ActionEntry] = &[ActionEntry {
    terminal: Terminal::Eof,
    action: ParserAction::Reduce(1),
}];
static ACTION_3: &[ActionEntry] = &[ActionEntry {
    terminal: Terminal::Eof,
    action: ParserAction::Reduce(2),
}];
static ACTION_4: &[ActionEntry] = &[ActionEntry {
    terminal: Terminal::Eof,
    action: ParserAction::Reduce(3),
}];
static ACTIONS: &[&[ActionEntry]] = &[ACTION_0, ACTION_1, ACTION_2, ACTION_3, ACTION_4];

static GOTO_0: &[GotoEntry] = &[
    GotoEntry {
        nonterminal: "document",
        state: 1,
    },
    GotoEntry {
        nonterminal: "$document.0",
        state: 4,
    },
];
static GOTO_1: &[GotoEntry] = &[];
static GOTO_2: &[GotoEntry] = &[];
static GOTO_3: &[GotoEntry] = &[];
static GOTO_4: &[GotoEntry] = &[];
static GOTOS: &[&[GotoEntry]] = &[GOTO_0, GOTO_1, GOTO_2, GOTO_3, GOTO_4];

static PRODUCTIONS: &[Production] = &[
    Production {
        lhs: "$accept",
        rhs: &[Operand {
            symbol: Symbol::Nonterminal("document"),
            actions: &[],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "$document.0",
        rhs: &[Operand {
            symbol: Symbol::Terminal(Terminal::Token("string")),
            actions: &[],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "$document.0",
        rhs: &[Operand {
            symbol: Symbol::Terminal(Terminal::Token("name")),
            actions: &[],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "document",
        rhs: &[Operand {
            symbol: Symbol::Nonterminal("$document.0"),
            actions: &[OperandAction::Field("item"), OperandAction::Alias(0)],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
];

pub static LANGUAGE: LanguageSpec = LanguageSpec {
    language: "quoted-profile",
    version: "v1",
    contract: "quoted-profile.v1",
    grammar_digest: "sha256:6cb81d1784076aa0915de79ea9f37088227324a5c9191f3f2dbf5add1935733c",
    case_insensitive: false,
    root_kind: 0,
    kinds: KINDS,
    terminals: TERMINALS,
    lexical_rules: LEXICAL_RULES,
    actions: ACTIONS,
    gotos: GOTOS,
    productions: PRODUCTIONS,
};
