;;; -*- Gerbil -*-
;;; Language test declarations share the admitted POO loader and invariants.
(import (only-in :std/test check test-case test-suite)
        (only-in :clan/poo/object .ref)
        (only-in :clan/poo/mop validate)
        (only-in ../language/entry LanguageLoaderContract language-parser-entry-ref run-language-test
                 +language-parser-entry-schema+)
        (only-in ../runtime/artifact parse-artifact-valid? parse-artifact-success?
                 parse-artifact-ref parse-artifact-roundtrip parse-artifact-events
                 token-event? token-event-token-kind event-kind)
        (only-in ../runtime/identity sha256-text)
        (only-in ../../language-support/fixture syntax-fixture-source syntax-fixture-source-digest)
        (only-in ./parser-ast check-parser-ast))
(export deflanguage-parser-tests)

(def (checked-test-loader loader)
  (validate LanguageLoaderContract loader)
  loader)

(def (checked-language-source loader source accepted?)
  (unless (and (equal? (language-parser-entry-ref loader 'schema)
                      +language-parser-entry-schema+) (string? source))
    (error "language test requires an admitted loader and string source" source))
  (let (artifact ((.ref loader '.parse) source))
    (check (parse-artifact-valid? artifact) => #t)
    (check (parse-artifact-success? artifact) => accepted?)
    (check (parse-artifact-roundtrip artifact) => source)
    (check (parse-artifact-ref artifact 'sourceDigest) => (sha256-text source))
    artifact))

(def (checked-language-fixtures loader)
  (let ((artifacts (run-language-test loader 'fixtures)) (fixtures (.ref loader 'fixtures)))
    (check (pair? artifacts) => #t)
    (check (length artifacts) => (length fixtures))
    (for-each (lambda (artifact fixture)
                (check (parse-artifact-valid? artifact) => #t)
                (check (parse-artifact-roundtrip artifact) => (syntax-fixture-source fixture))
                (check (parse-artifact-ref artifact 'sourceDigest) => (syntax-fixture-source-digest fixture)))
              artifacts fixtures)))

(def (nonempty-language-sources sources)
  (unless (and (list? sources) (pair? sources) (andmap string? sources))
    (error "language test source collection must be nonempty strings" sources))
  sources)

(def (artifact-node-kinds artifact)
  (map (lambda (event) (vector-ref event 2))
       (filter (lambda (event) (eq? (event-kind event) 'start-node))
               (parse-artifact-events artifact))))

(defrules language-artifact-expectation (nodes tokens counts without-nodes diagnostics artifact-ref projection)
  ((_ artifact (nodes kind ...))
   (begin (check (and (memq 'kind (artifact-node-kinds artifact)) #t) => #t) ...))
  ((_ artifact (without-nodes kind ...))
   (begin (check (and (memq 'kind (artifact-node-kinds artifact)) #t) => #f) ...))
  ((_ artifact (counts (kind count) ...))
   (begin (check (length (filter (lambda (value) (eq? value 'kind))
                                (artifact-node-kinds artifact))) => count) ...))
  ((_ artifact (tokens kind ...))
   (let (kinds (map token-event-token-kind (filter token-event? (parse-artifact-events artifact))))
     (check (and (memq 'kind kinds) #t) => #t) ...))
  ((_ artifact (diagnostics))
   (check (pair? (parse-artifact-ref artifact 'diagnostics)) => #t))
  ((_ artifact (artifact-ref key expected))
   (check (parse-artifact-ref artifact 'key) => expected))
  ((_ artifact (projection project (key expected) ...))
   (let (value (project artifact))
     (check (cdr (assq 'key value)) => expected) ...)))

(defrules language-test-clause (accepted rejected accepted-many rejected-many identity fixtures ast property bindings equal)
  ((_ loader (accepted label source expectation ...))
   (test-case label
     (let (artifact (checked-language-source loader source #t))
       (language-artifact-expectation artifact expectation) ... (void))))
  ((_ loader (rejected label source expectation ...))
   (test-case label
     (let (artifact (checked-language-source loader source #f))
       (language-artifact-expectation artifact expectation) ... (void))))
  ((_ loader (accepted-many label sources expectation ...))
   (test-case label
     (for-each (lambda (source)
                 (let (artifact (checked-language-source loader source #t))
                   (language-artifact-expectation artifact expectation) ... (void))) (nonempty-language-sources sources))))
  ((_ loader (rejected-many label sources expectation ...))
   (test-case label
     (for-each (lambda (source)
                 (let (artifact (checked-language-source loader source #f))
                   (language-artifact-expectation artifact expectation) ... (void))) (nonempty-language-sources sources))))
  ((_ loader (identity label (key expected) ...))
   (test-case label (check (language-parser-entry-ref loader 'key) => expected) ...))
  ((_ loader (fixtures label))
   (test-case label
     (checked-language-fixtures loader)))
  ((_ loader (ast label source pattern))
   (test-case label
     (let* ((text source) (artifact (checked-language-source loader text #t)))
       (check-parser-ast artifact text pattern))))
  ((_ loader (property label (bindings (name value) ...) (equal actual expected) ...))
   (test-case label
     (let* ((name value) ...)
       (check actual => expected) ...))))

;;; The loader expression is evaluated once. No free-form test-case body is
;;; accepted: each row and artifact expectation must match the closed syntax.
(defsyntax (deflanguage-parser-tests stx)
  (def (nonempty? rows pred) (and (pair? rows) (andmap pred rows)))
  (def (symbol-row? row) (and (list? row) (= (length row) 2) (symbol? (car row))))
  (def (expectation? row)
    (and (list? row) (pair? row)
      (case (car row)
        ((nodes tokens without-nodes) (nonempty? (cdr row) symbol?))
        ((counts) (nonempty? (cdr row) (lambda (item)
                    (and (symbol-row? item) (exact-integer? (cadr item)) (>= (cadr item) 0)))))
        ((diagnostics) (= (length row) 1))
        ((artifact-ref) (and (= (length row) 3) (symbol? (cadr row))))
        ((projection) (and (>= (length row) 3) (nonempty? (cddr row) symbol-row?)))
        (else #f))))
  (def (clause? row)
    (and (list? row) (>= (length row) 2) (string? (cadr row))
         (positive? (string-length (cadr row)))
      (case (car row)
        ((accepted rejected accepted-many rejected-many)
         (and (>= (length row) 3) (andmap expectation? (cdddr row))))
        ((fixtures) (= (length row) 2))
        ((identity) (nonempty? (cddr row) (lambda (item)
                       (and (symbol-row? item) (memq (car item) '(schema language version contract))))))
        ((ast) (= (length row) 4))
        ((property)
         (and (>= (length row) 4) (list? (caddr row)) (pair? (caddr row))
              (eq? (caaddr row) 'bindings) (andmap symbol-row? (cdaddr row))
              (nonempty? (cdddr row) (lambda (item)
                (and (list? item) (= (length item) 3) (eq? (car item) 'equal))))))
        (else #f))))
  (syntax-case stx (loader)
    ((_ name title (loader entry) clause ...)
     (and (identifier? #'name) (stx-string? #'title))
     (let ((rows (syntax->datum #'(clause ...))) (labels '()))
       (unless (nonempty? rows clause?)
         (raise-syntax-error #f "invalid language parser test clause or expectation" stx))
       (for-each (lambda (row)
                   (when (member (cadr row) labels)
                     (raise-syntax-error #f "duplicate language parser test label" stx))
                   (set! labels (cons (cadr row) labels))) rows)
       #'(begin
           (def name (let (owner (checked-test-loader entry))
                       (test-suite title (language-test-clause owner clause) ...)))
           (export name))))
    (_ (raise-syntax-error #f "language parser tests require a name, title and loader" stx))))
