;;; -*- Gerbil -*-
;;; Language test declarations share the admitted POO loader and invariants.
(import (only-in :std/test check test-case test-suite)
        (only-in :clan/poo/object .ref)
        (only-in :clan/poo/mop validate)
        (only-in ../language/entry LanguageLoaderContract language-parser-entry-ref run-language-test
                 +language-parser-entry-schema+)
        (only-in ../runtime/artifact parse-artifact-valid? parse-artifact-success?
                 parse-artifact-ref parse-artifact-roundtrip parse-artifact-events
                 token-event? token-event-token-kind event-kind)
        (only-in ../runtime/identity sha256-text)
        (only-in ../../language-support/fixture syntax-fixture-source syntax-fixture-source-digest syntax-fixture-expected-status)
        (only-in ./parser-ast check-parser-ast)
        (only-in ./language-strategy check-language-strategies check-language-installed
                 check-language-fixture-strategies)
        (only-in ../runtime/cst parse-artifact->cst syntax-node? syntax-node-kind
                 syntax-field-name
                 syntax-node-children syntax-field? syntax-field-children)
        (only-in ../runtime/token token? token-lexeme)
        (only-in ../compiler/bound-ir bound-grammar-ir-ref bound-grammar-ir-binding)
        (only-in ../compiler/parser-ir parser-ir-ref)
        (only-in ../compiler/lr lr-spec-ref production-lhs production-rhs)
        (only-in ../compiler/machine parser-machine-ir)
        (only-in ../runtime/lexer lex-source)
        (only-in ../runtime/significant parser-significant-tokens)
        (only-in ../runtime/lr-parser lr-parse/receipt)
        (only-in ../language/descriptor language-grammar? language-grammar-machine)
        (only-in ../runtime/incremental make-edit parse-source/incremental)
        (only-in ../runtime/recovery parse-source/recover)
        (only-in ../runtime/region-scanner source-prefix-at?)
        (only-in :std/string/utf8 string-utf8-length)
        (only-in :std/sync/barrier make-barrier barrier-post! barrier-wait!))
(export deflanguage-parser-tests)

(def (checked-test-loader loader)
  (validate LanguageLoaderContract loader)
  loader)

(def (checked-language-source loader source accepted?)
  (unless (and (equal? (language-parser-entry-ref loader 'schema)
                      +language-parser-entry-schema+) (string? source))
    (error "language test requires an admitted loader and string source" source))
  (let (artifact ((.ref loader '.parse) source))
    (check (parse-artifact-valid? artifact) => #t)
    (check (parse-artifact-success? artifact) => accepted?)
    (check (parse-artifact-roundtrip artifact) => source)
    (check (parse-artifact-ref artifact 'sourceDigest) => (sha256-text source))
    artifact))

(def (checked-language-fixtures loader (expected-status #f))
  (let ((artifacts (run-language-test loader 'fixtures)) (fixtures (.ref loader 'fixtures)))
    (check (pair? artifacts) => #t)
    (check (length artifacts) => (length fixtures))
    (when expected-status
      (check (map syntax-fixture-expected-status fixtures)
             => (make-list (length fixtures) expected-status)))
    (for-each (lambda (artifact fixture)
                (check (parse-artifact-valid? artifact) => #t)
                (check (parse-artifact-roundtrip artifact) => (syntax-fixture-source fixture))
                (check (parse-artifact-ref artifact 'sourceDigest) => (syntax-fixture-source-digest fixture)))
              artifacts fixtures)))

(def (nonempty-language-sources sources)
  (unless (and (list? sources) (pair? sources) (andmap string? sources))
    (error "language test source collection must be nonempty strings" sources))
  sources)

(def (artifact-node-kinds artifact)
  (map (lambda (event) (vector-ref event 2))
       (filter (lambda (event) (eq? (event-kind event) 'start-node))
               (parse-artifact-events artifact))))

(def (cst-direct-nodes value)
  (cond ((syntax-node? value) (list value))
        ((syntax-field? value) (apply append (map cst-direct-nodes (syntax-field-children value))))
        (else '())))

(def (cst-lexemes value)
  (cond ((token? value) (list (token-lexeme value)))
        ((syntax-node? value) (apply append (map cst-lexemes (syntax-node-children value))))
        ((syntax-field? value) (apply append (map cst-lexemes (syntax-field-children value))))
        (else '())))

;;; Child rows select the declared node kinds through transparent fields, then
;;; require exact count/order. Other direct node kinds are not selected.
(def (cst-node-matches? value pattern)
  (and (syntax-node? value) (eq? (syntax-node-kind value) (cadr pattern))
       (andmap
        (lambda (condition)
          (case (car condition)
            ((lexemes) (andmap (lambda (text) (member text (cst-lexemes value))) (cdr condition)))
            ((children)
             (let* ((patterns (cdr condition)) (kinds (map cadr patterns))
                    (selected (filter (lambda (child) (memq (syntax-node-kind child) kinds))
                                      (apply append (map cst-direct-nodes (syntax-node-children value))))))
               (and (= (length selected) (length patterns))
                    (andmap values (map cst-node-matches? selected patterns)))))
            (else (error "unknown CST test condition" condition))))
        (cddr pattern))))

(def (artifact-subtree-matches? artifact pattern)
  (def (visit value)
    (cond ((syntax-node? value)
           (or (cst-node-matches? value pattern) (ormap visit (syntax-node-children value))))
          ((syntax-field? value) (ormap visit (syntax-field-children value)))
          (else #f)))
  (and (visit (parse-artifact->cst artifact)) #t))

(def (artifact-field-counts artifact kind field)
  (let loop ((pending (list (parse-artifact->cst artifact))) (counts '()))
    (if (null? pending) (reverse counts)
      (let (value (car pending))
        (cond
         ((syntax-node? value)
          (loop (append (syntax-node-children value) (cdr pending))
                (if (eq? (syntax-node-kind value) kind)
                  (cons (length (filter (lambda (child)
                                         (and (syntax-field? child) (eq? (syntax-field-name child) field)))
                                       (syntax-node-children value))) counts)
                  counts)))
         ((syntax-field? value) (loop (append (syntax-field-children value) (cdr pending)) counts))
         (else (loop (cdr pending) counts)))))))

(def (test-grammar-machine loader)
  (let (descriptor (.ref loader 'descriptor))
    (unless (language-grammar? descriptor) (error "grammar test requires a Grammar IR loader"))
    (language-grammar-machine descriptor)))

(def (check-parallel-language loader workers sources)
  (let* ((inputs (nonempty-language-sources sources))
         (expected (map (lambda (source) (checked-language-source loader source #t)) inputs))
         (barrier (make-barrier workers))
         (threads (map (lambda (index)
                         (spawn (lambda ()
                                  (barrier-post! barrier) (barrier-wait! barrier)
                                  (with-catch (lambda (condition) (cons 'failed condition))
                                    (lambda () (cons 'parsed ((.ref loader '.parse)
                                                             (list-ref inputs (modulo index (length inputs))))))))))
                       (iota workers)))
         (results (map thread-join! threads)))
    ;; Join all workers before propagating a parser exception.
    (for-each (lambda (result) (when (eq? (car result) 'failed) (raise (cdr result)))) results)
    (check (map cdr results)
           => (map (lambda (index) (list-ref expected (modulo index (length inputs)))) (iota workers)))))

(def (test-incremental-receipt loader source old new)
  (let* ((offset (let find ((at 0))
                    (cond ((source-prefix-at? source at old) at)
                          ((>= at (string-length source)) (error "incremental test replacement not found" old))
                          (else (find (+ at 1))))))
         (prefix (substring source 0 offset))
         (edited (string-append prefix new (substring source (+ offset (string-length old)) (string-length source))))
         (base (checked-language-source loader source #t)))
    (let-values (((artifact receipt)
                  (parse-source/incremental (test-grammar-machine loader) source base
                                            (make-edit (string-utf8-length prefix) (string-utf8-length old) new))))
      (check artifact => (checked-language-source loader edited #t))
      receipt)))

(def (test-recovery-rejection loader source)
  (let-values (((artifact receipt) (parse-source/recover (test-grammar-machine loader) source)))
    (check (parse-artifact-success? artifact) => #f)
    (check (parse-artifact-valid? artifact) => #t)
    (check (parse-artifact-roundtrip artifact) => source)
    receipt))

(def (test-parser-ir-ref ir key)
  (case key
    ((rule-count) (length (parser-ir-ref ir 'rules)))
    (else (parser-ir-ref ir key))))

(def (test-lr-value ir key)
  (let (spec (parser-ir-ref ir 'lr-spec))
    (case key
      ((state-count) (lr-spec-ref spec 'state-count))
      ((fork-count)
       (apply + (map (lambda (row) (length (filter (lambda (entry) (eq? (cadr entry) 'fork)) row)))
                     (vector->list (lr-spec-ref spec 'actions)))))
      (else (error "unknown LR test value" key)))))

(def (nullable-prefix-productions ir prefixes)
  (filter (lambda (production)
            (and (null? (production-rhs production))
                 (ormap (lambda (prefix)
                          (string-prefix? prefix (symbol->string (production-lhs production)))) prefixes)))
          (lr-spec-ref (parser-ir-ref ir 'lr-spec) 'productions)))

(def (initial-shifts? ir literals)
  (let (actions (vector-ref (lr-spec-ref (parser-ir-ref ir 'lr-spec) 'actions) 0))
    (and (andmap (lambda (literal)
                   (let (entry (assoc (list 'terminal 'literal literal) actions))
                     (and entry (eq? (cadr entry) 'shift)))) literals) #t)))

(def (test-bound-rule ir name)
  (or (bound-grammar-ir-binding ir 'rule name) (error "missing bound test rule" name)))

(def (test-bound-source binding key)
  (bound-grammar-ir-ref (bound-grammar-ir-ref binding 'source) key))

(def (test-bound-source-prefix? binding key prefix)
  (let (value (test-bound-source binding key))
    (and (string? value) (string-prefix? prefix value))))

(def (test-lr-receipt machine source budget)
  (let ((spec (parser-ir-ref (parser-machine-ir machine) 'lr-spec))
        (tokens (parser-significant-tokens machine (lex-source machine source))))
    (let-values (((_root rest receipt) (lr-parse/receipt spec tokens budget)))
      (cons (cons 'rest rest) receipt))))

(defrules language-bound-expectation (source source-prefix references reference-names binding-id)
  ((_ binding (source key expected)) (check (test-bound-source binding 'key) => expected))
  ((_ binding (source-prefix key prefix)) (check (test-bound-source-prefix? binding 'key prefix) => #t))
  ((_ binding (references expected)) (check (bound-grammar-ir-ref binding 'references) => expected))
  ((_ binding (reference-names expected))
   (check (map (lambda (row) (bound-grammar-ir-ref row 'name))
               (bound-grammar-ir-ref binding 'references)) => expected))
  ((_ binding (binding-id expected)) (check (bound-grammar-ir-ref binding 'bindingId) => expected)))

(defrules language-bound-row ()
  ((_ ir (name expectation ...))
   (let (binding (test-bound-rule ir 'name))
     (language-bound-expectation binding expectation) ...)))

(defrules language-lr-expectation (state-count fork-count empty-nullable-prefixes initial-shifts)
  ((_ ir (state-count expected)) (check (test-lr-value ir 'state-count) => expected))
  ((_ ir (fork-count expected)) (check (test-lr-value ir 'fork-count) => expected))
  ((_ ir (empty-nullable-prefixes prefix ...))
   (check (nullable-prefix-productions ir '(prefix ...)) => '()))
  ((_ ir (initial-shifts literal ...)) (check (initial-shifts? ir '(literal ...)) => #t)))

(defrules language-artifact-expectation (nodes tokens counts without-nodes diagnostics artifact-ref projection root subtree without-subtree field-counts)
  ((_ artifact (nodes kind ...))
   (begin (check (and (memq 'kind (artifact-node-kinds artifact)) #t) => #t) ...))
  ((_ artifact (without-nodes kind ...))
   (begin (check (and (memq 'kind (artifact-node-kinds artifact)) #t) => #f) ...))
  ((_ artifact (counts (kind count) ...))
   (begin (check (length (filter (lambda (value) (eq? value 'kind))
                                (artifact-node-kinds artifact))) => count) ...))
  ((_ artifact (tokens kind ...))
   (let (kinds (map token-event-token-kind (filter token-event? (parse-artifact-events artifact))))
     (check (and (memq 'kind kinds) #t) => #t) ...))
  ((_ artifact (root kind)) (check (car (artifact-node-kinds artifact)) => 'kind))
  ((_ artifact (field-counts kind field (count ...)))
   (check (artifact-field-counts artifact 'kind 'field) => '(count ...)))
  ((_ artifact (without-subtree pattern)) (check (artifact-subtree-matches? artifact 'pattern) => #f))
  ((_ artifact (subtree pattern)) (check (artifact-subtree-matches? artifact 'pattern) => #t))
  ((_ artifact (diagnostics count)) (check (length (parse-artifact-ref artifact 'diagnostics)) => count))
  ((_ artifact (diagnostics))
   (check (pair? (parse-artifact-ref artifact 'diagnostics)) => #t))
  ((_ artifact (artifact-ref key expected))
   (check (parse-artifact-ref artifact 'key) => expected))
  ((_ artifact (projection project (key expected) ...))
   (let (value (project artifact))
     (check (cdr (assq 'key value)) => expected) ...)))

(defrules language-test-clause (accepted rejected accepted-many rejected-many identity fixtures ast property bindings equal parser-ir bound-ir bound-rules lr lr-receipt parallel incremental replace recovery-rejected status installed strategy-parity fixture-parity)
  ((_ loader (accepted label source expectation ...))
   (test-case label
     (let (artifact (checked-language-source loader source #t))
       (language-artifact-expectation artifact expectation) ... (void))))
  ((_ loader (rejected label source expectation ...))
   (test-case label
     (let (artifact (checked-language-source loader source #f))
       (language-artifact-expectation artifact expectation) ... (void))))
  ((_ loader (accepted-many label sources expectation ...))
   (test-case label
     (for-each (lambda (source)
                 (let (artifact (checked-language-source loader source #t))
                   (language-artifact-expectation artifact expectation) ... (void))) (nonempty-language-sources sources))))
  ((_ loader (rejected-many label sources expectation ...))
   (test-case label
     (for-each (lambda (source)
                 (let (artifact (checked-language-source loader source #f))
                   (language-artifact-expectation artifact expectation) ... (void))) (nonempty-language-sources sources))))
  ((_ loader (identity label (key expected) ...))
   (test-case label (check (language-parser-entry-ref loader 'key) => expected) ...))
  ((_ loader (fixtures label (status expected)))
   (test-case label (checked-language-fixtures loader 'expected)))
  ((_ loader (fixtures label))
   (test-case label
     (checked-language-fixtures loader)))
  ((_ loader (ast label source pattern))
   (test-case label
     (let* ((text source) (artifact (checked-language-source loader text #t)))
       (check-parser-ast artifact text pattern))))
  ((_ loader (parallel label workers sources))
   (test-case label (check-parallel-language loader workers sources)))
  ((_ loader (incremental label source (replace old new) (key expected) ...))
   (test-case label (let (receipt (test-incremental-receipt loader source old new))
                      (check (bound-grammar-ir-ref receipt 'key) => expected) ...)))
  ((_ loader (recovery-rejected label source (key expected) ...))
   (test-case label (let (receipt (test-recovery-rejection loader source))
                      (check (bound-grammar-ir-ref receipt 'key) => expected) ...)))
  ((_ loader (parser-ir label value (key expected) ...))
   (test-case label (let (ir value) (check (test-parser-ir-ref ir 'key) => expected) ...)))
  ((_ loader (bound-ir label value (binding-count expected)))
   (test-case label (check (bound-grammar-ir-ref value 'bindingCount) => expected)))
  ((_ loader (bound-rules label value row ...))
   (test-case label (let (ir value) (language-bound-row ir row) ...)))
  ((_ loader (lr label value expectation ...))
   (test-case label (let (ir value) (language-lr-expectation ir expectation) ...)))
  ((_ loader (lr-receipt label machine source budget (key expected) ...))
   (test-case label (let (receipt (test-lr-receipt machine source budget))
                      (check (bound-grammar-ir-ref receipt 'key) => expected) ...)))
  ((_ loader (installed label route))
   (test-case label (check-language-installed loader 'route)))
  ((_ loader (strategy-parity label specification option ...))
   (test-case label (check-language-strategies loader 'specification '(option ...))))
  ((_ loader (fixture-parity label expected-status option ...))
   (test-case label
     (checked-language-fixtures loader)
     (check-language-fixture-strategies loader 'expected-status '(option ...))))
  ((_ loader (property label (bindings (name value) ...) (equal actual expected) ...))
   (test-case label
     (let* ((name value) ...)
       (check actual => expected) ...))))

;;; The loader expression is evaluated once. No free-form test-case body is
;;; accepted: each row and artifact expectation must match the closed syntax.
(defsyntax (deflanguage-parser-tests stx)
  (def (nonempty? rows pred) (and (pair? rows) (andmap pred rows)))
  (def (symbol-row? row) (and (list? row) (= (length row) 2) (symbol? (car row))))
  (def (node-pattern? pattern)
    (and (list? pattern) (>= (length pattern) 2) (eq? (car pattern) 'node) (symbol? (cadr pattern))
         (andmap (lambda (row)
                   (and (list? row) (pair? row)
                        (case (car row)
                          ((lexemes) (nonempty? (cdr row) string?))
                          ((children) (nonempty? (cdr row) node-pattern?))
                          (else #f)))) (cddr pattern))))
  (def (bound-expectation? row)
    (and (list? row) (pair? row)
         (case (car row)
           ((source source-prefix) (and (= (length row) 3) (symbol? (cadr row))))
           ((references reference-names binding-id) (= (length row) 2))
           (else #f))))
  (def (lr-expectation? row)
    (and (list? row) (pair? row)
         (case (car row)
           ((state-count fork-count) (= (length row) 2))
           ((empty-nullable-prefixes initial-shifts) (nonempty? (cdr row) string?))
           (else #f))))
  (def (expectation? row)
    (and (list? row) (pair? row)
      (case (car row)
        ((nodes tokens without-nodes) (nonempty? (cdr row) symbol?))
        ((counts) (nonempty? (cdr row) (lambda (item)
                    (and (symbol-row? item) (exact-integer? (cadr item)) (>= (cadr item) 0)))))
        ((diagnostics) (or (= (length row) 1)
                           (and (= (length row) 2) (exact-integer? (cadr row)) (>= (cadr row) 0))))
        ((root) (and (= (length row) 2) (symbol? (cadr row))))
        ((subtree without-subtree) (and (= (length row) 2) (node-pattern? (cadr row))))
        ((field-counts)
         (and (= (length row) 4) (symbol? (cadr row)) (symbol? (caddr row))
              (list? (cadddr row)) (andmap (lambda (count) (and (exact-integer? count) (>= count 0))) (cadddr row))))
        ((artifact-ref) (and (= (length row) 3) (symbol? (cadr row))))
        ((projection) (and (>= (length row) 3) (nonempty? (cddr row) symbol-row?)))
        (else #f))))
  (def (positive-integer? value) (and (exact-integer? value) (> value 0)))
  (def (nonnegative-integer? value) (and (exact-integer? value) (>= value 0)))
  (def (template? node names)
    (cond ((string? node) #t)
          ((symbol? node) (or (eq? node 'index) (memq node names)))
          ((and (list? node) (pair? node))
           (case (car node)
             ((concat) (nonempty? (cdr node) (lambda (part) (template? part names))))
             ((choice) (nonempty? (cdr node) string?))
             ((character) (and (= (length node) 2) (string? (cadr node)) (positive? (string-length (cadr node)))))
             ((integer) (and (= (length node) 3) (exact-integer? (cadr node)) (positive-integer? (caddr node))))
             ((if-even) (and (= (length node) 3) (template? (cadr node) names) (template? (caddr node) names)))
             ((repeat) (and (= (length node) 4) (nonnegative-integer? (cadr node))
                            (positive-integer? (caddr node)) (template? (cadddr node) names)))
             ((when-equal) (and (= (length node) 4) (symbol? (cadr node)) (memq (cadr node) names)
                                (string? (caddr node)) (template? (cadddr node) names)))
             ((bind)
              (and (= (length node) 3) (list? (cadr node)) (pair? (cadr node))
                   (let loop ((rows (cadr node)) (scope names) (seen '()))
                     (if (null? rows) (template? (caddr node) scope)
                       (let (row (car rows))
                         (and (symbol-row? row) (not (eq? (car row) 'index))
                              (not (memq (car row) seen)) (template? (cadr row) scope)
                              (loop (cdr rows) (cons (car row) scope) (cons (car row) seen))))))))
             (else #f)))
          (else #f)))
  (def (source-specification? spec)
    (and (list? spec) (pair? spec)
         (case (car spec)
           ((sources) (nonempty? (cdr spec) string?))
           ((indexed) (and (= (length spec) 3) (positive-integer? (cadr spec)) (template? (caddr spec) '())))
           ((seeded) (and (= (length spec) 4) (nonnegative-integer? (cadr spec)) (< (cadr spec) 2147483648)
                          (positive-integer? (caddr spec)) (template? (cadddr spec) '())))
           ((append) (nonempty? (cdr spec) source-specification?))
           (else #f))))
  (def (strategy-options? options fixture?)
    (and (pair? options)
         (let loop ((rows options) (seen '()))
           (if (null? rows)
             (and (memq 'routes seen)
                  (let (routes (cdr (assq 'routes options)))
                    (or (>= (length routes) 2) (memq 'accepted seen) (memq 'lexical seen)))
                  (or (not (memq 'coverage seen)) (memq 'lexical seen)))
             (let (row (car rows))
               (and (list? row) (pair? row) (not (memq (car row) seen))
                    (case (car row)
                      ((routes) (let route-loop ((remaining (cdr row)) (used '()))
                                  (or (null? remaining)
                                      (and (memq (car remaining) '(entry indexed source-default source-ranked source-raw source-generic))
                                           (not (memq (car remaining) used))
                                           (route-loop (cdr remaining) (cons (car remaining) used))))))
                      ((lexical) (and (= (length row) 2) (memq (cadr row) '(fast fallback optional))))
                      ((accepted) (and (= (length row) 2) (boolean? (cadr row)) (pair? (cdr (assq 'routes options)))))
                      ((coverage) (and (not fixture?) (= (length row) 3) (nonnegative-integer? (cadr row)) (nonnegative-integer? (caddr row))))
                      ((diagnostics) (and fixture? (= (length row) 2) (nonnegative-integer? (cadr row))))
                      (else #f))
                    (loop (cdr rows) (cons (car row) seen))))))))
  (def (clause? row)
    (and (list? row) (>= (length row) 2) (string? (cadr row))
         (positive? (string-length (cadr row)))
      (case (car row)
        ((accepted rejected accepted-many rejected-many)
         (and (>= (length row) 3) (andmap expectation? (cdddr row))))
        ((fixtures) (or (= (length row) 2)
                        (and (= (length row) 3) (list? (caddr row)) (= (length (caddr row)) 2)
                             (eq? (caaddr row) 'status) (memq (cadr (caddr row)) '(accepted rejected)))))
        ((identity) (nonempty? (cddr row) (lambda (item)
                       (and (symbol-row? item) (memq (car item) '(schema language version contract))))))
        ((ast) (= (length row) 4))
        ((parallel)
         (and (= (length row) 4) (exact-integer? (caddr row)) (positive? (caddr row))))
        ((incremental)
         (and (>= (length row) 5) (list? (cadddr row)) (= (length (cadddr row)) 3)
              (eq? (car (cadddr row)) 'replace) (string? (cadr (cadddr row)))
              (positive? (string-length (cadr (cadddr row)))) (string? (caddr (cadddr row)))
              (nonempty? (list-tail row 4) symbol-row?)))
        ((recovery-rejected) (and (>= (length row) 4) (nonempty? (cdddr row) symbol-row?)))
        ((parser-ir)
         (and (>= (length row) 4)
              (nonempty? (cdddr row) (lambda (item)
                (and (symbol-row? item)
                     (memq (car item) '(rule-count root-rule materialization conflict-policy case-insensitive?)))))))
        ((bound-ir)
         (and (= (length row) 4) (symbol-row? (cadddr row)) (eq? (car (cadddr row)) 'binding-count)))
        ((bound-rules)
         (and (>= (length row) 4) (nonempty? (cdddr row) (lambda (item)
                (and (list? item) (pair? item) (symbol? (car item))
                     (nonempty? (cdr item) bound-expectation?))))))
        ((lr) (and (>= (length row) 4) (nonempty? (cdddr row) lr-expectation?)))
        ((lr-receipt)
         (and (>= (length row) 6) (exact-integer? (list-ref row 4)) (positive? (list-ref row 4))
              (nonempty? (list-tail row 5) (lambda (item)
                (and (symbol-row? item) (memq (car item)
                  '(rest branchesExplored speculativeBranchesExplored maxSpeculativeDepth successfulCompletions)))))))
        ((installed) (and (= (length row) 3) (memq (caddr row) '(step source))))
        ((strategy-parity) (and (>= (length row) 4) (source-specification? (caddr row))
                                (strategy-options? (cdddr row) #f)))
        ((fixture-parity) (and (>= (length row) 4) (memq (caddr row) '(accepted rejected))
                               (strategy-options? (cdddr row) #t)))
        ((property)
         (and (>= (length row) 4) (list? (caddr row)) (pair? (caddr row))
              (eq? (caaddr row) 'bindings) (andmap symbol-row? (cdaddr row))
              (nonempty? (cdddr row) (lambda (item)
                (and (list? item) (= (length item) 3) (eq? (car item) 'equal))))))
        (else #f))))
  (syntax-case stx (loader)
    ((_ name title (loader entry) clause ...)
     (and (identifier? #'name) (stx-string? #'title))
     (let ((rows (syntax->datum #'(clause ...))) (labels '()))
       (unless (nonempty? rows clause?)
         (raise-syntax-error #f "invalid language parser test clause or expectation" stx))
       (for-each (lambda (row)
                   (when (member (cadr row) labels)
                     (raise-syntax-error #f "duplicate language parser test label" stx))
                   (set! labels (cons (cadr row) labels))) rows)
       #'(begin
           (def name (let (owner (checked-test-loader entry))
                       (test-suite title (language-test-clause owner clause) ...)))
           (export name))))
    (_ (raise-syntax-error #f "language parser tests require a name, title and loader" stx))))
