(load "scripts/native-preparation-cache.ss")
(import (only-in :std/io/tempfile make-temporary-file-name))
(def root (make-temporary-file-name "parser-preparation-controls"))
(create-directory* root)
(def input (path-expand "input.ss" root))
(def output (path-expand "output.o" root))
(def receipt (path-expand "receipt.sexp" root))
(def count 0)
;; Static phase products are outputs too, not new dependency inputs.
(def library (path-expand "lib" root))
(for-each
 (lambda (suffix)
   (unless (conformance-module-product?
             (path-expand (string-append "static/gerbil-parser__t__fixture" suffix) library)
             library '("t/fixture"))
     (error "owned static phase product admitted as input" suffix)))
 '(".scm" "~0.scm" "~1.scm" "~0.c"))
(when (conformance-module-product?
        (path-expand "static/gerbil-parser__t__fixture-other~0.scm" library)
        library '("t/fixture"))
  (error "foreign static module excluded from inputs"))
(displayln "CACHE-CONTROL-OK static-phase-ownership")
(def (put path text)
  (when (file-exists? path) (delete-file path))
  (call-with-output-file path (lambda (port) (display text port))))
(def (prepare)
  (set! count (+ count 1))
  (put output (number->string count)))
(def (run)
  (call-with-preparation-cache receipt (lambda () (list input))
    (lambda () (if (file-exists? output) (list output) '())) prepare))
(def (check-count expected)
  (unless (= count expected) (error "wrong preparation count" expected count)))
(put input "a")
(when (file-exists? receipt) (delete-file receipt))
(run) (check-count 1)
(run) (check-count 1) (displayln "CACHE-CONTROL-OK unchanged")
(put input "b") (run) (check-count 2) (displayln "CACHE-CONTROL-OK input-content")
(put output "corrupt") (run) (check-count 3) (displayln "CACHE-CONTROL-OK output-content")
(delete-file output) (run) (check-count 4) (displayln "CACHE-CONTROL-OK missing-output")
(put receipt "broken (") (run) (check-count 5) (displayln "CACHE-CONTROL-OK corrupt-receipt")
(put input "c")
(with-catch
 (lambda (_) (void))
 (lambda () (call-with-preparation-cache receipt (lambda () (list input))
             (lambda () (list output)) (lambda () (error "expected preparation failure")))))
(when (file-exists? receipt) (error "failed preparation published a receipt"))
(run) (check-count 6) (displayln "CACHE-CONTROL-OK failure-retry")
(def store (path-expand "store" root))
(def (stored-run)
  (call-with-preparation-cache receipt (lambda () (list input))
    (lambda () (if (file-exists? output) (list output) '())) prepare store
    (lambda (path) (equal? path output))))
;; Publish a fresh content record into the independently restorable store.
(delete-file receipt) (stored-run) (check-count 7)
(delete-file receipt) (delete-file output)
(stored-run) (check-count 7) (displayln "CACHE-CONTROL-OK store-restore")
(delete-file receipt) (delete-file output)
(put (preparation-store-file store 0) "corrupt")
(stored-run) (check-count 8) (displayln "CACHE-CONTROL-OK corrupt-store")
(delete-file receipt) (delete-file output)
(put input "changed-after-store")
(stored-run) (check-count 9) (displayln "CACHE-CONTROL-OK store-input-change")
;; Mutating an input during preparation can never publish a usable record.
(delete-file receipt)
(with-catch
 (lambda (_) (void))
 (lambda () (call-with-preparation-cache receipt (lambda () (list input))
             (lambda () (list output)) (lambda () (put input "mutation")))))
(when (file-exists? receipt) (error "input mutation published a receipt"))
(displayln "CACHE-CONTROL-OK input-mutation")
(delete-file-or-directory root #t)
(displayln "OK")
