;;; Source declarations admit once to closed IR and its owned executable lowering.
(import (only-in :clan/poo/object .ref)
        (only-in ../runtime/contextual-ir make-contextual-parser-ir contextual-ir-copy)
        (only-in ../language/command-profile compile-command-profile admit-command-plan command-plan-recipe command-plan-kind)
        (only-in ../language/part-profile compile-part-profile part-plan-recipe admit-part-plan)
        (only-in ../language/scanner-profile compile-scanner-profile)
        (only-in ../language/result-profile compile-result-profile result-plan-recipe result-plan-catalog)
        (only-in ../runtime/region-scanner region-plan-specification prepare-region-plan))
(export compile-command-contextual-program compile-line-contextual-program
        contextual-program? contextual-program-ir contextual-program-regions
        contextual-program-scanner contextual-program-results contextual-program-parts contextual-program-commands)
(defstruct contextual-program (owned-ir regions owned-scanner results parts commands))
(def (contextual-program-scanner program)
  (contextual-ir-copy (contextual-program-owned-scanner program)))
(def (contextual-program-ir program) (contextual-ir-copy (contextual-program-owned-ir program)))
(def (construction results)
  (append (result-plan-catalog results) (list (cons 'projections (caddr (result-plan-recipe results))))))
(def (compile-command-contextual-program candidate)
  (let* ((results (compile-result-profile (.ref candidate 'results)))
         (regions (prepare-region-plan (region-plan-specification (.ref candidate 'regions))))
         (scanner-profile (.ref candidate 'scanner))
         (scanner (compile-scanner-profile scanner-profile))
         (commands (admit-command-plan (compile-command-profile (.ref candidate 'commands)) results scanner-profile))
         (parts (admit-part-plan (compile-part-profile (.ref candidate 'parts)) results regions))
         (command-data (command-plan-recipe commands))
         (root (command-plan-kind commands 'BashFile))
         (ir (make-contextual-parser-ir
              (list (cons 'dialect 'command)
                    (cons 'program (list (cons 'commands command-data) (cons 'parts (part-plan-recipe parts)))))
              scanner
              (list (cons 'regions (region-plan-specification regions))
                    (cons 'entries (list-ref command-data 4)))
              (construction results) root)))
    (make-contextual-program ir regions scanner results parts commands)))
(def (compile-line-contextual-program candidate)
  (let* ((results (compile-result-profile (.ref candidate 'results)))
         (root (.ref candidate 'root-kind)) (token (.ref candidate 'token-kind))
         (prefix (string-copy (.ref candidate 'required-prefix)))
         (_ (unless (assq token (cdr (assq 'terminals (result-plan-catalog results))))
              (error "line recognition token is outside construction vocabulary" token)))
         (ir (make-contextual-parser-ir
              (list (cons 'dialect 'lines)
                    (cons 'program (list (cons 'token-kind token) (cons 'required-prefix prefix))))
              '((operation . newline-inclusive)) '((entries . (lines)))
              (construction results) root)))
    (make-contextual-program ir #f #f results #f #f)))
