;;; -*- Gerbil -*-
;;; A closed Scheme event fold: execute the algorithm here and serialize its
;;; typed transitions for gerbil-scheme-rust-ir. No Rust source templates.

(import (only-in :std/encoding/json json->string)
        (only-in ../language/descriptor language-grammar-machine)
        (only-in ../runtime/identity sha256-text)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ./event-strategy-aot source-line-events kind-index line-starts-with?))
(export define-event-fold-parser run-event-fold event-fold-ir-json)

(def (fold-state states name)
  (let (entry (assq name states))
    (unless entry (error "undeclared event fold state" name))
    (cdr entry)))

(def (rust-state-name name)
  (list->string
   (map (lambda (character)
          (if (char=? character #\-) #\_ character))
        (string->list (symbol->string name)))))

(def (validate-state-names states)
  (let loop ((rest states) (seen []))
    (unless (null? rest)
      (let (name (rust-state-name (caar rest)))
        (when (member name seen)
          (error "duplicate event fold state" name))
        (loop (cdr rest) (cons name seen))))))

(def (fold-state-of-type states name predicate)
  (let (value (fold-state states name))
    (unless (predicate value) (error "event fold state has wrong type" name))
    value))

(def (fold-unsigned? value)
  (and (exact-integer? value) (>= value 0)))

(def (fold-update-state states name value)
  (map (lambda (entry)
         (if (eq? (car entry) name) (cons name value) entry))
       states))

(def (fold-marker-byte value)
  (unless (and (string? value) (= (string-length value) 1)
               (< (char->integer (string-ref value 0)) 128))
    (error "event fold marker must be one ASCII byte" value))
  (char->integer (string-ref value 0)))

(def (fold-uint expression line states)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) fold-unsigned?))
    ((line-marker-level)
     (let* ((marker (integer->char (fold-marker-byte (cadr expression))))
            (separator (integer->char (fold-marker-byte (caddr expression))))
            (size (string-length line)))
       (let loop ((index 0))
         (if (and (< index size) (char=? (string-ref line index) marker))
           (loop (+ index 1))
           (if (and (> index 0) (< index size)
                    (char=? (string-ref line index) separator))
             index 0)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-uint-ir expression states allow-line?)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (hash ("kind" "usize") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) fold-unsigned?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((line-marker-level)
     (unless allow-line? (error "event fold final transition has no line" expression))
     (hash ("kind" "line_marker_level")
           ("marker" (fold-marker-byte (cadr expression)))
           ("separator" (fold-marker-byte (caddr expression)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-predicate expression line states)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) boolean?))
    ((uint-positive?) (> (fold-uint (cadr expression) line states) 0))
    ((line-starts-with)
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (line-starts-with? line (cadr expression)))
    ((not) (not (fold-predicate (cadr expression) line states)))
    ((and) (and (fold-predicate (cadr expression) line states)
                (fold-predicate (caddr expression) line states)))
    ((or) (or (fold-predicate (cadr expression) line states)
              (fold-predicate (caddr expression) line states)))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-statements statements line start end states)
  (let loop ((rest statements) (state states) (events []))
    (if (null? rest) (cons state events)
        (let* ((form (car rest))
               (step
                (case (car form)
                  ((set-bool)
                   (let (value (fold-predicate (caddr form) line state))
                     (fold-state-of-type state (cadr form) boolean?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((set-uint)
                   (let (value (fold-uint (caddr form) line state))
                     (fold-state-of-type state (cadr form) fold-unsigned?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((close-through)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line state)))
                     (let close ((rest stack) (events []))
                       (if (and (pair? rest) (>= (car rest) level))
                         (close (cdr rest) (cons '(finish) events))
                         (cons (fold-update-state state (cadr form) rest) events)))))
                  ((open-level)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line state)))
                     (cons (fold-update-state state (cadr form) (cons level stack))
                           (list (list 'start (cadddr form))))))
                  ((close-all)
                   (let (stack (fold-state-of-type state (cadr form) list?))
                     (cons (fold-update-state state (cadr form) [])
                           (map (lambda (_) '(finish)) stack))))
                  ((start-node) (cons state (list (list 'start (cadr form)))))
                  ((token)
                   (cons state (list (list 'token (cadr form)
                                          (if (eq? (caddr form) 'start) start end)
                                          (if (eq? (cadddr form) 'start) start end)))))
                  ((finish-node) (cons state (list '(finish))))
                  ((if)
                   (fold-statements
                    (if (fold-predicate (cadr form) line state)
                      (caddr form) (cadddr form))
                    line start end state))
                  (else (error "unsupported event fold statement" form)))))
          (loop (cdr rest) (car step) (append events (cdr step)))))))

(def (run-event-fold source root initial line-forms finish-forms)
  (let (states (map (lambda (entry)
                       (cons (car entry) (if (equal? (cadr entry) '(uint-stack))
                                           [] (cadr entry)))) initial))
    (let* ((events
            (source-line-events
             source root
             (lambda (line start end)
               (let (step (fold-statements line-forms line start end states))
                 (set! states (car step))
                 (cdr step)))))
           (closing (fold-statements finish-forms "" 0 0 states)))
      (append (reverse (cdr (reverse events))) (cdr closing) '((finish))))))

(def (fold-predicate-ir expression states allow-line?)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (hash ("kind" "bool") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) boolean?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((uint-positive?)
     (hash ("kind" "usize_positive")
           ("value" (fold-uint-ir (cadr expression) states allow-line?))))
    ((line-starts-with)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (hash ("kind" "line_starts_with") ("value" (cadr expression))))
    ((not)
     (hash ("kind" "not")
           ("value" (fold-predicate-ir (cadr expression) states allow-line?))))
    ((and or)
     (hash ("kind" (symbol->string (car expression)))
           ("left" (fold-predicate-ir (cadr expression) states allow-line?))
           ("right" (fold-predicate-ir (caddr expression) states allow-line?))))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-statements-ir grammar statements states allow-line?)
  (list->vector
   (map
    (lambda (form)
      (case (car form)
        ((set-bool)
         (fold-state-of-type states (cadr form) boolean?)
         (hash ("kind" "set_bool") ("name" (rust-state-name (cadr form)))
               ("value" (fold-predicate-ir (caddr form) states allow-line?))))
        ((set-uint)
         (fold-state-of-type states (cadr form) fold-unsigned?)
         (hash ("kind" "set_usize") ("name" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states allow-line?))))
        ((close-through)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_through_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states allow-line?))))
        ((open-level)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "open_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states allow-line?))
               ("syntax_kind" (kind-index grammar (cadddr form) 'node))))
        ((close-all)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_all_levels")
               ("stack" (rust-state-name (cadr form)))))
        ((start-node)
         (hash ("kind" "start_node")
               ("syntax_kind" (kind-index grammar (cadr form) 'node))))
        ((token)
         (unless allow-line?
           (error "event fold final transition has no source offsets" form))
         (unless (and (= (length form) 4)
                      (memq (caddr form) '(start end))
                      (memq (cadddr form) '(start end)))
           (error "event fold token requires source offsets" form))
         (hash ("kind" "token")
               ("syntax_kind" (kind-index grammar (cadr form) 'token))
               ("start" (symbol->string (caddr form)))
               ("end" (symbol->string (cadddr form)))))
        ((finish-node) (hash ("kind" "finish_node")))
        ((if)
         (hash ("kind" "if")
               ("condition" (fold-predicate-ir (cadr form) states allow-line?))
               ("consequent" (fold-statements-ir grammar (caddr form) states allow-line?))
               ("alternate" (fold-statements-ir grammar (cadddr form) states allow-line?))))
        (else (error "unsupported event fold statement" form))))
    statements)))

(def (event-fold-ir-json name grammar root initial line-forms finish-forms)
  (let* ((states (map (lambda (entry)
                        (unless (and (= (length entry) 2) (symbol? (car entry))
                                     (or (boolean? (cadr entry))
                                         (fold-unsigned? (cadr entry))
                                         (equal? (cadr entry) '(uint-stack))))
                          (error "event fold requires typed state" entry))
                        (cons (car entry) (if (equal? (cadr entry) '(uint-stack))
                                            [] (cadr entry)))) initial))
         (initial-ir
          (list->vector
           (map (lambda (declaration)
                  (let ((name (rust-state-name (car declaration)))
                        (value (cadr declaration)))
                    (cond
                     ((boolean? value)
                      (hash ("kind" "let_bool") ("name" name) ("value" value)))
                     ((number? value)
                      (hash ("kind" "let_usize") ("name" name) ("value" value)))
                     (else (hash ("kind" "let_usize_stack") ("name" name))))))
                initial)))
         (digest
          (sha256-text
           (call-with-output-string
            (lambda (port)
              (write (list 'event-fold.v1
                           (parser-machine-grammar-digest
                            (language-grammar-machine grammar))
                           name root initial line-forms finish-forms) port))))))
    (validate-state-names states)
    (json->string
     (hash ("schema" "gerbil-scheme-rust.event-function-ir.v1")
           ("name" (symbol->string name))
           ("root_kind" (kind-index grammar root 'node))
           ("parser_digest" digest)
           ("initial" initial-ir)
           ("line" (fold-statements-ir grammar line-forms states #t))
           ("finish" (fold-statements-ir grammar finish-forms states #f)))
     sort-keys: #t)))

(defrules define-event-fold-parser ()
  ((_ scheme-name rust-name grammar root source initial (line-form ...) (finish-form ...))
   (begin
     (def (scheme-name source)
       (run-event-fold source 'root 'initial
                       '(line-form ...) '(finish-form ...)))
     (def rust-name
       (event-fold-ir-json 'rust-name grammar 'root 'initial
                           '(line-form ...) '(finish-form ...))))))
