;;; -*- Gerbil -*-
;;; Engine-owned native strategy source. No eval or runtime opcode fallback.
(import (only-in ./event-fold-ir event-fold-ir)
        (only-in ./event-fold-program snapshot-fold-data)
        (only-in ./event-fold-scheme-context
                 current-fold-scheme-prefix current-fold-scheme-expressions
                 current-fold-scheme-definitions)
        (only-in ./event-fold-scheme-statements
                 fold-scheme-statements fold-scheme-bindings fold-scheme-initial
                 current-fold-scheme-counter fold-scheme-fresh-name))
(export event-fold-scheme-source)

(def (validate-helper-graph helpers line finish)
  (def visited (make-table test: eq?))
  (def (visit name active)
    (let (helper (assq name helpers))
      (unless helper (error "unknown native fold helper" name))
      (when (memq name active) (error "recursive native fold helper" name))
      (unless (table-ref visited name #f)
        (walk (caddr helper) (cons name active))
        (table-set! visited name #t))))
  (def (walk forms active)
    (for-each
     (lambda (form)
       (case (car form)
         ((call-source-helper)
          (visit (cadr form) active))
         ((if join-once) (walk (caddr form) active) (walk (cadddr form) active))
         ((for-line-bytes) (walk (list-ref form 4) active))
         ((with-source-bounds) (walk (cadddr form) active))))
     forms))
  (walk line '())
  (walk finish '())
  ;; Reject dormant cycles too: generated products must be closed.
  (for-each (lambda (helper) (visit (car helper) '())) helpers))

(def (helper-definition helper names)
  (let* ((initial (cadr helper))
         (bindings (fold-scheme-bindings initial))
         (parameters (if (= (length helper) 4) (cadddr helper) '()))
         (arguments (map (lambda (_) (fold-scheme-fresh-name 'argument)) parameters)))
    `(def (,(cdr (assq (car helper) names)) source-bytes from until events ,@arguments)
       (unless (<= 0 from until (u8vector-length source-bytes))
         (error "native fold helper bounds outside source"))
       (let* ((slots ,(fold-scheme-initial initial))
              (line-bytes (subu8vector source-bytes from until))
              (line (utf8->string line-bytes))
              (start from) (end until))
         ,@(map (lambda (parameter argument)
                  `(vector-set! slots ,(caddr (cdr (assq parameter bindings))) ,argument))
                parameters arguments)
         ,@(fold-scheme-statements (caddr helper) bindings '() names)
         events))))

(def (event-fold-scheme-source name grammar root initial line finish
                               (helpers '()) (parameters '()))
  (parameterize ((current-fold-scheme-counter 0)
                 (current-fold-scheme-prefix name)
                 (current-fold-scheme-expressions (make-table test: equal?))
                 (current-fold-scheme-definitions '()))
    (apply fold-scheme-source-owned grammar
           (snapshot-fold-data (list name root initial line finish helpers parameters)))))

(def (fold-scheme-source-owned grammar name root initial line finish helpers parameters)
  ;; Snapshot/cycle admission precedes the shared typed lowering. Both products
  ;; use the same grammar-kind checks, state types, helper arity and digest.
  (let* ((ir (event-fold-ir name grammar root initial line finish helpers parameters))
         (digest (hash-get ir "parser_digest"))
         (binder (string->symbol (string-append "bind-" (symbol->string name))))
         (bindings (fold-scheme-bindings initial))
         (names (map (lambda (helper) (cons (car helper) (fold-scheme-fresh-name 'helper))) helpers)))
    (validate-helper-graph helpers line finish)
    (call-with-output-string
     (lambda (port)
       (display ";;; Generated by the engine native EventFold compiler.\n" port)
       (let (forms
        `((import (only-in :std/string/utf8 utf8->string)
                  (only-in :gerbil-parser/src/runtime/source-lines
                           fold-source-byte-lines line-starts-with?)
                  (only-in :gerbil-parser/src/compiler/event-list-marker
                           event-line-indent-column scan-event-list-marker)
                  (only-in :gerbil-parser/src/runtime/event-fold-lines
                           fold-key-byte?
                           line-starts-with-ascii-ci? fold-line-prefix-boundary?
                           fold-line-blank? fold-line-has-word-after-prefix?
                           fold-line-has-key-after-prefix? fold-line-name-set-contains?)
                  (only-in :gerbil-parser/src/compiler/event-fold-future
                           current-future-scan-cache fold-future-cache-for
                           fold-future-index-for fold-future-named-index
                           fold-future-named-index-result fold-future-heading-title?
                           fold-future-marker-before-boundary? fold-source-slices-equal?))
          ,@(map (lambda (helper) (helper-definition helper names)) helpers)
          (export ,name ,binder)
          (def (,binder expected-digest)
            (unless (equal? expected-digest ,digest)
              (error "native EventFold product identity mismatch"))
            ,name)
          (def (,name source (overrides '()))
            (parameterize ((current-future-scan-cache #f))
              (let ((source-bytes (string->utf8 source))
                    (slots ,(fold-scheme-initial initial)))
                (for-each
                 (lambda (override)
                   (unless (and (exact-integer? (cdr override)) (>= (cdr override) 0))
                     (error "invalid native fold parameter override" override))
                   (case (car override)
                     ,@(map
                        (lambda (entry)
                          `((,(car entry))
                            ,(if (and (exact-integer? (cadr entry)) (>= (cadr entry) 0))
                               `(vector-set! slots ,(caddr (cdr (assq (car entry) bindings)))
                                              (cdr override))
                               `(error "native fold parameter is not unsigned" override))))
                        initial)
                     (else (error "undeclared native fold parameter" override))))
                 overrides)
                (let* ((events
                        (fold-source-byte-lines source-bytes (list '(start ,root))
                          (lambda (line line-bytes start end events)
                            (begin
                              ,@(fold-scheme-statements line bindings '() names)
                              events))))
                       (line "") (line-bytes '#u8()) (start 0) (end 0))
                  (begin
                    (void)
                    ,@(fold-scheme-statements finish bindings '() names))
                  ;; Every outer event cell is allocated by this request's
                  ;; root, transitions or closed helpers. No callback can
                  ;; retain that private spine; publication consumes it once.
                  ;; Event payloads (including quoted markers) stay untouched.
                  (reverse! (cons '(finish) events))))))))
         (for-each
          (lambda (form) (write form port) (newline port))
          (cons (car forms)
                (append (reverse (current-fold-scheme-definitions)) (cdr forms)))))))))
