;;; -*- Gerbil -*-
;;; A closed Scheme event fold: execute the algorithm here and serialize its
;;; typed transitions for gerbil-scheme-rust-ir. No Rust source templates.

(import (only-in :std/encoding/json json->string)
        (only-in ../language/descriptor language-grammar-machine)
        (only-in ../runtime/identity sha256-text)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ./event-strategy-aot source-line-events kind-index line-starts-with?))
(export define-event-fold-parser run-event-fold event-fold-ir-json)

(def (fold-state states name)
  (let (entry (assq name states))
    (unless entry (error "undeclared event fold state" name))
    (cdr entry)))

(def (rust-state-name name)
  (list->string
   (map (lambda (character)
          (if (char=? character #\-) #\_ character))
        (string->list (symbol->string name)))))

(def (validate-state-names states)
  (let loop ((rest states) (seen []))
    (unless (null? rest)
      (let (name (rust-state-name (caar rest)))
        (when (member name seen)
          (error "duplicate event fold state" name))
        (loop (cdr rest) (cons name seen))))))

(def (fold-state-of-type states name predicate)
  (let (value (fold-state states name))
    (unless (predicate value) (error "event fold state has wrong type" name))
    value))

(def (fold-unsigned? value)
  (and (exact-integer? value) (>= value 0)))

(def (fold-update-state states name value)
  (map (lambda (entry)
         (if (eq? (car entry) name) (cons name value) entry))
       states))

(def (fold-marker-byte value)
  (unless (and (string? value) (= (string-length value) 1)
               (< (char->integer (string-ref value 0)) 128))
    (error "event fold marker must be one ASCII byte" value))
  (char->integer (string-ref value 0)))

(def (ascii-lower-byte value)
  (if (and (<= 65 value) (<= value 90)) (+ value 32) value))

(def (line-starts-with-ascii-ci? line prefix)
  (let ((actual (string->utf8 line)) (expected (string->utf8 prefix)))
    (and (>= (u8vector-length actual) (u8vector-length expected))
         (let loop ((index 0))
           (or (= index (u8vector-length expected))
               (and (= (ascii-lower-byte (u8vector-ref actual index))
                       (ascii-lower-byte (u8vector-ref expected index)))
                    (loop (+ index 1))))))))

(def (fold-line-blank? line)
  (let (bytes (string->utf8 line))
    (let loop ((index 0))
      (or (= index (u8vector-length bytes))
          (and (memv (u8vector-ref bytes index) '(9 10 13 32))
               (loop (+ index 1)))))))

(def (fold-line-prefix-boundary? line prefix marker?)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((bytes (string->utf8 line))
              (start (u8vector-length (string->utf8 prefix)))
              (end (u8vector-length bytes)))
         (if marker?
           (let loop ((cursor start))
             (or (= cursor end)
                 (and (memv (u8vector-ref bytes cursor) '(9 10 13 32))
                      (loop (+ cursor 1)))))
           (or (= start end)
               (memv (u8vector-ref bytes start) '(9 10 13 32)))))))

(def (fold-ascii-prefix? value)
  (and (string? value)
       (every (lambda (character) (< (char->integer character) 128))
              (string->list value))))

(def (fold-key-byte? byte)
  (or (and (<= 48 byte) (<= byte 57))
      (and (<= 65 byte) (<= byte 90))
      (and (<= 97 byte) (<= byte 122))
      (memv byte '(45 95))))

(def (fold-line-has-key-after-prefix? line prefix)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((bytes (string->utf8 line))
              (begin (u8vector-length (string->utf8 prefix)))
              (end (u8vector-length bytes)))
         (let loop ((cursor begin))
           (if (and (< cursor end) (fold-key-byte? (u8vector-ref bytes cursor)))
             (loop (+ cursor 1))
             (and (> cursor begin) (< cursor end)
                  (= (u8vector-ref bytes cursor) 58)))))))

(def (fold-offset expression line start end)
  (cond
   ((eq? expression 'start) start)
   ((eq? expression 'end) end)
   ((not (pair? expression))
    (error "invalid event fold source offset" expression))
   (else
    (case (car expression)
      ((line-prefix-end)
       (min end (+ start (u8vector-length (string->utf8 (cadr expression))))))
      ((line-marker-end)
       (+ start (fold-uint (cons 'line-marker-level (cdr expression)) line '())))
      ((line-skip-horizontal line-scan-word line-scan-key)
       (let* ((bytes (string->utf8 line))
              (cursor (fold-offset (cadr expression) line start end)))
         (let loop ((offset cursor))
           (if (and (< offset end)
                    ((if (eq? (car expression) 'line-skip-horizontal)
                       (lambda (byte) (memv byte '(9 32)))
                       (if (eq? (car expression) 'line-scan-key)
                         fold-key-byte?
                         (lambda (byte) (not (memv byte '(9 10 13 32))))))
                     (u8vector-ref bytes (- offset start))))
             (loop (+ offset 1)) offset))))
      ((line-step)
       (min end (+ 1 (fold-offset (cadr expression) line start end))))
      ((line-trim-end)
       (let (bytes (string->utf8 line))
         (let loop ((cursor end))
           (if (and (> cursor start)
                    (memv (u8vector-ref bytes (- cursor start 1))
                          '(9 10 11 12 13 32)))
             (loop (- cursor 1)) cursor))))
      (else (error "unsupported event fold source offset" expression))))))

(def (fold-line-has-word-after-prefix? line prefix)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((end (u8vector-length (string->utf8 line)))
              (cursor (fold-offset
                       (list 'line-skip-horizontal
                             (list 'line-prefix-end prefix)) line 0 end)))
         (and (< cursor end)
              (not (memv (u8vector-ref (string->utf8 line) cursor)
                         '(9 10 13 32)))))))

(def (fold-offset-ir expression)
  (cond
   ((memq expression '(start end)) (symbol->string expression))
   ((not (pair? expression))
    (error "invalid event fold source offset" expression))
   (else
    (case (car expression)
      ((line-prefix-end)
       (unless (and (= (length expression) 2)
                    (fold-ascii-prefix? (cadr expression)))
         (error "invalid event fold line prefix offset" expression))
       (hash ("kind" "line_prefix_end") ("value" (cadr expression))))
      ((line-marker-end)
       (unless (= (length expression) 3)
         (error "invalid event fold line marker offset" expression))
       (hash ("kind" "line_marker_end")
             ("marker" (fold-marker-byte (cadr expression)))
             ("separator" (fold-marker-byte (caddr expression)))))
      ((line-skip-horizontal line-scan-word line-scan-key line-step)
       (unless (= (length expression) 2)
         (error "invalid event fold scanner offset" expression))
       (hash ("kind" (rust-state-name (car expression)))
             ("from" (fold-offset-ir (cadr expression)))))
      ((line-trim-end)
       (unless (= (length expression) 1)
         (error "invalid event fold line trim offset" expression))
       (hash ("kind" "line_trim_end")))
      (else (error "unsupported event fold source offset" expression))))))

(def (fold-uint expression line states)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) fold-unsigned?))
    ((line-marker-level)
     (let* ((marker (integer->char (fold-marker-byte (cadr expression))))
            (separator (integer->char (fold-marker-byte (caddr expression))))
            (size (string-length line)))
       (let loop ((index 0))
         (if (and (< index size) (char=? (string-ref line index) marker))
           (loop (+ index 1))
           (if (and (> index 0) (< index size)
                    (char=? (string-ref line index) separator))
             index 0)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-uint-ir expression states allow-line?)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (hash ("kind" "usize") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) fold-unsigned?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((line-marker-level)
     (unless allow-line? (error "event fold final transition has no line" expression))
     (hash ("kind" "line_marker_level")
           ("marker" (fold-marker-byte (cadr expression)))
           ("separator" (fold-marker-byte (caddr expression)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-predicate expression line states)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) boolean?))
    ((uint-positive?) (> (fold-uint (cadr expression) line states) 0))
    ((uint-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned equality" expression))
     (= (fold-uint (cadr expression) line states)
        (fold-uint (caddr expression) line states)))
    ((line-starts-with)
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (line-starts-with? line (cadr expression)))
    ((line-starts-with-ascii-ci)
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold ASCII prefix" expression))
     (line-starts-with-ascii-ci? line (cadr expression)))
    ((line-prefix-boundary-ascii-ci line-marker-ascii-ci)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold ASCII line marker" expression))
     (fold-line-prefix-boundary?
      line (cadr expression) (eq? (car expression) 'line-marker-ascii-ci)))
    ((line-blank?)
     (unless (= (length expression) 1)
       (error "invalid event fold blank-line predicate" expression))
     (fold-line-blank? line))
    ((line-has-word-after-prefix?)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold word-prefix predicate" expression))
     (fold-line-has-word-after-prefix? line (cadr expression)))
    ((line-has-key-after-prefix?)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold key-prefix predicate" expression))
     (fold-line-has-key-after-prefix? line (cadr expression)))
    ((not) (not (fold-predicate (cadr expression) line states)))
    ((and) (and (fold-predicate (cadr expression) line states)
                (fold-predicate (caddr expression) line states)))
    ((or) (or (fold-predicate (cadr expression) line states)
              (fold-predicate (caddr expression) line states)))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-statements statements line start end states)
  (let loop ((rest statements) (state states) (events []))
    (if (null? rest) (cons state events)
        (let* ((form (car rest))
               (step
                (case (car form)
                  ((set-bool)
                   (let (value (fold-predicate (caddr form) line state))
                     (fold-state-of-type state (cadr form) boolean?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((set-uint)
                   (let (value (fold-uint (caddr form) line state))
                     (fold-state-of-type state (cadr form) fold-unsigned?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((close-through)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line state)))
                     (let close ((rest stack) (events []))
                       (if (and (pair? rest) (>= (car rest) level))
                         (close (cdr rest) (cons '(finish) events))
                         (cons (fold-update-state state (cadr form) rest) events)))))
                  ((open-level)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line state)))
                     (cons (fold-update-state state (cadr form) (cons level stack))
                           (list (list 'start (cadddr form))))))
                  ((close-all)
                   (let (stack (fold-state-of-type state (cadr form) list?))
                     (cons (fold-update-state state (cadr form) [])
                           (map (lambda (_) '(finish)) stack))))
                  ((start-node) (cons state (list (list 'start (cadr form)))))
                  ((token)
                   (cons state (list (list 'token (cadr form)
                                          (fold-offset (caddr form) line start end)
                                          (fold-offset (cadddr form) line start end)))))
                  ((finish-node) (cons state (list '(finish))))
                  ((if)
                   (fold-statements
                    (if (fold-predicate (cadr form) line state)
                      (caddr form) (cadddr form))
                    line start end state))
                  (else (error "unsupported event fold statement" form)))))
          (loop (cdr rest) (car step) (append events (cdr step)))))))

(def (run-event-fold source root initial line-forms finish-forms)
  (let (states (map (lambda (entry)
                       (cons (car entry) (if (equal? (cadr entry) '(uint-stack))
                                           [] (cadr entry)))) initial))
    (let* ((events
            (source-line-events
             source root
             (lambda (line start end)
               (let (step (fold-statements line-forms line start end states))
                 (set! states (car step))
                 (cdr step)))))
           (closing (fold-statements finish-forms "" 0 0 states)))
      (append (reverse (cdr (reverse events))) (cdr closing) '((finish))))))

(def (fold-predicate-ir expression states allow-line?)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (hash ("kind" "bool") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) boolean?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((uint-positive?)
     (hash ("kind" "usize_positive")
           ("value" (fold-uint-ir (cadr expression) states allow-line?))))
    ((uint-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned equality" expression))
     (hash ("kind" "usize_equal")
           ("left" (fold-uint-ir (cadr expression) states allow-line?))
           ("right" (fold-uint-ir (caddr expression) states allow-line?))))
    ((line-starts-with)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (hash ("kind" "line_starts_with") ("value" (cadr expression))))
    ((line-starts-with-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression))
                  (every (lambda (character) (< (char->integer character) 128))
                         (string->list (cadr expression))))
       (error "invalid event fold ASCII prefix" expression))
     (hash ("kind" "line_starts_with_ascii_case_insensitive")
           ("value" (cadr expression))))
    ((line-prefix-boundary-ascii-ci line-marker-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold ASCII line marker" expression))
     (hash ("kind" (if (eq? (car expression) 'line-marker-ascii-ci)
                       "line_marker_ascii_case_insensitive"
                       "line_prefix_boundary_ascii_case_insensitive"))
           ("value" (cadr expression))))
    ((line-blank?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (= (length expression) 1)
       (error "invalid event fold blank-line predicate" expression))
     (hash ("kind" "line_blank")))
    ((line-has-word-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold word-prefix predicate" expression))
     (hash ("kind" "line_has_word_after_prefix")
           ("value" (cadr expression))))
    ((line-has-key-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold key-prefix predicate" expression))
     (hash ("kind" "line_has_key_after_prefix")
           ("value" (cadr expression))))
    ((not)
     (hash ("kind" "not")
           ("value" (fold-predicate-ir (cadr expression) states allow-line?))))
    ((and or)
     (hash ("kind" (symbol->string (car expression)))
           ("left" (fold-predicate-ir (cadr expression) states allow-line?))
           ("right" (fold-predicate-ir (caddr expression) states allow-line?))))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-statements-ir grammar statements states allow-line?)
  (list->vector
   (map
    (lambda (form)
      (case (car form)
        ((set-bool)
         (fold-state-of-type states (cadr form) boolean?)
         (hash ("kind" "set_bool") ("name" (rust-state-name (cadr form)))
               ("value" (fold-predicate-ir (caddr form) states allow-line?))))
        ((set-uint)
         (fold-state-of-type states (cadr form) fold-unsigned?)
         (hash ("kind" "set_usize") ("name" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states allow-line?))))
        ((close-through)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_through_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states allow-line?))))
        ((open-level)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "open_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states allow-line?))
               ("syntax_kind" (kind-index grammar (cadddr form) 'node))))
        ((close-all)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_all_levels")
               ("stack" (rust-state-name (cadr form)))))
        ((start-node)
         (hash ("kind" "start_node")
               ("syntax_kind" (kind-index grammar (cadr form) 'node))))
        ((token)
         (unless allow-line?
           (error "event fold final transition has no source offsets" form))
         (unless (= (length form) 4)
           (error "event fold token requires source offsets" form))
         (hash ("kind" "token")
               ("syntax_kind" (kind-index grammar (cadr form) 'token))
               ("start" (fold-offset-ir (caddr form)))
               ("end" (fold-offset-ir (cadddr form)))))
        ((finish-node) (hash ("kind" "finish_node")))
        ((if)
         (hash ("kind" "if")
               ("condition" (fold-predicate-ir (cadr form) states allow-line?))
               ("consequent" (fold-statements-ir grammar (caddr form) states allow-line?))
               ("alternate" (fold-statements-ir grammar (cadddr form) states allow-line?))))
        (else (error "unsupported event fold statement" form))))
    statements)))

(def (event-fold-ir-json name grammar root initial line-forms finish-forms)
  (let* ((states (map (lambda (entry)
                        (unless (and (= (length entry) 2) (symbol? (car entry))
                                     (or (boolean? (cadr entry))
                                         (fold-unsigned? (cadr entry))
                                         (equal? (cadr entry) '(uint-stack))))
                          (error "event fold requires typed state" entry))
                        (cons (car entry) (if (equal? (cadr entry) '(uint-stack))
                                            [] (cadr entry)))) initial))
         (initial-ir
          (list->vector
           (map (lambda (declaration)
                  (let ((name (rust-state-name (car declaration)))
                        (value (cadr declaration)))
                    (cond
                     ((boolean? value)
                      (hash ("kind" "let_bool") ("name" name) ("value" value)))
                     ((number? value)
                      (hash ("kind" "let_usize") ("name" name) ("value" value)))
                     (else (hash ("kind" "let_usize_stack") ("name" name))))))
                initial)))
         (digest
          (sha256-text
           (call-with-output-string
            (lambda (port)
              (write (list 'event-fold.v1
                           (parser-machine-grammar-digest
                            (language-grammar-machine grammar))
                           name root initial line-forms finish-forms) port))))))
    (validate-state-names states)
    (json->string
     (hash ("schema" "gerbil-scheme-rust.event-function-ir.v1")
           ("name" (symbol->string name))
           ("root_kind" (kind-index grammar root 'node))
           ("parser_digest" digest)
           ("initial" initial-ir)
           ("line" (fold-statements-ir grammar line-forms states #t))
           ("finish" (fold-statements-ir grammar finish-forms states #f)))
     sort-keys: #t)))

(defrules define-event-fold-parser ()
  ((_ scheme-name rust-name grammar root source initial (line-form ...) (finish-form ...))
   (begin
     (def (scheme-name source)
       (run-event-fold source 'root 'initial
                       '(line-form ...) '(finish-form ...)))
     (def rust-name
       (event-fold-ir-json 'rust-name grammar 'root 'initial
                           '(line-form ...) '(finish-form ...))))))
