;;; -*- Gerbil -*-
;;; A closed Scheme event fold: execute the algorithm here and serialize its
;;; typed transitions for gerbil-scheme-rust-ir. No Rust source templates.

(import (only-in :std/encoding/json json->string)
        (only-in :std/string/utf8 utf8->string)
        (only-in ../language/descriptor language-grammar-machine)
        (only-in ../runtime/identity sha256-text)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ./event-list-marker.ss
                 event-line-indent-column scan-event-list-marker)
        (only-in ./event-strategy-aot source-line-events kind-index line-starts-with?))
(export define-event-fold-parser run-event-fold event-fold-ir-json)

(def (fold-state states name)
  (let (entry (assq name states))
    (unless entry (error "undeclared event fold state" name))
    (cdr entry)))

(def (rust-state-name name)
  (list->string
   (map (lambda (character)
          (if (char=? character #\-) #\_ character))
        (string->list (symbol->string name)))))

(def (validate-state-names states)
  (let loop ((rest states) (seen []))
    (unless (null? rest)
      (let (name (rust-state-name (caar rest)))
        (when (member name seen)
          (error "duplicate event fold state" name))
        (loop (cdr rest) (cons name seen))))))

(def (fold-state-of-type states name predicate)
  (let (value (fold-state states name))
    (unless (predicate value) (error "event fold state has wrong type" name))
    value))

(def (fold-static-name-set values)
  (unless (and (pair? values)
               (every (lambda (value)
                        (and (string? value)
                             (> (string-length value) 0)
                             (every (lambda (character)
                                      (< (char->integer character) 128))
                                    (string->list value))))
                      values)
               (let loop ((rest values))
                 (or (null? (cdr rest))
                     (and (string<? (car rest) (cadr rest))
                          (loop (cdr rest))))))
    (error "event fold static name set must be sorted unique ASCII" values))
  values)

(def (fold-unsigned? value)
  (and (exact-integer? value) (>= value 0)))

(def (fold-update-state states name value)
  (map (lambda (entry)
         (if (eq? (car entry) name) (cons name value) entry))
       states))

(def (fold-marker-byte value)
  (unless (and (string? value) (= (string-length value) 1)
               (< (char->integer (string-ref value 0)) 128))
    (error "event fold marker must be one ASCII byte" value))
  (char->integer (string-ref value 0)))

(def (ascii-lower-byte value)
  (if (and (<= 65 value) (<= value 90)) (+ value 32) value))

(def (line-starts-with-ascii-ci? line prefix)
  (let ((actual (string->utf8 line)) (expected (string->utf8 prefix)))
    (and (>= (u8vector-length actual) (u8vector-length expected))
         (let loop ((index 0))
           (or (= index (u8vector-length expected))
               (and (= (ascii-lower-byte (u8vector-ref actual index))
                       (ascii-lower-byte (u8vector-ref expected index)))
                    (loop (+ index 1))))))))

(def (fold-line-blank? line)
  (let (bytes (string->utf8 line))
    (let loop ((index 0))
      (or (= index (u8vector-length bytes))
          (and (memv (u8vector-ref bytes index) '(9 10 13 32))
               (loop (+ index 1)))))))

(def (fold-line-prefix-boundary? line prefix marker?)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((bytes (string->utf8 line))
              (start (u8vector-length (string->utf8 prefix)))
              (end (u8vector-length bytes)))
         (if marker?
           (let loop ((cursor start))
             (or (= cursor end)
                 (and (memv (u8vector-ref bytes cursor) '(9 10 13 32))
                      (loop (+ cursor 1)))))
           (or (= start end)
               (memv (u8vector-ref bytes start) '(9 10 13 32)))))))

(def (fold-future-line-end bytes start)
  (let (size (u8vector-length bytes))
    (let loop ((cursor start))
      (if (or (= cursor size) (memv (u8vector-ref bytes cursor) '(10 13)))
        (if (= cursor size) cursor
          (if (and (= (u8vector-ref bytes cursor) 13)
                   (< (+ cursor 1) size)
                   (= (u8vector-ref bytes (+ cursor 1)) 10))
            (+ cursor 2) (+ cursor 1)))
        (loop (+ cursor 1))))))

(def (fold-future-marker-line? bytes start end marker indent?)
  (let* ((prefix (string->utf8 marker))
         (begin (if indent?
                  (let skip ((cursor start))
                    (if (and (< cursor end)
                             (memv (u8vector-ref bytes cursor) '(9 32)))
                      (skip (+ cursor 1)) cursor))
                  start))
         (prefix-end (+ begin (u8vector-length prefix))))
    (and (<= prefix-end end)
         (let match ((cursor begin) (index 0))
           (or (= index (u8vector-length prefix))
               (and (= (ascii-lower-byte (u8vector-ref bytes cursor))
                       (ascii-lower-byte (u8vector-ref prefix index)))
                    (match (+ cursor 1) (+ index 1)))))
         (let tail ((cursor prefix-end))
           (or (= cursor end)
               (and (memv (u8vector-ref bytes cursor) '(9 10 13 32))
                    (tail (+ cursor 1))))))))

(def (fold-source-slices-equal? bytes left-from left-until
                                right-from right-until ascii-ci?)
  (let (size (u8vector-length bytes))
    (and (<= 0 left-from left-until size)
         (<= 0 right-from right-until size)
         (= (- left-until left-from) (- right-until right-from))
         (let loop ((left left-from) (right right-from))
           (or (= left left-until)
               (and (let ((a (u8vector-ref bytes left))
                          (b (u8vector-ref bytes right)))
                      (= (if ascii-ci? (ascii-lower-byte a) a)
                         (if ascii-ci? (ascii-lower-byte b) b)))
                    (loop (+ left 1) (+ right 1))))))))

(def (fold-future-named-marker-line? bytes start end name-from name-until
                                     prefix suffix indent? ascii-ci?)
  (let* ((prefix-bytes (string->utf8 prefix))
         (suffix-bytes (string->utf8 suffix))
         (begin (if indent?
                  (let skip ((cursor start))
                    (if (and (< cursor end)
                             (memv (u8vector-ref bytes cursor) '(9 32)))
                      (skip (+ cursor 1)) cursor))
                  start))
         (prefix-end (+ begin (u8vector-length prefix-bytes)))
         (name-end (+ prefix-end (- name-until name-from)))
         (suffix-end (+ name-end (u8vector-length suffix-bytes))))
    (and (< name-from name-until)
         (<= suffix-end end)
         (let match ((cursor begin) (index 0))
           (or (= index (u8vector-length prefix-bytes))
               (and (= (if ascii-ci?
                         (ascii-lower-byte (u8vector-ref bytes cursor))
                         (u8vector-ref bytes cursor))
                       (if ascii-ci?
                         (ascii-lower-byte (u8vector-ref prefix-bytes index))
                         (u8vector-ref prefix-bytes index)))
                    (match (+ cursor 1) (+ index 1)))))
         (fold-source-slices-equal? bytes name-from name-until
                                    prefix-end name-end ascii-ci?)
         (let match ((cursor name-end) (index 0))
           (or (= index (u8vector-length suffix-bytes))
               (and (= (if ascii-ci?
                         (ascii-lower-byte (u8vector-ref bytes cursor))
                         (u8vector-ref bytes cursor))
                       (if ascii-ci?
                         (ascii-lower-byte (u8vector-ref suffix-bytes index))
                         (u8vector-ref suffix-bytes index)))
                    (match (+ cursor 1) (+ index 1)))))
         (let tail ((cursor suffix-end))
           (or (= cursor end)
               (and (memv (u8vector-ref bytes cursor) '(9 10 13 32))
                    (tail (+ cursor 1))))))))

(def (fold-future-named-marker-before-boundary?
      bytes from name-from name-until prefix suffix stop
      heading-marker heading-separator indent? stop-at-heading? ascii-ci?)
  (let search ((cursor from))
    (if (>= cursor (u8vector-length bytes)) #f
      (let (end (fold-future-line-end bytes cursor))
        (cond
         ((and stop-at-heading?
               (fold-future-heading? bytes cursor end
                                     heading-marker heading-separator)) #f)
         ((and stop (fold-future-marker-line? bytes cursor end stop indent?)) #f)
         ((fold-future-named-marker-line?
           bytes cursor end name-from name-until prefix suffix indent? ascii-ci?) #t)
         (else (search end)))))))

(def (fold-future-heading? bytes start end marker separator)
  (let run ((cursor start))
    (and (< cursor end)
         (if (= (u8vector-ref bytes cursor) marker)
           (run (+ cursor 1))
           (and (> cursor start)
                (= (u8vector-ref bytes cursor) separator))))))

(def (fold-future-key-value-line? bytes start end marker)
  (let skip ((cursor start))
    (if (and (< cursor end) (memv (u8vector-ref bytes cursor) '(9 32)))
      (skip (+ cursor 1))
      (and (< cursor end) (= (u8vector-ref bytes cursor) marker)
           (let key ((cursor (+ cursor 1)) (key-start (+ cursor 1)))
             (and (< cursor end)
                  (let (byte (u8vector-ref bytes cursor))
                    (cond
                     ((= byte marker)
                      (and (> cursor key-start)
                           (or (= (+ cursor 1) end)
                               (memv (u8vector-ref bytes (+ cursor 1))
                                     '(9 10 13 32)))))
                     ((memv byte '(9 10 13 32)) #f)
                     (else (key (+ cursor 1) key-start))))))))))

(def (fold-future-marker-before-boundary? bytes from target stop
                                           heading-marker heading-separator
                                           indent? stop-at-heading? body-key-marker)
  (let search ((cursor from))
    (if (>= cursor (u8vector-length bytes)) #f
      (let (end (fold-future-line-end bytes cursor))
        (cond
         ((and stop-at-heading?
               (fold-future-heading? bytes cursor end
                                     heading-marker heading-separator)) #f)
         ((and stop (fold-future-marker-line? bytes cursor end stop indent?)) #f)
         ((fold-future-marker-line? bytes cursor end target indent?) #t)
         ((and body-key-marker
               (not (fold-future-key-value-line? bytes cursor end
                                                 body-key-marker))) #f)
         (else (search end)))))))

(def (fold-ascii-prefix? value)
  (and (string? value)
       (every (lambda (character) (< (char->integer character) 128))
              (string->list value))))

(def (fold-key-byte? byte)
  (or (and (<= 48 byte) (<= byte 57))
      (and (<= 65 byte) (<= byte 90))
      (and (<= 97 byte) (<= byte 122))
      (memv byte '(45 95))))

(def (fold-line-has-key-after-prefix? line prefix)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((bytes (string->utf8 line))
              (begin (u8vector-length (string->utf8 prefix)))
              (end (u8vector-length bytes)))
         (let loop ((cursor begin))
           (if (and (< cursor end) (fold-key-byte? (u8vector-ref bytes cursor)))
             (loop (+ cursor 1))
             (and (> cursor begin) (< cursor end)
                  (= (u8vector-ref bytes cursor) 58)))))))

(def (fold-offset expression line start end states indices)
  (cond
   ((eq? expression 'start) start)
   ((eq? expression 'end) end)
   ((not (pair? expression))
    (error "invalid event fold source offset" expression))
   (else
    (case (car expression)
      ((line-prefix-end)
       (min end (+ start (u8vector-length (string->utf8 (cadr expression))))))
      ((line-marker-end)
       (+ start (fold-uint (cons 'line-marker-level (cdr expression))
                           line start end states indices)))
      ((line-skip-horizontal line-scan-word line-scan-key)
       (let* ((bytes (string->utf8 line))
              (cursor (fold-offset (cadr expression) line start end states indices)))
         (let loop ((offset cursor))
           (if (and (< offset end)
                    ((if (eq? (car expression) 'line-skip-horizontal)
                       (lambda (byte) (memv byte '(9 32)))
                       (if (eq? (car expression) 'line-scan-key)
                         fold-key-byte?
                         (lambda (byte) (not (memv byte '(9 10 13 32))))))
                     (u8vector-ref bytes (- offset start))))
             (loop (+ offset 1)) offset))))
      ((line-scan-nonspace-until line-scan-until)
       (unless (= (length expression) 3)
         (error "invalid event fold bounded delimiter scan" expression))
       (let* ((bytes (string->utf8 line))
              (cursor (fold-offset (cadr expression) line start end states indices))
              (delimiter (fold-marker-byte (caddr expression))))
         (let loop ((offset cursor))
           (if (and (< offset end)
                    (not (= (u8vector-ref bytes (- offset start)) delimiter))
                    (or (eq? (car expression) 'line-scan-until)
                        (not (memv (u8vector-ref bytes (- offset start))
                                   '(9 10 13 32)))))
             (loop (+ offset 1)) offset))))
      ((line-physical-end)
       (unless (= (length expression) 2)
         (error "invalid event fold physical-line scan" expression))
       (let* ((bytes (string->utf8 line))
              (from (fold-offset (cadr expression) line start end states indices)))
         (let loop ((cursor (max start (min from end))))
           (if (and (< cursor end)
                    (not (memv (u8vector-ref bytes (- cursor start)) '(10 13))))
             (loop (+ cursor 1)) cursor))))
      ((line-step)
       (min end (+ 1 (fold-offset (cadr expression) line start end states indices))))
      ((line-trim-end)
       (let (bytes (string->utf8 line))
         (let loop ((cursor end))
           (if (and (> cursor start)
                    (memv (u8vector-ref bytes (- cursor start 1))
                          '(9 10 11 12 13 32)))
             (loop (- cursor 1)) cursor))))
      ((line-trim-end-from)
       (let ((bytes (string->utf8 line))
             (floor (fold-offset (cadr expression) line start end states indices)))
         (let loop ((cursor end))
           (if (and (> cursor floor)
                    (memv (u8vector-ref bytes (- cursor start 1))
                          '(9 10 11 12 13 32)))
             (loop (- cursor 1)) cursor))))
      ((line-content-end)
       (let (bytes (string->utf8 line))
         (let loop ((cursor end))
           (if (and (> cursor start)
                    (memv (u8vector-ref bytes (- cursor start 1)) '(10 13)))
             (loop (- cursor 1)) cursor))))
      ((line-index)
       (let (entry (assq (cadr expression) indices))
         (unless entry (error "unbound event fold line index" expression))
         (cdr entry)))
      ((state-offset)
       (fold-state-of-type states (cadr expression) fold-unsigned?))
      (else (error "unsupported event fold source offset" expression))))))

(def (fold-line-has-word-after-prefix? line prefix)
  (and (line-starts-with-ascii-ci? line prefix)
       (let* ((end (u8vector-length (string->utf8 line)))
              (cursor (fold-offset
                       (list 'line-skip-horizontal
                       (list 'line-prefix-end prefix)) line 0 end '() '())))
         (and (< cursor end)
              (not (memv (u8vector-ref (string->utf8 line) cursor)
                         '(9 10 13 32)))))))

(def (fold-offset-ir expression states indices)
  (cond
   ((memq expression '(start end)) (symbol->string expression))
   ((not (pair? expression))
    (error "invalid event fold source offset" expression))
   (else
    (case (car expression)
      ((line-prefix-end)
       (unless (and (= (length expression) 2)
                    (fold-ascii-prefix? (cadr expression)))
         (error "invalid event fold line prefix offset" expression))
       (hash ("kind" "line_prefix_end") ("value" (cadr expression))))
      ((line-marker-end)
       (unless (= (length expression) 3)
         (error "invalid event fold line marker offset" expression))
       (hash ("kind" "line_marker_end")
             ("marker" (fold-marker-byte (cadr expression)))
             ("separator" (fold-marker-byte (caddr expression)))))
      ((line-skip-horizontal line-scan-word line-scan-key
        line-physical-end line-step)
       (unless (= (length expression) 2)
         (error "invalid event fold scanner offset" expression))
       (hash ("kind" (rust-state-name (car expression)))
             ("from" (fold-offset-ir (cadr expression) states indices))))
      ((line-scan-nonspace-until line-scan-until)
       (unless (= (length expression) 3)
         (error "invalid event fold bounded delimiter scan" expression))
       (hash ("kind" (rust-state-name (car expression)))
             ("from" (fold-offset-ir (cadr expression) states indices))
             ("delimiter" (fold-marker-byte (caddr expression)))))
      ((line-trim-end)
       (unless (= (length expression) 1)
         (error "invalid event fold line trim offset" expression))
       (hash ("kind" "line_trim_end")))
      ((line-trim-end-from)
       (unless (= (length expression) 2)
         (error "invalid event fold bounded line trim offset" expression))
       (hash ("kind" "line_trim_end_from")
             ("from" (fold-offset-ir (cadr expression) states indices))))
      ((line-content-end)
       (unless (= (length expression) 1)
         (error "invalid event fold line content offset" expression))
       (hash ("kind" "line_content_end")))
      ((line-index)
       (unless (and (= (length expression) 2)
                    (memq (cadr expression) indices))
         (error "unbound event fold line index" expression))
       (hash ("kind" "line_index")
             ("name" (rust-state-name (cadr expression)))))
      ((state-offset)
       (unless (= (length expression) 2)
         (error "invalid event fold state offset" expression))
       (fold-state-of-type states (cadr expression) fold-unsigned?)
       (hash ("kind" "state_offset")
             ("name" (rust-state-name (cadr expression)))))
      (else (error "unsupported event fold source offset" expression))))))

(def (fold-uint expression line start end states indices)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) fold-unsigned?))
    ((offset) (fold-offset (cadr expression) line start end states indices))
    ((line-indent-column)
     (event-line-indent-column line (cadr expression)))
    ((stack-top)
     (let (stack (fold-state-of-type states (cadr expression) list?))
       (if (null? stack) 0 (car stack))))
    ((uint-add uint-multiply uint-divide)
     (let ((left (fold-uint (cadr expression) line start end states indices))
           (right (fold-uint (caddr expression) line start end states indices)))
       (case (car expression)
         ((uint-add) (+ left right))
         ((uint-multiply) (* left right))
         (else (quotient left (max 1 right))))))
    ((line-marker-level)
     (let* ((marker (integer->char (fold-marker-byte (cadr expression))))
            (separator (integer->char (fold-marker-byte (caddr expression))))
            (size (string-length line)))
       (let loop ((index 0))
         (if (and (< index size) (char=? (string-ref line index) marker))
           (loop (+ index 1))
           (if (and (> index 0) (< index size)
                    (char=? (string-ref line index) separator))
             index 0)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-uint-ir expression states indices allow-line?)
  (case (car expression)
    ((uint)
     (unless (and (= (length expression) 2)
                  (exact-integer? (cadr expression)) (>= (cadr expression) 0))
       (error "invalid event fold unsigned value" expression))
     (hash ("kind" "usize") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) fold-unsigned?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((offset)
     (unless allow-line? (error "event fold final transition has no line" expression))
     (hash ("kind" "offset")
           ("value" (fold-offset-ir (cadr expression) states indices))))
    ((line-indent-column)
     (unless (and allow-line? (= (length expression) 2)
                  (exact-integer? (cadr expression)) (> (cadr expression) 0))
       (error "invalid event fold indentation width" expression))
     (hash ("kind" "line_indent_column")
           ("tab_width" (cadr expression))))
    ((stack-top)
     (fold-state-of-type states (cadr expression) list?)
     (hash ("kind" "stack_top")
           ("stack" (rust-state-name (cadr expression)))))
    ((uint-add uint-multiply uint-divide)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned arithmetic" expression))
     (hash ("kind" (case (car expression)
                       ((uint-add) "add")
                       ((uint-multiply) "multiply")
                       (else "divide")))
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((line-marker-level)
     (unless allow-line? (error "event fold final transition has no line" expression))
     (hash ("kind" "line_marker_level")
           ("marker" (fold-marker-byte (cadr expression)))
           ("separator" (fold-marker-byte (caddr expression)))))
    (else (error "unsupported event fold unsigned expression" expression))))

(def (fold-predicate expression source-bytes line start end states indices)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (cadr expression))
    ((state) (fold-state-of-type states (cadr expression) boolean?))
    ((uint-positive?)
     (> (fold-uint (cadr expression) line start end states indices) 0))
    ((uint-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned equality" expression))
     (= (fold-uint (cadr expression) line start end states indices)
        (fold-uint (caddr expression) line start end states indices)))
    ((uint-not-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned inequality" expression))
     (not (= (fold-uint (cadr expression) line start end states indices)
             (fold-uint (caddr expression) line start end states indices))))
    ((uint-greater?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned comparison" expression))
     (> (fold-uint (cadr expression) line start end states indices)
        (fold-uint (caddr expression) line start end states indices)))
    ((offset-less?)
     (unless (= (length expression) 3)
       (error "invalid event fold offset comparison" expression))
     (< (fold-offset (cadr expression) line start end states indices)
        (fold-offset (caddr expression) line start end states indices)))
    ((stack-nonempty?)
     (pair? (fold-state-of-type states (cadr expression) list?)))
    ((line-starts-with)
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (line-starts-with? line (cadr expression)))
    ((line-starts-with-ascii-ci)
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold ASCII prefix" expression))
     (line-starts-with-ascii-ci? line (cadr expression)))
    ((line-prefix-boundary-ascii-ci line-marker-ascii-ci)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold ASCII line marker" expression))
     (fold-line-prefix-boundary?
      line (cadr expression) (eq? (car expression) 'line-marker-ascii-ci)))
    ((line-blank?)
     (unless (= (length expression) 1)
       (error "invalid event fold blank-line predicate" expression))
     (fold-line-blank? line))
    ((future-line-marker-before-boundary?)
     (unless (and (= (length expression) 8)
                  (fold-ascii-prefix? (cadr expression))
                  (> (string-length (cadr expression)) 0)
                  (fold-ascii-prefix? (caddr expression))
                  (boolean? (list-ref expression 5))
                  (boolean? (list-ref expression 6))
                  (or (equal? (list-ref expression 7) "")
                      (and (string? (list-ref expression 7))
                           (= (string-length (list-ref expression 7)) 1))))
       (error "invalid event fold future marker search" expression))
     (fold-future-marker-before-boundary?
      source-bytes end (cadr expression)
      (and (> (string-length (caddr expression)) 0) (caddr expression))
      (fold-marker-byte (cadddr expression))
      (fold-marker-byte (list-ref expression 4))
      (list-ref expression 5) (list-ref expression 6)
      (and (> (string-length (list-ref expression 7)) 0)
           (fold-marker-byte (list-ref expression 7)))))
    ((future-named-line-marker-before-boundary?)
     (unless (and (= (length expression) 11)
                  (fold-ascii-prefix? (list-ref expression 3))
                  (> (string-length (list-ref expression 3)) 0)
                  (fold-ascii-prefix? (list-ref expression 4))
                  (fold-ascii-prefix? (list-ref expression 5))
                  (boolean? (list-ref expression 8))
                  (boolean? (list-ref expression 9))
                  (boolean? (list-ref expression 10)))
       (error "invalid event fold future named marker search" expression))
     (fold-future-named-marker-before-boundary?
      source-bytes end
      (fold-offset (cadr expression) line start end states indices)
      (fold-offset (caddr expression) line start end states indices)
      (list-ref expression 3) (list-ref expression 4)
      (and (> (string-length (list-ref expression 5)) 0)
           (list-ref expression 5))
      (fold-marker-byte (list-ref expression 6))
      (fold-marker-byte (list-ref expression 7))
      (list-ref expression 8) (list-ref expression 9)
      (list-ref expression 10)))
    ((line-has-word-after-prefix?)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold word-prefix predicate" expression))
     (fold-line-has-word-after-prefix? line (cadr expression)))
    ((line-has-key-after-prefix?)
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold key-prefix predicate" expression))
     (fold-line-has-key-after-prefix? line (cadr expression)))
    ((line-byte-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold byte predicate" expression))
     (let ((at (fold-offset (cadr expression) line start end states indices))
           (byte (caddr expression))
           (bytes (string->utf8 line)))
       (and (< at end) (= (u8vector-ref bytes (- at start)) byte))))
    ((line-bytes-all-in? line-bytes-any-in?)
     (unless (and (= (length expression) 4)
                  (list? (cadddr expression))
                  (every (lambda (byte) (and (exact-integer? byte)
                                             (<= 0 byte 255)))
                         (cadddr expression)))
       (error "invalid event fold byte-set predicate" expression))
     (let ((from (fold-offset (cadr expression) line start end states indices))
           (until (fold-offset (caddr expression) line start end states indices))
           (bytes (string->utf8 line)))
       (unless (and (<= start from) (<= from until) (<= until end))
         (error "event fold byte range outside source line" expression))
       (let loop ((cursor from))
         (if (eq? (car expression) 'line-bytes-all-in?)
           (or (= cursor until)
               (and (memv (u8vector-ref bytes (- cursor start))
                          (cadddr expression))
                    (loop (+ cursor 1))))
           (and (< cursor until)
                (or (and (memv (u8vector-ref bytes (- cursor start))
                               (cadddr expression)) #t)
                    (loop (+ cursor 1))))))))
    ((line-bytes-in-set?)
     (unless (= (length expression) 4)
       (error "invalid event fold name-set predicate" expression))
     (let* ((names (fold-static-name-set (cadddr expression)))
            (from (fold-offset (cadr expression) line start end states indices))
            (until (fold-offset (caddr expression) line start end states indices))
            (bytes (string->utf8 line)))
       (unless (and (<= start from) (<= from until) (<= until end))
         (error "event fold name range outside source line" expression))
       (ormap (lambda (name)
                (and (= (- until from) (string-length name))
                     (let loop ((index 0))
                       (or (= index (string-length name))
                           (and (= (u8vector-ref bytes (+ (- from start) index))
                                   (char->integer (string-ref name index)))
                                (loop (+ index 1)))))))
              names)))
    ((source-slices-equal? source-slices-equal-ascii-ci?)
     (unless (= (length expression) 5)
       (error "invalid event fold source-slice comparison" expression))
     (let* ((left-from (fold-offset (cadr expression) line start end states indices))
            (left-until (fold-offset (caddr expression) line start end states indices))
            (right-from (fold-offset (cadddr expression) line start end states indices))
            (right-until (fold-offset (list-ref expression 4)
                                      line start end states indices))
            (ascii-ci? (eq? (car expression)
                            'source-slices-equal-ascii-ci?)))
       (fold-source-slices-equal? source-bytes left-from left-until
                                  right-from right-until ascii-ci?)))
    ((not) (not (fold-predicate (cadr expression) source-bytes line start end states indices)))
    ((and or)
     (unless (>= (length expression) 3)
       (error "event fold boolean combination needs two predicates" expression))
     (let (evaluate (lambda (part)
                     (fold-predicate part source-bytes line start end states indices)))
       (if (eq? (car expression) 'and)
         (every evaluate (cdr expression))
         (if (ormap evaluate (cdr expression)) #t #f))))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-frame-finishes count)
  (unless (and (exact-integer? count) (> count 0) (<= count 255))
    (error "event fold frame close arity must be positive" count))
  (let loop ((remaining count) (events []))
    (if (= remaining 0) events
      (loop (- remaining 1) (cons '(finish) events)))))

(def (fold-statements statements source-bytes line start end states indices helpers)
  (let loop ((rest statements) (state states) (events []))
    (if (null? rest) (cons state events)
        (let* ((form (car rest))
               (step
                (case (car form)
                  ((set-bool)
                   (let (value (fold-predicate (caddr form) source-bytes line start end state indices))
                     (fold-state-of-type state (cadr form) boolean?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((set-uint)
                   (let (value (fold-uint (caddr form) line start end state indices))
                     (fold-state-of-type state (cadr form) fold-unsigned?)
                     (cons (fold-update-state state (cadr form) value) [])))
                  ((close-through)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line start end state indices)))
                     (let close ((rest stack) (events []))
                       (if (and (pair? rest) (>= (car rest) level))
                         (close (cdr rest) (cons '(finish) events))
                         (cons (fold-update-state state (cadr form) rest) events)))))
                  ((open-level)
                   (let* ((stack (fold-state-of-type state (cadr form) list?))
                          (level (fold-uint (caddr form) line start end state indices)))
                     (cons (fold-update-state state (cadr form) (cons level stack))
                           (list (list 'start (cadddr form))))))
                  ((close-all)
                   (let (stack (fold-state-of-type state (cadr form) list?))
                     (cons (fold-update-state state (cadr form) [])
                           (map (lambda (_) '(finish)) stack))))
                  ((start-node) (cons state (list (list 'start (cadr form)))))
                  ((token)
                   (let ((from (fold-offset (caddr form) line start end state indices))
                         (to (fold-offset (cadddr form) line start end state indices)))
                     (cons state (if (= from to) []
                                   (list (list 'token (cadr form) from to))))))
                  ((finish-node) (cons state (list '(finish))))
                  ((if)
                   (fold-statements
                    (if (fold-predicate (cadr form) source-bytes line start end state indices)
                      (caddr form) (cadddr form))
                    source-bytes line start end state indices helpers))
                  ((for-line-bytes)
                   (let ((from (fold-offset (caddr form) line start end state indices))
                         (until (fold-offset (cadddr form) line start end state indices)))
                     (unless (and (<= start from) (<= from until) (<= until end))
                       (error "event fold iteration outside source line" form))
                     (let iterate ((cursor from) (current state) (reversed []))
                       (if (= cursor until) (cons current (reverse reversed))
                         (let (step (fold-statements (list-ref form 4) source-bytes line start end
                                                      current
                                                      (cons (cons (cadr form) cursor)
                                                            indices) helpers))
                           (iterate (+ cursor 1) (car step)
                                    (foldl cons reversed (cdr step))))))))
                  ((with-source-bounds)
                   (unless (= (length form) 4)
                     (error "invalid event fold source bounds" form))
                   (let ((from (fold-offset (cadr form) line start end state indices))
                         (until (fold-offset (caddr form) line start end state indices)))
                     (unless (and (<= 0 from) (<= from until)
                                  (<= until (u8vector-length source-bytes)))
                       (error "event fold bounds outside source" form))
                     (fold-statements
                      (cadddr form) source-bytes
                      (utf8->string (subu8vector source-bytes from until))
                      from until state indices helpers)))
                  ((call-source-helper)
                   (unless (= (length form) 4)
                     (error "invalid event helper call" form))
                   (let* ((helper (assq (cadr form) helpers))
                          (from (fold-offset (caddr form) line start end state indices))
                          (until (fold-offset (cadddr form) line start end state indices)))
                     (unless helper
                       (error "unknown or recursive event helper" (cadr form)))
                     (unless (and (<= 0 from) (<= from until)
                                  (<= until (u8vector-length source-bytes)))
                       (error "event helper bounds outside source" form))
                     (let (step (fold-statements
                                (caddr helper) source-bytes
                                (utf8->string (subu8vector source-bytes from until))
                                from until (fold-initial-states (cadr helper)) '() '()))
                       (cons state (cdr step)))))
                  ((scan-list-marker)
                   (unless (= (length form) 10)
                     (error "invalid event fold list marker statement" form))
                   (let* ((marker (scan-event-list-marker
                                   line start (cadr form) (caddr form)
                                   (cadddr form)))
                          (present (list-ref form 4))
                          (column (list-ref form 5))
                          (ordered (list-ref form 6))
                          (bullet-start (list-ref form 7))
                          (bullet-end (list-ref form 8))
                          (content-start (list-ref form 9)))
                     (fold-state-of-type state present boolean?)
                     (fold-state-of-type state column fold-unsigned?)
                     (fold-state-of-type state ordered boolean?)
                     (for-each (lambda (name)
                                 (fold-state-of-type state name fold-unsigned?))
                               (list bullet-start bullet-end content-start))
                     (let (updated (fold-update-state state present (if marker #t #f)))
                       (if marker
                         (cons (fold-update-state
                                (fold-update-state
                                 (fold-update-state
                                  (fold-update-state
                                   (fold-update-state updated column (vector-ref marker 0))
                                   ordered (vector-ref marker 1))
                                  bullet-start (vector-ref marker 2))
                                 bullet-end (vector-ref marker 3))
                                content-start (vector-ref marker 4)) [])
                         (cons updated [])))))
                  ((push-frame)
                   (let ((stack (fold-state-of-type state (cadr form) list?))
                         (value (fold-uint (caddr form) line start end state indices)))
                     (cons (fold-update-state state (cadr form) (cons value stack)) [])))
                  ((pop-frame)
                   (let (stack (fold-state-of-type state (cadr form) list?))
                     (cons (fold-update-state state (cadr form)
                                              (if (pair? stack) (cdr stack) [])) [])))
                  ((close-frames-while)
                   (let (closes (fold-frame-finishes (list-ref form 3)))
                     (let close ((current state) (reversed []))
                       (let (stack (fold-state-of-type current (cadr form) list?))
                         (if (and (pair? stack)
                                  (fold-predicate (caddr form) source-bytes line start end current indices))
                           (close (fold-update-state current (cadr form) (cdr stack))
                                  (foldl cons reversed closes))
                           (cons current (reverse reversed)))))))
                  ((close-all-frames)
                   (let ((stack (fold-state-of-type state (cadr form) list?))
                         (closes (fold-frame-finishes (caddr form))))
                     (cons (fold-update-state state (cadr form) [])
                           (apply append (map (lambda (_) closes) stack)))))
                  (else (error "unsupported event fold statement" form)))))
          (loop (cdr rest) (car step) (append events (cdr step)))))))

(def (fold-initial-states initial)
  (map (lambda (entry)
         (unless (and (= (length entry) 2) (symbol? (car entry))
                      (or (boolean? (cadr entry))
                          (fold-unsigned? (cadr entry))
                          (equal? (cadr entry) '(uint-stack))))
           (error "event fold requires typed state" entry))
         (cons (car entry) (if (equal? (cadr entry) '(uint-stack))
                             [] (cadr entry)))) initial))

(def (run-event-fold source root initial line-forms finish-forms (helpers '()))
  (let ((source-bytes (string->utf8 source))
        (states (fold-initial-states initial)))
    (let* ((events
            (source-line-events
             source root
             (lambda (line start end)
               (let (step (fold-statements line-forms source-bytes line start end
                                          states '() helpers))
                 (set! states (car step))
                 (cdr step)))))
           (closing (fold-statements finish-forms source-bytes "" 0 0
                                     states '() helpers)))
      (append (reverse (cdr (reverse events))) (cdr closing) '((finish))))))

(def (fold-predicate-ir expression states indices allow-line?)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (hash ("kind" "bool") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) boolean?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((uint-positive?)
     (hash ("kind" "usize_positive")
           ("value" (fold-uint-ir (cadr expression) states indices allow-line?))))
    ((uint-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned equality" expression))
     (hash ("kind" "usize_equal")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((uint-not-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned inequality" expression))
     (hash ("kind" "usize_not_equal")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((uint-greater?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned comparison" expression))
     (hash ("kind" "usize_greater")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((offset-less?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (= (length expression) 3)
       (error "invalid event fold offset comparison" expression))
     (hash ("kind" "offset_less")
           ("left" (fold-offset-ir (cadr expression) states indices))
           ("right" (fold-offset-ir (caddr expression) states indices))))
    ((stack-nonempty?)
     (unless (= (length expression) 2)
       (error "invalid event fold stack predicate" expression))
     (fold-state-of-type states (cadr expression) list?)
     (hash ("kind" "stack_nonempty")
           ("stack" (rust-state-name (cadr expression)))))
    ((line-starts-with)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (hash ("kind" "line_starts_with") ("value" (cadr expression))))
    ((line-starts-with-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression))
                  (every (lambda (character) (< (char->integer character) 128))
                         (string->list (cadr expression))))
       (error "invalid event fold ASCII prefix" expression))
     (hash ("kind" "line_starts_with_ascii_case_insensitive")
           ("value" (cadr expression))))
    ((line-prefix-boundary-ascii-ci line-marker-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold ASCII line marker" expression))
     (hash ("kind" (if (eq? (car expression) 'line-marker-ascii-ci)
                       "line_marker_ascii_case_insensitive"
                       "line_prefix_boundary_ascii_case_insensitive"))
           ("value" (cadr expression))))
    ((line-blank?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (= (length expression) 1)
       (error "invalid event fold blank-line predicate" expression))
     (hash ("kind" "line_blank")))
    ((future-line-marker-before-boundary?)
     (unless (and allow-line? (= (length expression) 8)
                  (fold-ascii-prefix? (cadr expression))
                  (> (string-length (cadr expression)) 0)
                  (fold-ascii-prefix? (caddr expression))
                  (boolean? (list-ref expression 5))
                  (boolean? (list-ref expression 6))
                  (or (equal? (list-ref expression 7) "")
                      (and (string? (list-ref expression 7))
                           (= (string-length (list-ref expression 7)) 1))))
       (error "invalid event fold future marker search" expression))
     (hash ("kind" "future_line_marker_before_boundary")
           ("target" (cadr expression))
           ("stop" (caddr expression))
           ("heading_marker" (fold-marker-byte (cadddr expression)))
           ("heading_separator" (fold-marker-byte (list-ref expression 4)))
           ("indent" (list-ref expression 5))
           ("stop_at_heading" (list-ref expression 6))
           ("body_key_marker"
            (if (equal? (list-ref expression 7) "") 0
              (fold-marker-byte (list-ref expression 7))))))
    ((future-named-line-marker-before-boundary?)
     (unless (and allow-line? (= (length expression) 11)
                  (fold-ascii-prefix? (list-ref expression 3))
                  (> (string-length (list-ref expression 3)) 0)
                  (fold-ascii-prefix? (list-ref expression 4))
                  (fold-ascii-prefix? (list-ref expression 5))
                  (boolean? (list-ref expression 8))
                  (boolean? (list-ref expression 9))
                  (boolean? (list-ref expression 10)))
       (error "invalid event fold future named marker search" expression))
     (hash ("kind" "future_named_line_marker_before_boundary")
           ("name_from" (fold-offset-ir (cadr expression) states indices))
           ("name_until" (fold-offset-ir (caddr expression) states indices))
           ("target_prefix" (list-ref expression 3))
           ("target_suffix" (list-ref expression 4))
           ("stop" (list-ref expression 5))
           ("heading_marker" (fold-marker-byte (list-ref expression 6)))
           ("heading_separator" (fold-marker-byte (list-ref expression 7)))
           ("indent" (list-ref expression 8))
           ("stop_at_heading" (list-ref expression 9))
           ("ascii_case_insensitive" (list-ref expression 10))))
    ((line-has-word-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold word-prefix predicate" expression))
     (hash ("kind" "line_has_word_after_prefix")
           ("value" (cadr expression))))
    ((line-has-key-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold key-prefix predicate" expression))
     (hash ("kind" "line_has_key_after_prefix")
           ("value" (cadr expression))))
    ((line-byte-equal?)
     (unless (and allow-line? (= (length expression) 3)
                  (exact-integer? (caddr expression))
                  (<= 0 (caddr expression) 255))
       (error "invalid event fold byte predicate" expression))
     (hash ("kind" "line_byte_equal")
           ("at" (fold-offset-ir (cadr expression) states indices))
           ("value" (caddr expression))))
    ((line-bytes-all-in? line-bytes-any-in?)
     (unless (and allow-line? (= (length expression) 4)
                  (list? (cadddr expression))
                  (every (lambda (byte) (and (exact-integer? byte)
                                             (<= 0 byte 255)))
                         (cadddr expression)))
       (error "invalid event fold byte-set predicate" expression))
     (hash ("kind" (if (eq? (car expression) 'line-bytes-all-in?)
                       "line_bytes_all_in" "line_bytes_any_in"))
           ("from" (fold-offset-ir (cadr expression) states indices))
           ("until" (fold-offset-ir (caddr expression) states indices))
           ("values" (list->vector (cadddr expression)))))
    ((line-bytes-in-set?)
     (unless (and allow-line? (= (length expression) 4))
       (error "invalid event fold name-set predicate" expression))
     (hash ("kind" "line_bytes_in_set")
           ("from" (fold-offset-ir (cadr expression) states indices))
           ("until" (fold-offset-ir (caddr expression) states indices))
           ("values" (list->vector
                       (fold-static-name-set (cadddr expression))))))
    ((source-slices-equal? source-slices-equal-ascii-ci?)
     (unless (and allow-line? (= (length expression) 5))
       (error "invalid event fold source-slice comparison" expression))
     (hash ("kind" "source_slices_equal")
           ("left_from" (fold-offset-ir (cadr expression) states indices))
           ("left_until" (fold-offset-ir (caddr expression) states indices))
           ("right_from" (fold-offset-ir (cadddr expression) states indices))
           ("right_until"
            (fold-offset-ir (list-ref expression 4) states indices))
           ("ascii_case_insensitive"
            (eq? (car expression) 'source-slices-equal-ascii-ci?))))
    ((not)
     (hash ("kind" "not")
           ("value" (fold-predicate-ir (cadr expression) states indices allow-line?))))
    ((and or)
     (unless (>= (length expression) 3)
       (error "event fold boolean combination needs two predicates" expression))
     (let ((kind (symbol->string (car expression)))
           (parts (map (lambda (part)
                         (fold-predicate-ir part states indices allow-line?))
                       (cdr expression))))
       (foldl (lambda (left right)
                (hash ("kind" kind) ("left" left) ("right" right)))
              (car parts) (cdr parts))))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-statements-ir grammar statements states indices allow-line? (helpers '()))
  (list->vector
   (map
    (lambda (form)
      (case (car form)
        ((set-bool)
         (fold-state-of-type states (cadr form) boolean?)
         (hash ("kind" "set_bool") ("name" (rust-state-name (cadr form)))
               ("value" (fold-predicate-ir (caddr form) states indices allow-line?))))
        ((set-uint)
         (fold-state-of-type states (cadr form) fold-unsigned?)
         (hash ("kind" "set_usize") ("name" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((close-through)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_through_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((open-level)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "open_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states indices allow-line?))
               ("syntax_kind" (kind-index grammar (cadddr form) 'node))))
        ((close-all)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_all_levels")
               ("stack" (rust-state-name (cadr form)))))
        ((start-node)
         (hash ("kind" "start_node")
               ("syntax_kind" (kind-index grammar (cadr form) 'node))))
        ((token)
         (unless (= (length form) 4)
           (error "event fold token requires source offsets" form))
         (unless (or allow-line?
                     (and (pair? (caddr form))
                          (eq? (caaddr form) 'state-offset)
                          (pair? (cadddr form))
                          (eq? (car (cadddr form)) 'state-offset)))
           (error "event fold final token requires saved source offsets" form))
         (hash ("kind" "token")
               ("syntax_kind" (kind-index grammar (cadr form) 'token))
               ("start" (fold-offset-ir (caddr form) states indices))
               ("end" (fold-offset-ir (cadddr form) states indices))))
        ((finish-node) (hash ("kind" "finish_node")))
        ((if)
         (hash ("kind" "if")
               ("condition" (fold-predicate-ir (cadr form) states indices allow-line?))
               ("consequent" (fold-statements-ir grammar (caddr form) states indices
                                                 allow-line? helpers))
               ("alternate" (fold-statements-ir grammar (cadddr form) states indices
                                                allow-line? helpers))))
        ((for-line-bytes)
         (unless (and allow-line? (= (length form) 5)
                      (symbol? (cadr form))
                      (not (assq (cadr form) states))
                      (not (memq (cadr form) indices)))
           (error "invalid event fold source-line iteration" form))
         (hash ("kind" "for_line_bytes")
               ("index" (rust-state-name (cadr form)))
               ("from" (fold-offset-ir (caddr form) states indices))
               ("until" (fold-offset-ir (cadddr form) states indices))
               ("body" (fold-statements-ir grammar (list-ref form 4) states
                                           (cons (cadr form) indices)
                                           allow-line? helpers))))
        ((with-source-bounds)
         (unless (and (= (length form) 4)
                      (or allow-line?
                          (and (pair? (cadr form))
                               (eq? (caadr form) 'state-offset)
                               (pair? (caddr form))
                               (eq? (caaddr form) 'state-offset))))
           (error "event fold final bounds require saved source offsets" form))
         (hash ("kind" "with_source_bounds")
               ("from" (fold-offset-ir (cadr form) states indices))
               ("until" (fold-offset-ir (caddr form) states indices))
               ("body" (fold-statements-ir grammar (cadddr form)
                                           states indices #t helpers))))
        ((call-source-helper)
         (unless (and (= (length form) 4)
                      (symbol? (cadr form))
                      (assq (cadr form) helpers)
                      (or allow-line?
                          (and (pair? (caddr form))
                               (eq? (caaddr form) 'state-offset)
                               (pair? (cadddr form))
                               (eq? (car (cadddr form)) 'state-offset))))
           (error "unknown or invalid event helper call" form))
         (hash ("kind" "call_source_helper")
               ("name" (rust-state-name (cadr form)))
               ("from" (fold-offset-ir (caddr form) states indices))
               ("until" (fold-offset-ir (cadddr form) states indices))))
        ((scan-list-marker)
         (unless (and allow-line? (= (length form) 10)
                      (string? (cadr form))
                      (boolean? (caddr form))
                      (exact-integer? (cadddr form))
                      (> (cadddr form) 0))
           (error "invalid event fold list marker statement" form))
         (fold-state-of-type states (list-ref form 4) boolean?)
         (fold-state-of-type states (list-ref form 5) fold-unsigned?)
         (fold-state-of-type states (list-ref form 6) boolean?)
         (for-each (lambda (name)
                     (fold-state-of-type states name fold-unsigned?))
                   (list (list-ref form 7) (list-ref form 8) (list-ref form 9)))
         (hash ("kind" "scan_list_marker")
               ("marker"
                (hash ("unordered" (cadr form))
                      ("ordered" (caddr form))
                      ("tab_width" (cadddr form))
                      ("present" (rust-state-name (list-ref form 4)))
                      ("column" (rust-state-name (list-ref form 5)))
                      ("ordered_slot" (rust-state-name (list-ref form 6)))
                      ("bullet_start" (rust-state-name (list-ref form 7)))
                      ("bullet_end" (rust-state-name (list-ref form 8)))
                      ("content_start" (rust-state-name (list-ref form 9)))))))
        ((push-frame)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "push_frame")
               ("stack" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((pop-frame)
         (unless (= (length form) 2)
           (error "invalid event fold frame pop" form))
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "pop_frame")
               ("stack" (rust-state-name (cadr form)))))
        ((close-frames-while)
         (fold-state-of-type states (cadr form) list?)
         (fold-frame-finishes (list-ref form 3))
         (hash ("kind" "close_frames_while")
               ("stack" (rust-state-name (cadr form)))
               ("condition" (fold-predicate-ir (caddr form) states indices allow-line?))
               ("finish_count" (list-ref form 3))))
        ((close-all-frames)
         (fold-state-of-type states (cadr form) list?)
         (fold-frame-finishes (caddr form))
         (hash ("kind" "close_all_frames")
               ("stack" (rust-state-name (cadr form)))
               ("finish_count" (caddr form))))
        (else (error "unsupported event fold statement" form))))
    statements)))

(def (fold-initial-ir initial)
  (list->vector
   (map (lambda (declaration)
          (let ((name (rust-state-name (car declaration)))
                (value (cadr declaration)))
            (cond
             ((boolean? value)
              (hash ("kind" "let_bool") ("name" name) ("value" value)))
             ((number? value)
              (hash ("kind" "let_usize") ("name" name) ("value" value)))
             (else (hash ("kind" "let_usize_stack") ("name" name))))))
        initial)))

(def (event-fold-ir-json name grammar root initial line-forms finish-forms
                         (helpers '()))
  (let* ((states (fold-initial-states initial))
         (helper-ir
          (list->vector
           (map (lambda (helper)
                  (unless (and (= (length helper) 3)
                               (symbol? (car helper)))
                    (error "invalid event helper declaration" helper))
                  (let ((local-states (fold-initial-states (cadr helper))))
                    (validate-state-names local-states)
                    (hash ("name" (rust-state-name (car helper)))
                          ("initial" (fold-initial-ir (cadr helper)))
                          ("body" (fold-statements-ir grammar (caddr helper)
                                                      local-states '() #t)))))
                helpers)))
         (digest
          (sha256-text
           (call-with-output-string
            (lambda (port)
              (write (append
                      (list 'event-fold.v1
                            (parser-machine-grammar-digest
                             (language-grammar-machine grammar))
                            name root initial line-forms finish-forms)
                      (if (null? helpers) '() (list helpers))) port)))))
         (payload
          (hash ("schema" "gerbil-scheme-rust.event-function-ir.v1")
                ("name" (symbol->string name))
                ("root_kind" (kind-index grammar root 'node))
                ("parser_digest" digest)
                ("initial" (fold-initial-ir initial))
                ("line" (fold-statements-ir grammar line-forms states '() #t helpers))
                ("finish" (fold-statements-ir grammar finish-forms states '() #f helpers)))))
    (validate-state-names states)
    (validate-state-names
     (map (lambda (helper) (cons (car helper) #f)) helpers))
    (when (pair? helpers) (hash-put! payload "helpers" helper-ir))
    (json->string payload sort-keys: #t)))

(defrules define-event-fold-parser ()
  ((_ scheme-name rust-name grammar root source initial (line-form ...) (finish-form ...))
   (begin
     (def (scheme-name source)
       (run-event-fold source 'root 'initial
                       '(line-form ...) '(finish-form ...)))
     (def rust-name
       (event-fold-ir-json 'rust-name grammar 'root 'initial
                           '(line-form ...) '(finish-form ...))))))
