;;; -*- Gerbil -*-
;;; Serialize the Scheme event fold as typed, source-owned AOT IR.
(import (only-in :std/encoding/json json->string)
        (only-in ../language/descriptor language-grammar-machine)
        (only-in ../runtime/identity sha256-text)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ./event-strategy-aot kind-index)
        (only-in ./event-fold-future.ss fold-future-heading-spec?)
        (only-in ./event-fold-runtime.ss
                 fold-ascii-prefix? fold-frame-finishes
                 fold-initial-states fold-marker-byte
                 fold-offset-ir fold-state-of-type fold-static-name-set fold-uint-ir
                 fold-unsigned? rust-state-name validate-state-names))
(export event-fold-ir-json)
(def (fold-predicate-ir expression states indices allow-line?)
  (unless (pair? expression)
    (error "event fold predicate must be structured" expression))
  (case (car expression)
    ((bool)
     (unless (and (= (length expression) 2) (boolean? (cadr expression)))
       (error "invalid event fold boolean" expression))
     (hash ("kind" "bool") ("value" (cadr expression))))
    ((state)
     (fold-state-of-type states (cadr expression) boolean?)
     (hash ("kind" "state") ("name" (rust-state-name (cadr expression)))))
    ((uint-positive?)
     (hash ("kind" "usize_positive")
           ("value" (fold-uint-ir (cadr expression) states indices allow-line?))))
    ((uint-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned equality" expression))
     (hash ("kind" "usize_equal")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((uint-not-equal?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned inequality" expression))
     (hash ("kind" "usize_not_equal")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((uint-greater?)
     (unless (= (length expression) 3)
       (error "invalid event fold unsigned comparison" expression))
     (hash ("kind" "usize_greater")
           ("left" (fold-uint-ir (cadr expression) states indices allow-line?))
           ("right" (fold-uint-ir (caddr expression) states indices allow-line?))))
    ((offset-less?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (= (length expression) 3)
       (error "invalid event fold offset comparison" expression))
     (hash ("kind" "offset_less")
           ("left" (fold-offset-ir (cadr expression) states indices))
           ("right" (fold-offset-ir (caddr expression) states indices))))
    ((stack-nonempty?)
     (unless (= (length expression) 2)
       (error "invalid event fold stack predicate" expression))
     (fold-state-of-type states (cadr expression) list?)
     (hash ("kind" "stack_nonempty")
           ("stack" (rust-state-name (cadr expression)))))
    ((line-starts-with)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression)))
       (error "invalid event fold prefix" expression))
     (hash ("kind" "line_starts_with") ("value" (cadr expression))))
    ((line-starts-with-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2) (string? (cadr expression))
                  (every (lambda (character) (< (char->integer character) 128))
                         (string->list (cadr expression))))
       (error "invalid event fold ASCII prefix" expression))
     (hash ("kind" "line_starts_with_ascii_case_insensitive")
           ("value" (cadr expression))))
    ((line-prefix-boundary-ascii-ci line-marker-ascii-ci)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold ASCII line marker" expression))
     (hash ("kind" (if (eq? (car expression) 'line-marker-ascii-ci)
                       "line_marker_ascii_case_insensitive"
                       "line_prefix_boundary_ascii_case_insensitive"))
           ("value" (cadr expression))))
    ((line-blank?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (= (length expression) 1)
       (error "invalid event fold blank-line predicate" expression))
     (hash ("kind" "line_blank")))
    ((future-line-marker-before-boundary?)
     (unless (and allow-line? (= (length expression) 8)
                  (fold-ascii-prefix? (cadr expression))
                  (> (string-length (cadr expression)) 0)
                  (fold-ascii-prefix? (caddr expression))
                  (boolean? (list-ref expression 5))
                  (boolean? (list-ref expression 6))
                  (or (equal? (list-ref expression 7) "")
                      (and (string? (list-ref expression 7))
                           (= (string-length (list-ref expression 7)) 1))))
       (error "invalid event fold future marker search" expression))
     (hash ("kind" "future_line_marker_before_boundary")
           ("target" (cadr expression))
           ("stop" (caddr expression))
           ("heading_marker" (fold-marker-byte (cadddr expression)))
           ("heading_separator" (fold-marker-byte (list-ref expression 4)))
           ("indent" (list-ref expression 5))
           ("stop_at_heading" (list-ref expression 6))
           ("body_key_marker"
            (if (equal? (list-ref expression 7) "") 0
                (fold-marker-byte (list-ref expression 7))))))
    ((future-heading-title?)
     (unless (and allow-line? (fold-future-heading-spec? expression))
       (error "invalid event fold future heading" expression))
     (hash ("kind" "future_heading_title")
           ("heading_marker" (fold-marker-byte (cadr expression)))
           ("heading_separator" (fold-marker-byte (caddr expression)))
           ("min_level"
            (fold-uint-ir
             (let (level (list-ref expression 3))
               (if (pair? level) level `(uint ,level)))
             states indices allow-line?))
           ("title" (list-ref expression 4))))
    ((future-named-line-marker-before-boundary?)
     (unless (and allow-line? (memv (length expression) '(11 16))
                  (fold-ascii-prefix? (list-ref expression 3))
                  (> (string-length (list-ref expression 3)) 0)
                  (fold-ascii-prefix? (list-ref expression 4))
                  (fold-ascii-prefix? (list-ref expression 5))
                  (boolean? (list-ref expression 8))
                  (boolean? (list-ref expression 9))
                  (boolean? (list-ref expression 10))
                  (or (= (length expression) 11)
                      (and (fold-ascii-prefix? (list-ref expression 13))
                           (> (string-length (list-ref expression 13)) 0)
                           (fold-ascii-prefix? (list-ref expression 14))
                           (boolean? (list-ref expression 15))
                           (equal? (list-ref expression 5) ""))))
       (error "invalid event fold future named marker search" expression))
     (let (payload
           (hash ("kind" "future_named_line_marker_before_boundary")
           ("name_from" (fold-offset-ir (cadr expression) states indices))
           ("name_until" (fold-offset-ir (caddr expression) states indices))
           ("target_prefix" (list-ref expression 3))
           ("target_suffix" (list-ref expression 4))
           ("stop" (list-ref expression 5))
           ("heading_marker" (fold-marker-byte (list-ref expression 6)))
           ("heading_separator" (fold-marker-byte (list-ref expression 7)))
           ("indent" (list-ref expression 8))
           ("stop_at_heading" (list-ref expression 9))
           ("ascii_case_insensitive" (list-ref expression 10))))
       (when (= (length expression) 16)
         (hash-put! payload "stop_name_from"
                    (fold-offset-ir (list-ref expression 11) states indices))
         (hash-put! payload "stop_name_until"
                    (fold-offset-ir (list-ref expression 12) states indices))
         (hash-put! payload "stop_prefix" (list-ref expression 13))
         (hash-put! payload "stop_suffix" (list-ref expression 14))
         (hash-put! payload "stop_ascii_case_insensitive"
                    (list-ref expression 15)))
       payload))
    ((line-has-word-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold word-prefix predicate" expression))
     (hash ("kind" "line_has_word_after_prefix")
           ("value" (cadr expression))))
    ((line-has-key-after-prefix?)
     (unless allow-line?
       (error "event fold final transition has no source line" expression))
     (unless (and (= (length expression) 2)
                  (fold-ascii-prefix? (cadr expression)))
       (error "invalid event fold key-prefix predicate" expression))
     (hash ("kind" "line_has_key_after_prefix")
           ("value" (cadr expression))))
    ((line-byte-equal?)
     (unless (and allow-line? (= (length expression) 3)
                  (exact-integer? (caddr expression))
                  (<= 0 (caddr expression) 255))
       (error "invalid event fold byte predicate" expression))
     (hash ("kind" "line_byte_equal")
           ("at" (fold-offset-ir (cadr expression) states indices))
           ("value" (caddr expression))))
    ((line-bytes-all-in? line-bytes-any-in?)
     (unless (and allow-line? (= (length expression) 4)
                  (list? (cadddr expression))
                  (every (lambda (byte) (and (exact-integer? byte)
                                             (<= 0 byte 255)))
                         (cadddr expression)))
       (error "invalid event fold byte-set predicate" expression))
     (hash ("kind" (if (eq? (car expression) 'line-bytes-all-in?)
                       "line_bytes_all_in" "line_bytes_any_in"))
           ("from" (fold-offset-ir (cadr expression) states indices))
           ("until" (fold-offset-ir (caddr expression) states indices))
           ("values" (list->vector (cadddr expression)))))
    ((line-bytes-in-set?)
     (unless (and allow-line? (= (length expression) 4))
       (error "invalid event fold name-set predicate" expression))
     (hash ("kind" "line_bytes_in_set")
           ("from" (fold-offset-ir (cadr expression) states indices))
           ("until" (fold-offset-ir (caddr expression) states indices))
           ("values" (list->vector
                       (fold-static-name-set (cadddr expression))))))
    ((source-slices-equal? source-slices-equal-ascii-ci?)
     (unless (and allow-line? (= (length expression) 5))
       (error "invalid event fold source-slice comparison" expression))
     (hash ("kind" "source_slices_equal")
           ("left_from" (fold-offset-ir (cadr expression) states indices))
           ("left_until" (fold-offset-ir (caddr expression) states indices))
           ("right_from" (fold-offset-ir (cadddr expression) states indices))
           ("right_until"
            (fold-offset-ir (list-ref expression 4) states indices))
           ("ascii_case_insensitive"
            (eq? (car expression) 'source-slices-equal-ascii-ci?))))
    ((not)
     (hash ("kind" "not")
           ("value" (fold-predicate-ir (cadr expression) states indices allow-line?))))
    ((and or)
     (unless (>= (length expression) 3)
       (error "event fold boolean combination needs two predicates" expression))
     (let ((kind (symbol->string (car expression)))
           (parts (map (lambda (part)
                         (fold-predicate-ir part states indices allow-line?))
                       (cdr expression))))
       (foldl (lambda (left right)
                (hash ("kind" kind) ("left" left) ("right" right)))
              (car parts) (cdr parts))))
    (else (error "unsupported event fold predicate" expression))))

(def (fold-final-token-offset? expression)
  (and (pair? expression)
       (eq? (car expression) (quote state-offset))
       (= (length expression) 2)))

(def (fold-statements-ir grammar statements states indices allow-line? (helpers '()))
  (list->vector
   (map
    (lambda (form)
      (case (car form)
        ((set-bool)
         (fold-state-of-type states (cadr form) boolean?)
         (hash ("kind" "set_bool") ("name" (rust-state-name (cadr form)))
               ("value" (fold-predicate-ir (caddr form) states indices allow-line?))))
        ((set-uint)
         (fold-state-of-type states (cadr form) fold-unsigned?)
         (hash ("kind" "set_usize") ("name" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((close-through)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_through_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((open-level)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "open_level")
               ("stack" (rust-state-name (cadr form)))
               ("level" (fold-uint-ir (caddr form) states indices allow-line?))
               ("syntax_kind" (kind-index grammar (cadddr form) 'node))))
        ((close-all)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "close_all_levels")
               ("stack" (rust-state-name (cadr form)))))
        ((start-node)
         (hash ("kind" "start_node")
               ("syntax_kind" (kind-index grammar (cadr form) 'node))))
        ((token)
         (unless (= (length form) 4)
           (error "event fold token requires source offsets" form))
         (unless (or allow-line?
                     (and (fold-final-token-offset? (caddr form))
                          (fold-final-token-offset? (cadddr form))))
           (error "event fold final token requires saved source offsets" form))
         (hash ("kind" "token")
               ("syntax_kind" (kind-index grammar (cadr form) 'token))
               ("start" (fold-offset-ir (caddr form) states indices))
               ("end" (fold-offset-ir (cadddr form) states indices))))
        ((finish-node) (hash ("kind" "finish_node")))
        ((if)
         (hash ("kind" "if")
               ("condition" (fold-predicate-ir (cadr form) states indices allow-line?))
               ("consequent" (fold-statements-ir grammar (caddr form) states indices
                                                 allow-line? helpers))
               ("alternate" (fold-statements-ir grammar (cadddr form) states indices
                                                allow-line? helpers))))
        ((for-line-bytes)
         (unless (and allow-line? (= (length form) 5)
                      (symbol? (cadr form))
                      (not (assq (cadr form) states))
                      (not (memq (cadr form) indices)))
           (error "invalid event fold source-line iteration" form))
         (hash ("kind" "for_line_bytes")
               ("index" (rust-state-name (cadr form)))
               ("from" (fold-offset-ir (caddr form) states indices))
               ("until" (fold-offset-ir (cadddr form) states indices))
               ("body" (fold-statements-ir grammar (list-ref form 4) states
                                           (cons (cadr form) indices)
                                           allow-line? helpers))))
        ((with-source-bounds)
         (unless (and (= (length form) 4)
                      (or allow-line?
                          (and (pair? (cadr form))
                               (eq? (caadr form) 'state-offset)
                               (pair? (caddr form))
                               (eq? (caaddr form) 'state-offset))))
           (error "event fold final bounds require saved source offsets" form))
         (hash ("kind" "with_source_bounds")
               ("from" (fold-offset-ir (cadr form) states indices))
               ("until" (fold-offset-ir (caddr form) states indices))
               ("body" (fold-statements-ir grammar (cadddr form)
                                           states indices #t helpers))))
        ((call-source-helper)
         (unless (and (memv (length form) '(4 5))
                      (symbol? (cadr form))
                      (assq (cadr form) helpers)
                      (or allow-line?
                          (and (pair? (caddr form))
                               (eq? (caaddr form) 'state-offset)
                               (pair? (cadddr form))
                               (eq? (car (cadddr form)) 'state-offset))))
           (error "unknown or invalid event helper call" form))
         (let* ((helper (assq (cadr form) helpers))
                (parameters (if (= (length helper) 4) (cadddr helper) '()))
                (arguments (if (= (length form) 5) (list-ref form 4) '())))
           (unless (and (list? arguments)
                        (= (length parameters) (length arguments)))
             (error "event helper argument arity" form))
           (hash ("kind" "call_source_helper")
                 ("name" (rust-state-name (cadr form)))
                 ("from" (fold-offset-ir (caddr form) states indices))
                 ("until" (fold-offset-ir (cadddr form) states indices))
                 ("arguments"
                  (list->vector
                   (map (lambda (argument)
                          (fold-uint-ir argument states indices allow-line?))
                        arguments))))))
        ((scan-list-marker)
         (unless (and allow-line? (= (length form) 10)
                      (string? (cadr form))
                      (boolean? (caddr form))
                      (exact-integer? (cadddr form))
                      (> (cadddr form) 0))
           (error "invalid event fold list marker statement" form))
         (fold-state-of-type states (list-ref form 4) boolean?)
         (fold-state-of-type states (list-ref form 5) fold-unsigned?)
         (fold-state-of-type states (list-ref form 6) boolean?)
         (for-each (lambda (name)
                     (fold-state-of-type states name fold-unsigned?))
                   (list (list-ref form 7) (list-ref form 8) (list-ref form 9)))
         (hash ("kind" "scan_list_marker")
               ("marker"
                (hash ("unordered" (cadr form))
                      ("ordered" (caddr form))
                      ("tab_width" (cadddr form))
                      ("present" (rust-state-name (list-ref form 4)))
                      ("column" (rust-state-name (list-ref form 5)))
                      ("ordered_slot" (rust-state-name (list-ref form 6)))
                      ("bullet_start" (rust-state-name (list-ref form 7)))
                      ("bullet_end" (rust-state-name (list-ref form 8)))
                      ("content_start" (rust-state-name (list-ref form 9)))))))
        ((push-frame)
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "push_frame")
               ("stack" (rust-state-name (cadr form)))
               ("value" (fold-uint-ir (caddr form) states indices allow-line?))))
        ((pop-frame)
         (unless (= (length form) 2)
           (error "invalid event fold frame pop" form))
         (fold-state-of-type states (cadr form) list?)
         (hash ("kind" "pop_frame")
               ("stack" (rust-state-name (cadr form)))))
        ((close-frame)
         (unless (= (length form) 3)
           (error "invalid event fold frame close" form))
         (fold-state-of-type states (cadr form) list?)
         (fold-frame-finishes (caddr form))
         (hash ("kind" "close_frame")
               ("stack" (rust-state-name (cadr form)))
               ("finish_count" (caddr form))))
        ((close-frames-while)
         (fold-state-of-type states (cadr form) list?)
         (fold-frame-finishes (list-ref form 3))
         (hash ("kind" "close_frames_while")
               ("stack" (rust-state-name (cadr form)))
               ("condition" (fold-predicate-ir (caddr form) states indices allow-line?))
               ("finish_count" (list-ref form 3))))
        ((close-all-frames)
         (fold-state-of-type states (cadr form) list?)
         (fold-frame-finishes (caddr form))
         (hash ("kind" "close_all_frames")
               ("stack" (rust-state-name (cadr form)))
               ("finish_count" (caddr form))))
        (else (error "unsupported event fold statement" form))))
    statements)))

(def (fold-initial-ir initial)
  (list->vector
   (map (lambda (declaration)
          (let ((name (rust-state-name (car declaration)))
                (value (cadr declaration)))
            (cond
             ((boolean? value)
              (hash ("kind" "let_bool") ("name" name) ("value" value)))
             ((number? value)
              (hash ("kind" "let_usize") ("name" name) ("value" value)))
             (else (hash ("kind" "let_usize_stack") ("name" name))))))
        initial)))

(def (event-fold-ir-json name grammar root initial line-forms finish-forms
                         (helpers '()) (parameters '()))
  (let* ((states (fold-initial-states initial))
         (helper-ir
          (list->vector
           (map (lambda (helper)
                  (unless (and (memv (length helper) '(3 4))
                               (symbol? (car helper)))
                    (error "invalid event helper declaration" helper))
                  (let ((local-states (fold-initial-states (cadr helper)))
                        (parameters (if (= (length helper) 4)
                                      (cadddr helper) '())))
                    (validate-state-names local-states)
                    (unless (and (list? parameters)
                                 (every symbol? parameters))
                      (error "invalid event helper parameters" helper))
                    (validate-state-names
                     (map (lambda (parameter) (cons parameter 0)) parameters))
                    (for-each
                     (lambda (parameter)
                       (fold-state-of-type local-states parameter fold-unsigned?))
                     parameters)
                    (hash ("name" (rust-state-name (car helper)))
                          ("initial" (fold-initial-ir (cadr helper)))
                          ("parameters"
                           (list->vector (map rust-state-name parameters)))
                          ("body" (fold-statements-ir grammar (caddr helper)
                                                      local-states '() #t helpers)))))
                helpers)))
         (digest
          (sha256-text
           (call-with-output-string
            (lambda (port)
              (write (append
                      (list 'event-fold.v1
                            (parser-machine-grammar-digest
                             (language-grammar-machine grammar))
                            name root initial line-forms finish-forms)
                      (if (null? helpers) '() (list helpers))
                      (if (null? parameters) '() (list parameters))) port)))))
         (payload
          (hash ("schema" "gerbil-scheme-rust.event-function-ir.v1")
                ("name" (symbol->string name))
                ("root_kind" (kind-index grammar root 'node))
                ("parser_digest" digest)
                ("initial" (fold-initial-ir initial))
                ("line" (fold-statements-ir grammar line-forms states '() #t helpers))
                ("finish" (fold-statements-ir grammar finish-forms states '() #f helpers)))))
    (validate-state-names states)
    (validate-state-names
     (map (lambda (helper) (cons (car helper) #f)) helpers))
    (when (pair? parameters)
      (hash-put! payload "parameters"
                 (list->vector
                  (map (lambda (parameter)
                         (unless (and (= (length parameter) 3)
                                      (symbol? (car parameter))
                                      (symbol? (cadr parameter))
                                      (fold-unsigned? (caddr parameter)))
                           (error "invalid event fold parameter" parameter))
                         (unless (= (fold-state-of-type states (cadr parameter)
                                                         fold-unsigned?)
                                    (caddr parameter))
                           (error "event fold parameter default differs from state"
                                  parameter))
                         (hash ("name" (rust-state-name (car parameter)))
                               ("state" (rust-state-name (cadr parameter)))
                               ("default" (caddr parameter))))
                       parameters))))
    (when (pair? helpers) (hash-put! payload "helpers" helper-ir))
    (json->string payload sort-keys: #t)))
