;;; -*- Gerbil -*-
;;; Direct transitions over request-local slots and a reversed event chain.
(import (only-in ./event-fold-scheme-context
                 current-fold-scheme-counter fold-scheme-fresh-name fold-scheme-share-statements)
        (only-in ./event-fold-scheme-expressions
                 fold-scheme-offset fold-scheme-uint fold-scheme-predicate))
(export fold-scheme-statements fold-scheme-bindings fold-scheme-initial
        current-fold-scheme-counter fold-scheme-fresh-name)

(def (fold-scheme-bindings initial)
  (let loop ((rest initial) (ordinal 0) (bindings '()))
    (if (null? rest) (reverse bindings)
      (loop (cdr rest) (+ ordinal 1)
            (cons (cons (caar rest) `(vector-ref slots ,ordinal)) bindings)))))

(def (fold-scheme-initial initial)
  `(vector ,@(map (lambda (entry)
                    (if (equal? (cadr entry) '(uint-stack)) ''() (cadr entry)))
                  initial)))

(def (lvalue bindings name)
  (let (entry (assq name bindings))
    (unless entry (error "unbound native fold transition slot" name))
    (cdr entry)))

(def (assign target value)
  (if (symbol? target) `(set! ,target ,value)
    `(vector-set! slots ,(caddr target) ,value)))

(def (fold-scheme-statements forms bindings indices helpers)
  (def (offset value) (fold-scheme-offset value bindings indices))
  (def (uint value) (fold-scheme-uint value bindings indices))
  (def (predicate value) (fold-scheme-predicate value bindings indices))
  (def (body statements (locals bindings) (cursors indices))
    (if (null? statements) '((void))
      (fold-scheme-statements statements locals cursors helpers)))
  (def (finishes count)
    (map (lambda (_) '(set! events (cons '(finish) events))) (iota count)))
  (fold-scheme-share-statements
   (map
   (lambda (form)
     (case (car form)
       ((set-bool set-uint)
        (assign (lvalue bindings (cadr form))
                (if (eq? (car form) 'set-bool)
                  (predicate (caddr form)) (uint (caddr form)))))
       ((start-node) `(set! events (cons '(start ,(cadr form)) events)))
       ((finish-node) '(set! events (cons '(finish) events)))
       ((token)
        `(let ((from ,(offset (caddr form))) (until ,(offset (cadddr form))))
           (unless (= from until)
             (set! events (cons (list 'token ',(cadr form) from until) events)))))
       ((if) `(if ,(predicate (cadr form))
                (begin ,@(body (caddr form))) (begin ,@(body (cadddr form)))))
       ((join-once)
        (let* ((handled (fold-scheme-fresh-name 'handled))
               (locals (cons (cons (cadr form) handled) bindings)))
          `(let (,handled #f)
             ,@(body (caddr form) locals)
             (unless ,handled ,@(body (cadddr form) locals)))))
       ((for-line-bytes)
        (let ((cursor (fold-scheme-fresh-name 'cursor)) (limit (fold-scheme-fresh-name 'limit)))
          `(let ((from ,(offset (caddr form))) (,limit ,(offset (cadddr form))))
             (unless (<= start from ,limit end)
               (error "native fold iteration outside source line"))
             (let iterate ((,cursor from))
               (unless (= ,cursor ,limit)
                 ,@(body (list-ref form 4) bindings (cons (cons (cadr form) cursor) indices))
                 (iterate (+ ,cursor 1)))))))
       ((with-source-bounds)
        `(let ((from ,(offset (cadr form))) (until ,(offset (caddr form))))
           (fold-source-frame-boundaries! source-bytes from until)
           (let ((start from) (end until))
             ,@(body (cadddr form)))))
       ((call-source-helper)
        (let (helper (assq (cadr form) helpers))
          (unless helper (error "unknown native fold helper" form))
          `(set! events
              (,(cdr helper) source-bytes ,(offset (caddr form)) ,(offset (cadddr form))
                            events ,@(map uint (if (= (length form) 5)
                                               (list-ref form 4) '()))))))
       ((scan-list-marker)
        `(let (marker (scan-event-list-marker-bytes source-bytes start end
                          ',(string->utf8 (cadr form)) ,(caddr form) ,(cadddr form)))
           ,(assign (lvalue bindings (list-ref form 4)) '(if marker #t #f))
           (when marker
             ,@(map (lambda (name ordinal)
                      (assign (lvalue bindings name) `(vector-ref marker ,ordinal)))
                    (list-tail form 5) '(0 1 2 3 4)))))
       ((push-frame open-level)
        (let (target (lvalue bindings (cadr form)))
          `(begin
             ,(assign target `(cons ,(uint (caddr form)) ,target))
             ,@(if (eq? (car form) 'open-level)
                 `((set! events (cons '(start ,(cadddr form)) events))) '()))))
       ((pop-frame close-frame)
        (let (target (lvalue bindings (cadr form)))
          `(when (pair? ,target)
             ,(assign target `(cdr ,target))
             ,@(if (eq? (car form) 'close-frame) (finishes (caddr form)) '()))))
       ((close-through)
        (let (target (lvalue bindings (cadr form)))
          `(let (level ,(uint (caddr form)))
             (let close ()
               (when (and (pair? ,target) (>= (car ,target) level))
                 ,(assign target `(cdr ,target))
                 (set! events (cons '(finish) events))
                 (close))))))
       ((close-frames-while)
        (let (target (lvalue bindings (cadr form)))
          `(let close ()
             (when (and (pair? ,target) ,(predicate (caddr form)))
               ,(assign target `(cdr ,target))
               ,@(finishes (list-ref form 3))
               (close)))))
       ((close-all close-all-frames)
        (let ((target (lvalue bindings (cadr form)))
              (count (if (eq? (car form) 'close-all) 1 (caddr form))))
          `(begin
             (let close ()
               (when (pair? ,target)
                 ,(assign target `(cdr ,target))
                 ,@(finishes count)
                 (close)))
             ,(assign target ''()))))
       (else (error "unadmitted native fold transition" form))))
   forms) bindings indices))
