;;; -*- Gerbil -*-
;;; Generic source-backed list-marker lexing for a bounded Scheme event fold.

(export event-line-indent-column scan-event-list-marker)

(def (horizontal? byte)
  (memv byte '(9 32)))

(def (content-end bytes)
  (let loop ((cursor (u8vector-length bytes)))
    (if (and (> cursor 0) (memv (u8vector-ref bytes (- cursor 1)) '(10 13)))
      (loop (- cursor 1)) cursor)))

(def (line-indent bytes limit tab-width)
  (unless (and (exact-integer? tab-width) (> tab-width 0))
    (error "event list tab width must be positive" tab-width))
  (let loop ((cursor 0) (column 0))
    (if (and (< cursor limit) (horizontal? (u8vector-ref bytes cursor)))
      (loop (+ cursor 1)
            (if (= (u8vector-ref bytes cursor) 9)
              (* (+ (quotient column tab-width) 1) tab-width)
              (+ column 1)))
      (values cursor column))))

(def (event-line-indent-column line tab-width)
  (let* ((bytes (string->utf8 line))
         (limit (content-end bytes)))
    (let-values (((_ column) (line-indent bytes limit tab-width)))
      column)))

(def (ascii-digit? byte)
  (<= 48 byte 57))

(def (ascii-alpha? byte)
  (or (<= 65 byte 90) (<= 97 byte 122)))

(def (ordered-end bytes first limit)
  (let (byte (u8vector-ref bytes first))
    (cond
     ((ascii-digit? byte)
      (let loop ((cursor (+ first 1)))
        (if (and (< cursor limit) (ascii-digit? (u8vector-ref bytes cursor)))
          (loop (+ cursor 1))
          (and (< cursor limit) (memv (u8vector-ref bytes cursor) '(41 46))
               (+ cursor 1)))))
     ((ascii-alpha? byte)
      (and (< (+ first 1) limit)
           (memv (u8vector-ref bytes (+ first 1)) '(41 46))
           (+ first 2)))
     (else #f))))

(def (scan-event-list-marker line start unordered ordered? tab-width)
  (unless (and (string? unordered) (> (string-length unordered) 0)
               (every (lambda (character) (< (char->integer character) 128))
                      (string->list unordered)))
    (error "event list markers must be nonempty ASCII" unordered))
  (let* ((bytes (string->utf8 line))
         (limit (content-end bytes))
         (unordered-bytes (string->utf8 unordered)))
    (let-values (((first column) (line-indent bytes limit tab-width)))
      (and (< first limit)
           (let* ((byte (u8vector-ref bytes first))
                  (unordered? (let loop ((index 0))
                                (and (< index (u8vector-length unordered-bytes))
                                     (or (= byte (u8vector-ref unordered-bytes index))
                                         (loop (+ index 1))))))
                  (bullet-end
                   (if unordered? (+ first 1)
                     (and ordered? (ordered-end bytes first limit)))))
             (and bullet-end
                  (or (= bullet-end limit)
                      (horizontal? (u8vector-ref bytes bullet-end)))
                  (let skip ((cursor bullet-end))
                    (if (and (< cursor limit)
                             (horizontal? (u8vector-ref bytes cursor)))
                      (skip (+ cursor 1))
                      (vector column (not unordered?)
                              (+ start first) (+ start bullet-end)
                              (+ start cursor))))))))))
