;;; -*- Gerbil -*-
;;; Checked POO graph rules to an immutable Rowan projection table.

(import (only-in ../language/descriptor
                 language-grammar-ir language-grammar-machine)
        (only-in ../runtime/identity sha256-text)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ../modules/parser/graph-projection-objects
                 graph-projection? graph-projection-nodes
                 graph-node-syntax-kind graph-node-category graph-node-label
                 graph-node-fields graph-field-token graph-field-name))
(export graph-projection-digest graph-projection-rowan-source
        generate-graph-projection-rowan-module)

(def (kind-index kinds name category)
  (let loop ((rest kinds) (index 0))
    (cond
     ((null? rest) (error "unknown graph projection syntax kind" name category))
     ((eq? (caar rest) name)
      (unless (eq? (cadar rest) category)
        (error "graph projection kind has wrong category" name category))
      index)
     (else (loop (cdr rest) (+ index 1))))))

(def (projection-fingerprint grammar-digest nodes)
  (sha256-text
   (call-with-output-string
    (lambda (port)
      (write
       (list 'gerbil-parser-graph-projection-v1 grammar-digest
             (map (lambda (node)
                    (list (graph-node-syntax-kind node)
                          (graph-node-category node)
                          (graph-node-label node)
                          (map (lambda (field)
                                 (list (graph-field-token field)
                                       (graph-field-name field)))
                               (graph-node-fields node))))
                  nodes))
       port)))))

(def (graph-projection-digest language-grammar projection)
  (unless (graph-projection? projection)
    (error "graph projection digest requires a checked POO value" projection))
  (projection-fingerprint
   (parser-machine-grammar-digest
    (language-grammar-machine language-grammar))
   (graph-projection-nodes projection)))

(def (graph-projection-rowan-source language-grammar projection)
  (unless (graph-projection? projection)
    (error "graph projection AOT requires a checked POO value" projection))
  (let* ((ir (language-grammar-ir language-grammar))
         (kinds (cdr (assq 'syntax-kinds ir)))
         (digest (parser-machine-grammar-digest
                  (language-grammar-machine language-grammar)))
         (nodes (graph-projection-nodes projection))
         (projection-digest (graph-projection-digest language-grammar projection)))
    (call-with-output-string
     (lambda (port)
       (display "// @generated by gerbil-parser/src/compiler/graph-projection-rowan.ss\n" port)
       (display "use gerbil_parser_rowan::{GraphFieldRule, GraphNodeRule, GraphProjectionSpec};\n\n" port)
       (display "pub static GRAPH: GraphProjectionSpec = GraphProjectionSpec {\n" port)
       (display "    grammar_digest: " port)
       (write digest port)
       (display ",\n    projection_digest: " port)
       (write projection-digest port)
       (display ",\n    rules: &[\n" port)
       (for-each
        (lambda (node)
          (display "        GraphNodeRule { syntax_kind: " port)
          (display (kind-index kinds (graph-node-syntax-kind node) 'node) port)
          (display ", category: " port)
          (write (graph-node-category node) port)
          (display ", kind: " port)
          (write (graph-node-label node) port)
          (display ", fields: &[" port)
          (for-each
           (lambda (field)
             (display "GraphFieldRule { token_kind: " port)
             (display (kind-index kinds (graph-field-token field) 'token) port)
             (display ", name: " port)
             (write (graph-field-name field) port)
             (display " }, " port))
           (graph-node-fields node))
          (display "] },\n" port))
        nodes)
       (display "    ],\n};\n" port)))))

(def (generate-graph-projection-rowan-module output-path language-grammar projection)
  (let (source (graph-projection-rowan-source language-grammar projection))
    (call-with-output-file output-path
      (lambda (port) (display source port)))))
