;;; -*- Gerbil -*-
;;; POO line-structure declaration to immutable generic Rowan table.

(import (only-in ../language/descriptor
                 language-grammar-ir language-grammar-machine)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ../modules/parser/line-structure-objects
                 line-structure?
                 line-structure-heading line-structure-blocks line-structure-text
                 heading-line-marker heading-line-separator
                 heading-line-section-node heading-line-heading-node
                 heading-line-heading-token
                 block-line-opening block-line-closing block-line-case-insensitive
                 block-line-indent block-line-block-node block-line-begin-token
                 block-line-body-token block-line-end-token
                 text-line-node text-line-token))
(export line-structure-rowan-source
        generate-line-structure-rowan-module)

(def (kind-index kinds name category)
  (let loop ((rest kinds) (index 0))
    (cond
     ((null? rest) (error "unknown line-structure syntax kind" name category))
     ((eq? (caar rest) name)
      (unless (eq? (cadar rest) category)
        (error "line-structure syntax kind has wrong category" name category))
      index)
     (else (loop (cdr rest) (+ index 1))))))

(def (emit-kind port kinds name category)
  (display (kind-index kinds name category) port))

(def (emit-block port kinds block)
  (display "    BlockLineRule { opening: " port)
  (write (block-line-opening block) port)
  (display ", closing: " port)
  (write (block-line-closing block) port)
  (display ", case_insensitive: " port)
  (display (if (block-line-case-insensitive block) "true" "false") port)
  (display ", indent: " port)
  (display (if (block-line-indent block) "true" "false") port)
  (display ", block_node: " port)
  (emit-kind port kinds (block-line-block-node block) 'node)
  (display ", begin_token: " port)
  (emit-kind port kinds (block-line-begin-token block) 'token)
  (display ", body_token: " port)
  (emit-kind port kinds (block-line-body-token block) 'token)
  (display ", end_token: " port)
  (emit-kind port kinds (block-line-end-token block) 'token)
  (display " },\n" port))

;; Public input is one validated POO contract. Canonical Parser IR is the
;; internal kind catalog; this projection never interprets author-facing rows.
(def (line-structure-rowan-source language-grammar structure)
  (unless (line-structure? structure)
    (error "line-structure AOT requires a POO parser declaration" structure))
  (let* ((ir (language-grammar-ir language-grammar))
         (kinds (cdr (assq 'syntax-kinds ir)))
         (heading (line-structure-heading structure))
         (blocks (line-structure-blocks structure))
         (text (line-structure-text structure))
         (digest (parser-machine-grammar-digest
                  (language-grammar-machine language-grammar))))
    (call-with-output-string
     (lambda (port)
       (display "// @generated by gerbil-parser/src/compiler/line-structure-rowan.ss\n" port)
       (display "use gerbil_parser_rowan::{BlockLineRule, HeadingLineRule, LineStructureSpec};\n\n" port)
       (display "pub static STRUCTURE: LineStructureSpec = LineStructureSpec {\n" port)
       (display "    grammar_digest: " port)
       (write digest port)
       (display ",\n    heading: HeadingLineRule { marker: " port)
       (display (char->integer (string-ref (heading-line-marker heading) 0)) port)
       (display ", separator: " port)
       (display (char->integer (string-ref (heading-line-separator heading) 0)) port)
       (display ", section_node: " port)
       (emit-kind port kinds (heading-line-section-node heading) 'node)
       (display ", heading_node: " port)
       (emit-kind port kinds (heading-line-heading-node heading) 'node)
       (display ", heading_token: " port)
       (emit-kind port kinds (heading-line-heading-token heading) 'token)
       (display " },\n    blocks: &[\n" port)
       (for-each (lambda (block) (emit-block port kinds block)) blocks)
       (display "    ],\n    text_node: " port)
       (emit-kind port kinds (text-line-node text) 'node)
       (display ", text_token: " port)
       (emit-kind port kinds (text-line-token text) 'token)
       (display ",\n};\n" port)))))

(def (generate-line-structure-rowan-module output-path language-grammar structure)
  (let (source (line-structure-rowan-source language-grammar structure))
    (call-with-output-file output-path
      (lambda (port) (display source port)))))
