;;; -*- Gerbil -*-
;;; Canonical Parser IR v1 to immutable Rust/Rowan table generation.

(import (only-in ../language/descriptor
                 language-grammar-contract
                 language-grammar-ir
                 language-grammar-language
                 language-grammar-machine
                 language-grammar-version)
        (only-in ./machine parser-machine-grammar-digest))
(export generate-language-rust-rowan-module
        generate-rust-rowan-module
        rust-rowan-module-source)

(def (alist-ref rows key (default #f))
  (let (entry (assq key rows))
    (if entry (cdr entry) default)))

(def (rust-string value)
  (call-with-output-string (lambda (port) (write value port))))

(def (symbol-text value)
  (if (symbol? value) (symbol->string value) value))

(def (kind-index kinds name)
  (let loop ((rest kinds) (offset 0))
    (cond
     ((null? rest) (error "unknown Rust/Rowan syntax kind" name))
     ((eq? (caar rest) name) offset)
     (else (loop (cdr rest) (+ offset 1))))))

(def (emit-terminal port terminal)
  (case (cadr terminal)
    ((eof) (display "Terminal::Eof" port))
    ((literal)
     (display "Terminal::Literal(" port)
     (display (rust-string (caddr terminal)) port)
     (display ")" port))
    ((token)
     (display "Terminal::Token(" port)
     (display (rust-string (symbol-text (caddr terminal))) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan terminal" terminal))))

(def (emit-parser-action port action)
  (case (car action)
    ((shift)
     (display "ParserAction::Shift(" port)
     (display (cadr action) port)
     (display ")" port))
    ((reduce)
     (display "ParserAction::Reduce(" port)
     (display (cadr action) port)
     (display ")" port))
    ((accept) (display "ParserAction::Accept" port))
    ((reject-nonassoc) (display "ParserAction::RejectNonAssoc" port))
    ((fork)
     (display "ParserAction::Fork(&[" port)
     (let loop ((rest (cdr action)))
       (unless (null? rest)
         (emit-parser-action port (car rest))
         (unless (null? (cdr rest)) (display ", " port))
         (loop (cdr rest))))
     (display "])" port))
    (else (error "unsupported Rust/Rowan parser action" action))))

(def (emit-action-rows port rows)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "static ACTION_" port)
      (display state port)
      (display ": &[ActionEntry] = &[\n" port)
      (for-each
       (lambda (entry)
         (display "    ActionEntry { terminal: " port)
         (emit-terminal port (car entry))
         (display ", action: " port)
         (emit-parser-action port (cdr entry))
         (display " },\n" port))
       (vector-ref rows state))
      (display "];\n" port)
      (loop (+ state 1))))
  (display "static ACTIONS: &[&[ActionEntry]] = &[\n" port)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "    ACTION_" port)
      (display state port)
      (display ",\n" port)
      (loop (+ state 1))))
  (display "];\n\n" port))

(def (emit-goto-rows port rows)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "static GOTO_" port)
      (display state port)
      (display ": &[GotoEntry] = &[\n" port)
      (for-each
       (lambda (entry)
         (display "    GotoEntry { nonterminal: " port)
         (display (rust-string (symbol-text (car entry))) port)
         (display ", state: " port)
         (display (cdr entry) port)
         (display " },\n" port))
       (vector-ref rows state))
      (display "];\n" port)
      (loop (+ state 1))))
  (display "static GOTOS: &[&[GotoEntry]] = &[\n" port)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "    GOTO_" port)
      (display state port)
      (display ",\n" port)
      (loop (+ state 1))))
  (display "];\n\n" port))

(def (base-operand operand)
  (if (and (pair? operand) (eq? (car operand) 'marked))
    (cadr operand)
    operand))

(def (operand-actions operand)
  (if (and (pair? operand) (eq? (car operand) 'marked))
    (caddr operand)
    '()))

(def (emit-symbol port symbol)
  (case (car symbol)
    ((terminal)
     (display "Symbol::Terminal(" port)
     (emit-terminal port symbol)
     (display ")" port))
    ((nonterminal)
     (display "Symbol::Nonterminal(" port)
     (display (rust-string (symbol-text (cadr symbol))) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan production symbol" symbol))))

(def (emit-operand-action port action kinds)
  (case (car action)
    ((field)
     (display "OperandAction::Field(" port)
     (display (rust-string (symbol-text (cadr action))) port)
     (display ")" port))
    ((alias)
     (display "OperandAction::Alias(" port)
     (display (kind-index kinds (cadr action)) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan operand action" action))))

(def (emit-operand port operand kinds)
  (display "Operand { symbol: " port)
  (emit-symbol port (base-operand operand))
  (display ", actions: &[" port)
  (let loop ((rest (operand-actions operand)))
    (unless (null? rest)
      (emit-operand-action port (car rest) kinds)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "] }" port))

(def (emit-production port production kinds)
  (display "    Production { lhs: " port)
  (display (rust-string (symbol-text (cadr production))) port)
  (display ", rhs: &[" port)
  (let loop ((rest (caddr production)))
    (unless (null? rest)
      (emit-operand port (car rest) kinds)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "], reduction: " port)
  (case (cadddr production)
    ((pass) (display "Reduction::Pass" port))
    ((concat) (display "Reduction::Concat" port))
    (else (error "unsupported Rust/Rowan reduction"
                 (cadddr production))))
  (display ", dynamic_precedence: " port)
  (let (precedence (car (cddddr production)))
    (display (if (and precedence (eq? (car precedence) 'dynamic))
               (cadr precedence)
               0)
             port))
  (display " },\n" port))

(def (emit-rust-string-slice port values)
  (display "&[" port)
  (let loop ((rest values))
    (unless (null? rest)
      (display (rust-string (car rest)) port)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "]" port))

(def (emit-lexical-expression port expression)
  (case (car expression)
    ((whitespace+) (display "LexicalExpr::Whitespace" port))
    ((horizontal-whitespace+)
     (display "LexicalExpr::HorizontalWhitespace" port))
    ((newline+) (display "LexicalExpr::Newline" port))
    ((decimal-digit+) (display "LexicalExpr::DecimalDigits" port))
    ((number) (display "LexicalExpr::Number" port))
    ((number-literal)
     (display "LexicalExpr::NumberLiteral { prefixes: " port)
     (emit-rust-string-slice port (cadr expression))
     (display ", separator: " port)
     (display (rust-string (caddr expression)) port)
     (display ", suffixes: " port)
     (emit-rust-string-slice port (cadddr expression))
     (display ", leading_period: " port)
     (display (if (car (cddddr expression)) "true" "false") port)
     (display ", trailing_period: " port)
     (display (if (cadr (cddddr expression)) "true" "false") port)
     (display " }" port))
    ((identifier) (display "LexicalExpr::Identifier" port))
    ((quoted-string)
     (display "LexicalExpr::QuotedString(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((heredoc) (display "LexicalExpr::Heredoc" port))
    ((line-comment)
     (display "LexicalExpr::LineComment(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((block-comment nested-block-comment)
     (display (if (eq? (car expression) 'block-comment)
                "LexicalExpr::BlockComment { opening: "
                "LexicalExpr::NestedBlockComment { opening: ") port)
     (display (rust-string (cadr expression)) port)
     (display ", closing: " port)
     (display (rust-string (caddr expression)) port)
     (display " }" port))
    ((choice)
     (display "LexicalExpr::Choice(&[" port)
     (let loop ((rest (cdr expression)))
       (unless (null? rest)
         (emit-lexical-expression port (car rest))
         (unless (null? (cdr rest)) (display ", " port))
         (loop (cdr rest))))
     (display "])" port))
    ((fallback) (display "LexicalExpr::Fallback" port))
    ((literals)
     (display "LexicalExpr::Literals(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((precedence)
     (emit-lexical-expression port (caddr expression)))
    (else
     (error "lexical expression is not yet supported by Rust/Rowan v1"
            expression))))

(def (lexical-precedence expression)
  (if (eq? (car expression) 'precedence) (cadr expression) 0))

(def (rust-rowan-module-source language version contract grammar-digest ir)
  (unless (equal? (alist-ref ir 'schema) "gerbil-parser.parser-ir.v1")
    (error "Rust/Rowan generation requires Parser IR v1" ir))
  (let* ((kinds (alist-ref ir 'syntax-kinds))
         (terminals (alist-ref ir 'terminals))
         (lexical-rules (alist-ref ir 'lexical-rules))
         (extras (map car (alist-ref ir 'extras)))
         (lr (alist-ref ir 'lr-spec))
         (productions (alist-ref lr 'productions))
         (actions (alist-ref lr 'actions))
         (gotos (alist-ref lr 'gotos)))
    (call-with-output-string
     (lambda (port)
       (display "// @generated by gerbil-parser/src/compiler/rust-rowan.ss\n" port)
       (display "// Source authority: canonical Grammar IR v1; do not edit.\n\n" port)
       (display "use gerbil_parser_rowan::{ActionEntry, GotoEntry, KindCategory, KindSpec, LanguageSpec, LexicalExpr, LexicalRule, Operand, OperandAction, ParserAction, Production, Reduction, Symbol, Terminal, TerminalSpec};\n\n" port)
       (display "static KINDS: &[KindSpec] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    KindSpec { name: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", category: KindCategory::" port)
          (display (case (cadr row) ((node) "Node") ((token) "Token")
                           (else (error "unknown syntax-kind category" row)))
                   port)
          (display " },\n" port))
        kinds)
       (display "];\n\nstatic TERMINALS: &[TerminalSpec] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    TerminalSpec { name: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", syntax_kind: " port)
          (display (kind-index kinds (cadr row)) port)
          (display " },\n" port))
        terminals)
       (display "];\n\nstatic LEXICAL_RULES: &[LexicalRule] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    LexicalRule { terminal: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", expression: " port)
          (emit-lexical-expression port (cadr row))
          (display ", precedence: " port)
          (display (lexical-precedence (cadr row)) port)
          (display ", extra: " port)
          (display (if (memq (car row) extras) "true" "false") port)
          (display " },\n" port))
        lexical-rules)
       (display "];\n\n" port)
       (emit-action-rows port actions)
       (emit-goto-rows port gotos)
       (display "static PRODUCTIONS: &[Production] = &[\n" port)
       (for-each (lambda (production)
                   (emit-production port production kinds))
                 productions)
       (display "];\n\npub static LANGUAGE: LanguageSpec = LanguageSpec {\n" port)
       (display "    language: " port) (display (rust-string language) port)
       (display ",\n    version: " port) (display (rust-string version) port)
       (display ",\n    contract: " port) (display (rust-string contract) port)
       (display ",\n    grammar_digest: " port)
       (display (rust-string grammar-digest) port)
       (display ",\n    case_insensitive: " port)
       (display (if (alist-ref ir 'case-insensitive?) "true" "false") port)
       (display ",\n    root_kind: " port)
       (display (kind-index kinds (alist-ref ir 'root-kind)) port)
       (display ",\n    kinds: KINDS,\n    terminals: TERMINALS,\n    lexical_rules: LEXICAL_RULES,\n    actions: ACTIONS,\n    gotos: GOTOS,\n    productions: PRODUCTIONS,\n};\n" port)))))

(def (generate-rust-rowan-module output-path language version contract
                                 grammar-digest ir)
  (let (source
        (rust-rowan-module-source
         language version contract grammar-digest ir))
    (create-directory* (path-directory output-path))
    (call-with-output-file output-path
      (lambda (port) (display source port)))
    output-path))

;;; A language author supplies only deflanguage/grammar.ss.  The generated
;;; descriptor already owns identity, Parser IR, machine, and grammar digest;
;;; repository/release tooling supplies only the Rust artifact destination.
(def (generate-language-rust-rowan-module output-path language-grammar)
  (generate-rust-rowan-module
   output-path
   (language-grammar-language language-grammar)
   (language-grammar-version language-grammar)
   (language-grammar-contract language-grammar)
   (parser-machine-grammar-digest
    (language-grammar-machine language-grammar))
   (language-grammar-ir language-grammar)))
