;;; -*- Gerbil -*-
;;; Restricted Rust syntax values for deterministic AOT table generation.

(export rust-struct rust-static rust-array rust-some rust-none
        rust-number rust-string rust-identifier rust-module rust-render
        rust-struct-form? rust-struct-form-name rust-struct-form-fields
        rust-field-name rust-field-value
        rust-module-form? rust-module-form-item
        rust-static-form? rust-static-form-value)

(defstruct rust-field (name value) transparent: #t)
(defstruct rust-struct-form (name fields) transparent: #t)
(defstruct rust-static-form (name type value) transparent: #t)
(defstruct rust-array-form (values) transparent: #t)
(defstruct rust-some-form (value) transparent: #t)
(defstruct rust-none-form () transparent: #t)
(defstruct rust-number-form (value) transparent: #t)
(defstruct rust-string-form (value) transparent: #t)
(defstruct rust-identifier-form (value) transparent: #t)
(defstruct rust-module-form (imports item) transparent: #t)

;; The macro admits only named fields. Callers build Rust syntax values, not
;; snippets of Rust text; the renderer is the sole textual boundary.
(defrules rust-struct ()
  ((_ name (field value) ...)
   (make-rust-struct-form 'name
                     (list (make-rust-field 'field value) ...))))

(defrules rust-static ()
  ((_ name type value)
   (make-rust-static-form 'name 'type value)))

(def (rust-array values) (make-rust-array-form values))
(def (rust-some value) (make-rust-some-form value))
(def (rust-none) (make-rust-none-form))
(def (rust-number value) (make-rust-number-form value))
(def (rust-string value) (make-rust-string-form value))
(def (rust-identifier value) (make-rust-identifier-form value))
(def (rust-module imports item) (make-rust-module-form imports item))

(def (render-sequence port values)
  (let loop ((rest values) (first? #t))
    (when (pair? rest)
      (unless first? (display ", " port))
      (render-node port (car rest))
      (loop (cdr rest) #f))))

(def (render-field port field)
  (display (rust-field-name field) port)
  (display ": " port)
  (render-node port (rust-field-value field)))

(def (render-node port node)
  (cond
   ((rust-struct-form? node)
    (display (rust-struct-form-name node) port)
    (display " { " port)
    (let loop ((fields (rust-struct-form-fields node)) (first? #t))
      (when (pair? fields)
        (unless first? (display ", " port))
        (render-field port (car fields))
        (loop (cdr fields) #f)))
    (display " }" port))
   ((rust-static-form? node)
    (display "pub static " port)
    (display (rust-static-form-name node) port)
    (display ": " port)
    (display (rust-static-form-type node) port)
    (display " = " port)
    (render-node port (rust-static-form-value node))
    (display ";\n" port))
   ((rust-array-form? node)
    (display "&[" port)
    (render-sequence port (rust-array-form-values node))
    (display "]" port))
   ((rust-some-form? node)
    (display "Some(" port)
    (render-node port (rust-some-form-value node))
    (display ")" port))
   ((rust-none-form? node) (display "None" port))
   ((rust-number-form? node) (display (rust-number-form-value node) port))
   ((rust-string-form? node) (write (rust-string-form-value node) port))
   ((rust-identifier-form? node)
    (display (rust-identifier-form-value node) port))
   ((rust-module-form? node)
    (display "// @generated by gerbil-parser/src/compiler/line-structure-rowan.ss\n" port)
    (display "use gerbil_parser_rowan::{" port)
    (let loop ((imports (rust-module-form-imports node)) (first? #t))
      (when (pair? imports)
        (unless first? (display ", " port))
        (display (car imports) port)
        (loop (cdr imports) #f)))
    (display "};\n\n" port)
    (render-node port (rust-module-form-item node)))
   (else (error "unsupported Rust syntax value" node))))

(def (rust-render node)
  (call-with-output-string
   (lambda (port) (render-node port node))))
