;;; -*- Gerbil -*-
;;; Canonical Parser IR v1 to immutable Rust/Rowan table generation.

(import (only-in ../language/descriptor
                 language-grammar-contract
                 language-grammar-ir
                 language-grammar-language
                 language-grammar-machine
                 language-grammar-version require-portable-language-policy!)
        (only-in ./machine parser-machine-grammar-digest))
(export generate-language-rust-rowan-module
        generate-rust-rowan-module
        language-rust-rowan-module-source rust-rowan-module-source)

(def (alist-ref rows key (default #f))
  (let (entry (assq key rows))
    (if entry (cdr entry) default)))

(def (rust-string value)
  (call-with-output-string (lambda (port) (write value port))))

(def (symbol-text value)
  (if (symbol? value) (symbol->string value) value))

(def (kind-index kinds name)
  (let loop ((rest kinds) (offset 0))
    (cond
     ((null? rest) (error "unknown Rust/Rowan syntax kind" name))
     ((eq? (caar rest) name) offset)
     (else (loop (cdr rest) (+ offset 1))))))

(def (emit-terminal port terminal)
  (case (cadr terminal)
    ((eof) (display "Terminal::Eof" port))
    ((literal)
     (display "Terminal::Literal(" port)
     (display (rust-string (caddr terminal)) port)
     (display ")" port))
    ((token)
     (display "Terminal::Token(" port)
     (display (rust-string (symbol-text (caddr terminal))) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan terminal" terminal))))

(def (emit-parser-action port action)
  (case (car action)
    ((shift)
     (display "ParserAction::Shift(" port)
     (display (cadr action) port)
     (display ")" port))
    ((reduce)
     (display "ParserAction::Reduce(" port)
     (display (cadr action) port)
     (display ")" port))
    ((accept) (display "ParserAction::Accept" port))
    ((reject-nonassoc) (display "ParserAction::RejectNonAssoc" port))
    ((fork)
     (display "ParserAction::Fork(&[" port)
     (let loop ((rest (cdr action)))
       (unless (null? rest)
         (emit-parser-action port (car rest))
         (unless (null? (cdr rest)) (display ", " port))
         (loop (cdr rest))))
     (display "])" port))
    (else (error "unsupported Rust/Rowan parser action" action))))

(def (emit-action-rows port rows)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "static ACTION_" port)
      (display state port)
      (display ": &[ActionEntry] = &[\n" port)
      (for-each
       (lambda (entry)
         (display "    ActionEntry { terminal: " port)
         (emit-terminal port (car entry))
         (display ", action: " port)
         (emit-parser-action port (cdr entry))
         (display " },\n" port))
       (vector-ref rows state))
      (display "];\n" port)
      (loop (+ state 1))))
  (display "static ACTIONS: &[&[ActionEntry]] = &[\n" port)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "    ACTION_" port)
      (display state port)
      (display ",\n" port)
      (loop (+ state 1))))
  (display "];\n\n" port))

(def (emit-goto-rows port rows)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "static GOTO_" port)
      (display state port)
      (display ": &[GotoEntry] = &[\n" port)
      (for-each
       (lambda (entry)
         (display "    GotoEntry { nonterminal: " port)
         (display (rust-string (symbol-text (car entry))) port)
         (display ", state: " port)
         (display (cdr entry) port)
         (display " },\n" port))
       (vector-ref rows state))
      (display "];\n" port)
      (loop (+ state 1))))
  (display "static GOTOS: &[&[GotoEntry]] = &[\n" port)
  (let loop ((state 0))
    (when (< state (vector-length rows))
      (display "    GOTO_" port)
      (display state port)
      (display ",\n" port)
      (loop (+ state 1))))
  (display "];\n\n" port))

(def (base-operand operand)
  (if (and (pair? operand) (eq? (car operand) 'marked))
    (cadr operand)
    operand))

(def (operand-actions operand)
  (if (and (pair? operand) (eq? (car operand) 'marked))
    (caddr operand)
    '()))

(def (emit-symbol port symbol)
  (case (car symbol)
    ((terminal)
     (display "Symbol::Terminal(" port)
     (emit-terminal port symbol)
     (display ")" port))
    ((nonterminal)
     (display "Symbol::Nonterminal(" port)
     (display (rust-string (symbol-text (cadr symbol))) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan production symbol" symbol))))

(def (emit-operand-action port action kinds)
  (case (car action)
    ((field)
     (display "OperandAction::Field(" port)
     (display (rust-string (symbol-text (cadr action))) port)
     (display ")" port))
    ((alias)
     (display "OperandAction::Alias(" port)
     (display (kind-index kinds (cadr action)) port)
     (display ")" port))
    (else (error "unsupported Rust/Rowan operand action" action))))

(def (emit-operand port operand kinds)
  (display "Operand { symbol: " port)
  (emit-symbol port (base-operand operand))
  (display ", actions: &[" port)
  (let loop ((rest (operand-actions operand)))
    (unless (null? rest)
      (emit-operand-action port (car rest) kinds)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "] }" port))

(def (emit-production port production kinds)
  (display "    Production { lhs: " port)
  (display (rust-string (symbol-text (cadr production))) port)
  (display ", rhs: &[" port)
  (let loop ((rest (caddr production)))
    (unless (null? rest)
      (emit-operand port (car rest) kinds)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "], reduction: " port)
  (case (cadddr production)
    ((pass) (display "Reduction::Pass" port))
    ((concat) (display "Reduction::Concat" port))
    (else (error "unsupported Rust/Rowan reduction"
                 (cadddr production))))
  (display ", dynamic_precedence: " port)
  (let (precedence (car (cddddr production)))
    (display (if (and precedence (eq? (car precedence) 'dynamic))
               (cadr precedence)
               0)
             port))
  (display " },\n" port))

(def (emit-rust-string-slice port values)
  (display "&[" port)
  (let loop ((rest values))
    (unless (null? rest)
      (display (rust-string (car rest)) port)
      (unless (null? (cdr rest)) (display ", " port))
      (loop (cdr rest))))
  (display "]" port))

(def (emit-text-class port expression)
  (case (car expression)
    ((alphabetic) (display "gerbil_parser_rowan::TextClass::Alphabetic" port))
    ((numeric) (display "gerbil_parser_rowan::TextClass::Numeric" port))
    ((ascii-letter) (display "gerbil_parser_rowan::TextClass::AsciiLetter" port))
    ((characters) (display "gerbil_parser_rowan::TextClass::Characters(" port)
                  (display (rust-string (cadr expression)) port) (display ")" port))
    ((union) (display "gerbil_parser_rowan::TextClass::Union(&[" port)
             (for-each (lambda (child) (emit-text-class port child) (display "," port)) (cdr expression))
             (display "])" port))))

(def (emit-text-profile port expression)
  (case (car expression)
    ((literal) (display "gerbil_parser_rowan::TextProfile::Literal(" port)
               (display (rust-string (cadr expression)) port) (display ")" port))
    ((run) (display "gerbil_parser_rowan::TextProfile::Run { class: " port) (emit-text-class port (cadr expression))
           (display ", minimum: " port) (display (caddr expression) port)
           (display ", maximum: " port)
           (if (cadddr expression)
             (begin (display "Some(" port) (display (cadddr expression) port) (display ")" port))
             (display "None" port)) (display " }" port))
    ((run-containing)
     (display "gerbil_parser_rowan::TextProfile::RunContaining { class: " port) (emit-text-class port (cadr expression))
     (display ", required: " port) (emit-text-class port (caddr expression))
     (display ", minimum: " port) (display (cadddr expression) port) (display ", maximum: " port)
     (if (car (cddddr expression)) (begin (display "Some(" port) (display (car (cddddr expression)) port) (display ")" port)) (display "None" port))
     (display " }" port))
    ((ends-in ends-not-in)
     (display "gerbil_parser_rowan::TextProfile::EndsIn { class: " port) (emit-text-class port (cadr expression))
     (display ", body: &" port) (emit-text-profile port (caddr expression))
     (display (if (eq? (car expression) 'ends-in) ", positive: true }" ", positive: false }") port))
    ((seq) (display "gerbil_parser_rowan::TextProfile::Sequence(&[" port)
           (for-each (lambda (child) (emit-text-profile port child) (display "," port)) (cdr expression))
           (display "])" port))
    ((optional) (display "gerbil_parser_rowan::TextProfile::Optional(&" port) (emit-text-profile port (cadr expression)) (display ")" port))
    ((if-next) (display "gerbil_parser_rowan::TextProfile::IfNext { class: " port) (emit-text-class port (cadr expression))
               (display ", body: &" port) (emit-text-profile port (caddr expression))
               (display ", otherwise: " port)
               (if (= (length expression) 4)
                 (begin (display "Some(&" port) (emit-text-profile port (cadddr expression)) (display ")" port))
                 (display "None" port)) (display " }" port))
    ((not-next) (display "gerbil_parser_rowan::TextProfile::NotNext(" port) (emit-text-class port (cadr expression)) (display ")" port))))

(def (emit-lexical-expression port expression)
  (case (car expression)
    ((text-profile) (display "LexicalExpr::TextProfile(&" port)
                    (emit-text-profile port (cadr expression)) (display ")" port))
    ((whitespace+) (display "LexicalExpr::Whitespace" port))
    ((horizontal-whitespace+)
     (display "LexicalExpr::HorizontalWhitespace" port))
    ((newline+) (display "LexicalExpr::Newline" port))
    ((line) (display "LexicalExpr::Line" port))
    ((decimal-digit+) (display "LexicalExpr::DecimalDigits" port))
    ((number) (display "LexicalExpr::Number" port))
    ((number-literal)
     (display "LexicalExpr::NumberLiteral { prefixes: " port)
     (emit-rust-string-slice port (cadr expression))
     (display ", separator: " port)
     (display (rust-string (caddr expression)) port)
     (display ", suffixes: " port)
     (emit-rust-string-slice port (cadddr expression))
     (display ", leading_period: " port)
     (display (if (car (cddddr expression)) "true" "false") port)
     (display ", trailing_period: " port)
     (display (if (cadr (cddddr expression)) "true" "false") port)
     (display " }" port))
    ((identifier) (display "LexicalExpr::Identifier" port))
    ((quoted-string-profile)
     (display "LexicalExpr::QuotedStringProfile { delimiter: " port)
     (display (rust-string (cadr expression)) port)
     (display ", escapes: " port)
     (display (rust-string (caddr expression)) port)
     (display ", unicode_width: " port)
     (display (cadddr expression) port)
     (display " }" port))
    ((header-delimiter header-data)
     (display (if (eq? (car expression) 'header-delimiter)
                "LexicalExpr::HeaderDelimiter { prefix: " "LexicalExpr::HeaderData { prefix: ") port)
     (display (rust-string (cadr expression)) port)
     (display ", count: " port) (display (caddr expression) port)
     (display (if (eq? (car expression) 'header-delimiter) ", index: " ", stops: ") port)
     (display (if (eq? (car expression) 'header-delimiter)
                (cadddr expression) (rust-string (cadddr expression))) port)
     (display " }" port))
    ((until-delimiters)
     (display "LexicalExpr::UntilDelimiters(" port)
     (display (rust-string (cadr expression)) port)
     (display ")" port))
    ((character-run)
     (display "LexicalExpr::CharacterRun { character: " port)
     (display (rust-string (cadr expression)) port)
     (display ", minimum: " port)
     (display (caddr expression) port)
     (display " }" port))
    ((quoted-string)
     (display "LexicalExpr::QuotedString(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((escaped-quoted-string)
     (display "LexicalExpr::EscapedQuotedString(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((heredoc) (display "LexicalExpr::Heredoc" port))
    ((line-comment)
     (display "LexicalExpr::LineComment(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((block-comment nested-block-comment)
     (display (if (eq? (car expression) 'block-comment)
                "LexicalExpr::BlockComment { opening: "
                "LexicalExpr::NestedBlockComment { opening: ") port)
     (display (rust-string (cadr expression)) port)
     (display ", closing: " port)
     (display (rust-string (caddr expression)) port)
     (display " }" port))
    ((choice)
     (display "LexicalExpr::Choice(&[" port)
     (let loop ((rest (cdr expression)))
       (unless (null? rest)
         (emit-lexical-expression port (car rest))
         (unless (null? (cdr rest)) (display ", " port))
         (loop (cdr rest))))
     (display "])" port))
    ((fallback) (display "LexicalExpr::Fallback" port))
    ((literals)
     (display "LexicalExpr::Literals(" port)
     (emit-rust-string-slice port (cdr expression))
     (display ")" port))
    ((precedence)
     (emit-lexical-expression port (caddr expression)))
    (else
     (error "lexical expression is not yet supported by Rust/Rowan v1"
            expression))))

(def (lexical-precedence expression)
  (if (eq? (car expression) 'precedence) (cadr expression) 0))

(def (rust-rowan-module-source language version contract grammar-digest ir)
  (unless (equal? (alist-ref ir 'schema) "gerbil-parser.parser-ir.v1")
    (error "Rust/Rowan generation requires Parser IR v1" ir))
  (let* ((kinds (alist-ref ir 'syntax-kinds))
         (terminals (alist-ref ir 'terminals))
         (lexical-rules (alist-ref ir 'lexical-rules))
         (extras (map car (alist-ref ir 'extras)))
         (lr (alist-ref ir 'lr-spec))
         (productions (alist-ref lr 'productions))
         (actions (alist-ref lr 'actions))
         (gotos (alist-ref lr 'gotos)))
    (call-with-output-string
     (lambda (port)
       (display "// @generated by gerbil-parser/src/compiler/rust-rowan.ss\n" port)
       (display "// Source authority: canonical Grammar IR v1; do not edit.\n\n" port)
       (display "use gerbil_parser_rowan::{ActionEntry, GotoEntry, KindCategory, KindSpec, LanguageSpec, LexicalExpr, LexicalRule, Operand, OperandAction, ParserAction, Production, Reduction, Symbol, Terminal, TerminalSpec};\n\n" port)
       (display "static KINDS: &[KindSpec] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    KindSpec { name: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", category: KindCategory::" port)
          (display (case (cadr row) ((node) "Node") ((token) "Token")
                           (else (error "unknown syntax-kind category" row)))
                   port)
          (display " },\n" port))
        kinds)
       (display "];\n\nstatic TERMINALS: &[TerminalSpec] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    TerminalSpec { name: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", syntax_kind: " port)
          (display (kind-index kinds (cadr row)) port)
          (display " },\n" port))
        terminals)
       (display "];\n\nstatic LEXICAL_RULES: &[LexicalRule] = &[\n" port)
       (for-each
        (lambda (row)
          (display "    LexicalRule { terminal: " port)
          (display (rust-string (symbol-text (car row))) port)
          (display ", expression: " port)
          (emit-lexical-expression port (cadr row))
          (display ", precedence: " port)
          (display (lexical-precedence (cadr row)) port)
          (display ", extra: " port)
          (display (if (memq (car row) extras) "true" "false") port)
          (display " },\n" port))
        lexical-rules)
       (display "];\n\n" port)
       (emit-action-rows port actions)
       (emit-goto-rows port gotos)
       (display "static PRODUCTIONS: &[Production] = &[\n" port)
       (for-each (lambda (production)
                   (emit-production port production kinds))
                 productions)
       (display "];\n\npub static LANGUAGE: LanguageSpec = LanguageSpec {\n" port)
       (display "    language: " port) (display (rust-string language) port)
       (display ",\n    version: " port) (display (rust-string version) port)
       (display ",\n    contract: " port) (display (rust-string contract) port)
       (display ",\n    grammar_digest: " port)
       (display (rust-string grammar-digest) port)
       (display ",\n    case_insensitive: " port)
       (display (if (alist-ref ir 'case-insensitive?) "true" "false") port)
       (display ",\n    root_kind: " port)
       (display (kind-index kinds (alist-ref ir 'root-kind)) port)
       (display ",\n    kinds: KINDS,\n    terminals: TERMINALS,\n    lexical_rules: LEXICAL_RULES,\n    actions: ACTIONS,\n    gotos: GOTOS,\n    productions: PRODUCTIONS,\n};\n" port)))))

(def (write-rust-rowan-module! output-path source)
  (create-directory* (path-directory output-path))
  (call-with-output-file output-path (lambda (port) (display source port)))
  output-path)

;;; Raw IR describes recognition only. Complete descriptor products must use
;;; the admission boundary below, including contextual scanner products.
(def (generate-rust-rowan-module output-path language version contract
                                 grammar-digest ir)
  (write-rust-rowan-module!
   output-path (rust-rowan-module-source language version contract grammar-digest ir)))

;;; The sole descriptor-to-Rust source boundary. All product frontends delegate
;;; identity, capability admission and recognition emission here. Policy failure
;;; precedes product preparation, directory creation and output publication.
(def (language-rust-rowan-module-source descriptor)
  (require-portable-language-policy! descriptor)
  (rust-rowan-module-source
   (language-grammar-language descriptor)
   (language-grammar-version descriptor)
   (language-grammar-contract descriptor)
   (parser-machine-grammar-digest (language-grammar-machine descriptor))
   (language-grammar-ir descriptor)))

(def (generate-language-rust-rowan-module output-path descriptor)
  (write-rust-rowan-module! output-path (language-rust-rowan-module-source descriptor)))
