;;; -*- Gerbil -*-
;;; Restricted Rust syntax values for deterministic AOT table generation.

(export rust-struct rust-static rust-array rust-some rust-none
        rust-number rust-string rust-identifier rust-module rust-render
        rust-function rust-function-value rust-block rust-let rust-call rust-method
        rust-before rust-after rust-first-word rust-words rust-any
        rust-empty rust-string-in rust-if
        rust-binary
        rust-function-form? rust-function-form-name
        rust-function-form-parameters rust-function-form-result
        rust-function-form-body rust-block-form? rust-block-form-statements
        rust-block-form-result rust-let-form? rust-let-form-name
        rust-let-form-value
        rust-method-form? rust-method-form-method
        rust-first-word-form? rust-string-in-form?
        rust-any-form? rust-empty-form?
        rust-if-form? rust-if-form-condition rust-if-form-alternate
        rust-struct-form? rust-struct-form-name rust-struct-form-fields
        rust-field-name rust-field-value
        rust-array-form? rust-array-form-values
        rust-string-form? rust-string-form-value
        rust-identifier-form? rust-identifier-form-value
        rust-some-form? rust-some-form-value
        rust-number-form? rust-number-form-value
        rust-module-form? rust-module-form-item
        rust-static-form? rust-static-form-value)

(defstruct rust-field (name value) transparent: #t)
(defstruct rust-struct-form (name fields) transparent: #t)
(defstruct rust-static-form (name type value) transparent: #t)
(defstruct rust-array-form (values) transparent: #t)
(defstruct rust-some-form (value) transparent: #t)
(defstruct rust-none-form () transparent: #t)
(defstruct rust-number-form (value) transparent: #t)
(defstruct rust-string-form (value) transparent: #t)
(defstruct rust-identifier-form (value) transparent: #t)
(defstruct rust-module-form (imports item) transparent: #t)
(defstruct rust-function-form (name parameters result body) transparent: #t)
(defstruct rust-block-form (statements result) transparent: #t)
(defstruct rust-let-form (name value) transparent: #t)
(defstruct rust-call-form (callee arguments) transparent: #t)
(defstruct rust-method-form (receiver method arguments) transparent: #t)
(defstruct rust-before-form (value delimiter owned?) transparent: #t)
(defstruct rust-after-form (value delimiter) transparent: #t)
(defstruct rust-first-word-form (value) transparent: #t)
(defstruct rust-words-form (value) transparent: #t)
(defstruct rust-any-form (collection variable body slice?) transparent: #t)
(defstruct rust-empty-form (value) transparent: #t)
(defstruct rust-string-in-form (value collection) transparent: #t)
(defstruct rust-if-form (condition consequent alternate) transparent: #t)
(defstruct rust-binary-form (operator left right) transparent: #t)

;; The macro admits only named fields. Callers build Rust syntax values, not
;; snippets of Rust text; the renderer is the sole textual boundary.
(defrules rust-struct ()
  ((_ name (field value) ...)
   (make-rust-struct-form 'name
                     (list (make-rust-field 'field value) ...))))

(defrules rust-static ()
  ((_ name type value)
   (make-rust-static-form 'name 'type value)))

(def (rust-array values) (make-rust-array-form values))
(def (rust-some value) (make-rust-some-form value))
(def (rust-none) (make-rust-none-form))
(def (rust-number value) (make-rust-number-form value))
(def (rust-string value) (make-rust-string-form value))
(def (rust-identifier value) (make-rust-identifier-form value))
(def (rust-module imports item) (make-rust-module-form imports item))

;; A bounded function surface for pure Scheme algorithms lowered ahead of time.
;; Parameters and result types are explicit: the renderer never infers Rust
;; types or accepts a pre-rendered function body.
(defrules rust-function ()
  ((_ name ((parameter type) ...) result body)
   (rust-function-value 'name
                        (list (cons 'parameter type) ...)
                        result body)))

(def (rust-function-value name parameters result body)
  (unless (and (symbol? name)
               (list? parameters)
               (andmap (lambda (parameter)
                         (and (pair? parameter)
                              (symbol? (car parameter))
                              (string? (cdr parameter))
                              (> (string-length (cdr parameter)) 0)))
                       parameters)
               (string? result) (> (string-length result) 0)
               (rust-block-form? body))
    (error "invalid Rust function syntax" name parameters result body))
  (make-rust-function-form name parameters result body))

(def (rust-block statements result)
  (make-rust-block-form statements result))
(def (rust-let name value)
  (make-rust-let-form name value))
(def (rust-call callee arguments)
  (make-rust-call-form callee arguments))
(def (rust-method receiver method arguments)
  (make-rust-method-form receiver method arguments))
(def (rust-before value delimiter owned?)
  (unless (rust-identifier-form? value)
    (error "Rust before requires a single bound value" value))
  (make-rust-before-form value delimiter owned?))
(def (rust-after value delimiter)
  (make-rust-after-form value delimiter))
(def (rust-first-word value)
  (make-rust-first-word-form value))
(def (rust-words value) (make-rust-words-form value))
(def (rust-any collection variable body slice?)
  (make-rust-any-form collection variable body slice?))
(def (rust-empty value) (make-rust-empty-form value))
(def (rust-string-in value collection)
  (make-rust-string-in-form value collection))
(def (rust-if condition consequent alternate)
  (make-rust-if-form condition consequent alternate))
(def (rust-binary operator left right)
  (unless (member operator '("||" "&&" "=="))
    (error "unsupported Rust pure binary operator" operator))
  (make-rust-binary-form operator left right))

(def (render-sequence port values)
  (let loop ((rest values) (first? #t))
    (when (pair? rest)
      (unless first? (display ", " port))
      (render-node port (car rest))
      (loop (cdr rest) #f))))

(def (render-field port field)
  (display (rust-field-name field) port)
  (display ": " port)
  (render-node port (rust-field-value field)))

(def (render-block port block)
  (display "{\n" port)
  (for-each (lambda (statement)
              (display "    " port)
              (render-node port statement)
              (display ";\n" port))
            (rust-block-form-statements block))
  (display "    " port)
  (render-node port (rust-block-form-result block))
  (display "\n}" port))

(def (render-binary-operand port operand operator)
  (let (group? (and (rust-binary-form? operand)
                   (not (equal? (rust-binary-form-operator operand)
                                operator))))
    (when group? (display "(" port))
    (render-node port operand)
    (when group? (display ")" port))))

(def (render-node port node)
  (cond
   ((rust-struct-form? node)
    (display (rust-struct-form-name node) port)
    (display " { " port)
    (let loop ((fields (rust-struct-form-fields node)) (first? #t))
      (when (pair? fields)
        (unless first? (display ", " port))
        (render-field port (car fields))
        (loop (cdr fields) #f)))
    (display " }" port))
   ((rust-static-form? node)
    (display "pub static " port)
    (display (rust-static-form-name node) port)
    (display ": " port)
    (display (rust-static-form-type node) port)
    (display " = " port)
    (render-node port (rust-static-form-value node))
    (display ";\n" port))
   ((rust-array-form? node)
    (display "&[" port)
    (render-sequence port (rust-array-form-values node))
    (display "]" port))
   ((rust-some-form? node)
    (display "Some(" port)
    (render-node port (rust-some-form-value node))
    (display ")" port))
   ((rust-none-form? node) (display "None" port))
   ((rust-number-form? node) (display (rust-number-form-value node) port))
   ((rust-string-form? node) (write (rust-string-form-value node) port))
   ((rust-identifier-form? node)
    (display (rust-identifier-form-value node) port))
   ((rust-module-form? node)
    (display "// @generated by gerbil-parser/src/compiler/line-structure-rowan.ss\n" port)
    (display "use gerbil_parser_rowan::{" port)
    (let loop ((imports (rust-module-form-imports node)) (first? #t))
      (when (pair? imports)
        (unless first? (display ", " port))
        (display (car imports) port)
        (loop (cdr imports) #f)))
    (display "};\n\n" port)
    (render-node port (rust-module-form-item node)))
   ((rust-function-form? node)
    (display "pub fn " port)
    (display (rust-function-form-name node) port)
    (display "(" port)
    (let loop ((parameters (rust-function-form-parameters node))
               (first? #t))
      (when (pair? parameters)
        (unless first? (display ", " port))
        (display (caar parameters) port)
        (display ": " port)
        (display (cdar parameters) port)
        (loop (cdr parameters) #f)))
    (display ") -> " port)
    (display (rust-function-form-result node) port)
    (display " " port)
    (render-block port (rust-function-form-body node))
    (newline port))
   ((rust-block-form? node) (render-block port node))
   ((rust-let-form? node)
    (display "let " port)
    (display (rust-let-form-name node) port)
    (display " = " port)
    (render-node port (rust-let-form-value node)))
   ((rust-call-form? node)
    (render-node port (rust-call-form-callee node))
    (display "(" port)
    (render-sequence port (rust-call-form-arguments node))
    (display ")" port))
   ((rust-method-form? node)
    (render-node port (rust-method-form-receiver node))
    (display "." port)
    (display (rust-method-form-method node) port)
    (display "(" port)
    (render-sequence port (rust-method-form-arguments node))
    (display ")" port))
   ((rust-before-form? node)
    (render-node port (rust-before-form-value node))
    (display ".split_once(" port)
    (render-node port (rust-before-form-delimiter node))
    (display ").map_or(" port)
    (render-node port (rust-before-form-value node))
    (display ", |(head, _)| head)" port)
    (when (rust-before-form-owned? node)
      (display ".to_owned()" port)))
   ((rust-after-form? node)
    (render-node port (rust-after-form-value node))
    (write-string ".split_once(" port)
    (render-node port (rust-after-form-delimiter node))
    (write-string ").map_or(\"\", |(_, tail)| tail)" port))
   ((rust-first-word-form? node)
    (render-node port (rust-first-word-form-value node))
    (display ".split_whitespace().next().unwrap_or(\"\")" port))
   ((rust-words-form? node)
    (render-node port (rust-words-form-value node))
    (write-string ".split_whitespace()" port))
   ((rust-any-form? node)
    (render-node port (rust-any-form-collection node))
    (when (rust-any-form-slice? node)
      (write-string ".iter().map(String::as_str)" port))
    (write-string ".any(|" port)
    (write-string (rust-any-form-variable node) port)
    (write-string "| " port)
    (render-node port (rust-any-form-body node))
    (write-string ")" port))
   ((rust-empty-form? node)
    (render-node port (rust-empty-form-value node))
    (write-string ".is_empty()" port))
   ((rust-string-in-form? node)
    (render-node port (rust-string-in-form-collection node))
    (display ".contains(&" port)
    (render-node port (rust-string-in-form-value node))
    (display ")" port))
   ((rust-if-form? node)
    (display "if " port)
    (render-node port (rust-if-form-condition node))
    (display " { " port)
    (render-node port (rust-if-form-consequent node))
    (if (rust-if-form? (rust-if-form-alternate node))
      (begin
        (display " } else " port)
        (render-node port (rust-if-form-alternate node)))
      (begin
        (display " } else { " port)
        (render-node port (rust-if-form-alternate node))
        (display " }" port))))
   ((rust-binary-form? node)
    (render-binary-operand port (rust-binary-form-left node)
                           (rust-binary-form-operator node))
    (display " " port)
    (display (rust-binary-form-operator node) port)
    (display " " port)
    (render-binary-operand port (rust-binary-form-right node)
                           (rust-binary-form-operator node)))
   (else (error "unsupported Rust syntax value" node))))

(def (rust-render node)
  (call-with-output-string
   (lambda (port) (render-node port node))))
