;;; -*- Gerbil -*-
;;; Shared contextual Scanner IR to immutable Rust declarations.
(import (only-in :clan/poo/object .ref)
        (only-in ../language/source-strategy bind-source-strategy)
        (only-in ../language/scanner-profile compile-scanner-profile)
        (only-in ../language/command-profile compile-command-profile command-plan-recipe admit-command-plan)
        (only-in ../runtime/region-scanner region-plan-specification prepare-scoped-region-source)
        (only-in ../runtime/contextual-scanner prepare-contextual-scanner-plan)
        (only-in ./contextual-scanner-ir contextual-scanner-ir-ref)
        (only-in ./rust-rowan language-rust-rowan-module-source rust-text-profile-expression-source result-profile-rust-source)
        (only-in ../language/part-profile part-plan? compile-part-profile part-plan-recipe part-plan-binding binding-plan-region-plan binding-plan-region-scopes admit-part-plan)
        (only-in ../language/result-profile result-plan? compile-result-profile)
        (only-in ../language/descriptor language-grammar-ir language-grammar-machine)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ../runtime/parser-ir-data parser-ir-ref)
        (only-in ../runtime/parser prepare-contextual-parser))
(export command-source-rust-module-source generate-command-source-rust-module command-profile-rust-source part-profile-rust-source region-plan-rust-source rust-scanner-module-source generate-rust-scanner-module generate-contextual-language-rust-rowan-module)
(def (rust-text port value)
  (display "\"" port)
  (for-each
   (lambda (ch)
     (case ch
       ((#\\) (display "\\\\" port))
       ((#\") (display "\\\"" port))
       ((#\newline) (display "\\n" port))
       ((#\return) (display "\\r" port))
       ((#\tab) (display "\\t" port))
       (else
        (let (code (char->integer ch))
          (if (or (< code 32) (= code 127))
            (begin (display "\\u{" port) (display (number->string code 16) port) (display "}" port))
            (write-char ch port)))))) (string->list value))
  (display "\"" port))
(def (rust-name port name) (rust-text port (symbol->string name)))
(def (rust-strings port values)
  (display "&[" port)
  (for-each (lambda (value) (rust-text port value) (display "," port)) values)
  (display "]" port))
(def (rust-symbols port values) (rust-strings port (map symbol->string values)))
(def (rust-char port ch)
  (display "'\\u{" port) (display (number->string (char->integer ch) 16) port)
  (display "}'" port))
(def (emit-region-fields port stops quotes pairs initial-stop)
  (display "stops: " port) (rust-strings port stops)
  (display ", quotes: &[" port)
  (for-each
   (lambda (row)
     (display "gerbil_parser_rowan::scanner::RegionQuote { delimiter: " port)
     (rust-char port (car row))
     (display (if (cadr row) ", escaped: true, pairs: " ", escaped: false, pairs: ") port)
     (rust-strings port (caddr row)) (display " }," port)) quotes)
  (display "], pairs: &[" port)
  (for-each
   (lambda (row)
     (display "gerbil_parser_rowan::scanner::RegionPair { prefix: " port)
     (rust-text port (car row)) (display ", opening: " port) (rust-char port (cadr row))
     (display ", closing: " port) (rust-char port (caddr row))
     (display ", depth: " port) (display (cadddr row) port) (display " }," port)) pairs)
  (display (if initial-stop "], consume_initial_stop: true" "], consume_initial_stop: false") port))
(def (region-plan-rust-source plan (scopes '()))
  (prepare-scoped-region-source plan "" scopes)
  (let ((data (region-plan-specification plan)) (port (open-output-string)))
    (display "pub static REGION: gerbil_parser_rowan::scanner::RegionSpec = gerbil_parser_rowan::scanner::RegionSpec { " port)
    (apply emit-region-fields port data)
    (display " };\npub static SCOPES: &[gerbil_parser_rowan::scanner::RegionScope] = &[" port)
    (for-each (lambda (scope)
      (display "gerbil_parser_rowan::scanner::RegionScope { prefix: " port) (rust-text port (car scope))
      (display ", pairs: " port) (rust-strings port (cdr scope)) (display " }," port)) scopes)
    (display "];\n" port) (get-output-string port)))
(def (emit-matcher port matcher)
  (display "ScannerMatcher::" port)
  (match matcher
    (['literal text] (display "Literal(" port) (rust-text port text) (display ")" port))
    (['literals values] (display "Literals(" port) (rust-strings port values) (display ")" port))
    (['quoted-string values] (display "QuotedString(" port) (rust-strings port values) (display ")" port))
    (['unless-prefix prefixes exceptions child]
     (display "UnlessPrefix { prefixes: " port) (rust-strings port prefixes)
     (display ", exceptions: " port) (rust-strings port exceptions)
     (display ", child: &" port) (emit-matcher port child) (display " }" port))
    (['line-prefix prefix separator]
     (display "LinePrefix { prefix: " port) (rust-text port prefix)
     (display ", separator: " port) (rust-char port (string-ref separator 0)) (display " }" port))
    (['marker-line-at separator]
     (display "MarkerLineAt(" port) (rust-char port (string-ref separator 0)) (display ")" port))
    (['body-line-at separator]
     (display "BodyLineAt(" port) (rust-char port (string-ref separator 0)) (display ")" port))
    (['region-word [stops quotes pairs initial-stop]]
     (display "RegionWord { " port)
     (emit-region-fields port stops quotes pairs initial-stop)
     (display " }" port))
    (['balanced-word stops quotes pairs]
     (display "BalancedWord { stops: " port) (rust-strings port stops)
     (display ", quotes: " port) (rust-strings port quotes)
     (display ", pairs: &[" port)
     (for-each
      (lambda (pair)
        (display "BalancedPair { prefix: " port) (rust-text port (car pair))
        (display ", opening: " port) (rust-char port (cadr pair))
        (display ", closing: " port) (rust-char port (caddr pair))
        (display " }," port)) pairs)
     (display "] }" port))
    ([opcode]
     (display (case opcode
                ((horizontal-whitespace+) "HorizontalWhitespace")
                ((newline) "Newline") ((newline-one) "NewlineOne")
                ((identifier) "Identifier") ((marker-line) "MarkerLine")
                ((body-line) "BodyLine")
                (else (error "unsupported Rust scanner opcode" opcode))) port))
    (else (error "unsupported Rust scanner matcher" matcher))))
(def (emit-action port action)
  (display "ScannerAction::" port)
  (match action
    ('keep (display "Keep" port))
    (['expect-marker strip?]
     (display (if strip? "ExpectMarker(true)" "ExpectMarker(false)") port))
    (['expect-marker-in strip? mode]
     (display (if strip? "ExpectMarkerIn { strip_tabs: true, mode: " "ExpectMarkerIn { strip_tabs: false, mode: ") port)
     (rust-name port mode) (display " }" port))
    (['enqueue-marker-in policy mode]
     (display "EnqueueMarkerIn { policy: MarkerPolicy::" port)
     (display (case policy ((raw) "Raw") ((shell-quote-removal) "ShellQuoteRemoval")
                (else (error "unsupported Rust delimiter policy" policy))) port)
     (display ", mode: " port) (rust-name port mode) (display " }" port))
    (['enqueue-if-expecting policy]
     (display "EnqueueIfExpecting(MarkerPolicy::" port)
     (display (case policy ((raw) "Raw") ((shell-quote-removal) "ShellQuoteRemoval")
                (else (error "unsupported Rust delimiter policy" policy))) port)
     (display ")" port))
    (['activate-next mode]
     (display "ActivateNext(" port) (rust-name port mode) (display ")" port))
    (['finish-marker base body]
     (display "FinishMarker { base: " port) (rust-name port base)
     (display ", body: " port) (rust-name port body) (display " }" port))
    (else (error "unsupported Rust scanner action" action))))
(def (rust-scanner-module-source ir)
  ;; Runtime admission verifies the Scheme-owned digest/opcode contract before
  ;; any generated output. Languages provide no Rust source or callbacks.
  (prepare-contextual-scanner-plan ir)
  (call-with-output-string
   (lambda (port)
     (display "// @generated from Scheme contextual Scanner IR; do not edit.\n" port)
     (display "#[allow(unused_imports)]\nuse gerbil_parser_rowan::scanner::{BalancedPair, MarkerPolicy, ScannerAction, ScannerCell, ScannerMatcher, ScannerRule, ScannerSpec};\n" port)
     (display "pub static SCANNER: ScannerSpec = ScannerSpec {\n opcode_contract: " port)
     (rust-text port (contextual-scanner-ir-ref ir 'opcode-contract))
     (display ",\n digest: " port) (rust-text port (contextual-scanner-ir-ref ir 'digest))
     (display ",\n base_grammar_digest: " port)
     (let (digest (contextual-scanner-ir-ref ir 'grammar-digest))
       (if digest (begin (display "Some(" port) (rust-text port digest) (display ")" port))
           (display "None" port)))
     (display ",\n initial_mode: " port) (rust-name port (contextual-scanner-ir-ref ir 'initial-mode))
     (display ",\n modes: " port) (rust-symbols port (contextual-scanner-ir-ref ir 'modes))
     (display ",\n positions: " port) (rust-symbols port (contextual-scanner-ir-ref ir 'positions))
     (display ",\n rules: &[\n" port)
     (for-each
      (lambda (row)
        (display "ScannerRule { name: " port) (rust-name port (list-ref row 0))
        (display ", mode: " port) (rust-name port (list-ref row 1))
        (display ", form: " port) (rust-name port (list-ref row 2))
        (display ", matcher: " port) (emit-matcher port (list-ref row 3))
        (unless (<= -9223372036854775808 (list-ref row 4) 9223372036854775807)
          (error "scanner rank exceeds Rust i64" (list-ref row 4)))
        (display ", rank: " port) (display (list-ref row 4) port)
        (display ", action: " port) (emit-action port (list-ref row 5))
        (display " },\n" port)) (contextual-scanner-ir-ref ir 'rules))
     (display "],\n cells: &[\n" port)
     (for-each
      (lambda (row)
        (display "ScannerCell { mode: " port) (rust-name port (list-ref row 0))
        (display ", position: " port) (rust-name port (list-ref row 1))
        (display ", form: " port) (rust-name port (list-ref row 2))
        (display ", terminal: " port) (rust-name port (car (list-ref row 3)))
        (display " },\n" port)) (filter (lambda (row) (list-ref row 3)) (contextual-scanner-ir-ref ir 'cells)))
     (display "]\n};\n" port))))
(def (generate-rust-scanner-module path ir)
  (let (source (rust-scanner-module-source ir))
    (create-directory* (path-directory path))
    (call-with-output-file path (lambda (port) (display source port)))
    path))

;;; One downstream descriptor and its compiled contextual declaration produce
;;; the complete Rust language/parser/scanner data product.
(def (generate-contextual-language-rust-rowan-module path descriptor product)
  (let (language-source (language-rust-rowan-module-source descriptor))
    (prepare-contextual-parser (language-grammar-machine descriptor) product)
    (let (actions (cdr (assq 'actions (parser-ir-ref (language-grammar-ir descriptor) 'lr-spec))))
      (when (any (lambda (row) (any (lambda (entry) (eq? (cadr entry) 'fork)) row))
                 (vector->list actions))
        (error "Rust contextual AOT does not admit GLR scanner branch state")))
    (let (scanner-source (rust-scanner-module-source (cdr (assq 'scanner product))))
      (create-directory* (path-directory path))
      (call-with-output-file path
        (lambda (port)
          (display language-source port)
          (display "pub mod contextual_scanner {\n" port) (display scanner-source port)
          (display "}\npub static CONTEXTUAL: gerbil_parser_rowan::ContextualParserSpec = gerbil_parser_rowan::ContextualParserSpec { language: &LANGUAGE, scanner: &contextual_scanner::SCANNER, parser_digest: " port)
          (rust-text port (cdr (assq 'digest product)))
          (display ", state_positions: " port)
          (rust-symbols port (map cdr (cdr (assq 'state-positions product))))
          (display " };\n" port)))
      path)))


;;; Lower admitted POO recognition slots; downstream languages supply no Rust.
(def (part-profile-rust-source profile results regions)
  (let* ((plan (if (part-plan? profile) profile (compile-part-profile profile)))
         (result-plan (if (result-plan? results) results (compile-result-profile results)))
         (_ (admit-part-plan plan result-plan regions))
         (recipe (part-plan-recipe plan)) (bindings (list-ref recipe 3))
         (port (open-output-string)))
    (def (binding-index role)
      (let loop ((rows bindings) (index 0))
        (cond ((null? rows) (error "unknown part binding" role))
              ((eq? (caar rows) role) index) (else (loop (cdr rows) (+ index 1))))))
    (display "use gerbil_parser_rowan::{BindingSpec, SubscriptSpec, PartGuard, PartOpcode, PartRule, PartProfileSpec};\n" port)
    (display "pub mod regions {\n" port) (display (region-plan-rust-source regions) port) (display "}\n" port)
    (for-each (lambda (row index)
      (let* ((binding (part-plan-binding plan (car row))) (derived (binding-plan-region-plan binding regions)))
        (when derived
          (display "mod subscript_" port) (display index port) (display " {\n" port)
          (display (region-plan-rust-source derived (binding-plan-region-scopes binding regions)) port)
          (display "}\n" port)))) bindings (iota (length bindings)))
    (display "pub static PART_PROFILE: PartProfileSpec = PartProfileSpec { contexts: " port)
    (rust-symbols port (car recipe)) (display ", literal: " port) (rust-name port (caddr recipe))
    (display ", assignment: " port)
    (if (assq 'assignment bindings)
      (begin (display "Some(" port) (display (binding-index 'assignment) port) (display ")" port))
      (display "None" port))
    (display ", bindings: &[" port)
    (for-each (lambda (row index)
      (let* ((binding (cadr row)) (subscript (cadddr binding)))
        (display "BindingSpec { name: &" port) (display (rust-text-profile-expression-source (car binding)) port)
        (display ", prefixes: " port) (rust-strings port (cadr binding))
        (display ", operators: " port) (rust-strings port (caddr binding))
        (display ", subscript: " port)
        (if subscript
          (begin (display "Some(SubscriptSpec { prefix: " port) (rust-text port (car subscript))
            (display ", closing: " port) (rust-char port (cadr subscript))
            (display ", regions: &subscript_" port) (display index port) (display "::REGION, scopes: subscript_" port)
            (display index port) (display "::SCOPES })" port))
          (display "None" port))
        (display " }," port))) bindings (iota (length bindings)))
    (display "], rules: &[" port)
    (for-each (lambda (row)
      (let* ((prefix (cadadr row)) (guard (caddr (cadr row))) (form (caddr row))
             (operation (car form)) (kind (if (eq? operation 'parameter) 'ParameterExpansion (cadr form)))
             (opening (case operation ((parameter) 2) ((name escape) 1) (else (caddr form))))
             (closing (case operation ((parameter) 1) ((name escape) 0) (else (cadddr form)))))
        (display "PartRule { contexts: " port) (rust-symbols port (car row))
        (display ", prefix: " port) (rust-text port prefix)
        (display ", guard: PartGuard::" port)
        (case guard ((any) (display "Any" port)) ((next) (display "Next" port))
          (else (display "Characters(" port) (rust-text port guard) (display ")" port)))
        (display ", projection: " port) (rust-name port kind)
        (display ", opening: " port) (display opening port) (display ", closing: " port) (display closing port)
        (display ", opcode: PartOpcode::" port)
        (case operation
          ((parameter name)
           (display (if (eq? operation 'parameter) "Parameter" "Name") port)
           (display " { binding: " port) (display (binding-index (if (eq? operation 'parameter) 'parameter (caddr form))) port)
           (display " }" port))
          ((quote quoted-body)
           (display (if (eq? operation 'quote) "Quote" "QuotedBody") port)
           (display " { delimiter: " port) (rust-char port (list-ref form 4)) (display " }" port))
          ((pair) (display "Pair" port)) ((escape) (display "Escape" port)))
        (display " }," port))) (cadr recipe))
    (display "] };\n" port) (get-output-string port)))

;;; Command control programs lower from the admitted POO slots, never hand-written Rust.
(def (emit-command-trigger port trigger)
 (display "CommandTrigger::" port)
 (case (car trigger)
  ((none) (display "None" port))
  ((manual) (if (null? (cdr trigger)) (display "Manual(None)" port)
    (begin (display "Manual(Some(&" port) (emit-command-trigger port (cadr trigger)) (display "))" port))))
  ((role) (display "Role(" port) (rust-name port (cadr trigger)) (display ")" port))
  ((or lookahead adjacent)
   (display (case (car trigger) ((or) "Or(") ((lookahead) "Lookahead(") (else "Adjacent(")) port)
   (display "&[" port) (for-each (lambda (row) (emit-command-trigger port row) (display "," port)) (cdr trigger)) (display "])" port))
  (else (display "Token { kind: " port) (rust-name port (car trigger))
    (display ", literals: " port) (rust-strings port (cdr trigger)) (display " }" port))))
(def (emit-command-program port program)
 (display "&[" port)
 (for-each (lambda (step)
  (display "CommandInstruction::" port)
  (case (car step)
   ((as raw word command)
    (display (case (car step) ((as) "As(") ((raw) "Raw(") ((word) "Word(") (else "Command(")) port)
    (rust-name port (cadr step)) (display ")" port))
   ((take) (display "Take { field: " port) (rust-name port (cadr step)) (display ", trigger: " port)
    (emit-command-trigger port (caddr step)) (display " }" port))
   ((list) (display "List { field: " port) (rust-name port (cadr step)) (display ", until: " port)
    (emit-command-trigger port (caddr step)) (display (if (cadddr step) ", allow_empty: true }" ", allow_empty: false }") port))
   ((call) (display "Call { field: " port) (rust-name port (cadr step)) (display ", form: " port) (rust-name port (caddr step)) (display " }" port))
   ((node) (display "Node { field: " port) (rust-name port (cadr step)) (display ", kind: " port) (rust-name port (caddr step))
    (display ", program: " port) (emit-command-program port (cdddr step)) (display " }" port))
   ((optional many until)
    (display (case (car step) ((optional) "Optional") ((many) "Many") (else "Until")) port)
    (display " { trigger: " port) (emit-command-trigger port (cadr step))
    (display ", program: " port) (emit-command-program port (cddr step)) (display " }" port))
   ((branch) (display "Branch { trigger: " port) (emit-command-trigger port (cadr step))
    (display ", yes: " port) (emit-command-program port (caddr step)) (display ", no: " port) (emit-command-program port (cadddr step)) (display " }" port))
   ((choose) (display "Choose(&[" port) (for-each (lambda (row)
    (display "CommandChoice { trigger: " port) (emit-command-trigger port (car row))
    (display ", program: " port) (emit-command-program port (cdr row)) (display " }," port)) (cdr step)) (display "])" port))
   ((balance) (display "Balance { open: " port) (emit-command-trigger port (cadr step))
    (display ", close: " port) (emit-command-trigger port (caddr step)) (display ", depth: " port) (display (list-ref step 3) port)
    (display ", open_field: " port) (rust-name port (list-ref step 4)) (display ", close_field: " port) (rust-name port (list-ref step 5))
    (display ", program: " port) (emit-command-program port (list-tail step 6)) (display " }" port))
   (else (error "unregistered command Rust instruction" step)))
  (display "," port)) program)
 (display "]" port))
(def (command-profile-rust-source profile results scanner)
 (let* ((plan (compile-command-profile profile))
        (results (if (result-plan? results) results (compile-result-profile results)))
        (_ (admit-command-plan plan results scanner))
        (recipe (command-plan-recipe plan)) (port (open-output-string)))
  (display "use gerbil_parser_rowan::{CommandProgramSpec, CommandForm, CommandInstruction, CommandChoice, CommandTrigger, CommandRole, CommandTokenClass};\n" port)
  (display "pub static COMMAND_PROFILE: CommandProgramSpec = CommandProgramSpec { assignment_tail: " port)
  (rust-name port (cadr (assq 'assignment-tail (list-ref recipe 4))))
  (display ", pipeline_head: " port)
  (rust-name port (cadr (assq 'pipeline-head (list-ref recipe 4))))
  (display ", nodes: &[" port)
  (for-each (lambda (row) (display "(" port) (rust-name port (car row)) (display "," port) (rust-name port (cadr row)) (display ")," port)) (caddr recipe))
  (display "], roles: &[" port)
  (for-each (lambda (row)
   (display "CommandRole { name: " port) (rust-name port (car row)) (display ", classes: &[" port)
   (for-each (lambda (clause) (display "CommandTokenClass { kind: " port) (rust-name port (car clause))
    (display ", literals: " port) (rust-strings port (cdr clause)) (display " }," port)) (cdr row))
   (display "] }," port)) (car recipe))
  (display "], descriptor: &" port) (display (rust-text-profile-expression-source (cadar (cadr recipe))) port)
  (display ", forms: &[" port)
  (for-each (lambda (row)
   (display "CommandForm { id: " port) (rust-name port (car row)) (display ", trigger: " port) (emit-command-trigger port (cadr row))
   (display ", priority: " port) (display (caddr row) port) (display ", kind: " port) (rust-name port (cadddr row))
   (display ", program: " port) (emit-command-program port (list-tail row 4)) (display " }," port)) (list-ref recipe 3))
  (display "] };\n" port) (get-output-string port)))

(def (command-source-rust-module-source strategy)
 (let-values (((recipe engine) (bind-source-strategy strategy)))
  (unless (eq? (car recipe) 'shell) (error "Command Source Rust AOT requires the closed shell strategy"))
  (let* ((results (.ref strategy 'results)) (parts (.ref strategy 'parts))
         (commands (.ref strategy 'commands)) (scanner (.ref strategy 'scanner)) (regions (.ref strategy 'regions))
         (port (open-output-string)))
   (display (result-profile-rust-source (compile-result-profile results)) port)
   (display (part-profile-rust-source parts results regions) port)
   (display (command-profile-rust-source commands results scanner) port)
   (display "pub mod scanner {\n" port) (display (rust-scanner-module-source (compile-scanner-profile scanner)) port) (display "}\n" port)
   (display "pub static SOURCE: gerbil_parser_rowan::CommandSourceSpec = gerbil_parser_rowan::CommandSourceSpec { scanner: &scanner::SCANNER, parts: &PART_PROFILE, regions: &regions::REGION, results: &RESULT_PROFILE, commands: &COMMAND_PROFILE };\n" port)
   (get-output-string port))))
(def (generate-command-source-rust-module strategy path)
 (let (source (command-source-rust-module-source strategy))
  (create-directory* (path-directory path))
  (call-with-output-file path (lambda (port) (display source port))) path))
