;;; -*- Gerbil -*-
;;; Shared contextual Scanner IR to immutable Rust declarations.
(import (only-in ../runtime/region-scanner region-plan-specification prepare-scoped-region-source)
        (only-in ../runtime/contextual-scanner prepare-contextual-scanner-plan)
        (only-in ./contextual-scanner-ir contextual-scanner-ir-ref)
        (only-in ./rust-rowan language-rust-rowan-module-source)
        (only-in ../language/descriptor language-grammar-ir language-grammar-machine)
        (only-in ./machine parser-machine-grammar-digest)
        (only-in ../runtime/parser-ir-data parser-ir-ref)
        (only-in ../runtime/parser prepare-contextual-parser))
(export region-plan-rust-source rust-scanner-module-source generate-rust-scanner-module generate-contextual-language-rust-rowan-module)
(def (rust-text port value)
  (display "\"" port)
  (for-each
   (lambda (ch)
     (case ch
       ((#\\) (display "\\\\" port))
       ((#\") (display "\\\"" port))
       ((#\newline) (display "\\n" port))
       ((#\return) (display "\\r" port))
       ((#\tab) (display "\\t" port))
       (else
        (let (code (char->integer ch))
          (if (or (< code 32) (= code 127))
            (begin (display "\\u{" port) (display (number->string code 16) port) (display "}" port))
            (write-char ch port)))))) (string->list value))
  (display "\"" port))
(def (rust-name port name) (rust-text port (symbol->string name)))
(def (rust-strings port values)
  (display "&[" port)
  (for-each (lambda (value) (rust-text port value) (display "," port)) values)
  (display "]" port))
(def (rust-symbols port values) (rust-strings port (map symbol->string values)))
(def (rust-char port ch)
  (display "'\\u{" port) (display (number->string (char->integer ch) 16) port)
  (display "}'" port))
(def (emit-region-fields port stops quotes pairs initial-stop)
  (display "stops: " port) (rust-strings port stops)
  (display ", quotes: &[" port)
  (for-each
   (lambda (row)
     (display "gerbil_parser_rowan::scanner::RegionQuote { delimiter: " port)
     (rust-char port (car row))
     (display (if (cadr row) ", escaped: true, pairs: " ", escaped: false, pairs: ") port)
     (rust-strings port (caddr row)) (display " }," port)) quotes)
  (display "], pairs: &[" port)
  (for-each
   (lambda (row)
     (display "gerbil_parser_rowan::scanner::RegionPair { prefix: " port)
     (rust-text port (car row)) (display ", opening: " port) (rust-char port (cadr row))
     (display ", closing: " port) (rust-char port (caddr row))
     (display ", depth: " port) (display (cadddr row) port) (display " }," port)) pairs)
  (display (if initial-stop "], consume_initial_stop: true" "], consume_initial_stop: false") port))
(def (region-plan-rust-source plan (scopes '()))
  (prepare-scoped-region-source plan "" scopes)
  (let ((data (region-plan-specification plan)) (port (open-output-string)))
    (display "pub static REGION: gerbil_parser_rowan::scanner::RegionSpec = gerbil_parser_rowan::scanner::RegionSpec { " port)
    (apply emit-region-fields port data)
    (display " };\npub static SCOPES: &[gerbil_parser_rowan::scanner::RegionScope] = &[" port)
    (for-each (lambda (scope)
      (display "gerbil_parser_rowan::scanner::RegionScope { prefix: " port) (rust-text port (car scope))
      (display ", pairs: " port) (rust-strings port (cdr scope)) (display " }," port)) scopes)
    (display "];\n" port) (get-output-string port)))
(def (emit-matcher port matcher)
  (display "ScannerMatcher::" port)
  (match matcher
    (['literal text] (display "Literal(" port) (rust-text port text) (display ")" port))
    (['literals values] (display "Literals(" port) (rust-strings port values) (display ")" port))
    (['quoted-string values] (display "QuotedString(" port) (rust-strings port values) (display ")" port))
    (['unless-prefix prefixes exceptions child]
     (display "UnlessPrefix { prefixes: " port) (rust-strings port prefixes)
     (display ", exceptions: " port) (rust-strings port exceptions)
     (display ", child: &" port) (emit-matcher port child) (display " }" port))
    (['line-prefix prefix separator]
     (display "LinePrefix { prefix: " port) (rust-text port prefix)
     (display ", separator: " port) (rust-char port (string-ref separator 0)) (display " }" port))
    (['marker-line-at separator]
     (display "MarkerLineAt(" port) (rust-char port (string-ref separator 0)) (display ")" port))
    (['body-line-at separator]
     (display "BodyLineAt(" port) (rust-char port (string-ref separator 0)) (display ")" port))
    (['region-word [stops quotes pairs initial-stop]]
     (display "RegionWord { " port)
     (emit-region-fields port stops quotes pairs initial-stop)
     (display " }" port))
    (['balanced-word stops quotes pairs]
     (display "BalancedWord { stops: " port) (rust-strings port stops)
     (display ", quotes: " port) (rust-strings port quotes)
     (display ", pairs: &[" port)
     (for-each
      (lambda (pair)
        (display "BalancedPair { prefix: " port) (rust-text port (car pair))
        (display ", opening: " port) (rust-char port (cadr pair))
        (display ", closing: " port) (rust-char port (caddr pair))
        (display " }," port)) pairs)
     (display "] }" port))
    ([opcode]
     (display (case opcode
                ((horizontal-whitespace+) "HorizontalWhitespace")
                ((newline) "Newline") ((newline-one) "NewlineOne")
                ((identifier) "Identifier") ((marker-line) "MarkerLine")
                ((body-line) "BodyLine")
                (else (error "unsupported Rust scanner opcode" opcode))) port))
    (else (error "unsupported Rust scanner matcher" matcher))))
(def (emit-action port action)
  (display "ScannerAction::" port)
  (match action
    ('keep (display "Keep" port))
    (['expect-marker strip?]
     (display (if strip? "ExpectMarker(true)" "ExpectMarker(false)") port))
    (['expect-marker-in strip? mode]
     (display (if strip? "ExpectMarkerIn { strip_tabs: true, mode: " "ExpectMarkerIn { strip_tabs: false, mode: ") port)
     (rust-name port mode) (display " }" port))
    (['enqueue-marker-in policy mode]
     (display "EnqueueMarkerIn { policy: MarkerPolicy::" port)
     (display (case policy ((raw) "Raw") ((shell-quote-removal) "ShellQuoteRemoval")
                (else (error "unsupported Rust delimiter policy" policy))) port)
     (display ", mode: " port) (rust-name port mode) (display " }" port))
    (['enqueue-if-expecting policy]
     (display "EnqueueIfExpecting(MarkerPolicy::" port)
     (display (case policy ((raw) "Raw") ((shell-quote-removal) "ShellQuoteRemoval")
                (else (error "unsupported Rust delimiter policy" policy))) port)
     (display ")" port))
    (['activate-next mode]
     (display "ActivateNext(" port) (rust-name port mode) (display ")" port))
    (['finish-marker base body]
     (display "FinishMarker { base: " port) (rust-name port base)
     (display ", body: " port) (rust-name port body) (display " }" port))
    (else (error "unsupported Rust scanner action" action))))
(def (rust-scanner-module-source ir)
  ;; Runtime admission verifies the Scheme-owned digest/opcode contract before
  ;; any generated output. Languages provide no Rust source or callbacks.
  (prepare-contextual-scanner-plan ir)
  (call-with-output-string
   (lambda (port)
     (display "// @generated from Scheme contextual Scanner IR; do not edit.\n" port)
     (display "#[allow(unused_imports)]\nuse gerbil_parser_rowan::scanner::{BalancedPair, MarkerPolicy, ScannerAction, ScannerCell, ScannerMatcher, ScannerRule, ScannerSpec};\n" port)
     (display "pub static SCANNER: ScannerSpec = ScannerSpec {\n opcode_contract: " port)
     (rust-text port (contextual-scanner-ir-ref ir 'opcode-contract))
     (display ",\n digest: " port) (rust-text port (contextual-scanner-ir-ref ir 'digest))
     (display ",\n base_grammar_digest: " port)
     (let (digest (contextual-scanner-ir-ref ir 'grammar-digest))
       (if digest (begin (display "Some(" port) (rust-text port digest) (display ")" port))
           (display "None" port)))
     (display ",\n initial_mode: " port) (rust-name port (contextual-scanner-ir-ref ir 'initial-mode))
     (display ",\n modes: " port) (rust-symbols port (contextual-scanner-ir-ref ir 'modes))
     (display ",\n positions: " port) (rust-symbols port (contextual-scanner-ir-ref ir 'positions))
     (display ",\n rules: &[\n" port)
     (for-each
      (lambda (row)
        (display "ScannerRule { name: " port) (rust-name port (list-ref row 0))
        (display ", mode: " port) (rust-name port (list-ref row 1))
        (display ", form: " port) (rust-name port (list-ref row 2))
        (display ", matcher: " port) (emit-matcher port (list-ref row 3))
        (unless (<= -9223372036854775808 (list-ref row 4) 9223372036854775807)
          (error "scanner rank exceeds Rust i64" (list-ref row 4)))
        (display ", rank: " port) (display (list-ref row 4) port)
        (display ", action: " port) (emit-action port (list-ref row 5))
        (display " },\n" port)) (contextual-scanner-ir-ref ir 'rules))
     (display "],\n cells: &[\n" port)
     (for-each
      (lambda (row)
        (display "ScannerCell { mode: " port) (rust-name port (list-ref row 0))
        (display ", position: " port) (rust-name port (list-ref row 1))
        (display ", form: " port) (rust-name port (list-ref row 2))
        (display ", terminal: " port) (rust-name port (car (list-ref row 3)))
        (display " },\n" port)) (filter (lambda (row) (list-ref row 3)) (contextual-scanner-ir-ref ir 'cells)))
     (display "]\n};\n" port))))
(def (generate-rust-scanner-module path ir)
  (let (source (rust-scanner-module-source ir))
    (create-directory* (path-directory path))
    (call-with-output-file path (lambda (port) (display source port)))
    path))

;;; One downstream descriptor and its compiled contextual declaration produce
;;; the complete Rust language/parser/scanner data product.
(def (generate-contextual-language-rust-rowan-module path descriptor product)
  (let (language-source (language-rust-rowan-module-source descriptor))
    (prepare-contextual-parser (language-grammar-machine descriptor) product)
    (let (actions (cdr (assq 'actions (parser-ir-ref (language-grammar-ir descriptor) 'lr-spec))))
      (when (any (lambda (row) (any (lambda (entry) (eq? (cadr entry) 'fork)) row))
                 (vector->list actions))
        (error "Rust contextual AOT does not admit GLR scanner branch state")))
    (let (scanner-source (rust-scanner-module-source (cdr (assq 'scanner product))))
      (create-directory* (path-directory path))
      (call-with-output-file path
        (lambda (port)
          (display language-source port)
          (display "pub mod contextual_scanner {\n" port) (display scanner-source port)
          (display "}\npub static CONTEXTUAL: gerbil_parser_rowan::ContextualParserSpec = gerbil_parser_rowan::ContextualParserSpec { language: &LANGUAGE, scanner: &contextual_scanner::SCANNER, parser_digest: " port)
          (rust-text port (cdr (assq 'digest product)))
          (display ", state_positions: " port)
          (rust-symbols port (map cdr (cdr (assq 'state-positions product))))
          (display " };\n" port)))
      path)))
