;;; Native syntax vocabulary elaboration for the common shell source library.
(import (only-in :gerbil/expander core-expand1)
        (only-in ../../language-support/command-grammar lower-command-grammar)
        (only-in :gerbil/core/expander syntax-case syntax with-syntax datum->syntax syntax->datum stx-map raise-syntax-error))
(export expand-shell-grammar-syntax)
(def (expand-shell-grammar-syntax stx compile-entry)
  (def origins (make-table test: eq?))
  (def constructors '(at node field seq choice optional repeat empty-allowed balanced reference word operator role newline adjacent))
  (def (expand expression (invocation #f))
    (syntax-case expression ()
      ((head argument ...)
       (if (memq (syntax->datum #'head) constructors)
         (let (result (cons (syntax->datum #'head)
                           (stx-map (lambda (child) (expand child invocation)) #'(argument ...))))
           (table-set! origins result (or invocation expression))
           result)
         (let (expanded (core-expand1 expression))
           (when (eq? expression expanded)
             (raise-syntax-error #f "unknown source grammar constructor" expression stx))
           (expand expanded (or invocation expression)))))
      (_ (syntax->datum expression))))
  (syntax-case stx (operators regions bindings words commands roles descriptor rules)
    ((_ (operators operator-value ...) (regions region ...) (bindings binding ...)
        (words word-value ...)
        (commands (roles role-value ...) (descriptor descriptor-value)) (rules (name expression) ...))
     (let* ((rule-data (map (lambda (name expression) (list (syntax->datum name) (expand expression)))
                              (stx-map values #'(name ...)) (stx-map values #'(expression ...))))
            (declaration (list (cons 'operators (syntax->datum #'(operator-value ...)))
                               (cons 'regions (syntax->datum #'(region ...)))
                               (cons 'bindings (syntax->datum #'(binding ...)))
                               (cons 'words (syntax->datum #'(word-value ...)))
                               (list 'commands (cons 'roles (syntax->datum #'(role-value ...)))
                                     (list 'descriptor (syntax->datum #'descriptor-value))
                                     (cons 'rules rule-data)))))
       (with-catch
        (lambda (condition)
          (if (syntax-error? condition) (raise condition)
            (raise-syntax-error #f (error-message condition) #'(rules (name expression) ...) stx)))
        (lambda ()
          (lower-command-grammar rule-data
            (lambda (message value)
              (raise-syntax-error #f message
                (table-ref origins value #'(rules (name expression) ...)) stx)))))
       (with-syntax ((compile compile-entry) (data (datum->syntax compile-entry declaration)))
         #'(compile 'data))))
    (_ (raise-syntax-error #f "shell grammar requires ordered operators, regions, bindings, words and commands sections" stx))))
