/* Standalone lifecycle for the closure generated by Gerbil's compiler.
 * See Gambit's official examples/pthread/pthread.c for setup/cleanup ownership.
 * The build owner supplies GERBIL_PARSER_LINKER; no generated C is rewritten. */
#include <gambit.h>
#include <pthread.h>
#include <stdatomic.h>
#include <gerbil-parser/language-v2.h>
#include <gerbil-parser/runtime.h>
#ifndef GERBIL_PARSER_LINKER
#error "The native library builder must supply its Gambit linker symbol"
#endif
extern ___mod_or_lnk GERBIL_PARSER_LINKER(___global_state);
static ___setup_params_struct params; /* reset_argv contains self-references */
static _Atomic int gp_runtime_state = 0; /* fresh, starting, ready, closed, failed */
int32_t gerbil_parser_runtime_init(void) {
  int fresh = 0;
  if (!atomic_compare_exchange_strong(&gp_runtime_state,&fresh,1)) return -3;
  ___setup_params_reset(&params);
  params.version = ___VERSION;
  params.linker = GERBIL_PARSER_LINKER;
  ___SCMOBJ status = ___setup(&params);
  if (status != ___FIX(___NO_ERR)) {
    atomic_store(&gp_runtime_state,4);
    return -4;
  }
  atomic_store(&gp_runtime_state,2);
  return 0;
}
int32_t gerbil_parser_runtime_shutdown(void) {
  if (atomic_load(&gp_runtime_state) != 2) return -3;
  if (!gerbil_parser_language_is_owner_thread()) return -1;
  int32_t status = gerbil_parser_language_runtime_detach();
  if (status) return status;
  ___cleanup();
  atomic_store(&gp_runtime_state,3);
  return 0;
}
