//! Lossless Rowan runtime for parser tables generated by `gerbil-parser`.
//!
//! Gerbil owns grammar declarations and LR conflict resolution at AOT time;
//! this crate executes the resulting immutable Rust tables.

#![forbid(unsafe_code)]

extern crate self as gerbil_parser_rowan;

mod engine;

pub use engine::{
    ActionEntry, BlockContents, BlockHeaderRule, BlockLineRule, Diagnostic, GerbilLanguage,
    GotoEntry, GraphFieldMode, GraphFieldRule, GraphFieldValue, GraphNodeRule, GraphProjectionSpec,
    GraphRecord, HeadingFieldsRule, HeadingLineRule, InlineLinkRule, KeyLineContext, KeyLineMode,
    KeyLineRule, KeyValueLineRule, KindCategory, KindSpec, LanguageSpec, LexicalExpr, LexicalRule,
    LineStructureSpec, ListLineRule, Operand, OperandAction, Parse, ParseError, ParseReceipt,
    ParserAction, Production, Reduction, ScannedToken, SelectiveGlrReceipt, Symbol, SyntaxKind,
    SyntaxNode, SyntaxToken, TableLineRule, Terminal, TerminalSpec, TreeEvent, UnclosedBlockPolicy,
    build_rowan_events, parse, parse_generated_events, parse_scanned, parse_structural_lines,
    project_syntax_graph,
};
