//! Lossless Rowan execution for parser tables generated by `gerbil-parser`.
//!
//! Grammar declarations and LR conflict resolution remain owned by Scheme at
//! AOT time. This crate executes only the resulting immutable tables.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::sync::Arc;

use rowan::{GreenNode, GreenNodeBuilder};
use sha2::{Digest, Sha256};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KindCategory {
    Node,
    Token,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct KindSpec {
    pub name: &'static str,
    pub category: KindCategory,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TerminalSpec {
    pub name: &'static str,
    pub syntax_kind: u16,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LexicalExpr {
    Whitespace,
    HorizontalWhitespace,
    Newline,
    DecimalDigits,
    Number,
    Identifier,
    Literals(&'static [&'static str]),
    Fallback,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LexicalRule {
    pub terminal: &'static str,
    pub expression: LexicalExpr,
    pub precedence: i32,
    pub extra: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Terminal {
    Eof,
    Literal(&'static str),
    Token(&'static str),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ParserAction {
    Shift(u32),
    Reduce(u32),
    Accept,
    RejectNonAssoc,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ActionEntry {
    pub terminal: Terminal,
    pub action: ParserAction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct GotoEntry {
    pub nonterminal: &'static str,
    pub state: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Symbol {
    Terminal(Terminal),
    Nonterminal(&'static str),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OperandAction {
    Field(&'static str),
    Alias(u16),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Operand {
    pub symbol: Symbol,
    pub actions: &'static [OperandAction],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Reduction {
    Pass,
    Concat,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Production {
    pub lhs: &'static str,
    pub rhs: &'static [Operand],
    pub reduction: Reduction,
}

#[derive(Clone, Copy, Debug)]
pub struct LanguageSpec {
    pub language: &'static str,
    pub version: &'static str,
    pub contract: &'static str,
    pub grammar_digest: &'static str,
    pub case_insensitive: bool,
    pub root_kind: u16,
    pub kinds: &'static [KindSpec],
    pub terminals: &'static [TerminalSpec],
    pub lexical_rules: &'static [LexicalRule],
    pub actions: &'static [&'static [ActionEntry]],
    pub gotos: &'static [&'static [GotoEntry]],
    pub productions: &'static [Production],
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SyntaxKind(pub u16);

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum GerbilLanguage {}

impl rowan::Language for GerbilLanguage {
    type Kind = SyntaxKind;

    fn kind_from_raw(raw: rowan::SyntaxKind) -> Self::Kind {
        SyntaxKind(raw.0)
    }

    fn kind_to_raw(kind: Self::Kind) -> rowan::SyntaxKind {
        rowan::SyntaxKind(kind.0)
    }
}

pub type SyntaxNode = rowan::SyntaxNode<GerbilLanguage>;
pub type SyntaxToken = rowan::SyntaxToken<GerbilLanguage>;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParseReceipt {
    pub language: &'static str,
    pub version: &'static str,
    pub contract: &'static str,
    pub grammar_digest: &'static str,
    pub source_digest: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Diagnostic {
    pub reason_kind: &'static str,
    pub byte_offset: usize,
    pub message: String,
}

#[derive(Clone, Debug)]
pub struct Parse {
    green: GreenNode,
    kinds: Arc<[KindSpec]>,
    receipt: ParseReceipt,
}

impl Parse {
    #[must_use]
    pub fn syntax(&self) -> SyntaxNode {
        SyntaxNode::new_root(self.green.clone())
    }

    #[must_use]
    pub fn receipt(&self) -> &ParseReceipt {
        &self.receipt
    }

    #[must_use]
    pub fn kind_name(&self, kind: SyntaxKind) -> Option<&str> {
        self.kinds.get(usize::from(kind.0)).map(|kind| kind.name)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParseError {
    pub receipt: ParseReceipt,
    pub diagnostic: Box<Diagnostic>,
}

#[derive(Clone, Debug)]
struct Token<'source> {
    terminal: &'static str,
    syntax_kind: u16,
    text: &'source str,
    start: usize,
    end: usize,
    extra: bool,
}

#[derive(Clone, Debug)]
struct Child {
    field: Option<&'static str>,
    value: Value,
}

#[derive(Clone, Debug)]
enum Value {
    Token(usize),
    Node {
        kind: u16,
        start: usize,
        end: usize,
        children: Vec<Child>,
    },
    Fragment(Vec<Child>),
}

impl Value {
    fn start(&self, tokens: &[Token<'_>], fallback: usize) -> usize {
        match self {
            Self::Token(index) => tokens[*index].start,
            Self::Node { start, .. } => *start,
            Self::Fragment(children) => children
                .first()
                .map_or(fallback, |child| child.value.start(tokens, fallback)),
        }
    }

    fn end(&self, tokens: &[Token<'_>], fallback: usize) -> usize {
        match self {
            Self::Token(index) => tokens[*index].end,
            Self::Node { end, .. } => *end,
            Self::Fragment(children) => children
                .last()
                .map_or(fallback, |child| child.value.end(tokens, fallback)),
        }
    }

    fn into_children(self) -> Vec<Child> {
        match self {
            Self::Fragment(children) => children,
            value => vec![Child { field: None, value }],
        }
    }
}

pub fn parse(spec: &'static LanguageSpec, source: &str) -> Result<Parse, ParseError> {
    let receipt = receipt(spec, source);
    validate_spec(spec).map_err(|message| ParseError {
        receipt: receipt.clone(),
        diagnostic: Box::new(Diagnostic {
            reason_kind: "invalid-aot-artifact",
            byte_offset: 0,
            message,
        }),
    })?;
    let tokens = lex(spec, source).map_err(|diagnostic| ParseError {
        receipt: receipt.clone(),
        diagnostic: Box::new(diagnostic),
    })?;
    let root = parse_tokens(spec, &tokens).map_err(|diagnostic| ParseError {
        receipt: receipt.clone(),
        diagnostic: Box::new(diagnostic),
    })?;
    let green = build_green(spec, source, &tokens, &root).map_err(|message| ParseError {
        receipt: receipt.clone(),
        diagnostic: Box::new(Diagnostic {
            reason_kind: "invalid-cst",
            byte_offset: 0,
            message,
        }),
    })?;
    Ok(Parse {
        green,
        kinds: Arc::from(spec.kinds),
        receipt,
    })
}

fn receipt(spec: &LanguageSpec, source: &str) -> ParseReceipt {
    let digest = Sha256::digest(source.as_bytes());
    let mut encoded = String::with_capacity(71);
    encoded.push_str("sha256:");
    for byte in digest {
        let _ = write!(encoded, "{byte:02x}");
    }
    ParseReceipt {
        language: spec.language,
        version: spec.version,
        contract: spec.contract,
        grammar_digest: spec.grammar_digest,
        source_digest: encoded,
    }
}

fn validate_spec(spec: &LanguageSpec) -> Result<(), String> {
    if spec.grammar_digest.len() != 71 || !spec.grammar_digest.starts_with("sha256:") {
        return Err("grammar digest is not a canonical SHA-256 identity".into());
    }
    if spec.kinds.len() > usize::from(u16::MAX) + 1 {
        return Err("syntax-kind catalog exceeds Rowan u16 identity space".into());
    }
    if usize::from(spec.root_kind) >= spec.kinds.len()
        || spec.kinds[usize::from(spec.root_kind)].category != KindCategory::Node
    {
        return Err("root kind is not a declared node".into());
    }
    if spec.actions.len() != spec.gotos.len() {
        return Err("LR action and goto state counts differ".into());
    }
    for terminal in spec.terminals {
        let Some(kind) = spec.kinds.get(usize::from(terminal.syntax_kind)) else {
            return Err(format!(
                "terminal {} has an unknown syntax kind",
                terminal.name
            ));
        };
        if kind.category != KindCategory::Token {
            return Err(format!(
                "terminal {} does not resolve to a token kind",
                terminal.name
            ));
        }
    }
    for rule in spec.lexical_rules {
        if !spec
            .terminals
            .iter()
            .any(|terminal| terminal.name == rule.terminal)
        {
            return Err(format!(
                "lexical rule references unknown terminal {}",
                rule.terminal
            ));
        }
    }
    let state_count = spec.actions.len();
    for row in spec.actions {
        for entry in *row {
            match entry.action {
                ParserAction::Shift(state) if state as usize >= state_count => {
                    return Err(format!("shift targets unknown state {state}"));
                }
                ParserAction::Reduce(production)
                    if production as usize >= spec.productions.len() =>
                {
                    return Err(format!("reduce references unknown production {production}"));
                }
                _ => {}
            }
        }
    }
    for row in spec.gotos {
        for entry in *row {
            if entry.state as usize >= state_count {
                return Err(format!("goto targets unknown state {}", entry.state));
            }
        }
    }
    for production in spec.productions {
        for operand in production.rhs {
            for action in operand.actions {
                if let OperandAction::Alias(kind) = action {
                    let Some(specification) = spec.kinds.get(usize::from(*kind)) else {
                        return Err(format!("alias references unknown syntax kind {kind}"));
                    };
                    if specification.category != KindCategory::Node {
                        return Err(format!("alias references non-node syntax kind {kind}"));
                    }
                }
            }
        }
    }
    Ok(())
}

fn lex<'source>(
    spec: &LanguageSpec,
    source: &'source str,
) -> Result<Vec<Token<'source>>, Diagnostic> {
    let terminal_kinds = spec
        .terminals
        .iter()
        .map(|terminal| (terminal.name, terminal.syntax_kind))
        .collect::<HashMap<_, _>>();
    let mut offset = 0;
    let mut tokens = Vec::new();
    while offset < source.len() {
        if !source.is_char_boundary(offset) {
            return Err(Diagnostic {
                reason_kind: "lexer-offset",
                byte_offset: offset,
                message: "lexer offset is not a UTF-8 boundary".into(),
            });
        }
        let mut selected: Option<(&LexicalRule, usize, usize)> = None;
        for (order, rule) in spec.lexical_rules.iter().enumerate() {
            let Some(end) = lexical_end(rule.expression, source, offset) else {
                continue;
            };
            if end <= offset {
                continue;
            }
            let replace = selected.is_none_or(|(current, current_end, current_order)| {
                end > current_end
                    || (end == current_end && rule.precedence > current.precedence)
                    || (end == current_end
                        && rule.precedence == current.precedence
                        && order < current_order)
            });
            if replace {
                selected = Some((rule, end, order));
            }
        }
        let Some((rule, end, _)) = selected else {
            return Err(Diagnostic {
                reason_kind: "lexical-rejected",
                byte_offset: offset,
                message: "no generated lexical rule consumed the source".into(),
            });
        };
        let Some(&syntax_kind) = terminal_kinds.get(rule.terminal) else {
            return Err(Diagnostic {
                reason_kind: "invalid-aot-artifact",
                byte_offset: offset,
                message: format!("unknown generated terminal {}", rule.terminal),
            });
        };
        tokens.push(Token {
            terminal: rule.terminal,
            syntax_kind,
            text: &source[offset..end],
            start: offset,
            end,
            extra: rule.extra,
        });
        offset = end;
    }
    Ok(tokens)
}

fn lexical_end(expression: LexicalExpr, source: &str, offset: usize) -> Option<usize> {
    let suffix = &source[offset..];
    match expression {
        LexicalExpr::Whitespace => consume_while(source, offset, char::is_whitespace),
        LexicalExpr::HorizontalWhitespace => {
            consume_while(source, offset, |character| matches!(character, ' ' | '\t'))
        }
        LexicalExpr::Newline => {
            consume_while(source, offset, |character| matches!(character, '\r' | '\n'))
        }
        LexicalExpr::DecimalDigits => {
            consume_while(source, offset, |character| character.is_numeric())
        }
        LexicalExpr::Number => number_end(source, offset),
        LexicalExpr::Identifier => identifier_end(source, offset),
        LexicalExpr::Literals(values) => values
            .iter()
            .filter(|value| suffix.starts_with(**value))
            .max_by_key(|value| value.len())
            .map(|value| offset + value.len()),
        LexicalExpr::Fallback => suffix
            .chars()
            .next()
            .map(|character| offset + character.len_utf8()),
    }
}

fn identifier_end(source: &str, offset: usize) -> Option<usize> {
    let mut characters = source[offset..].char_indices();
    let (_, first) = characters.next()?;
    if first != '_' && !first.is_alphabetic() {
        return None;
    }
    let mut end = offset + first.len_utf8();
    for (_, character) in characters {
        if character != '_'
            && character != '-'
            && !character.is_alphabetic()
            && !character.is_numeric()
        {
            break;
        }
        end += character.len_utf8();
    }
    Some(end)
}

fn number_end(source: &str, offset: usize) -> Option<usize> {
    let whole_end = consume_while(source, offset, |character| character.is_numeric())?;
    let fraction_end = if source[whole_end..].starts_with('.') {
        let digits_start = whole_end + 1;
        consume_while(source, digits_start, |character| character.is_numeric()).unwrap_or(whole_end)
    } else {
        whole_end
    };
    let Some(exponent) = source[fraction_end..].chars().next() else {
        return Some(fraction_end);
    };
    if !matches!(exponent, 'e' | 'E') {
        return Some(fraction_end);
    }
    let mut digits_start = fraction_end + exponent.len_utf8();
    if let Some(sign) = source[digits_start..].chars().next()
        && matches!(sign, '+' | '-')
    {
        digits_start += sign.len_utf8();
    }
    consume_while(source, digits_start, |character| character.is_numeric()).or(Some(fraction_end))
}

fn consume_while(source: &str, offset: usize, predicate: impl Fn(char) -> bool) -> Option<usize> {
    let mut end = offset;
    for character in source[offset..].chars() {
        if !predicate(character) {
            break;
        }
        end += character.len_utf8();
    }
    (end > offset).then_some(end)
}

fn parse_tokens(spec: &LanguageSpec, tokens: &[Token<'_>]) -> Result<Value, Diagnostic> {
    let significant = tokens
        .iter()
        .enumerate()
        .filter_map(|(index, token)| (!token.extra).then_some(index))
        .collect::<Vec<_>>();
    let mut states = vec![0_u32];
    let mut values = Vec::new();
    let mut cursor = 0;
    loop {
        let state = *states.last().expect("LR state stack is never empty");
        let token = significant.get(cursor).map(|index| &tokens[*index]);
        let action = find_action(spec, state, token).ok_or_else(|| Diagnostic {
            reason_kind: "parse-rejected",
            byte_offset: token
                .map_or_else(|| tokens.last().map_or(0, |last| last.end), |t| t.start),
            message: format!("no LR action in state {state}"),
        })?;
        match action {
            ParserAction::Shift(next) => {
                let Some(&token_index) = significant.get(cursor) else {
                    return Err(Diagnostic {
                        reason_kind: "invalid-aot-artifact",
                        byte_offset: tokens.last().map_or(0, |token| token.end),
                        message: "generated LR table shifts EOF".into(),
                    });
                };
                states.push(next);
                values.push(Value::Token(token_index));
                cursor += 1;
            }
            ParserAction::Reduce(production_id) => {
                let production = spec
                    .productions
                    .get(production_id as usize)
                    .ok_or_else(|| Diagnostic {
                        reason_kind: "invalid-aot-artifact",
                        byte_offset: token.map_or(0, |token| token.start),
                        message: format!("unknown production {production_id}"),
                    })?;
                let count = production.rhs.len();
                if states.len() <= count || values.len() < count {
                    return Err(Diagnostic {
                        reason_kind: "invalid-aot-artifact",
                        byte_offset: token.map_or(0, |token| token.start),
                        message: format!("production {production_id} underflows the LR stack"),
                    });
                }
                states.truncate(states.len() - count);
                let reduced_from = values.split_off(values.len() - count);
                let fallback = token.map_or_else(
                    || tokens.last().map_or(0, |last| last.end),
                    |lookahead| lookahead.start,
                );
                let reduced = reduce(production, reduced_from, tokens, fallback);
                let owner = *states.last().expect("LR owner state exists");
                let next = spec.gotos[owner as usize]
                    .iter()
                    .find(|entry| entry.nonterminal == production.lhs)
                    .map(|entry| entry.state)
                    .ok_or_else(|| Diagnostic {
                        reason_kind: "invalid-aot-artifact",
                        byte_offset: fallback,
                        message: format!("missing goto for {} from state {owner}", production.lhs),
                    })?;
                states.push(next);
                values.push(reduced);
            }
            ParserAction::Accept => {
                if cursor != significant.len() || values.len() != 1 {
                    return Err(Diagnostic {
                        reason_kind: "invalid-aot-artifact",
                        byte_offset: token.map_or(0, |token| token.start),
                        message: "generated accept action did not cover one complete root".into(),
                    });
                }
                return Ok(values.pop().expect("one accepted semantic value"));
            }
            ParserAction::RejectNonAssoc => {
                return Err(Diagnostic {
                    reason_kind: "parse-rejected",
                    byte_offset: token.map_or(0, |token| token.start),
                    message: "non-associative operator chain rejected".into(),
                });
            }
        }
    }
}

fn find_action(spec: &LanguageSpec, state: u32, token: Option<&Token<'_>>) -> Option<ParserAction> {
    let row = spec.actions.get(state as usize)?;
    if let Some(token) = token {
        row.iter()
            .find(|entry| match entry.terminal {
                Terminal::Literal(value) => {
                    if spec.case_insensitive {
                        value.eq_ignore_ascii_case(token.text)
                    } else {
                        value == token.text
                    }
                }
                _ => false,
            })
            .or_else(|| {
                row.iter().find(|entry| {
                    matches!(entry.terminal, Terminal::Token(name) if name == token.terminal)
                })
            })
            .map(|entry| entry.action)
    } else {
        row.iter()
            .find(|entry| entry.terminal == Terminal::Eof)
            .map(|entry| entry.action)
    }
}

fn reduce(
    production: &Production,
    values: Vec<Value>,
    tokens: &[Token<'_>],
    fallback: usize,
) -> Value {
    let mut groups = Vec::with_capacity(values.len());
    for (operand, mut value) in production.rhs.iter().zip(values) {
        for action in operand.actions {
            match *action {
                OperandAction::Field(field) => {
                    let mut children = value.into_children();
                    for child in &mut children {
                        child.field = Some(field);
                    }
                    value = Value::Fragment(children);
                }
                OperandAction::Alias(kind) => {
                    let start = value.start(tokens, fallback);
                    let end = value.end(tokens, fallback);
                    value = Value::Node {
                        kind,
                        start,
                        end,
                        children: value.into_children(),
                    };
                }
            }
        }
        groups.push(value);
    }
    match production.reduction {
        Reduction::Pass if groups.len() == 1 => groups.pop().expect("one pass operand"),
        Reduction::Pass | Reduction::Concat => {
            Value::Fragment(groups.into_iter().flat_map(Value::into_children).collect())
        }
    }
}

fn build_green(
    spec: &LanguageSpec,
    source: &str,
    tokens: &[Token<'_>],
    root: &Value,
) -> Result<GreenNode, String> {
    let Value::Node { kind, children, .. } = root else {
        return Err("accepted semantic value is not a syntax node".into());
    };
    if *kind != spec.root_kind {
        return Err("accepted syntax node does not have the declared root kind".into());
    }
    let mut builder = GreenNodeBuilder::new();
    let mut next_token = 0;
    builder.start_node(rowan::SyntaxKind(*kind));
    for child in children {
        emit_node(&mut builder, tokens, &child.value, &mut next_token)?;
    }
    while next_token < tokens.len() {
        emit_token(&mut builder, &tokens[next_token]);
        next_token += 1;
    }
    builder.finish_node();
    let green = builder.finish();
    if green.to_string() != source {
        return Err("Rowan tree does not reproduce the complete source".into());
    }
    Ok(green)
}

fn emit_node(
    builder: &mut GreenNodeBuilder<'_>,
    tokens: &[Token<'_>],
    value: &Value,
    next_token: &mut usize,
) -> Result<(), String> {
    match value {
        Value::Token(index) => {
            while *next_token < *index {
                emit_token(builder, &tokens[*next_token]);
                *next_token += 1;
            }
            if *next_token != *index {
                return Err("recognition token order is not monotonic".into());
            }
            emit_token(builder, &tokens[*index]);
            *next_token += 1;
        }
        Value::Node { kind, children, .. } => {
            builder.start_node(rowan::SyntaxKind(*kind));
            for child in children {
                emit_node(builder, tokens, &child.value, next_token)?;
            }
            builder.finish_node();
        }
        Value::Fragment(children) => {
            for child in children {
                emit_node(builder, tokens, &child.value, next_token)?;
            }
        }
    }
    Ok(())
}

fn emit_token(builder: &mut GreenNodeBuilder<'_>, token: &Token<'_>) {
    builder.token(rowan::SyntaxKind(token.syntax_kind), token.text);
}

pub mod generated;
