//! Lossless Rowan runtime for parser tables generated by `gerbil-parser`.
//!
//! Gerbil owns grammar declarations and LR conflict resolution at AOT time;
//! this crate executes the resulting immutable Rust tables.

#![forbid(unsafe_code)]

extern crate self as gerbil_parser_rowan;

mod engine;

pub use engine::{
    ActionEntry, Diagnostic, GerbilLanguage, GotoEntry, KindCategory, KindSpec, LanguageSpec,
    LexicalExpr, LexicalRule, Operand, OperandAction, Parse, ParseError, ParseReceipt,
    ParserAction, Production, Reduction, SelectiveGlrReceipt, Symbol, SyntaxKind, SyntaxNode,
    SyntaxToken, Terminal, TerminalSpec, parse,
};

/// AOT language modules maintained by `gerbil-parser`.
pub mod generated;
