//! Lossless parser runtime for parser tables generated by `gerbil-parser`.
//!
//! Gerbil owns grammar declarations and LR conflict resolution at AOT time;
//! this crate executes the resulting immutable Rust tables.

#![forbid(unsafe_code)]

extern crate self as gerbil_parser_runtime;

mod engine;
pub mod scanner;

pub use engine::{
    ActionEntry, BindingSpec, BlockContents, BlockHeaderRule, BlockLineRule, BlockOpeningMode,
    CaptureKind, CaptureSpec, CommandChoice, CommandEvent, CommandForm, CommandInstruction,
    CommandParse, CommandProgramSpec, CommandRole, CommandSourceSpec, CommandTokenClass,
    CommandTrigger, ContextualParserSpec, Diagnostic, EventCatalog, GotoEntry, GraphFieldMode,
    GraphFieldRule, GraphFieldValue, GraphIndex, GraphIndexError, GraphNodeRule,
    GraphProjectionSpec, GraphRecord, GraphRelation, HeadingFieldsRule, HeadingLineRule,
    InlineLinkRule, KeyLineContext, KeyLineMode, KeyLineRule, KeyValueLineRule, KindCategory,
    KindSpec, LanguageSpec, LexicalExpr, LexicalRule, LineStructureSpec, ListLineRule,
    ModuleTextProfile, Operand, OperandAction, Parse, ParseError, ParseReceipt, ParserAction,
    PartGuard, PartOpcode, PartProfileSpec, PartRule, PreparedCommandProgram,
    PreparedCommandSource, PreparedPartProfile, PreparedResultNode, PreparedResultProfile,
    PreparedResultProjection, PreparedTextProfile, Production, ProjectedChild, ProjectedNode,
    ProjectedValue, ProjectionInstruction, ProjectionOpcode, Reduction, ResultCapture,
    ResultChildCapture, ResultNodeSpec, ResultProfileSpec, ResultProjection, ScannedToken,
    SelectiveGlrReceipt, SubscriptSpec, Symbol, SyntaxKind, SyntaxNode, SyntaxToken, TableLineRule,
    Terminal, TerminalSpec, TextClass, TextProfile, TreeEvent, UnclosedBlockPolicy,
    build_syntax_events, build_syntax_events_catalog, parse, parse_contextual,
    parse_generated_events, parse_scanned, parse_structural_lines, project_syntax_graph,
};

#[cfg(test)]
#[path = "../tests/unit/records_contextual_fixture.rs"]
mod records_contextual_fixture;

pub use gerbil_parser_artifact::syntax::{SyntaxTree, TextRange, TextSize};

#[cfg(test)]
#[path = "../tests/unit/artifact_generation.rs"]
mod artifact_generation_tests;
