(import :gerbil-parser/tools/qualification/plans)
(def (check condition label) (unless condition (error "local plan control failed" label)))
(check (equal? (diagnostic-modules '("gql-profile" "gql-actors" "gql-profile"))
               '("reduction-counts" "execution-counts" "matched-stages" "actors")) 'diagnostic-union)
(let (plan (local-diagnostic-plan '("gql-profile" "gql-actors") #f))
 (check (= (length plan) 2) 'single-driver-single-diagnostics-build)
 (check (= (length (qualification-stage-command (cadr plan))) 6) 'four-distinct-module-inputs))
(check (null? (local-diagnostic-plan '("gql-profile" "gql-actors") #t)) 'prepared-build-free)
(check (with-catch (lambda (_) #t) (lambda () (local-diagnostic-plan '("ffi") #t) #f)) 'prepared-scope-rejected)
(check (with-catch (lambda (_) #t) (lambda () (local-diagnostic-plan '("unknown") #f) #f)) 'unknown-suite-rejected)
(displayln "LOCAL-PLAN-CONTROLS-OK") (force-output)
(exit 0)
