;;; Controlled children qualify cancellation and isolation, never existing jobs.
(import :gerbil-parser/tools/qualification/process :gerbil-parser/tools/qualification/ownership :std/io/tempfile :std/misc/ports)
(def (check condition label) (unless condition (error "process control failed" label)))
(def (main fixture)
 (let (directory (make-temporary-file-name "parser-process-controls-"))
  (create-directory directory)
  (try
   (def (run mode (budget 1.5) (idle 0.8))
    (run-observed-process [fixture mode] (path-expand (string-append mode ".log") directory)
      timeout: budget idle-timeout: idle))
   (for-each
    (lambda (row)
     (let (result (run (car row)))
      (check (eq? (process-result-reason result) (cadr row)) (car row))
      (displayln "PROCESS-CONTROL-OK " (car row)) (force-output)))
    '(("silent" idle-timeout) ("continuous" total-timeout)
      ("closed-output" idle-timeout) ("error" error-output)))
   (let* ((escaped (path-expand "escaped-marker" directory))
          (unrelated (path-expand "unrelated-marker" directory))
          (other (open-process [path: fixture arguments: ["unrelated" unrelated]])))
    (try
     (let (result (run-observed-process [fixture "escaped" escaped]
                       (path-expand "escaped.log" directory) timeout: 1.5 idle-timeout: 0.8))
      (check (eq? (process-result-reason result) 'idle-timeout) 'escaped-timeout)
      (check (receipt-present? "^ESCAPED-SESSION " (utf8->string (process-result-output result))) 'escaped-started))
     (check (= (process-status other 4 -1) 0) 'unrelated-exit)
     (thread-sleep! 1)
     (check (file-exists? unrelated) 'unrelated-survived)
     (check (not (file-exists? escaped)) 'escaped-stopped)
     (finally (close-port other)))
    (displayln "PROCESS-CONTROL-OK escaped-session-stopped unrelated-survived") (force-output))
   (let* ((ready (path-expand "flood-ready" directory))
          (log (path-expand "flood.log" directory))
          (pipe (open-process [path: "gxi" arguments:
                  ["qualify.ss" "run" "--timeout" "6" "--idle-timeout" "0.8"
                   "--log" log "--require" "^OK$" "--" fixture "flood" ready]
                  stderr-redirection: #t])))
    (close-output-port pipe)
    (try
     (let (started (##current-time-point))
      (let loop ()
       (unless (file-exists? ready)
        (when (> (- (##current-time-point) started) 4)
         (let (status (process-status pipe 0 #f))
          (error "flood child did not start" status (and status (utf8->string (read-all-as-u8vector pipe))))))
        (thread-sleep! 0.05) (loop))))
     ;; No reads while the consumer applies more pressure than the idle fence.
     (thread-sleep! 1.2)
     (let* ((bytes (read-all-as-u8vector pipe)) (text (utf8->string bytes))
            (saved (call-with-input-file log read-all-as-u8vector)))
      (check (= (process-status pipe 2 -1) 0) 'backpressure-exit)
      (check (= (length (filter (lambda (line) (string-prefix? "PIPE-PROGRESS " line))
                               (string-split text #\newline))) 2000) 'console-byte-completeness)
      (check (= (u8vector-length saved) (+ (* 2000 (+ 15 2000)) 3)) 'logged-byte-completeness)
      (check (receipt-present? "^OK$" text) 'flood-final-receipt))
     (finally (close-port pipe)))
    (displayln "PROCESS-CONTROL-OK unicode-backpressure blocking-native-descriptors") (force-output))
   (let (result (run "early-error" 3 1.5))
    (check (eq? (process-result-reason result) 'error-output) 'early-error)
    (check (< (process-result-elapsed result) 2.5) 'early-error-stopped)
    (displayln "PROCESS-CONTROL-OK immediate-error-cancellation") (force-output))
   (let (result (run "signal" 3 1.5))
    (check (eq? (process-result-reason result) 'signal-exit) 'signal-distinguished)
    (check (= (process-result-status result) 143) 'signal-status))
   (check (= (process-result-status (run "failure" 3 1.5)) 42) 'nonzero-propagated)
   (check (not (receipt-present? "^FINAL-OK$" "CASE-OK\nHARNESS-OK\n")) 'missing-final-receipt)
   (let (plan (ownership-plan 100 '((100 10 100) (101 100 100) (102 101 102)
                                  (103 102 102) (200 10 200) (201 200 200)) 100))
    (check (and (member 100 (cadr plan)) (member 102 (cadr plan)) (andmap (lambda (group) (member group '(100 102))) (cadr plan))) 'owned-groups-only))
   (displayln "PROCESS-OWNERSHIP-CONTROLS-OK") (force-output)
   (finally (delete-file-or-directory directory #t))))
 (exit 0))
