;;; One native process contract shared by compilation, testing and generation.
(import :std/misc/process :std/io/tempfile :std/text/pregexp ./ownership)
(export #t)
(def qualification-library-root (path-expand "lib" (gerbil-path)))
(defstruct process-result (status reason output elapsed) transparent: #t)
(defstruct process-interruption (reason) transparent: #t)
(def (normal-exit-status raw)
  (if (zero? (modulo raw 256)) (quotient raw 256) (+ 128 (modulo raw 128))))
(def (receipt-present? pattern output)
  (any (lambda (line) (pregexp-match pattern line)) (string-split output #\newline)))

(def (run-observed-process command log timeout: (budget 60) idle-timeout: (idle #f)
                           error-output?: (error-output? #t) observe: (observe void))
  (unless (and (pair? command) (> budget 0) (or (not idle) (> idle 0)))
    (error "expected command and positive deadlines" command budget idle))
  (create-directory* (path-directory log))
  (let (directory (make-temporary-file-name "parser-process-"))
   (create-directory directory)
   (try
    (let* ((witness (path-expand "session" directory))
           (started (##current-time-point)) (last-output started)
           (coordinator (current-thread)) (capture (open-output-u8vector))
           (output (open-output-file log))
           (process (open-process [path: "gxi"
                     arguments: (append ["tools/qualification/process-child.ss" witness (getenv "GERBIL_LOADPATH" "")] command)
                     environment: (map (lambda (entry) (string-append (car entry) "="
                        (if (equal? (car entry) "GERBIL_LOADPATH")
                            (string-append qualification-library-root ":" (cdr entry)) (cdr entry))))
                       (if (getenv "GERBIL_LOADPATH" #f) (get-environment-variables)
                           (cons (cons "GERBIL_LOADPATH" "") (get-environment-variables))))
                     stderr-redirection: #t]))
           (reader #f) (waiter #f) (monitor #f) (raw #f) (reason #f)
           (line-prefix "") (eof? #f) (output-complete? #f) (exited? #f))
      (close-output-port process)
      (def (fail! why)
        (unless reason
          (set! reason why)
          (stop-owned-processes! process witness (integer? raw))
          (thread-interrupt! coordinator (lambda () (raise (process-interruption why))))))
      (def (observe-error! bytes)
        (when error-output?
          (let loop ((index 0))
            (when (< index (u8vector-length bytes))
              (let (byte (u8vector-ref bytes index))
                (cond
                 ((= byte 10)
                  (when (equal? line-prefix "ERROR") (fail! 'error-output))
                  (set! line-prefix ""))
                 ((< (string-length line-prefix) 10)
                  (set! line-prefix (string-append line-prefix (string (integer->char byte))))
                  (when (or (equal? line-prefix "*** ERROR")
                            (and (= (string-length line-prefix) 6)
                                 (equal? (substring line-prefix 0 5) "ERROR")
                                 (not (or (<= 48 byte 57) (<= 65 byte 90)
                                          (<= 97 byte 122) (= byte 95)))))
                    (fail! 'error-output)))))
              (loop (+ index 1))))))
      (try
       (set! reader
         (spawn
          (lambda ()
            (with-catch
             (lambda (ex) (thread-send coordinator (cons 'exception ex)))
             (lambda ()
               (let (buffer (make-u8vector 65536))
                 (let loop ()
                   (let (count (read-subu8vector buffer 0 65536 process 1))
                     (if (zero? count) (begin (set! output-complete? #t) (thread-send coordinator '(eof)))
                       (let (bytes (subu8vector buffer 0 count))
                         (set! last-output (##current-time-point))
                         (write-subu8vector bytes 0 count capture)
                         (write-subu8vector bytes 0 count output) (force-output output)
                         (thread-send coordinator (cons 'output bytes))
                         (observe-error! bytes)
                         (loop)))))))))))
       (set! waiter
         (spawn
          (lambda ()
            (with-catch
             (lambda (ex) (thread-send coordinator (cons 'exception ex)))
             (lambda ()
               ;; SDK process-status suspends this green thread until child exit.
               (set! raw (process-status process))
               (thread-send coordinator (cons 'exit raw)))))))
       (set! monitor
         (spawn
          (lambda ()
            (with-catch
             (lambda (ex) (thread-send coordinator (cons 'exception ex)))
             (lambda ()
               (let loop ()
                 (let (now (##current-time-point))
                   (cond ((>= (- now started) budget) (fail! 'total-timeout))
                         ((and idle (not (and output-complete? raw)) (>= (- now last-output) idle))
                          (fail! 'idle-timeout))
                         (else
                          (when (eq? (observe) #t) (set! last-output (##current-time-point)))
                          (thread-sleep! 0.05) (loop))))))))))
       (with-catch
        (lambda (ex) (unless (process-interruption? ex) (raise ex)))
        (lambda ()
          (let loop ()
            (unless (and eof? exited?)
              (let (message (thread-receive))
                (case (car message)
                  ((output)
                   (let (bytes (cdr message))
                     (write-subu8vector bytes 0 (u8vector-length bytes)) (force-output)))
                  ((eof) (set! eof? #t))
                  ((exit) (set! exited? #t))
                  ((exception) (raise (cdr message))))
                (loop))))))
       (when monitor (thread-terminate! monitor) (set! monitor #f))
       (when waiter (thread-terminate! waiter) (set! waiter #f))
       (unless raw (set! raw (process-status process 2 9)))
       (let* ((exit-file (string-append witness ".exit"))
              (command-raw (if (file-exists? exit-file) (call-with-input-file exit-file read) raw))
              (bytes (get-output-u8vector capture)) (text (utf8->string bytes))
              (failed? (and error-output? (receipt-present? "^(ERROR\\b|\\*\\*\\* ERROR)" text))))
         (process-result (normal-exit-status command-raw) (or reason (and failed? 'error-output)
                          (and (not (zero? (modulo command-raw 256))) 'signal-exit)) bytes
                         (- (##current-time-point) started)))
       (finally
        (when monitor (thread-terminate! monitor))
        (when waiter (thread-terminate! waiter))
        (when reader (thread-terminate! reader))
        (unless raw
          (stop-owned-processes! process witness #f)
          (process-status process 2 #f))
        (close-port process) (close-port output) (close-port capture)))))))

(def (run-qualified! command log timeout: (budget 60) idle-timeout: (idle #f)
                     require: (receipts '()) observe: (observe void))
  (displayln "PROCESS-START " log " timeout=" budget) (force-output)
  (let* ((result (run-observed-process command log timeout: budget idle-timeout: idle observe: observe))
         (text (utf8->string (process-result-output result)))
         (missing (filter (lambda (pattern) (not (receipt-present? pattern text))) receipts)))
    (displayln "PROCESS-RESULT elapsed=" (process-result-elapsed result)
               " exit=" (process-result-status result) " reason=" (process-result-reason result)
               " missing=" missing) (force-output)
    (unless (and (zero? (process-result-status result)) (not (process-result-reason result)) (null? missing))
      (error "process qualification failed" log (process-result-status result)
             (process-result-reason result) missing))
    result))
