// @generated by gerbil-parser/src/compiler/event-strategy-aot.ss
use gerbil_parser_rowan::TreeEvent;

pub const PARSER_DIGEST: &str =
    "sha256:88bbe27e4b43bf5f5c31b1133325f5eadedbfda0fc9c8defeabdf501f010ed89";

pub fn parse_event_lines(source: &str) -> Vec<TreeEvent> {
    let bytes = source.as_bytes();
    let mut events = Vec::with_capacity(bytes.len() / 16 + 2);
    events.push(TreeEvent::StartNode(0));
    let mut start = 0usize;
    while start < bytes.len() {
        let mut end = start;
        while end < bytes.len() && bytes[end] != b'\n' && bytes[end] != b'\r' {
            end += 1;
        }
        if end < bytes.len() {
            if bytes[end] == b'\r' && bytes.get(end + 1) == Some(&b'\n') {
                end += 2;
            } else {
                end += 1;
            }
        }
        let line = &source[start..end];
        if line.starts_with("* ") {
            events.push(TreeEvent::StartNode(1));
            events.push(TreeEvent::Token {
                kind: 3,
                start,
                end,
            });
            events.push(TreeEvent::FinishNode);
        } else {
            events.push(TreeEvent::StartNode(2));
            events.push(TreeEvent::Token {
                kind: 3,
                start,
                end,
            });
            events.push(TreeEvent::FinishNode);
        }
        start = end;
    }
    events.push(TreeEvent::FinishNode);
    events
}
