// @generated by gerbil-parser/src/compiler/rust-rowan.ss
// Source authority: canonical Grammar IR v1; do not edit.

use gerbil_parser_rowan::{
    ActionEntry, GotoEntry, KindCategory, KindSpec, LanguageSpec, LexicalExpr, LexicalRule,
    Operand, OperandAction, ParserAction, Production, Reduction, Symbol, Terminal, TerminalSpec,
};

static KINDS: &[KindSpec] = &[
    KindSpec {
        name: "Document",
        category: KindCategory::Node,
    },
    KindSpec {
        name: "Heading",
        category: KindCategory::Node,
    },
    KindSpec {
        name: "Text",
        category: KindCategory::Node,
    },
    KindSpec {
        name: "Line",
        category: KindCategory::Token,
    },
    KindSpec {
        name: "Section",
        category: KindCategory::Node,
    },
];

static TERMINALS: &[TerminalSpec] = &[TerminalSpec {
    name: "line",
    syntax_kind: 3,
}];

static LEXICAL_RULES: &[LexicalRule] = &[LexicalRule {
    terminal: "line",
    expression: LexicalExpr::Line,
    precedence: 0,
    extra: false,
}];

static ACTION_0: &[ActionEntry] = &[
    ActionEntry {
        terminal: Terminal::Eof,
        action: ParserAction::Reduce(1),
    },
    ActionEntry {
        terminal: Terminal::Token("line"),
        action: ParserAction::Reduce(1),
    },
];
static ACTION_1: &[ActionEntry] = &[ActionEntry {
    terminal: Terminal::Eof,
    action: ParserAction::Accept,
}];
static ACTION_2: &[ActionEntry] = &[
    ActionEntry {
        terminal: Terminal::Eof,
        action: ParserAction::Reduce(3),
    },
    ActionEntry {
        terminal: Terminal::Token("line"),
        action: ParserAction::Shift(4),
    },
];
static ACTION_3: &[ActionEntry] = &[
    ActionEntry {
        terminal: Terminal::Eof,
        action: ParserAction::Reduce(2),
    },
    ActionEntry {
        terminal: Terminal::Token("line"),
        action: ParserAction::Reduce(2),
    },
];
static ACTION_4: &[ActionEntry] = &[
    ActionEntry {
        terminal: Terminal::Eof,
        action: ParserAction::Reduce(4),
    },
    ActionEntry {
        terminal: Terminal::Token("line"),
        action: ParserAction::Reduce(4),
    },
];
static ACTIONS: &[&[ActionEntry]] = &[ACTION_0, ACTION_1, ACTION_2, ACTION_3, ACTION_4];

static GOTO_0: &[GotoEntry] = &[
    GotoEntry {
        nonterminal: "document",
        state: 1,
    },
    GotoEntry {
        nonterminal: "$document.0",
        state: 2,
    },
];
static GOTO_1: &[GotoEntry] = &[];
static GOTO_2: &[GotoEntry] = &[GotoEntry {
    nonterminal: "text-line",
    state: 3,
}];
static GOTO_3: &[GotoEntry] = &[];
static GOTO_4: &[GotoEntry] = &[];
static GOTOS: &[&[GotoEntry]] = &[GOTO_0, GOTO_1, GOTO_2, GOTO_3, GOTO_4];

static PRODUCTIONS: &[Production] = &[
    Production {
        lhs: "$accept",
        rhs: &[Operand {
            symbol: Symbol::Nonterminal("document"),
            actions: &[],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "$document.0",
        rhs: &[],
        reduction: Reduction::Concat,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "$document.0",
        rhs: &[
            Operand {
                symbol: Symbol::Nonterminal("$document.0"),
                actions: &[],
            },
            Operand {
                symbol: Symbol::Nonterminal("text-line"),
                actions: &[OperandAction::Field("line")],
            },
        ],
        reduction: Reduction::Concat,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "document",
        rhs: &[Operand {
            symbol: Symbol::Nonterminal("$document.0"),
            actions: &[OperandAction::Alias(0)],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
    Production {
        lhs: "text-line",
        rhs: &[Operand {
            symbol: Symbol::Terminal(Terminal::Token("line")),
            actions: &[OperandAction::Field("line"), OperandAction::Alias(2)],
        }],
        reduction: Reduction::Pass,
        dynamic_precedence: 0,
    },
];

pub static LANGUAGE: LanguageSpec = LanguageSpec {
    language: "event-lines",
    version: "v1",
    contract: "event-lines.v1",
    grammar_digest: "sha256:aec70367661a61688da821a945661893e3254de02059656eef7b28b22b5a9dda",
    case_insensitive: false,
    root_kind: 0,
    kinds: KINDS,
    terminals: TERMINALS,
    lexical_rules: LEXICAL_RULES,
    actions: ACTIONS,
    gotos: GOTOS,
    productions: PRODUCTIONS,
};
