#!/usr/bin/env gxi
;;; Native suite entry: run compiled tests without reloading expander interfaces.
(import (only-in :std/test/base TestConfig current-test-config VERBOSITY-CASE
                 test-suite! test-result-ok?)
        (prefix-in (only-in :gerbil-parser/t/benchmarks/versioned-languages/all-languages main) benchmark-)
        (prefix-in (only-in :gerbil-parser/t/fixtures/language-pack-research/package-expression-runtime main) concise-runtime-)
        (prefix-in (only-in :gerbil-parser/t/fixtures/language-pack-research/composition-history main) history-)
        (prefix-in (only-in :gerbil-parser/t/fixtures/language-pack-research/list-runtime main) native-poo-runtime-)
        (prefix-in (only-in :gerbil-parser/t/fixtures/language-pack-research/provenance-language main) provenance-)
        (only-in :gerbil-parser/t/fixtures/runtime-record-assignments/languages/records/parser-test records-parser-tests)
        (only-in :gerbil-parser/t/test-style-contract-test test-style-contract-test)
        (only-in :gerbil-parser/t/language-diagnostics-test language-diagnostics-test)
        (only-in :gerbil-parser/t/language-surface-test language-surface-test)
        (only-in :gerbil-parser/t/grammar-composition-test grammar-composition-test)
        (only-in :gerbil-parser/t/language-artifact-test language-artifact-tests)
        (only-in :gerbil-parser/t/language-entry-boundary-test language-entry-boundary-test)
        (only-in :gerbil-parser/t/generate-native-language-alignment write-native-language-alignment!)
        (only-in :gerbil-parser/t/language-topology-test language-topology-test)
        (only-in :gerbil-parser/t/language-loader-test language-loader-test)
        (only-in :gerbil-parser/t/language-loader-value-test language-loader-value-test)
        (only-in :gerbil-parser/t/antlr4-source-test antlr4-source-test)
        (only-in :gerbil-parser/languages/gql/parser-test gql-parser-test)
        (only-in :gerbil-parser/languages/arithmetic/parser-test arithmetic-parser-test)
        (only-in :gerbil-parser/languages/bash/parser-test bash-parser-test)
        (only-in :gerbil-parser/languages/cypher/parser-test opencypher-parser-test)
        (only-in :gerbil-parser/languages/fhirpath/parser-test fhirpath-parser-test)
        (only-in :gerbil-parser/languages/hcl/parser-test hcl-parser-test)
        (only-in :gerbil-parser/languages/hl7/parser-test hl7-parser-test)
        (only-in :gerbil-parser/languages/tla-plus/parser-test tla-plus-core-parser-test tla-plus-layout-parser-test tla-plus-sany-candidate-parser-test)
        (only-in :gerbil-parser/t/gql/benchmark-profile-test gql-benchmark-profile-test)
        (only-in :gerbil-parser/t/language-pack-metadata-test language-pack-metadata-test)
        (only-in :gerbil-parser/t/source-strategy-test source-strategy-test)
        (only-in :gerbil-parser/t/source-grammar-test source-grammar-test)
        (only-in :gerbil-parser/t/command-profile-test command-profile-test)
        (only-in :gerbil-parser/t/build-strategy-test build-strategy-test)
        (only-in :gerbil-parser/t/fixtures/language-pack-research/package-expression-parser-test package-expression-parser-test)
        (only-in :gerbil-parser/t/fixtures/language-pack-research/list-parser-test list-parser-test))
(export main)
(def suites
  (list
        (cons "downstream-records" (list records-parser-tests))
        (cons "test-style" (list test-style-contract-test))
        (cons "diagnostics" (list language-diagnostics-test))
        (cons "surface" (list language-surface-test))
        (cons "composition" (list grammar-composition-test))
        (cons "publication" (list language-artifact-tests))
        (cons "entry-boundaries" (list language-entry-boundary-test))
        (cons "topology" (list language-topology-test))
        (cons "loaders" (list language-loader-test language-loader-value-test))
        (cons "gql" (list antlr4-source-test gql-parser-test))
        (cons "arithmetic" (list arithmetic-parser-test))
        (cons "bash" (list source-grammar-test command-profile-test bash-parser-test))
        (cons "cypher" (list opencypher-parser-test))
        (cons "fhirpath" (list fhirpath-parser-test))
        (cons "hcl" (list hcl-parser-test))
        (cons "hl7" (list hl7-parser-test))
        (cons "tla-plus" (list tla-plus-core-parser-test tla-plus-layout-parser-test tla-plus-sany-candidate-parser-test))
        (cons "gql-profile" (list gql-benchmark-profile-test))
        (cons "pack-metadata" (list language-pack-metadata-test))
        (cons "source-services" (list source-strategy-test))
        (cons "build-services" (list build-strategy-test))
        (cons "concise-package" (list package-expression-parser-test))
        (cons "composed-package" (list list-parser-test))))
(def (main name . args)
  (let (program (assoc name (list (cons "concise-runtime" concise-runtime-main)
                                (cons "history" history-main)
                                (cons "native-poo-runtime" native-poo-runtime-main)
                                (cons "provenance" provenance-main))))
    (when program
      (unless (null? args) (error "unexpected research control arguments" args))
      ((cdr program))))
  (if (equal? name "native-language-alignment")
    (begin
      (unless (= (length args) 1) (error "expected native alignment output path" args))
      (write-native-language-alignment! (car args)) (exit 0))
    (if (equal? name "all-language-benchmark")
    (apply benchmark-main (if (null? args) ["1"] args))
    (let (row (assoc name suites))
      (unless (null? args) (error "unexpected native suite arguments" args))
      (unless row (error "unknown native conformance suite" name))
      (for-each
       (lambda (suite)
         (let (result
               (parameterize ((current-test-config
                               (TestConfig verbosity: VERBOSITY-CASE capture-output?: #f)))
                 (test-suite! suite)))
           (unless (test-result-ok? result) (exit 1))))
       (cdr row))
      (displayln "DSL-SUITE-OK: " name) (force-output) (exit 0)))))
