;;; -*- Gerbil -*-
;;; Native ABI fixture publication has a build owner separate from test assertions.
(import (prefix-in (only-in :gerbil-parser/src/ffi/language-artifact-codec bind-native-language native-descriptor-payload native-parse-binary-payload) codec-)
        (only-in :gerbil-parser/language-support/entry language-metadata-ref)
        (only-in :clan/poo/object .ref)
        (only-in :gerbil-parser/t/language-entry-boundary-test language-entry-pairs)
        (only-in :gerbil-parser/language-support/development language-loader-fixtures)
        (only-in :gerbil-parser/language-support/fixture syntax-fixture-source)
        (only-in :gerbil-parser/src/runtime/artifact parse-artifact-success?))
(export write-native-language-alignment!)
;;; Each native backend is checked from its configured public parser descriptor.
(def (write-native-language-alignment! output)
  (def (emit-bytes port bytes)
    (let (length (u8vector-length bytes))
      (for-each (lambda (shift) (write-u8 (bitwise-and 255 (arithmetic-shift length (- shift))) port))
                '(0 8 16 24)))
    (write-u8vector bytes port))
  (call-with-output-file output
    (lambda (port)
      (for-each
        (lambda (row)
          (let* ((entry (car row)) (development (cadr row))
                 (metadata (.ref entry 'metadata))
                 (name (language-metadata-ref metadata 'contract))
                 (native (codec-bind-native-language (.ref entry 'descriptor))))
            (for-each
              (lambda (status)
                (let (fixtures (language-loader-fixtures development status))
                  (when (null? fixtures) (error "missing native alignment control" name status))
                  (let* ((source (syntax-fixture-source (car fixtures)))
                         (artifact ((.ref entry '.parse) source)))
                    (unless (eq? (parse-artifact-success? artifact) (eq? status 'accepted))
                      (error "native alignment fixture status mismatch" name status))
                    (emit-bytes port (string->utf8 name))
                    (emit-bytes port (string->utf8 (codec-native-descriptor-payload native)))
                    (emit-bytes port (string->utf8 source))
                    (emit-bytes port (codec-native-parse-binary-payload native source))
                    (write-u8 (if (eq? status 'accepted) 1 0) port)
                    (displayln "NATIVE-ALIGNMENT-CASE " name " " status) (force-output))))
              '(accepted rejected))))
        language-entry-pairs)))
  (displayln "NATIVE-LANGUAGE-ALIGNMENT-GENERATED") (force-output))
