#!/usr/bin/env gxi
;;; Real production BindingProfile names lower through the shared TextProfile IR.
(import (only-in :gerbil-parser/t/fixtures/tla-sany-differential/exit-child-process test-child-process-exit!)
        (only-in :gerbil-parser/t/fixtures/bash-products bash-parts)
        (only-in :gerbil-parser/src/language/part-profile compile-part-profile part-plan-recipe part-plan-binding binding-plan-name-end)
        (only-in :gerbil-parser/src/compiler/rust-runtime rust-text-profile-expression-source))
(def controls '("" "α_123" "123x" "@rest" "_rest" "α-β" "λ中😀" "1α" "!α" "?α" "aβγ"))
(def (byte-at source at) (u8vector-length (string->utf8 (substring source 0 at))))
(def (main output)
 (let* ((plan (compile-part-profile bash-parts)) (recipes (list-ref (part-plan-recipe plan) 3))
        (count 0))
  (call-with-output-file output (lambda (port)
   (display "// @generated from production Bash BindingProfile declarations.\n" port)
   (display "pub static PROFILES: &[(&str, gerbil_parser_runtime::TextProfile)] = &[\n" port)
   (for-each (lambda (role)
     (display "(" port) (write (symbol->string role) port) (display ", " port)
     (display (rust-text-profile-expression-source (car (cadr (assq role recipes)))) port)
     (display "),\n" port)) '(simple parameter assignment))
   (display "];\npub static TRACES: &[(usize, &str, usize, usize, Option<usize>)] = &[\n" port)
   (for-each (lambda (index)
     (let* ((role (list-ref '(simple parameter assignment) index)) (binding (part-plan-binding plan role)))
       (for-each (lambda (text)
         (let (source (string-append "前:" text ":tail"))
           (for-each (lambda (width)
             (let* ((start 2) (limit (+ start width))
                    (end (binding-plan-name-end binding source start limit)))
               (display "(" port) (display index port) (display ", " port) (write source port)
               (display ", " port) (display (byte-at source start) port)
               (display ", " port) (display (byte-at source limit) port) (display ", " port)
               (if (> end start) (begin (display "Some(" port) (display (byte-at source end) port) (display ")" port))
                 (display "None" port))
               (display "),\n" port) (set! count (+ count 1))))
             (iota (+ (string-length text) 1))))) controls))) '(0 1 2))
   (display "];\n" port)))
  (displayln "BINDING-NAMES-RUST-GENERATED traces=" count) (force-output) (test-child-process-exit! 0)))
