#!/usr/bin/env gxi
(import (only-in :gerbil-parser/t/fixtures/tla-sany-differential/exit-child-process test-child-process-exit!)
        (only-in :gerbil-parser/src/compiler/rust-runtime language-rust-runtime-module-source)
        (only-in :gerbil-parser/t/module-source-test module-framing-language-grammar)
        (only-in "module-source-cases.ss" module-source-cases))
(def (main output)
 (call-with-output-file output (lambda (port)
  (display (language-rust-runtime-module-source module-framing-language-grammar) port)
  (display "\npub const MODULE_CASES: &[(&str, usize, Option<usize>)] = &[\n" port)
  (for-each (lambda (row)
   (display "(" port) (write (car row) port) (display ", " port) (display (cadr row) port) (display ", " port)
   (if (caddr row) (begin (display "Some(" port) (display (caddr row) port) (display ")" port)) (display "None" port))
   (display "),\n" port)) module-source-cases)
  (display "];\n" port)))
 (displayln "MODULE-SOURCE-RUST-GENERATED") (force-output) (test-child-process-exit! 0))
