#!/usr/bin/env gxi
;;; Recognition controls come from the actual Scheme Source engine, including fields and deferred links.
(import (only-in :gerbil-parser/t/fixtures/tla-sany-differential/exit-child-process test-child-process-exit!)
        (only-in :clan/poo/object .o .ref)
        (only-in :gerbil-parser/t/fixtures/bash-products bash-results bash-parts bash-word-regions bash-commands bash-command-scanner)
        (only-in :gerbil-parser/src/compiler/rust-scanner command-source-rust-module-source)
        (only-in :gerbil-parser/src/runtime/source-engines ShellSourceStrategy.)
        (only-in :gerbil-parser/src/compiler/rust-runtime result-profile-rust-source)
        (only-in :gerbil-parser/src/language/result-profile compile-result-profile result-plan-recipe)
        (only-in :gerbil-parser/src/language/part-profile compile-part-profile)
        (only-in :gerbil-parser/src/language/command-profile compile-command-profile)
        (only-in :gerbil-parser/src/language/scanner-profile compile-scanner-profile)
        (only-in :gerbil-parser/src/runtime/contextual-scanner prepare-contextual-scanner contextual-scanner-initial-state contextual-scanner-step)
        (only-in :gerbil-parser/src/runtime/shell-parser make-shell-parser shell-here-document-link-marker-start shell-here-document-link-body-start)
        (only-in :gerbil-parser/src/runtime/artifact parse-artifact-success? parse-artifact-events event-kind token-event-token-kind event-start event-end))
(def controls
 '("" "  # hi\n" "echo α😀" "a=中 x+=λ echo \"${x:-中}\" 2>out tail" "arr=(α \"中\"\nλ) echo ok"
   "echo α|&cat && echo 中 || echo λ" "time -p ! echo α | cat" "! echo α" "time echo α"
   "if echo α; then echo 中; elif echo λ; then echo β; else echo 😀; fi"
   "while echo α; do echo 中; done" "until echo α; do echo 中; done"
   "for x in α 中; do echo $x; done" "for ((i=0;i<2;i++)); do echo $i; done"
   "select x in α 中; do echo $x; done"
   "case α in α|β) echo 中;; (λ) ;; esac"
   "function f() { echo α; } >out" "f ( ) { echo 中; }" "[[ α == 中 && -n $x ]]"
   "((1+(2*3)))" "{ echo α; } 2>out" "(echo α; echo 中)"
   "cat <<A <<'B'\nα${x:-中}\nA\n$raw\nB\n" "cat <<-A\n\t${x:-中}\n\tA\n"
   "cat <<''\nα\n\n" "cat <<A\r\nα\r\nA\r\n" "cat <<A\\\nB\nα\nAB\n"
   "if echo α; then fi" "while echo; done" "case x in x) echo;" "function f"
   "[[ x" "((x)" "echo |" "echo &&" ";echo" "then" "arr=(x" "cat <<A\nα\n"
   "cat <<\n" "echo '${x'" "if echo; then echo; fi extra" "{ }" "( )" "a= echo"
   "for x; do echo; done" "case x in esac" "f(){ echo; }" "echo >"))
;;; A second POO declaration changes the pipeline role and form keyword, using identical engine code.
(def extended
 (.o (:: self bash-commands)
  roles: (map (lambda (row) (if (eq? (car row) 'pipeline) '(pipeline (operator "&&")) row)) (.ref bash-commands 'roles))
  projections: (map (lambda (row) (if (eq? (car row) 'BashFile) '(BashFile CommandList) row)) (.ref bash-commands 'projections))
  forms: (map (lambda (row) (case (car row)
    ((brace-group) '(brace-group (word "开始") 0 BraceGroup (take open (word "开始")) (list body (word "结束") #f) (take close (word "结束"))))
    ((pipeline-prefix) '(pipeline-prefix (manual) 0 Pipeline)) (else row))) (.ref bash-commands 'forms))))
(def (scan ir source)
 (let* ((scanner (prepare-contextual-scanner ir source)) (state (contextual-scanner-initial-state scanner)))
  (let loop ((state state) (tokens '()))
   (let-values (((token next) (contextual-scanner-step scanner state 'source)))
    (if token (loop next (cons token tokens)) (reverse tokens))))))
(def (main output)
 (let* ((results (compile-result-profile bash-results)) (recipe (result-plan-recipe results))
        (nodes (map car (car recipe))) (terminals (cadr recipe)) (ir (compile-scanner-profile bash-command-scanner)) (count 0))
  (def (index kind values base)
   (let loop ((values values) (at base)) (cond ((null? values) (error "unknown result kind" kind))
    ((eq? kind (car values)) at) (else (loop (cdr values) (+ at 1))))))
  (call-with-output-file output (lambda (port)
   (display "// @generated by actual Scheme Source recognition; do not edit.\n" port)
   (display "pub struct Control {pub source:&'static str,pub accepted:bool,pub events:&'static [gerbil_parser_runtime::TreeEvent],pub fields:&'static [&'static str],pub links:&'static [(usize,usize)]}\n" port)
   (for-each (lambda (entry)
    (let ((name (car entry)) (profile (cadr entry)) (sources (caddr entry)))
     (display "pub mod " port) (display name port) (display " {\nuse gerbil_parser_runtime::TreeEvent;\n" port)
     (display (command-source-rust-module-source (.o (:: self ShellSourceStrategy.) regions: bash-word-regions results: bash-results parts: bash-parts commands: profile scanner: bash-command-scanner)) port)
     (display "pub static CONTROLS:&[super::Control]=&[\n" port)
     (let-values (((parse receipt) (make-shell-parser bash-word-regions results (compile-part-profile bash-parts) (compile-command-profile profile))))
      (for-each (lambda (source)
       (displayln "COMMAND-SOURCE-CONTROL " name " " count) (force-output)
       (let-values (((artifact links) (receipt source (lambda (source) (scan ir source)) "control")))
        (display "super::Control {source:" port) (write source port)
        (display (if (parse-artifact-success? artifact) ",accepted:true,events:&[" ",accepted:false,events:&[") port)
        (when (parse-artifact-success? artifact)
         (for-each (lambda (event)
          (case (event-kind event)
           ((start-node) (display "TreeEvent::StartNode(" port) (display (index (vector-ref event 2) nodes 0) port) (display ")," port))
           ((finish-node) (display "TreeEvent::FinishNode," port))
           ((token) (display "TreeEvent::Token {kind:" port) (display (index (token-event-token-kind event) terminals (length nodes)) port)
            (display ",start:" port) (display (event-start event) port) (display ",end:" port) (display (event-end event) port) (display "}," port)))) (parse-artifact-events artifact)))
        (display "],fields:&[" port)
        (when (parse-artifact-success? artifact)
         (for-each (lambda (event) (when (eq? (event-kind event) 'start-field) (write (symbol->string (vector-ref event 1)) port) (display "," port))) (parse-artifact-events artifact)))
        (display "],links:&[" port)
        (for-each (lambda (link) (display "(" port) (display (shell-here-document-link-marker-start link) port)
         (display "," port) (display (shell-here-document-link-body-start link) port) (display ")," port)) links)
        (display "]},\n" port) (set! count (+ count 1)))) sources))
     (display "];\n}\n" port)))
    (list (list "bash" bash-commands controls)
          (list "extended" extended '("开始 echo α; 结束" "echo α && echo 中" "{ echo α; }" "开始 结束" "time echo α"))))))
  (displayln "COMMAND-SOURCE-RUST-GENERATED controls=" count) (force-output) (test-child-process-exit! 0)))
