#!/usr/bin/env gxi
;;; Scheme executes production and generic declarations; Rust recognizes sources independently.
(import (only-in :gerbil-parser/t/fixtures/tla-sany-differential/exit-child-process test-child-process-exit!)
        (only-in :gerbil-parser/languages/bash/grammar bash-word-regions)
        (only-in :gerbil-parser/src/compiler/rust-scanner region-plan-rust-source)
        (only-in :gerbil-parser/src/runtime/region-scanner prepare-region-plan region-plan-specification
                 region-plan-end prepare-scoped-region-source region-source-pair-end region-source-quote-end))
(def generic (prepare-region-plan '((";") ((#\« #t ("λ{")))
                                    (("λ{" #\{ #\} 1) ("[" #\[ #\] 1)) #f)))
(def generic-scopes '(("λ{" "λ{") ("[" "λ{" "[")))
(def sources '("α😀" "'α😀'" "\"α${x:-中}\"" "${arr[${i:-1}]:-λ}" "$((1+$(echo α)))"
               "<(echo \"中\")>stop" "`echo α`" "x\\α;tail" "x tail" "'unterminated"
               "${x:-\"bad}" "${x:-${y:-z}}" "λ{[}tail" "[λ{[}λ{中}]" "«λ{中}»;tail"
               "«\\»中»" "[λ{中}" ";tail" "${x}" "λ{λ{中}}"))
(def (byte-at text at) (u8vector-length (string->utf8 (substring text 0 at))))
(def (attempt text thunk)
  (with-catch (lambda (_) -1)
    (lambda () (let (end (thunk)) (if end (byte-at text end) -2)))))
(def (main output)
  (call-with-output-file output
    (lambda (port)
      (display "// @generated by Scheme region execution; do not edit.\n" port)
      (for-each
       (lambda (entry)
         (let* ((name (car entry)) (plan (cadr entry)) (scopes (caddr entry))
                (data (region-plan-specification plan)))
           (display "pub mod " port) (display name port) (display " {\n" port)
           (display (region-plan-rust-source plan scopes) port)
           (display "type Request = (u32, usize, i64);\npub static TRACES: &[(&str, &[Request])] = &[\n" port)
           (for-each
            (lambda (text)
              (let (source (prepare-scoped-region-source plan text scopes))
                (display "(" port) (write text port) (display ", &[" port)
                ;; Plain word matching has no scope; scoped boundary requests use source caches.
                (display "(0,0," port) (display (attempt text (lambda () (region-plan-end plan text 0))) port) (display ")," port)
                (let loop ((at 0))
                  (when (< at (string-length text))
                    (when (ormap (lambda (row)
                      (let (prefix (car row))
                        (and (<= (+ at (string-length prefix)) (string-length text))
                             (string=? prefix (substring text at (+ at (string-length prefix))))))) (caddr data))
                      (display "(1," port) (display (byte-at text at) port) (display "," port)
                      (display (attempt text (lambda () (region-source-pair-end source at))) port) (display ")," port))
                    (let (quote (assv (string-ref text at) (cadr data)))
                      (when quote
                        (display "(" port) (display (char->integer (car quote)) port) (display "," port)
                        (display (byte-at text at) port) (display "," port)
                        (display (attempt text (lambda () (region-source-quote-end source at (car quote)))) port)
                        (display ")," port)))
                    (loop (+ at 1))))
                (display "]),\n" port))) sources)
           (display "];\n}\n" port)))
       (list (list "bash" bash-word-regions '()) (list "generic" generic generic-scopes)))))
  (displayln "REGION-BOUNDARIES-RUST-GENERATED sources=" (* 2 (length sources)))
  (force-output) (test-child-process-exit! 0))
