;;; Prepared layout projections preserve the former pure action decision.
(import :std/test
        (only-in :gerbil-parser/src/runtime/layout
                 prepare-layout-action-selector make-layout-columns
                 current-layout-columns current-layout-frames)
        (only-in :gerbil-parser/src/runtime/lr-action-index index-action-rows)
        (only-in :gerbil-parser/src/runtime/token make-token)
        (only-in ./fixtures/lr-action-selection reference-lr-action-selector))
(def lr-action-preparation-test
  (test-suite "prepared layout action projections"
    (test-case "all action forms, frame states, token refinements and EOF agree"
      (for-each (lambda (action)
        (let* ((entries
                (list (cons '(terminal literal "end") action)
                      (cons '(terminal literal "END") '(layout-guard (reduce 12) (reduce 14)))
                      (cons '(terminal literal "É") '(reduce 13))
                      (cons '(terminal token word) '(fork (shift 4) (reduce 5)))
                      (cons '(terminal layout-next "end") action)
                      (cons '(terminal layout-start "end") action)
                      (cons '(terminal eof) '(accept))))
               (rows (vector entries)))
          (for-each (lambda (casefold?)
            (let* ((index (index-action-rows rows casefold?))
                   (reference (reference-lr-action-selector rows index casefold? #t))
                   (candidate (prepare-layout-action-selector rows index casefold?)))
              (parameterize ((current-layout-columns (make-layout-columns "end é\nEND")))
                (for-each (lambda (frames)
                  (parameterize ((current-layout-frames frames))
                    (for-each (lambda (tokens)
                      (check (candidate 0 tokens) => (reference 0 tokens)))
                      (list '() (list (make-token 'word "end" 0 3))
                            (list (make-token 'word "é" 4 6))
                            (list (make-token 'word "END" 7 10))
                            (list (make-token 'word "foo" 7 10))))))
                  '(() ((2 . "end")) ((100 . "outer")) ((4 . "é"))
                    ((2 . "end") (100 . "outer"))))))) '(#f #t))))
        '((shift 1) (reduce 2) (accept) (fork (shift 3) (reduce 4))
          (layout-guard (shift 5) (reduce 15)) (layout-guard (reduce 6) (reduce 16))
          (layout-guard (fork (shift 7) (reduce 8)) (reduce 17))
          (fork (layout-guard (shift 9) (reduce 18)) (fork (shift 10) (reduce 11))))))
    (test-case "denied first literal never falls through to duplicates or token kinds"
      (let* ((entries '(((terminal literal "end") shift 1)
                       ((terminal literal "end") reduce 2)
                       ((terminal literal "END") reduce 3)
                       ((terminal token word) reduce 4)))
             (rows (vector entries))
             (index (index-action-rows rows #t))
             (candidate (prepare-layout-action-selector rows index #t)))
        (parameterize ((current-layout-columns (make-layout-columns "end"))
                       (current-layout-frames '((100 . "outer"))))
          (check (candidate 0 (list (make-token 'word "end" 0 3))) => #f))))
    (test-case "pure reductions skip column decisions only after marker precedence"
      (let* ((entry '((terminal literal "end") reduce 1))
             (rows (vector (list entry '((terminal layout-next "end") shift 2))))
             (index (index-action-rows rows #f))
             (candidate (prepare-layout-action-selector rows index #f))
             (reference (reference-lr-action-selector rows index #f #t))
             (tokens (list (make-token 'word "end" 0 3))))
        (parameterize ((current-layout-columns (make-layout-columns "end")))
          (for-each (lambda (frames)
            (parameterize ((current-layout-frames frames))
              (check (candidate 0 tokens) => (reference 0 tokens))))
            '(() ((2 . "end")) ((100 . "outer")))))))
    (test-case "missing source context retains original entry identity"
      (let* ((entry '((terminal literal "end") layout-guard (reduce 1) (reduce 2)))
             (rows (vector (list entry))) (index (index-action-rows rows #f))
             (candidate (prepare-layout-action-selector rows index #f)))
        (parameterize ((current-layout-columns #f)
                       (current-layout-frames '((100 . "outer"))))
          (check (eq? (candidate 0 (list (make-token 'word "end" 0 3))) entry) => #t))))))
(export lr-action-preparation-test)
