;;; Recognition rules are executable POO values, including independent dialects.
(import :std/test
        (only-in :clan/poo/object .o .ref)
        :gerbil-parser/src/language/part-profile
        (only-in :gerbil-parser/src/language/result-profile compile-result-profile)
        (only-in :gerbil-parser/src/runtime/shell-word make-shell-word-parser)
        (only-in :gerbil-parser/src/runtime/recognition recognition-node-kind)
        (only-in :gerbil-parser/src/runtime/token make-token token-kind token-lexeme token-start token-end)
        (only-in :gerbil-parser/src/language/source declare-source-language source-language-digest)
        (only-in :gerbil-parser/src/runtime/source-engines ShellSourceStrategy.)
        (only-in :gerbil-parser/languages/bash/grammar bash-parts bash-results bash-word-regions bash-command-scanner bash-source-language))
(export part-profile-test)
(def (rejects? thunk) (with-catch (lambda (_) #t) (lambda () (thunk) #f)))
(defpart-profile (template-parts :: self PartProfile.)
 (contexts word HereDocument)
 (rules ((word HereDocument) (prefix "@" next) (name SimpleParameter "?")))
 (literal LiteralPart))
(defpart-profile (literal-parts :: self template-parts) (rules))
(def (components profile text)
  (let-values (((word assignment here)
                (make-shell-word-parser bash-word-regions (compile-result-profile bash-results)
                 (admit-part-plan (compile-part-profile profile) (compile-result-profile bash-results) bash-word-regions))))
    (word (make-token 'word text 0 (u8vector-length (string->utf8 text))))))
(def part-profile-test
 (test-suite "closed part recognition plans"
  (test-case "independent template uses the same execution operations and exact UTF-8 spans"
   (let-values (((node tokens) (components template-parts "α@name😀")))
     (check (recognition-node-kind node) => 'Word)
     (check (map token-kind tokens) => '(LiteralPart SimpleParameter LiteralPart))
     (check (map token-lexeme tokens) => '("α" "@name" "😀"))
     (check (map token-start tokens) => '(0 2 7))
     (check (map token-end tokens) => '(2 7 11)))
   (let-values (((node tokens) (components literal-parts "α@name😀")))
     (check (map token-kind tokens) => '(LiteralPart))
     (check (map token-lexeme tokens) => '("α@name😀"))))
  (test-case "non-ASCII prefixes use the same ordered recognition and byte projection"
   (let-values (((node tokens)
                 (components (.o (:: self template-parts)
                                 rules: '(((word HereDocument) (prefix "λ" next) (name SimpleParameter "?"))))
                             "中λname😀")))
     (check (map token-lexeme tokens) => '("中" "λname" "😀"))
     (check (map token-start tokens) => '(0 3 9))
     (check (map token-end tokens) => '(3 9 13))))
  (test-case "one matcher controls literal boundary and recognition precedence"
   (let (plan (compile-part-profile bash-parts))
     (check (part-step-kind (part-plan-match plan "$((1))" 0 6 'word)) => 'ArithmeticExpansion)
     (check (part-step-kind (part-plan-match plan "$(x)" 0 4 'word)) => 'CommandSubstitution)
     (check (part-plan-match plan "$x" 0 2 'SingleQuoted) => #f)
     (check (part-plan-literal-end plan "a$x" 0 3 'word) => 1)
     (check (part-plan-literal-end plan "a$x" 0 3 'SingleQuoted) => 3)
     (check (part-plan-match plan "\\q" 0 2 'HereDocument) => #f)
     (check (part-step-operation (part-plan-match plan "\\$" 0 2 'HereDocument)) => 'escape)
     (check (rejects? (lambda () (part-plan-match plan "x" 0 1 'undeclared))) => #t)))
  (test-case "unknown dollars preserve token grouping instead of dropping boundaries"
   (let-values (((node tokens) (components bash-parts "a$%b$x")))
     (check (map token-kind tokens) => '(LiteralPart LiteralPart SimpleParameter))
     (check (map token-lexeme tokens) => '("a" "$%b" "$x"))))
  (test-case "owned declarations and returned recipes cannot mutate executable dispatch"
   (let* ((declarations (list (list '(word HereDocument) (list 'prefix (string-copy "@") 'next) '(name SimpleParameter "?"))))
          (profile (.o (:: self template-parts) rules: declarations))
          (plan (compile-part-profile profile)) (recipe (part-plan-recipe plan)))
     (string-set! (cadadr (car declarations)) 0 #\!)
     (string-set! (cadadr (caadr recipe)) 0 #\!)
     (check (part-step-kind (part-plan-match plan "@x" 0 2 'word)) => 'SimpleParameter)
     (check (part-plan-match plan "!x" 0 2 'word) => #f)))
  (test-case "malformed contexts, matchers, operations and ambiguous duplicates reject"
   (for-each (lambda (profile) (check (rejects? (lambda () (compile-part-profile profile))) => #t))
    (list (.o (:: self template-parts) contexts: '(word word))
          (.o (:: self template-parts) rules: '(((other) (prefix "@" next) (name SimpleParameter "?"))))
          (.o (:: self template-parts) rules: '(((word) (prefix "" any) (escape EscapeSequence))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@" any) (callback arbitrary))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@" any) (pair CommandSubstitution 2 1))))
          (.o (:: self template-parts) rules: (append (.ref template-parts 'rules) (.ref template-parts 'rules))))))
  (test-case "loader admission rejects result and region disagreement before source execution"
   (for-each (lambda (profile)
               (check (rejects? (lambda () (admit-part-plan (compile-part-profile profile)
                                             (compile-result-profile bash-results) bash-word-regions))) => #t))
    (list (.o (:: self template-parts) literal: 'Undeclared)
          (.o (:: self template-parts) rules: '(((word) (prefix "@" next) (name Undeclared "?"))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@(" any) (pair CommandSubstitution 2 1))))
          (.o (:: self bash-parts) rules: '(((word) (prefix "$((" any) (pair ArithmeticExpansion 3 1)))))))
  (test-case "recognition values participate in source identity without changing source schema"
   (let (changed (declare-source-language "bash" "5.3" "bash-5.3-structured-source.v1"
                  (.o (:: self ShellSourceStrategy.) regions: bash-word-regions scanner: bash-command-scanner
                      results: bash-results parts: literal-parts)))
     (check (equal? (source-language-digest changed) (source-language-digest bash-source-language)) => #f)))))
