;;; Recognition rules are executable POO values, including independent dialects.
(import :std/test
        (only-in :clan/poo/object .o .ref)
        :gerbil-parser/src/language/part-profile
        (only-in :gerbil-parser/src/language/result-profile compile-result-profile ResultProfile. defresult-profile result-plan-recipe)
        (only-in :gerbil-parser/src/runtime/shell-word make-shell-word-parser)
        (only-in :gerbil-parser/src/runtime/scan make-bounded-text-profile-scanner make-bounded-literal-end-scanner)
        (only-in :gerbil-parser/src/runtime/recognition recognition-node-kind recognition-node-children recognition-child-field)
        (only-in :gerbil-parser/src/runtime/token make-token token-kind token-lexeme token-start token-end)
        (only-in :gerbil-parser/src/language/source declare-source-language source-language-digest)
        (only-in :gerbil-parser/src/runtime/source-engines ShellSourceStrategy.)
        (only-in :gerbil-parser/t/fixtures/bash-products bash-commands bash-parts bash-simple-binding bash-parameter-binding bash-assignment-binding bash-results bash-word-regions bash-command-scanner bash-source-language))
(export part-profile-test)
(def (rejects? thunk) (with-catch (lambda (_) #t) (lambda () (thunk) #f)))
(defpart-profile (template-parts :: self PartProfile.)
 (contexts word HereDocument)
 (bindings (template (.o (:: self BindingProfile.))))
 (rules ((word HereDocument) (prefix "@" next) (name SimpleParameter template)))
 (literal LiteralPart))
(defpart-profile (literal-parts :: self template-parts) (rules))
(defresult-profile (template-results :: self ResultProfile.)
 (projections
  (Word TemplateWord ((parts parts)) (many fragment parts))
  (HereDocumentLine TemplateBody ((parts parts)) (many fragment parts))
  (LiteralPart TemplateLiteral ((text span)) (token content text text required))
  (SimpleParameter TemplateName ((text span)) (token identifier name text required))))
(def (components profile text)
  (let-values (((word assignment here)
                (make-shell-word-parser bash-word-regions (compile-result-profile bash-results)
                 (admit-part-plan (compile-part-profile profile) (compile-result-profile bash-results) bash-word-regions))))
    (word (make-token 'word text 0 (u8vector-length (string->utf8 text))))))
(def (assignment-components profile text)
  (let-values (((word assignment here)
                (make-shell-word-parser bash-word-regions (compile-result-profile bash-results)
                 (admit-part-plan (compile-part-profile profile) (compile-result-profile bash-results) bash-word-regions))))
    (assignment (make-token 'word text 0 (u8vector-length (string->utf8 text))))))
(def part-profile-test
 (test-suite "closed part recognition plans"
  (test-case "independent template projection replaces every public word field and terminal through POO"
   (let* ((results (compile-result-profile template-results))
          (parts (admit-part-plan (compile-part-profile template-parts) results bash-word-regions)))
     (let-values (((word assignment here) (make-shell-word-parser bash-word-regions results parts)))
       (let-values (((node tokens) (word (make-token 'raw "α@name😀" 7 18))))
         (check (recognition-node-kind node) => 'TemplateWord)
         (check (map recognition-child-field (recognition-node-children node)) => '(fragment fragment fragment))
         (check (map token-kind tokens) => '(text name text))
         (check (map token-start tokens) => '(7 9 14))
         (check (map token-end tokens) => '(9 14 18)))
       (let-values (((node tokens) (here (make-token 'raw "中@name" 0 8))))
         (check (recognition-node-kind node) => 'TemplateBody)
         (check (map token-kind tokens) => '(text name))))))
  (test-case "missing word projection rejects and projection-only change alters Source identity"
   (let* ((projection-declarations (caddr (result-plan-recipe (compile-result-profile bash-results))))
          (replacement (map (lambda (row) (if (eq? (car row) 'Word)
                                         (cons 'Word (cons 'HereDocumentLine (cddr row))) row)) projection-declarations))
          (result-override (.o (:: self bash-results) projections: replacement)))
     (check (rejects? (lambda () (admit-part-plan (compile-part-profile bash-parts)
                      (compile-result-profile (.o (:: self bash-results) projections: '())) bash-word-regions))) => #t)
     (let (changed (declare-source-language "bash" "5.3" "bash-5.3-structured-source.v1"
                     (.o (:: self ShellSourceStrategy.) regions: bash-word-regions scanner: bash-command-scanner
                          results: result-override parts: bash-parts commands: bash-commands)))
       (check (equal? (source-language-digest changed) (source-language-digest bash-source-language)) => #f))))
  (test-case "independent template uses the same execution operations and exact UTF-8 spans"
   (let-values (((node tokens) (components template-parts "α@name😀")))
     (check (recognition-node-kind node) => 'Word)
     (check (map token-kind tokens) => '(LiteralPart SimpleParameter LiteralPart))
     (check (map token-lexeme tokens) => '("α" "@name" "😀"))
     (check (map token-start tokens) => '(0 2 7))
     (check (map token-end tokens) => '(2 7 11)))
   (let-values (((node tokens) (components literal-parts "α@name😀")))
     (check (map token-kind tokens) => '(LiteralPart))
     (check (map token-lexeme tokens) => '("α@name😀"))))
  (test-case "non-ASCII prefixes use the same ordered recognition and byte projection"
   (let-values (((node tokens)
                 (components (.o (:: self template-parts)
                                 rules: '(((word HereDocument) (prefix "λ" next) (name SimpleParameter template))))
                             "中λname😀")))
     (check (map token-lexeme tokens) => '("中" "λname" "😀"))
     (check (map token-start tokens) => '(0 3 9))
     (check (map token-end tokens) => '(3 9 13))))
  (test-case "one matcher controls literal boundary and recognition precedence"
   (let (plan (compile-part-profile bash-parts))
     (check (part-step-kind (part-plan-match plan "$((1))" 0 6 'word)) => 'ArithmeticExpansion)
     (check (part-step-kind (part-plan-match plan "$(x)" 0 4 'word)) => 'CommandSubstitution)
     (check (part-plan-match plan "$x" 0 2 'SingleQuoted) => #f)
     (check (part-plan-literal-end plan "a$x" 0 3 'word) => 1)
     (check (part-plan-literal-end plan "a$x" 0 3 'SingleQuoted) => 3)
     (check (part-plan-match plan "\\q" 0 2 'HereDocument) => #f)
     (check (part-step-operation (part-plan-match plan "\\$" 0 2 'HereDocument)) => 'escape)
     (check (rejects? (lambda () (part-plan-match plan "x" 0 1 'undeclared))) => #t)))
  (test-case "literal runs agree with complete matching at every candidate boundary"
   (let (plan (compile-part-profile bash-parts))
     (for-each (lambda (context)
       (for-each (lambda (text)
         (let (end (string-length text))
           (let starts ((start 0))
             (when (< start end)
               (check (part-plan-literal-end plan text start end context)
                      => (let reference ((offset (+ start 1)))
                           (if (or (= offset end) (part-plan-match plan text offset end context))
                             offset (reference (+ offset 1)))))
               (starts (+ start 1))))))
         (list "plain" "中λ😀" "a$" "a$%b$x" "a\\qb\\$c" "a$(x)b" "a$((1))b" "a'α'b")))
       '(word HereDocument SingleQuoted)))
   (let* ((profile (.o (:: self template-parts)
                       rules: '(((word HereDocument) (prefix "λ" next) (name SimpleParameter template)))))
          (plan (compile-part-profile profile)))
     (check (part-plan-literal-end plan "中λ" 0 2 'word) => 2)
     (check (part-plan-literal-end plan "中λx" 0 3 'word) => 1)))
  (test-case "literal scanning terminates on empty ranges and rejects invalid bounds"
   (let (plan (compile-part-profile bash-parts))
     (check (part-plan-literal-end plan "" 0 0 'word) => 0)
     (check (part-plan-literal-end plan "αx" 1 1 'word) => 1)
     (for-each (lambda (range)
       (check (rejects? (lambda () (part-plan-literal-end plan "αx" (car range) (cadr range) 'word))) => #t))
       '((-1 2) (2 1) (0 3) (0 1/2) (1/2 2)))))
  (test-case "unknown dollars preserve token grouping instead of dropping boundaries"
   (let-values (((node tokens) (components bash-parts "a$%b$x")))
     (check (map token-kind tokens) => '(LiteralPart LiteralPart SimpleParameter))
     (check (map token-lexeme tokens) => '("a" "$%b" "$x"))))
  (test-case "owned declarations and returned recipes cannot mutate executable dispatch"
   (let* ((declarations (list (list '(word HereDocument) (list 'prefix (string-copy "@") 'next) '(name SimpleParameter template))))
          (profile (.o (:: self template-parts) rules: declarations))
          (plan (compile-part-profile profile)) (recipe (part-plan-recipe plan)))
     (string-set! (cadadr (car declarations)) 0 #\!)
     (string-set! (cadadr (caadr recipe)) 0 #\!)
     (check (part-step-kind (part-plan-match plan "@x" 0 2 'word)) => 'SimpleParameter)
     (check (part-plan-match plan "!x" 0 2 'word) => #f)))
  (test-case "malformed contexts, matchers, operations and ambiguous duplicates reject"
   (for-each (lambda (profile) (check (rejects? (lambda () (compile-part-profile profile))) => #t))
    (list (.o (:: self template-parts) contexts: '(word word))
          (.o (:: self template-parts) rules: '(((other) (prefix "@" next) (name SimpleParameter template))))
          (.o (:: self template-parts) rules: '(((word) (prefix "" any) (escape EscapeSequence))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@" any) (callback arbitrary))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@" any) (pair CommandSubstitution 2 1))))
          (.o (:: self template-parts) rules: (append (.ref template-parts 'rules) (.ref template-parts 'rules))))))
  (test-case "loader admission rejects result and region disagreement before source execution"
   (for-each (lambda (profile)
               (check (rejects? (lambda () (admit-part-plan (compile-part-profile profile)
                                             (compile-result-profile bash-results) bash-word-regions))) => #t))
    (list (.o (:: self template-parts) literal: 'Undeclared)
          (.o (:: self template-parts) rules: '(((word) (prefix "@" next) (name Undeclared template))))
          (.o (:: self template-parts) rules: '(((word) (prefix "@(" any) (pair CommandSubstitution 2 1))))
          (.o (:: self bash-parts) rules: '(((word) (prefix "$((" any) (pair ArithmeticExpansion 3 1)))))))
  (test-case "bounded lexical profiles and tries cannot see outside the current body"
   (let ((name (make-bounded-text-profile-scanner '(run (alphabetic) 1 #f)))
         (operator (make-bounded-literal-end-scanner '(":" ":-"))))
     (check (name "αβgamma" 0 2) => 2)
     (check (name "αβgamma" 2 2) => #f)
     (check (operator ":-x" 0 1) => 1)
     (check (operator ":-x" 0 2) => 2)
     (check (operator ":-x" 0 0) => #f)
     (check (name "x" 0 2) => #f)))
  (test-case "parameter, simple and assignment names execute the shared text algebra"
   (let* ((plan (compile-part-profile bash-parts)) (parameter (part-plan-binding plan 'parameter))
          (simple (part-plan-binding plan 'simple)) (assignment (part-plan-binding plan 'assignment)))
     (check (binding-plan-name-end parameter "123x" 0 4) => 3)
     (check (binding-plan-name-end simple "123x" 0 4) => 1)
     (check (binding-plan-name-end parameter "α_1:-x" 0 6) => 3)
     (check (binding-plan-name-end assignment "1x=" 0 3) => 0)
     (check (binding-plan-prefix-end parameter "#" 0 1) => #f)
     (check (binding-plan-prefix-end parameter "#α" 0 2) => 1)
     (check (binding-plan-operator-end parameter "##rest" 0 6) => 2)))
  (test-case "independent assignment syntax inherits the same projection without callbacks"
   (let* ((binding (.o (:: self BindingProfile.) operators: '("=" ":=")))
          (profile (.o (:: self template-parts) bindings: (list (cons 'template (.o (:: name BindingProfile.)))
                                                            (cons 'assignment binding)))))
     (let-values (((node tokens) (assignment-components profile "α:=中@name")))
       (check (recognition-node-kind node) => 'Assignment)
       (check (map token-lexeme tokens) => '("α" ":=" "中" "@name"))
       (check (map token-start tokens) => '(0 2 4 7)))
     (let-values (((node tokens) (assignment-components profile "1α:=中"))) (check node => #f))))
  (test-case "binding recipes own value overrides and reject nullable names or missing references"
   (let* ((operator-declarations (list (string-copy ":=")))
          (binding (.o (:: self BindingProfile.) operators: operator-declarations))
          (profile (.o (:: self template-parts) bindings: (list (cons 'template binding))))
          (plan (compile-part-profile profile)) (recipe (part-plan-recipe plan)))
     (string-set! (car operator-declarations) 0 #\!)
     (string-set! (car (caddr (cadar (list-ref recipe 3)))) 0 #\!)
     (check (binding-plan-operator-end (part-plan-binding plan 'template) ":=x" 0 3) => 2))
   (for-each (lambda (profile) (check (rejects? (lambda () (compile-part-profile profile))) => #t))
    (list (.o (:: self template-parts) bindings: '())
          (.o (:: self template-parts) bindings: (list (cons 'template (.o (:: binding BindingProfile.)
                                                                     name: '(run (alphabetic) 0 #f)))))
          (.o (:: self template-parts) bindings: (list (cons 'template (.o (:: binding BindingProfile.) operators: '("=" "="))))))))
  (test-case "recognition values participate in source identity without changing source schema"
   (let (changed (declare-source-language "bash" "5.3" "bash-5.3-structured-source.v1"
                  (.o (:: self ShellSourceStrategy.) regions: bash-word-regions scanner: bash-command-scanner
                      results: bash-results parts: literal-parts commands: bash-commands)))
     (check (equal? (source-language-digest changed) (source-language-digest bash-source-language)) => #f)))))
