;;; -*- Gerbil -*-
;;; The Rust AOT macro constructs syntax values before rendering source.

(import (only-in :std/test check test-case test-suite)
        (only-in :gerbil-parser/src/compiler/rust-syntax
                 rust-struct rust-static rust-array rust-some rust-none
                 rust-number rust-string rust-module rust-render
                 rust-struct-form? rust-struct-form-name rust-struct-form-fields
                 rust-field-name rust-module-form-item
                 rust-static-form-value))
(export rust-syntax-test)

(def rust-syntax-test
  (test-suite "Rust AOT syntax macro"
    (test-case "named fields are syntax nodes, not pre-rendered snippets"
      (let* ((value
              (rust-struct LineStructureSpec
                (grammar_digest (rust-string "sha256:abc"))
                (paragraph_node (rust-some (rust-number 4)))
                (table (rust-none))
                (blocks (rust-array '()))))
             (module (rust-module '("LineStructureSpec")
                                  (rust-static STRUCTURE LineStructureSpec value))))
        (check (rust-struct-form? value) => #t)
        (check (rust-struct-form-name value) => 'LineStructureSpec)
        (check (map rust-field-name (rust-struct-form-fields value))
               => '(grammar_digest paragraph_node table blocks))
        (check (rust-static-form-value (rust-module-form-item module))
               => value)
        (check (rust-render module)
               => (string-append
                   "// @generated by gerbil-parser/src/compiler/line-structure-rowan.ss\n"
                   "use gerbil_parser_rowan::{LineStructureSpec};\n\n"
                   "pub static STRUCTURE: LineStructureSpec = "
                   "LineStructureSpec { grammar_digest: \"sha256:abc\", "
                   "paragraph_node: Some(4), table: None, blocks: &[] };\n"))))))
