;;; -*- Gerbil -*-
;;; Parser IR v1 is the sole authority for deterministic Rust/Rowan output.

(import (only-in :std/io/tempfile make-temporary-file-name)
        (only-in :std/test check test-case test-suite)
        (only-in :gerbil-parser/languages/arithmetic/v1/grammar
                 +arithmetic-language-version+
                 +arithmetic-syntax-contract+
                 arithmetic-language-grammar
                 arithmetic-parser-ir
                 arithmetic-parser)
        (only-in :gerbil-parser/languages/gql/iso-39075-2024/grammar
                 +gql-syntax-contract+
                 gql-iso-parser-ir
                 gql-iso-parser)
        (only-in :gerbil-parser/src/compiler/machine
                 parser-machine-grammar-digest)
        (only-in :gerbil-parser/rust-rowan-support
                 generate-language-rust-rowan-module)
        (only-in :gerbil-parser/src/compiler/rust-rowan
                 rust-rowan-module-source))
(export rust-rowan-generation-tests)

(def (arithmetic-rust-source)
  (rust-rowan-module-source
   "arithmetic"
   +arithmetic-language-version+
   +arithmetic-syntax-contract+
   (parser-machine-grammar-digest arithmetic-parser)
   arithmetic-parser-ir))

(def rust-rowan-generation-tests
  (test-suite "Rust/Rowan AOT generation"
    (test-case "one Parser IR produces one deterministic Rust module"
      (let ((first (arithmetic-rust-source))
            (second (arithmetic-rust-source)))
        (check first => second)
        (check (and
                (string-contains first
                 "Source authority: canonical Grammar IR v1")
                (string-contains first
                 "use gerbil_parser_rowan::{")
                (string-contains first
                 (parser-machine-grammar-digest arithmetic-parser))
                (string-contains first "ParserAction::Shift(9)")
                (string-contains first "OperandAction::Alias(0)")
                (string-contains first
                 "LexicalExpr::Literals(&[\"+\", \"-\", \"*\""))
               => #t)))
    (test-case "GQL lowers its lexical algebra and selective-GLR tables"
      (let (source
            (rust-rowan-module-source
             "gql"
             "edition-1-2024-04"
             +gql-syntax-contract+
             (parser-machine-grammar-digest gql-iso-parser)
             gql-iso-parser-ir))
        (check (and (string-contains source "LexicalExpr::NumberLiteral")
                    (string-contains source "LexicalExpr::Choice")
                    (string-contains source "ParserAction::Fork(&[")
                    (string-contains source "dynamic_precedence:"))
               => #t)))
    (test-case "whole-line lexical IR lowers to the generic Rowan engine"
      (let* ((line-ir
              (map (lambda (entry)
                     (if (eq? (car entry) 'lexical-rules)
                       (cons 'lexical-rules
                             (map (lambda (row)
                                    (if (eq? (car row) 'number)
                                      '(number (line))
                                      row))
                                  (cdr entry)))
                       entry))
                   arithmetic-parser-ir))
             (source
              (rust-rowan-module-source
               "arithmetic" +arithmetic-language-version+
               +arithmetic-syntax-contract+
               (parser-machine-grammar-digest arithmetic-parser)
               line-ir)))
        (check (string-contains source
                                "LexicalRule { terminal: \"number\", expression: LexicalExpr::Line")
               => #t)))
    (test-case "the language descriptor is the complete generation input"
      (let (path (make-temporary-file-name "gerbil-parser-rowan"))
        (try
         (begin
           (generate-language-rust-rowan-module
            path arithmetic-language-grammar)
           (check (call-with-input-file
                   path (lambda (port) (read-line port #f)))
                  => "// @generated by gerbil-parser/src/compiler/rust-rowan.ss"))
         (finally
          (when (file-exists? path) (delete-file path))))))))
