;;; -*- Gerbil -*-
;;; Parser IR v1 is the sole authority for deterministic Rust/Rowan output.

(import (only-in :std/os/temporaries make-temporary-file-name)
        (only-in :std/srfi/13 string-contains)
        (only-in :std/test check test-case test-suite)
        (only-in :gerbil-parser/languages/arithmetic/v1/grammar
                 +arithmetic-language-version+
                 +arithmetic-syntax-contract+
                 arithmetic-language-grammar
                 arithmetic-parser-ir
                 arithmetic-parser)
        (only-in :gerbil-parser/src/compiler/machine
                 parser-machine-grammar-digest)
        (only-in :gerbil-parser/src/compiler/rust-rowan
                 generate-language-rust-rowan-module
                 rust-rowan-module-source))
(export rust-rowan-generation-tests)

(def (arithmetic-rust-source)
  (rust-rowan-module-source
   "arithmetic"
   +arithmetic-language-version+
   +arithmetic-syntax-contract+
   (parser-machine-grammar-digest arithmetic-parser)
   arithmetic-parser-ir))

(def rust-rowan-generation-tests
  (test-suite "Rust/Rowan AOT generation"
    (test-case "one Parser IR produces one deterministic Rust module"
      (let ((first (arithmetic-rust-source))
            (second (arithmetic-rust-source)))
        (check first => second)
        (check (and
                (string-contains first
                 "Source authority: canonical Grammar IR v1")
                (string-contains first
                 (parser-machine-grammar-digest arithmetic-parser))
                (string-contains first "ParserAction::Shift(9)")
                (string-contains first "OperandAction::Alias(0)")
                (string-contains first
                 "LexicalExpr::Literals(&[\"+\", \"-\", \"*\""))
               => #t)))
    (test-case "the language descriptor is the complete generation input"
      (let (path (make-temporary-file-name "gerbil-parser-rowan"))
        (try
         (begin
           (generate-language-rust-rowan-module
            path arithmetic-language-grammar)
           (check (call-with-input-file
                   path (lambda (port) (read-line port #f)))
                  => "// @generated by gerbil-parser/src/compiler/rust-rowan.ss"))
         (finally
          (when (file-exists? path) (delete-file path))))))))
