;;; Engine checkpoints are owned by the creating worker, including shared text.
(import :std/test
        (only-in :gerbil-parser/src/runtime/source-scanner
                 make-source-scanner source-scanner-tokens source-scanner-initial-state source-scanner-step
                 source-scan-state-with-context source-scan-state-byte-offset
                 make-source-scan-session source-scan-session-tokens
                 source-scan-session-scanned-token-count source-scan-session-reused-token-count)
        (only-in :gerbil-parser/src/runtime/token token-start token-end token-kind token-lexeme)
        (only-in :gerbil-parser/src/runtime/source-scanner source-scan-state-context)
        (only-in :gerbil-parser/src/runtime/contextual-scanner
                 +empty-delimiter-queue+ delimiter-queue-enqueue delimiter-queue-take
                 delimiter-queue-list delimiter-obligation-marker delimiter-obligation-quoted?
                 contextual-scan-state-canonical decode-marker)
        (only-in :gerbil-parser/src/language/source source-language-scanner-factory
                 parse-source-language parse-source-language/session source-language-session-artifact
                 source-language-session? source-language-history? source-language-session-history
                 source-language-session-scanned-token-count source-language-session-reused-token-count)
        (only-in :gerbil-parser/src/runtime/artifact parse-artifact-success?))
(import (only-in :gerbil-parser/languages/bash/parser bash-source-language))
(def (pending-markers state)
 (map car (cdr (assq 'pending (contextual-scan-state-canonical state)))))
(def (rejected? thunk)
  (with-catch (lambda (_) #t) (lambda () (thunk) #f)))
(def source-scanner-test
  (test-suite "source scanner worker ownership"
    (test-case "history retains scanner ownership without retaining the published artifact"
      (let* ((initial (parse-source-language/session bash-source-language "cat <<A\nα\nA\necho end\n"))
             (history (source-language-session-history initial))
             (source "echo猫 <<A\nα\nA\necho end\n")
             (next (parse-source-language/session bash-source-language source history)))
        (check (source-language-history? history) => #t)
        (check (source-language-session? history) => #f)
        (check (source-language-session-artifact next) => (parse-source-language bash-source-language source))
        (check (source-language-session-scanned-token-count next) => 1)
        (check (> (source-language-session-reused-token-count next) 0) => #t)))
    (test-case "Bash sessions reuse lexical suffixes and publish full fresh-parser parity"
      (let* ((old (parse-source-language/session bash-source-language "cat <<A\nα\nA\necho end\n"))
             (source "echo猫 <<A\nα\nA\necho end\n")
             (next (parse-source-language/session bash-source-language source old))
             (later-source "echo猫 <<A\nα\nA\necho 終わり\n")
             (later (parse-source-language/session bash-source-language later-source next)))
        (check (parse-artifact-success? (source-language-session-artifact next)) => #t)
        (check (source-language-session-artifact next) => (parse-source-language bash-source-language source))
        (check (source-language-session-scanned-token-count next) => 1)
        (check (source-language-session-reused-token-count next)
               => (- (source-language-session-scanned-token-count old) 1))
        ;; The second edit consumes checkpoints rebound by the first edit.
        (check (source-language-session-artifact later) => (parse-source-language bash-source-language later-source))
        (check (> (source-language-session-reused-token-count later) 0) => #t)))
    (test-case "changed quoted delimiter waits for the obligation to close before reuse"
      (let* ((old (parse-source-language/session bash-source-language "cat <<A\nα\nA\necho end\n"))
             (source "cat <<'A'\nα\nA\necho end\n")
             (next (parse-source-language/session bash-source-language source old)))
        (check (source-language-session-artifact next) => (parse-source-language bash-source-language source))
        (check (source-language-session-scanned-token-count next) => 7)
        (check (source-language-session-reused-token-count next) => 4)))
    (test-case "source session cache owns tokens and rejects ordinary callback reuse"
      (let* ((factory (source-language-scanner-factory bash-source-language))
             (text (string-copy "cat <<A\nα\nA\n"))
             (old (make-source-scan-session (factory text) 'command))
             (published (source-scan-session-tokens old)))
        (string-set! text 0 #\X)
        (string-set! (token-lexeme (car published)) 0 #\X)
        (vector-set! (car published) 2 999)
        (check (token-lexeme (car (source-scan-session-tokens old))) => "cat")
        (let* ((next (make-source-scan-session (factory "echo猫 <<A\nα\nA\n") 'command old))
               (fresh (source-scanner-tokens (factory "echo猫 <<A\nα\nA\n") 'command)))
          (check (source-scan-session-tokens next) => fresh)
          (check (source-scan-session-scanned-token-count next) => 1)
          (check (> (source-scan-session-reused-token-count next) 0) => #t))
        (let* ((calls 0)
               (worker (make-source-scanner "xy" #f
                         (lambda (_source start context _mode)
                           (set! calls (+ calls 1))
                           (if (= start 2) (values #f start context)
                             (values 'character (+ start 1) context)))))
               (first (make-source-scan-session worker 'ordinary))
               (second (make-source-scan-session worker 'ordinary first)))
          (check calls => 6)
          (check (source-scan-session-reused-token-count second) => 0))))
    (test-case "long session histories rebind prefix middle tail and EOF edits"
      (let* ((factory (source-language-scanner-factory bash-source-language))
             (prefix (string-join (make-list 64 "echo prefix\n") ""))
             (tail (string-join (make-list 64 "echo tail\n") ""))
             (original (string-append prefix "cat <<A\nα\nA\n" tail))
             (first (make-source-scan-session (factory original) 'command)))
        (for-each
         (lambda (source)
           (let* ((next (make-source-scan-session (factory source) 'command first))
                  (fresh (source-scanner-tokens (factory source) 'command))
                  (published (source-scan-session-tokens next))
                  (again (make-source-scan-session (factory source) 'command next)))
             (check published => fresh)
             (check (source-scan-session-tokens again) => fresh)
             (check (source-scan-session-scanned-token-count again) => 0)
             (check (source-scan-session-reused-token-count again) => (length fresh))
             (when (pair? published)
               (string-set! (token-lexeme (car published)) 0 #\X)
               (vector-set! (car published) 2 999))
             (check (source-scan-session-tokens next) => fresh)
             (check (source-scan-session-tokens first)
                    => (source-scanner-tokens (factory original) 'command))))
         (list (string-append "猫 " original)
               (string-append prefix "cat <<'A'\nβ\nA\n" tail)
               (string-append original "echo 終\n")
               (string-append original "\n")
               ""))))
    (test-case "lexical rejection publishes the original diagnostic and retains no cache"
      (let* ((bad-source "echo 'unterminated")
             (bad (parse-source-language/session bash-source-language bad-source))
             (good (parse-source-language/session bash-source-language "echo ok\n" bad)))
        (check (source-language-session-artifact bad) => (parse-source-language bash-source-language bad-source))
        (check (parse-artifact-success? (source-language-session-artifact bad)) => #f)
        (check (source-language-session-scanned-token-count bad) => #f)
        (check (source-language-session-reused-token-count good) => 0)
        (check (source-language-session-artifact good) => (parse-source-language bash-source-language "echo ok\n"))))
    (test-case "shared FIFO preserves order and branches without copying the pending prefix"
      (let* ((a (decode-marker 'raw "A" #f)) (b (decode-marker 'raw "B" #f))
             (first (delimiter-queue-enqueue +empty-delimiter-queue+ a))
             (second (delimiter-queue-enqueue first b)))
        (check (map delimiter-obligation-marker (delimiter-queue-list first)) => '("A"))
        (let-values (((head rest) (delimiter-queue-take second)))
          (check (delimiter-obligation-marker head) => "A")
          (check (map delimiter-obligation-marker (delimiter-queue-list rest)) => '("B"))
          (check (map delimiter-obligation-marker (delimiter-queue-list second)) => '("A" "B")))
        (check (rejected? (lambda () (delimiter-queue-enqueue first 'callback))) => #t)
        (check (rejected? (lambda () (delimiter-queue-take +empty-delimiter-queue+))) => #t)))
    (test-case "Bash uses engine quote removal including preserved double-quote escapes"
      (for-each
       (lambda (row)
         (let (marker (decode-marker 'shell-quote-removal (car row) #f))
           (check (delimiter-obligation-marker marker) => (cadr row))
           (check (delimiter-obligation-quoted? marker) => (caddr row))))
       '(("A" "A" #f) ("'A'" "A" #t) ("\"a\\q\"" "a\\q" #t)
         ("\"a\\$\"" "a$" #t) ("'a\\q'" "a\\q" #t)
         ("A\\\nB" "AB" #f) ("''" "" #t)))
      (check (rejected? (lambda () (decode-marker 'shell-quote-removal "" #f))) => #t)
      (check (rejected? (lambda () (decode-marker 'shell-quote-removal "'A" #f))) => #t)
      (check (rejected? (lambda () (decode-marker 'arbitrary "A" #f))) => #t))
    (test-case "Bash queued checkpoint replay retains its own pending obligations"
      (let* ((worker ((source-language-scanner-factory bash-source-language) "<<A <<B\nα\nA\nβ\nB\n"))
             (initial (source-scanner-initial-state worker)))
        (let-values (((open after-open) (source-scanner-step worker initial 'command)))
          (let-values (((marker queued) (source-scanner-step worker after-open 'command)))
            (check (pending-markers (source-scan-state-context queued)) => '("A"))
            (let-values (((again replay) (source-scanner-step worker after-open 'command)))
              (check (token-lexeme again) => "A")
              (check (pending-markers (source-scan-state-context replay)) => '("A")))
            (check (pending-markers (source-scan-state-context initial)) => '())))))
    (test-case "large Bash deferred batches drain in declaration order"
      (let* ((markers (map (lambda (n) (string-append "END" (number->string n))) (iota 128)))
             (source (string-append "cat "
                       (apply string-append (map (lambda (name) (string-append "<<" name " ")) markers))
                       "\n" (apply string-append (map (lambda (name) (string-append "α\n" name "\n")) markers))))
             (tokens (source-scanner-tokens ((source-language-scanner-factory bash-source-language) source) 'command)))
        (check (map token-lexeme (filter (lambda (token) (eq? (token-kind token) 'heredoc-marker)) tokens)) => markers)
        (check (map token-lexeme (filter (lambda (token) (eq? (token-kind token) 'heredoc-end)) tokens))
               => (map (lambda (name) (string-append name "\n")) markers))
        (check (apply string-append (map token-lexeme tokens)) => source)))
    (test-case "another worker cannot use a checkpoint over the exact same string"
      (let* ((source "αx") (calls 0)
             (step (lambda (_source offset context _mode)
                     (set! calls (+ calls 1))
                     (values 'character (+ offset 1) context)))
             (left (make-source-scanner source 'left step))
             (right (make-source-scanner source 'right step))
             (initial (source-scanner-initial-state left)))
        (check (rejected? (lambda () (source-scanner-step right initial 'test))) => #t)
        (check calls => 0)
        (check (rejected? (lambda ()
                           (source-scanner-step right (source-scan-state-with-context initial 'changed) 'test))) => #t)
        (check calls => 0)))
    (test-case "owned checkpoint replay and context updates preserve UTF-8 spans"
      (let* ((worker (make-source-scanner "αx" 'initial
                      (lambda (_source offset context _mode)
                        (if (= offset 2) (values #f offset context)
                          (values 'character (+ offset 1) context)))))
             (initial (source-scanner-initial-state worker)))
        (let-values (((first next) (source-scanner-step worker initial 'test)))
          (check (list (token-start first) (token-end first)) => '(0 2))
          (check (source-scan-state-byte-offset initial) => 0)
          (let-values (((again replay) (source-scanner-step worker initial 'test)))
            (check (list (token-start again) (token-end again)) => '(0 2))
            (check (source-scan-state-byte-offset replay) => 2))
          (let-values (((second end) (source-scanner-step worker (source-scan-state-with-context next 'updated) 'test)))
            (check (list (token-start second) (token-end second)) => '(2 3))
            (let-values (((eof final) (source-scanner-step worker end 'test)))
              (check eof => #f)
              (check (source-scan-state-byte-offset final) => 3))))))))
(export source-scanner-test)
