#!/usr/bin/env gxi
(import :std/test :std/iter
        (only-in :gerbil-parser/src/runtime/token make-token token-kind token-lexeme token-start token-end)
        (only-in :gerbil-parser/src/runtime/source-index
                 source-index-count source-index-height source-index-start source-index-end
                 source-index-shift source-index-concat source-index-slice source-index->lists
                 source-index-audit source-index-storage make-source-index-builder
                 source-index-builder-token! source-index-builder-shared! source-index-builder-finish
                 source-index-builder-fresh source-index-builder-shared source-index-builder-chunks source-index-builder-mode-chunks
                 make-source-index-cursor source-index-cursor-copy source-index-cursor-token
                 source-index-cursor-mode source-index-cursor-rank source-index-cursor-next! source-index-cursor-seek!))
(def (build tokens modes)
  (let (builder (make-source-index-builder))
    (for-each (lambda (token mode) (source-index-builder-token! builder token mode)) tokens modes)
    (source-index-builder-finish builder)))
(def (tokens n)
  (let loop ((at 0) (found '()))
    (if (= at n) (reverse found)
      (loop (+ at 1) (cons (make-token 'identifier "x" at (+ at 1)) found)))))
(def (materialize tree)
  (call-with-values (lambda () (source-index->lists tree)) list))
(def (relocate token delta)
  (make-token (token-kind token) (token-lexeme token) (+ delta (token-start token)) (+ delta (token-end token))))
(def source-index-test
  (test-suite "persistent measured source index"
    (test-case "empty streams and token/mode ownership"
      (let* ((source (tokens 130)) (modes (map (lambda (at) (modulo at 7)) (iota 130)))
             (tree (build source modes)))
        (check (source-index-count #f) => 0)
        (check (materialize #f) => '(() ()))
        (check (source-index-audit tree) => #t)
        (check (materialize tree) => (list source modes))
        (check (<= (source-index-height tree) 4) => #t)
        (let (cursor (make-source-index-cursor tree 63))
          (check (eq? (source-index-cursor-token cursor) (list-ref source 63)) => #t)
          (check (source-index-cursor-mode cursor) => 0)
          (source-index-cursor-next! cursor)
          (check (source-index-cursor-token cursor) => (list-ref source 64))
          (check (source-index-cursor-mode cursor) => 1))))
    (test-case "UTF8 byte positions remain independent of character measures"
      (let* ((source (list (make-token 'identifier "λ中😀" 0 9) (make-token 'trivia " " 9 10)
                           (make-token 'identifier "é" 10 12))) (modes '(2 2 4))
             (tree (build source modes)) (shifted (source-index-shift tree 5)))
        (check (source-index-audit shifted) => #t)
        (check (materialize shifted) => (list (map (cut relocate <> 5) source) modes))
        (check (eq? (source-index-shift shifted -5) tree) => #t)
        (let (cursor (make-source-index-cursor shifted))
          (source-index-cursor-seek! cursor 6)
          (check (source-index-cursor-rank cursor) => 1)
          (check (token-start (source-index-cursor-token cursor)) => 14)
          (source-index-cursor-seek! cursor 15)
          (check (source-index-cursor-mode cursor) => 4)
          (source-index-cursor-seek! cursor 17)
          (check (source-index-cursor-token cursor) => #f))))
    (test-case "slice/concat retain backing chunks and rejected trials do not consume"
      (let* ((source (tokens 1024)) (modes (make-list 1024 3)) (tree (build source modes))
             (middle (source-index-slice tree 71 831)))
        (check (source-index-audit middle) => #t)
        (check (materialize middle) => (list (take (drop source 71) 831) (make-list 831 3)))
        (check (every (lambda (storage) (and (memq storage (source-index-storage tree)) #t))
                      (source-index-storage middle)) => #t)
        (let* ((cursor (make-source-index-cursor middle 63)) (trial (source-index-cursor-copy cursor)))
          (source-index-cursor-seek! trial 800)
          (check (source-index-cursor-rank trial) => 729)
          (check (source-index-cursor-rank cursor) => 63)
          (check (token-start (source-index-cursor-token cursor)) => 134))
        (check (materialize (source-index-concat (source-index-slice tree 0 512)
                                                (source-index-slice tree 512 512)))
               => (list source modes))))
    (test-case "origins coalesce and fresh allocations are confined to changed chunks"
      (let* ((tree (build (tokens 1024) (make-list 1024 1)))
             (builder (make-source-index-builder (source-index-slice tree 0 100))))
        (source-index-builder-token! builder (make-token 'identifier "zz" 100 102) 6)
        (source-index-builder-shared! builder tree 100 400 2)
        (source-index-builder-shared! builder tree 500 524 2)
        (let (next (source-index-builder-finish builder))
          (check (source-index-count next) => 1025)
          (check (source-index-end next) => 1026)
          (check (source-index-builder-fresh builder) => 1)
          (check (source-index-builder-shared builder) => 1024)
          (check (source-index-builder-chunks builder) => 1)
          (check (source-index-audit next) => #t)
          (check (> (length (filter (lambda (storage) (memq storage (source-index-storage tree)))
                                  (source-index-storage next))) 10) => #t))))
    (test-case "sparse mode changes retain token chunks and old mode versions"
      (let* ((original (tokens 130)) (old-modes (make-list 130 1)) (tree (build original old-modes))
             (builder (make-source-index-builder)))
        (source-index-builder-shared! builder tree 0 63 0)
        (source-index-builder-shared! builder tree 63 1 0 0)
        (source-index-builder-shared! builder tree 64 1 0 9)
        (source-index-builder-shared! builder tree 65 65 0)
        (let (next (source-index-builder-finish builder))
          (check (source-index-audit next) => #t)
          (check (materialize tree) => (list original old-modes))
          (check (materialize next) => (list original (append (make-list 63 1) '(0 9) (make-list 65 1))))
          (check (every eq? (source-index-storage next) (source-index-storage tree)) => #t)
          (check (source-index-builder-chunks builder) => 0)
          (check (source-index-builder-mode-chunks builder) => 2))))
    (test-case "deterministic sequential splices preserve old versions and AVL measures"
      (let* ((original (tokens 1024)) (modes (make-list 1024 2)) (initial (build original modes)))
        (let loop ((step 0) (tree initial) (expected original) (expected-modes modes))
          (check (source-index-audit tree) => #t)
          (check (materialize tree) => (list expected expected-modes))
          (check (materialize initial) => (list original modes))
          (check (<= (source-index-height tree) 16) => #t)
          (when (< step 180)
            (let* ((size (length expected)) (at (modulo (+ (* step 37) 5) size))
                   (deleted (min (modulo step 5) (- size at))) (added (modulo (+ step 2) 7))
                   (delta (- added deleted))
                   (middle (map (lambda (n) (make-token 'identifier "y" (+ at n) (+ at n 1))) (iota added)))
                   (middle-modes (make-list added (modulo step 9)))
                   (builder (make-source-index-builder (source-index-slice tree 0 at))))
              (for-each (lambda (token mode) (source-index-builder-token! builder token mode)) middle middle-modes)
              (source-index-builder-shared! builder tree (+ at deleted) (- size at deleted) delta)
              (loop (+ step 1) (source-index-builder-finish builder)
                    (append (take expected at) middle (map (cut relocate <> delta) (drop expected (+ at deleted))))
                    (append (take expected-modes at) middle-modes (drop expected-modes (+ at deleted)))))))))
    (test-case "invalid gaps and out-of-range slices fail before sharing"
      (let (tree (build (tokens 10) (make-list 10 0)))
        (check-exception (source-index-slice tree 9 2) true)
        (check-exception (source-index-slice tree -1 1) true)
        (check-exception (source-index-concat tree (source-index-shift tree 11)) true)
        (check-exception (build (list (make-token 'trivia "" 0 0)) '(0)) true)))))
(export source-index-test)
