;;; -*- Gerbil -*-
;;; Canonical LexicalExpr v1 constructors.

(import (for-syntax (only-in :gerbil/expander core-expand1)))
(export lexical-expression
        lexical-expression? text-profile? text-profile-minimum-width
        text-profile-data deftext-profile
        (for-syntax expand-text-lexical-rows))

;;; Profile expansion is a compiler helper, separate from grammar inference.
(begin-syntax
  (def (expand-text-lexical-rows rows owner)
    (stx-map
     (lambda (row)
       (syntax-case row ()
         ((name kind expression)
          (list (syntax->datum #'name) (syntax->datum #'kind)
                (expand-text-profile-syntax #'expression owner)))
         (_ (raise-syntax-error #f "invalid concise lexical declaration" owner))))
     rows))
  (def (expand-text-profile-syntax expression owner (profile? #f) (depth 0))
    (when (>= depth 64) (raise-syntax-error #f "text profile declaration exceeds depth limit" owner))
    (syntax-case expression ()
      ((head argument ...)
       (let (name (syntax->datum #'head))
         (if (and profile? (eq? name 'ref))
           (syntax-case #'(argument ...) ()
             ((fragment)
              (identifier? #'fragment)
              (let* ((use #'(fragment)) (expanded (core-expand1 use)))
                (when (eq? expanded use)
                  (raise-syntax-error #f "unknown text profile fragment" owner))
                (expand-text-profile-syntax expanded owner #t (+ depth 1))))
             (_ (raise-syntax-error #f "text profile ref requires one declared fragment" owner)))
           (cons name
                 (stx-map
                  (lambda (child)
                    (expand-text-profile-syntax child owner (or profile? (eq? name 'text-profile)) (+ depth 1)))
                  #'(argument ...))))))
      (atom (syntax->datum #'atom)))))


(def (strings? values)
  (let loop ((rest values))
    (or (null? rest)
        (and (string? (car rest))
             (positive? (string-length (car rest)))
             (loop (cdr rest))))))

(def (lexical-expressions? values)
  (let loop ((rest values))
    (or (null? rest)
        (and (lexical-expression? (car rest))
             (loop (cdr rest))))))

;;; Closed text profiles have no callbacks or recursive references. Nullable
;;; children support guards, but each admitted scanner must make progress.
(def (text-class? value (depth 0))
  (and (< depth 64) (pair? value) (list? value)
       (case (car value)
         ((numeric ascii-letter) (= (length value) 1))
         ((characters) (and (= (length value) 2) (string? (cadr value))
                            (positive? (string-length (cadr value)))))
         ((union) (and (pair? (cdr value))
                       (andmap (lambda (child) (text-class? child (+ depth 1))) (cdr value))))
         (else #f))))

(def (text-profile-minimum-width value (depth 0))
  (and (< depth 64) (pair? value) (list? value)
       (case (car value)
         ((literal) (and (= (length value) 2) (string? (cadr value))
                         (positive? (string-length (cadr value))) (string-length (cadr value))))
         ((run) (and (= (length value) 4) (text-class? (cadr value))
                     (exact-integer? (caddr value)) (<= 0 (caddr value) 4294967295)
                     (or (not (cadddr value))
                         (and (exact-integer? (cadddr value)) (<= (caddr value) (cadddr value) 4294967295)))
                     (caddr value)))
         ((seq) (and (pair? (cdr value))
                     (let loop ((rest (cdr value)) (width 0))
                       (if (null? rest) width
                         (let (next (text-profile-minimum-width (car rest) (+ depth 1)))
                           (and next (<= (+ width next) 4294967295)
                                (loop (cdr rest) (+ width next))))))))
         ((optional) (and (= (length value) 2)
                          (text-profile-minimum-width (cadr value) (+ depth 1)) 0))
         ((if-next) (and (memv (length value) '(3 4)) (text-class? (cadr value))
                         (let ((yes (text-profile-minimum-width (caddr value) (+ depth 1)))
                               (no (if (= (length value) 4)
                                     (text-profile-minimum-width (cadddr value) (+ depth 1)) 0)))
                           (and yes no (min yes no)))))
         ((not-next) (and (= (length value) 2) (text-class? (cadr value)) 0))
         (else #f))))


;;; Named fragments expand only during declaration lowering. Runtime IR is
;;; closed data and has no name lookup or callback.
(defrules text-profile-data (literal run seq optional if-next not-next)
  ((_ (literal value)) (list 'literal value))
  ((_ (run class minimum maximum)) (list 'run 'class minimum maximum))
  ((_ (seq expression ...)) (cons 'seq (list (text-profile-data expression) ...)))
  ((_ (optional expression)) (list 'optional (text-profile-data expression)))
  ((_ (if-next class yes)) (list 'if-next 'class (text-profile-data yes)))
  ((_ (if-next class yes no))
   (list 'if-next 'class (text-profile-data yes) (text-profile-data no)))
  ((_ (not-next class)) (list 'not-next 'class)))

(defrules deftext-profile ()
  ((_ binding expression)
   (defrules binding () ((_ ) expression))))

(def (text-profile? value)
  (let (width (text-profile-minimum-width value)) (and width (positive? width))))

(def (lexical-expression? value)
  (and (list? value)
       (case (car value)
         ((whitespace+ horizontal-whitespace+ newline+ line
           decimal-digit+ number identifier heredoc fallback)
          (null? (cdr value)))
         ((text-profile) (and (= (length value) 2) (text-profile? (cadr value))))
         ((number-literal)
          (and (= (length value) 6)
               (pair? (cadr value))
               (strings? (cadr value))
               (string? (caddr value))
               (= (string-length (caddr value)) 1)
               (strings? (cadddr value))
               (boolean? (car (cddddr value)))
               (boolean? (cadr (cddddr value)))))
         ((quoted-string escaped-quoted-string)
          (and (pair? (cdr value)) (strings? (cdr value))))
         ((quoted-string-profile)
          (and (= (length value) 4)
               (string? (cadr value)) (= (string-length (cadr value)) 1)
               (string? (caddr value))
               (exact-integer? (cadddr value)) (<= 0 (cadddr value) 8)))
         ((header-delimiter header-data)
          (and (= (length value) 4)
               (string? (cadr value)) (positive? (string-length (cadr value)))
               (exact-integer? (caddr value)) (<= 1 (caddr value) 32)
               (if (eq? (car value) 'header-delimiter)
                 (and (exact-integer? (cadddr value)) (<= 0 (cadddr value))
                      (< (cadddr value) (caddr value)))
                 (string? (cadddr value)))))
         ((until-delimiters)
          (and (= (length value) 2)
               (string? (cadr value))
               (positive? (string-length (cadr value)))))
         ((character-run)
          (and (= (length value) 3)
               (string? (cadr value))
               (= (string-length (cadr value)) 1)
               (exact-integer? (caddr value))
               (positive? (caddr value))))
         ((line-comment)
          (and (pair? (cdr value)) (strings? (cdr value))))
         ((block-comment nested-block-comment)
          (and (= (length value) 3) (strings? (cdr value))))
         ((literals)
          (and (pair? (cdr value))
               (strings? (cdr value))))
         ((choice)
          (and (pair? (cdr value))
               (lexical-expressions? (cdr value))))
         ((precedence)
          (and (= (length value) 3)
               (integer? (cadr value))
               (lexical-expression? (caddr value))))
         ((external)
          (and (= (length value) 3)
               (or (symbol? (cadr value)) (string? (cadr value)))
               (symbol? (caddr value))))
         (else #f))))

(def (lexical-primitive kind)
  (unless (memq kind '(whitespace+ horizontal-whitespace+ newline+ line
                       decimal-digit+ number identifier heredoc fallback))
    (error "unknown lexical primitive" kind))
  (list kind))

(def (lexical-literals values)
  (unless (and (pair? values) (strings? values))
    (error "lexical literals require non-empty strings" values))
  (cons 'literals values))

(def (lexical-precedence rank expression)
  (unless (integer? rank)
    (error "lexical precedence rank must be an integer" rank))
  (unless (lexical-expression? expression)
    (error "lexical precedence requires a lexical expression" expression))
  (list 'precedence rank expression))

(def (lexical-external version scanner)
  (unless (or (symbol? version) (string? version))
    (error "external scanner version must be a symbol or string" version))
  (unless (symbol? scanner)
    (error "external scanner identity must be a symbol" scanner))
  (list 'external version scanner))

;;; Expands the closed lexical algebra into validated canonical data.
;;; Scanner execution remains in runtime/scan.ss, outside the syntax phase.
;; lexical-expression
;;   : (-> Syntax Syntax)
;;   | doc m%
;;       `lexical-expression` expands one declarative lexical expression.
;;
;;       # Examples
;;
;;       ```scheme
;;       (lexical-expression (identifier))
;;       ;; => (identifier)
;;       ```
;;     %
(defrules lexical-expression
  (whitespace+ horizontal-whitespace+ newline+ line decimal-digit+ number identifier
   heredoc number-literal text-profile
   quoted-string escaped-quoted-string quoted-string-profile until-delimiters character-run header-delimiter header-data
   line-comment block-comment nested-block-comment
   choice literals fallback precedence external)
  ((_ (whitespace+))
   (lexical-primitive 'whitespace+))
  ((_ (horizontal-whitespace+))
   (lexical-primitive 'horizontal-whitespace+))
  ((_ (newline+))
   (lexical-primitive 'newline+))
  ((_ (line))
   (lexical-primitive 'line))
  ((_ (decimal-digit+))
   (lexical-primitive 'decimal-digit+))
  ((_ (number))
   (lexical-primitive 'number))
  ((_ (number-literal (prefix ...) separator (suffix ...)
                      leading-period? trailing-period?))
   (list 'number-literal (list prefix ...) separator (list suffix ...)
         leading-period? trailing-period?))
  ((_ (text-profile expression))
   (list 'text-profile (text-profile-data expression)))
  ((_ (identifier))
   (lexical-primitive 'identifier))
  ((_ (quoted-string delimiter ...))
   (cons 'quoted-string (list delimiter ...)))
  ((_ (escaped-quoted-string delimiter ...))
   (cons 'escaped-quoted-string (list delimiter ...)))
  ((_ (quoted-string-profile delimiter escapes unicode-width))
   (list 'quoted-string-profile delimiter escapes unicode-width))
  ((_ (header-delimiter prefix count index))
   (list 'header-delimiter prefix count index))
  ((_ (header-data prefix count stops))
   (list 'header-data prefix count stops))
  ((_ (until-delimiters characters))
   (list 'until-delimiters characters))
  ((_ (character-run character minimum))
   (list 'character-run character minimum))
  ((_ (heredoc))
   (lexical-primitive 'heredoc))
  ((_ (line-comment start ...))
   (cons 'line-comment (list start ...)))
  ((_ (block-comment start finish))
   (list 'block-comment start finish))
  ((_ (nested-block-comment start finish))
   (list 'nested-block-comment start finish))
  ((_ (choice expression ...))
   (cons 'choice (list (lexical-expression expression) ...)))
  ((_ (precedence rank expression))
   (lexical-precedence rank (lexical-expression expression)))
  ((_ (external version scanner))
   (lexical-external version 'scanner))
  ((_ (literals value ...))
   (lexical-literals (list value ...)))
  ((_ (fallback))
   (lexical-primitive 'fallback)))
