;;; Build entry for any module exporting one admitted language descriptor.
(import :gerbil/expander
        (only-in :std/misc/ports read-all-as-string)
        (only-in :gerbil-parser/language-build-support make-fused-reduction-strategy emit-build-strategy)
        (only-in :gerbil-parser/src/language/descriptor language-grammar?))
(def (module-descriptor path)
  (let* ((context (import-module (if (and (> (string-length path) 0) (char=? (string-ref path 0) #\:))
                                    (string->symbol path) path) #f #t))
         (descriptors (filter-map
                       (lambda (exported)
                         (and (= (module-export-phi exported) 0)
                              (let (value (eval (binding-id (core-resolve-module-export exported))))
                                (and (language-grammar? value) value))))
                       (module-context-export context))))
    (unless (= (length descriptors) 1) (error "expected one language descriptor" path))
    (car descriptors)))
(def (main . args)
  (unless (and (= (length args) 3) (member (car args) '("module" "check")))
    (error "expected module|check grammar-module output-path" args))
  (let* ((strategy (make-fused-reduction-strategy (module-descriptor (cadr args))))
         (emit (lambda (port) (emit-build-strategy strategy port))))
    (if (equal? (car args) "module")
      (call-with-output-file (caddr args) emit)
      (let ((expected (call-with-output-string emit)) (repeated (call-with-output-string emit))
            (actual (call-with-input-file (caddr args) read-all-as-string)))
        (unless (and (equal? expected repeated) (equal? expected actual))
          (error "generated fused reduction product is stale or nondeterministic" (caddr args)))
        (displayln "GENERATED-REDUCTIONS-OK " (cadr args))))))
(export main)
