(def (test-plan-unique? values)
  (let loop ((rest values) (seen '()))
    (or (null? rest)
        (and (not (member (car rest) seen))
             (loop (cdr rest) (cons (car rest) seen))))))
;;; Read the existing build and execution declarations; no second Suite catalog.
(def (test-plan-definition file name)
  (call-with-input-file file
    (lambda (port)
      (let loop ()
        (let (form (read port))
          (cond ((eof-object? form) (error "missing test plan declaration" file name))
                ((and (pair? form) (eq? (car form) 'def) (equal? (cadr form) name))
                 (caddr form))
                (else (loop))))))))
(def (test-plan-symbols form)
  (cond ((symbol? form) (list form))
        ((pair? form) (append (test-plan-symbols (car form)) (test-plan-symbols (cdr form))))
        (else '())))
(def (validate-conformance-test-plan catalog imports execution)
  (let* ((owners (filter (lambda (name) (string-suffix? "-test" name)) catalog))
         (rows (filter (lambda (form)
                         (and (pair? form) (eq? (car form) 'only-in)
                              (symbol? (cadr form))
                              (string-prefix? ":gerbil-parser/" (symbol->string (cadr form)))
                              (string-suffix? "-test" (symbol->string (cadr form)))))
                       (cdr imports)))
         (imported (map (lambda (row) (let (name (symbol->string (cadr row))) (substring name 15 (string-length name)))) rows))
         (names (apply append (map cddr rows)))
         (used (filter (lambda (name) (member name names)) (test-plan-symbols execution))))
    (unless (and (equal? (list-sort string<? owners) (list-sort string<? imported))
                 (test-plan-unique? owners)
                 (test-plan-unique? names)
                 (equal? (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b))) names)
                         (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b))) used)))
      (error "conformance test ownership or Suite execution is incomplete" owners imported names used))
    (map (lambda (owner) (string-append owner ".ss")) owners)))
(def (conformance-covered-test-files)
  (let ((catalog (test-plan-definition "build-language-conformance.ss" 'conformance-modules))
        (imports (call-with-input-file "t/conformance-main.ss"
                   (lambda (port)
                     (let loop ()
                       (let (form (read port))
                         (cond ((eof-object? form) (error "missing conformance imports"))
                               ((and (pair? form) (eq? (car form) 'import)) form)
                               (else (loop))))))))
        (execution (test-plan-definition "t/conformance-main.ss" 'suites)))
    (unless (and (pair? catalog) (eq? (car catalog) 'quote))
      (error "expected literal conformance module catalog"))
    (let* ((covered (validate-conformance-test-plan (cadr catalog) imports execution))
           (source-rows (conformance-source-suites)))
      (unless (and (test-plan-unique? (map car source-rows))
                   (andmap (lambda (row)
                             (and (member (string-append (car row) ".ss") covered)
                                  (pair? (cdr row))
                                  (test-plan-unique? (append (conformance-imported-test-names (car row)) (cdr row)))
                                  (andmap (lambda (name) (and (symbol? name) (string-suffix? "-test" (symbol->string name)))) (cdr row)))) source-rows))
        (error "invalid or overlapping source Suite declarations" source-rows))
      covered)))

(def (conformance-imported-test-names file)
  (call-with-input-file "t/conformance-main.ss"
    (lambda (port)
      (let loop ()
        (let (form (read port))
          (cond ((eof-object? form) (error "missing conformance imports" file))
                ((and (pair? form) (eq? (car form) 'import))
                 (let (row (find (lambda (row)
                                  (and (pair? row) (eq? (car row) 'only-in)
                                       (equal? (symbol->string (cadr row))
                                               (string-append ":gerbil-parser/" file)))) (cdr form)))
                   (unless row (error "missing conformance test import" file))
                   (cddr row)))
                (else (loop))))))))
(def (validate-test-export-coverage! expected actual)
  (let (less? (lambda (a b) (string<? (symbol->string a) (symbol->string b))))
    (unless (equal? (list-sort less? expected) (list-sort less? actual))
      (error "conformance imports omit or repeat exported test Suites" expected actual))))

(def (validate-test-suite-ownership! compiled source actual)
  (unless (and (test-plan-unique? (append compiled source))
               (test-plan-unique? actual))
    (error "overlapping or repeated test Suite ownership" compiled source actual))
  (validate-test-export-coverage! (append compiled source) actual)
  source)
(def (source-test-suite-selected? name compiled)
  (and (string-suffix? "-test" (symbol->string name)) (not (memq name compiled))))

(def (conformance-source-suites)
  (let (form (test-plan-definition "t/conformance-main.ss" 'source-suites))
    (unless (and (pair? form) (eq? (car form) 'quote) (list? (cadr form)))
      (error "expected literal source Suite declarations"))
    (cadr form)))
(def (conformance-source-suite-names module)
  (let (row (assoc module (conformance-source-suites)))
    (if row (cdr row) '())))
