;;; -*- Gerbil -*-
;;; Language-independent native admission. All calls belong to one runtime thread.
(import (only-in ./language-artifact-codec bind-native-language
                 native-parse-binary-payload native-descriptor-payload))
(export register-native-language! release-native-language!
        native-language-handle-descriptor native-language-handle-parse
        native-language-handle-owner! native-language-handle-count +native-source-byte-limit+)
(def +native-source-byte-limit+ 67108864)
(def +owner-thread+ #f)
(def +next-handle+ 0)
(def +languages+ (make-hash-table-eqv))
(def (native-language-handle-owner!)
  (unless +owner-thread+ (set! +owner-thread+ (current-thread)))
  (unless (eq? +owner-thread+ (current-thread))
    (error "native language handle requires its runtime owner thread")))
(def (native-language-handle-count)
  (native-language-handle-owner!)
  (hash-length +languages+))
(def (register-native-language! descriptor (contextual-product #f))
  (native-language-handle-owner!)
  (let (language (bind-native-language descriptor contextual-product))
    (when (>= +next-handle+ 18446744073709551615)
      (error "native language handle space exhausted"))
    (set! +next-handle+ (+ +next-handle+ 1))
    (hash-put! +languages+ +next-handle+ language)
    +next-handle+))
(def (release-native-language! handle)
  (native-language-handle-owner!)
  (hash-remove! +languages+ handle))
(def (admit-handle handle)
  (native-language-handle-owner!)
  (or (hash-get +languages+ handle)
      (error "unknown or released native language handle" handle)))
(def (native-language-handle-descriptor handle)
  (native-descriptor-payload (admit-handle handle)))
(def (native-language-handle-parse handle bytes)
  (let (language (admit-handle handle))
    (unless (and (u8vector? bytes)
                 (<= (u8vector-length bytes) +native-source-byte-limit+))
      (error "invalid or oversized native source bytes"))
    (let (source (utf8->string bytes))
      ;; Some decoders replace invalid sequences; never parse replacement text.
      (unless (equal? bytes (string->utf8 source))
        (error "native source is not canonical UTF-8"))
      (native-parse-binary-payload language source))))
