;;; Inert native metadata projection; ABI/schema stay v1.
(import (only-in :gerbil/core call-with-output-string))
(export native-datum-write)
(def (native-datum-write value)
  (call-with-output-string
   (lambda (port)
     (def (emit value depth)
       (when (> depth 64) (error "native datum depth bound"))
       (cond
        ((hash-table? value)
         (display "(object" port)
         (for-each
          (lambda (entry)
            (display " (" port)
            (write (car entry) port)
            (display " " port) (emit (cdr entry) (+ depth 1))
            (display ")" port))
          (list-sort (lambda (a b) (string<? (car a) (car b)))
                     (map (lambda (entry)
                            (cons (if (symbol? (car entry))
                                    (symbol->string (car entry)) (car entry))
                                  (cdr entry))) (hash->list value))))
         (display ")" port))
        ((or (list? value) (vector? value))
         (display "(list" port)
         (for-each (lambda (item) (display " " port) (emit item (+ depth 1)))
                   (if (vector? value) (vector->list value) value))
         (display ")" port))
        ((or (string? value) (boolean? value) (number? value)) (write value port))
        (else (error "unsupported native datum"))))
     (emit value 0))))
