;;; ParseArtifact binary layout and exact-buffer event publication.
(import (only-in ./schema +native-event-version+)
        (only-in :std/vector/u8vector little u8vector-u32-set! u8vector-u64-set!)
        (only-in :std/encoding/hex hex-decode)
        (only-in ../runtime/token token-kind token-start token-end)
        (only-in ./native-language-context native-language-syntax-kind-index
                 native-language-terminal-index native-language-field-index))
(export +binary-header-size+ +binary-event-size+ copy-digest! write-event! native-event-payload)

(def +binary-header-size+ 80)
(def +binary-event-size+ 24)

(def +event-tags+
  (hash (start-node 1)
        (finish-node 2)
        (start-field 3)
        (finish-field 4)
        (token 5)))

(def (required-index table symbol domain)
  (or (hash-get table symbol)
      (error "native ParseArtifact symbol is outside descriptor" domain symbol)))

(def (copy-digest! payload offset digest)
  (let (bytes (hex-decode digest 7))
    (unless (= (u8vector-length bytes) 32)
      (error "invalid ParseArtifact digest" digest))
    (subu8vector-move! bytes 0 32 payload offset)))

(def (write-event! language payload row event)
  (let* ((offset (+ +binary-header-size+ (* row +binary-event-size+)))
         (tag (vector-ref event 0)))
    (u8vector-u32-set! payload offset
                       (required-index +event-tags+ tag 'event-tag) little)
    (case tag
      ((start-node finish-node)
       (u8vector-u32-set!
        payload (+ offset 4)
        (required-index (native-language-syntax-kind-index language)
                        (vector-ref event 2) 'syntax-kind)
        little)
       (u8vector-u64-set! payload (+ offset 8) (vector-ref event 1) little)
       (let (position (vector-ref event 3))
         (u8vector-u32-set! payload (+ offset 16)
                            (if (eq? tag 'start-node) position 0) little)
         (u8vector-u32-set! payload (+ offset 20)
                            (if (eq? tag 'finish-node) position 0) little)))
      ((start-field finish-field)
       (u8vector-u32-set!
        payload (+ offset 4)
        (required-index (native-language-field-index language)
                        (vector-ref event 1) 'field)
        little)
       (let (position (vector-ref event 2))
         (u8vector-u32-set! payload (+ offset 16)
                            (if (eq? tag 'start-field) position 0) little)
         (u8vector-u32-set! payload (+ offset 20)
                            (if (eq? tag 'finish-field) position 0) little)))
      ((token)
       (u8vector-u32-set!
        payload (+ offset 4)
        (required-index (native-language-terminal-index language)
                        (vector-ref event 2) 'token-kind)
        little)
       (u8vector-u64-set! payload (+ offset 8) (vector-ref event 1) little)
       (u8vector-u32-set! payload (+ offset 16) (vector-ref event 4) little)
       (u8vector-u32-set! payload (+ offset 20) (vector-ref event 5) little)))))

;;; Validate/count without event objects, then publish one exact-sized buffer.
;;; Both passes consume the same immutable recognition/program representation.
;;; The thunk keeps binary allocation/catalog failures outside the parse catch.
(def (native-event-payload language grammar-digest source-digest walk)
  (let (count 0)
    (def (count-node _tag _id _kind _position) (set! count (+ count 1)))
    (def (count-field _tag _field _position) (set! count (+ count 1)))
    (def (count-token _id _token) (set! count (+ count 1)))
    (walk count-node count-field count-token)
    (lambda ()
      (let ((payload (make-u8vector (+ +binary-header-size+ (* count +binary-event-size+)) 0))
            (row 0))
        (def (emit-row! tag index id start end)
          (let (offset (+ +binary-header-size+ (* row +binary-event-size+)))
            (u8vector-u32-set! payload offset tag little)
            (u8vector-u32-set! payload (+ offset 4) index little)
            (u8vector-u64-set! payload (+ offset 8) id little)
            (u8vector-u32-set! payload (+ offset 16) start little)
            (u8vector-u32-set! payload (+ offset 20) end little)
            (set! row (+ row 1))))
        (def (emit-node! tag id kind position)
          (emit-row! (if (eq? tag 'start-node) 1 2)
                     (required-index (native-language-syntax-kind-index language) kind 'syntax-kind)
                     id (if (eq? tag 'start-node) position 0)
                     (if (eq? tag 'finish-node) position 0)))
        (def (emit-field! tag field position)
          (emit-row! (if (eq? tag 'start-field) 3 4)
                     (required-index (native-language-field-index language) field 'field)
                     0 (if (eq? tag 'start-field) position 0)
                     (if (eq? tag 'finish-field) position 0)))
        (def (emit-token! id token)
          (emit-row! 5 (required-index (native-language-terminal-index language)
                                      (token-kind token) 'token-kind)
                     id (token-start token) (token-end token)))
        (walk emit-node! emit-field! emit-token!)
        (unless (= row count) (error "native event count changed during publication"))
        (subu8vector-move! #u8(71 80 65 49) 0 4 payload 0)
        (u8vector-u32-set! payload 4 +native-event-version+ little)
        (u8vector-u32-set! payload 12 count little)
        (copy-digest! payload 16 grammar-digest)
        (subu8vector-move! source-digest 0 32 payload 48)
        payload))))

