;;; -*- Gerbil -*-
;;; Version-pinned TLA+ module syntax generated by the language-neutral engine.

(import :gerbil-parser/src/language/grammar)
(export +tla-plus-language-version+ +tla-plus-syntax-contract-v1+
        +tla-plus-grammar-oracle-version+ +tla-plus-grammar-oracle-commit+
        +tla-plus-examples-commit+ tla-plus-1-5-language-grammar
        tla-plus-1-5-grammar tla-plus-1-5-parser-ir tla-plus-1-5-parser)

(def +tla-plus-language-version+ "1.5.0")
(def +tla-plus-syntax-contract-v1+ "tla-plus.module-core.v1")
(def +tla-plus-grammar-oracle-version+ "tree-sitter-tlaplus-1.5.0")
(def +tla-plus-grammar-oracle-commit+ "8a8413f1d08e7ee40b347206d26eac4324db9fd9")
(def +tla-plus-examples-commit+ "ceeaa904140e3e03781cb2a79cd6c6d8b8b08e10")

(deflanguage-grammar tla-plus-1-5
  (identity "tla-plus" +tla-plus-language-version+ +tla-plus-syntax-contract-v1+)
  (syntax-kinds
   (SourceFile node (module)) (Module node (name item))
   (ExtendsDeclaration node (module)) (ConstantDeclaration node (name))
   (VariableDeclaration node (name))
   (OperatorDefinition node (name parameter body))
   (TheoremDeclaration node (body)) (Separator node ()) (EmptyLine node ())
   (ExpressionLine node (token)) (Identifier token (text))
   (Number token (text)) (String token (text))
   (HorizontalWhitespace token (text)) (Newline token (text))
   (Comment token (text)) (ModuleBorder token (text))
   (ModuleEnd token (text)) (SeparatorLine token (text))
   (Punctuation token (text)) (Unknown token (text)))
  (terminals
   (identifier Identifier) (number Number) (string String)
   (horizontal-whitespace HorizontalWhitespace) (newline Newline)
   (comment Comment) (module-border ModuleBorder) (module-end ModuleEnd)
   (separator-line SeparatorLine) (punctuation Punctuation) (unknown Unknown))
  (lexical-rules
   (horizontal-whitespace (horizontal-whitespace+)) (newline (newline+))
   (comment
    (choice (line-comment "\\*") (nested-block-comment "(*" "*)")))
   (string (quoted-string "\""))
   (module-end (literals "==============================================================" "===="))
   (separator-line (literals "--------------------------------------------------------------"))
   (module-border (literals "----------------------" "----"))
   (number (number)) (identifier (identifier))
   (punctuation
    (literals "<=>" "|->" "[]" "<>" "=>" "==" "/\\" "\\/"
              "\\notin" "\\in" ".." "<<" ">>" "<=" ">="
              "#" "=" "<" ">" "+" "-" "*" "/" "^" "'"
              "(" ")" "[" "]" "{" "}" "," ":" "!" "_" "."))
   (unknown (fallback)))
  (rules
   (source-file (alias SourceFile (field module (reference module))))
   (module
    (alias Module
      (seq (token module-border) (literal "MODULE")
           (field name (token identifier)) (token module-border) (token newline)
           (repeat (field item (reference module-item)))
           (token module-end) (optional (token newline)))))
   (module-item
    (choice (reference extends-declaration) (reference constant-declaration)
            (reference variable-declaration) (reference operator-definition)
            (reference theorem-declaration) (reference separator)
            (reference empty-line)))
   (extends-declaration
    (alias ExtendsDeclaration
      (seq (literal "EXTENDS") (field module (token identifier))
           (repeat (seq (literal ",") (field module (token identifier))))
           (token newline))))
   (constant-declaration
    (alias ConstantDeclaration
      (seq (choice (literal "CONSTANT") (literal "CONSTANTS"))
           (field name (token identifier))
           (repeat (seq (literal ",") (field name (token identifier))))
           (token newline))))
   (variable-declaration
    (alias VariableDeclaration
      (seq (choice (literal "VARIABLE") (literal "VARIABLES"))
           (field name (token identifier))
           (repeat (seq (literal ",") (field name (token identifier))))
           (token newline))))
   (operator-definition
    (alias OperatorDefinition
      (seq (field name (token identifier))
           (optional
            (seq (literal "(") (field parameter (token identifier))
                 (repeat (seq (literal ",") (field parameter (token identifier))))
                 (literal ")")))
           (literal "==") (field body (reference expression-line))
           (token newline))))
   (theorem-declaration
    (alias TheoremDeclaration
      (seq (literal "THEOREM") (field body (reference expression-line))
           (token newline))))
   (separator (alias Separator (seq (token separator-line) (token newline))))
   (empty-line (alias EmptyLine (token newline)))
   (expression-line
    (alias ExpressionLine (repeat1 (field token (reference expression-token)))))
   (expression-token
    (choice (token identifier) (token number) (token string)
            (token punctuation) (token unknown))))
  (extras horizontal-whitespace comment)
  (keywords (module "MODULE") (extends "EXTENDS") (constant "CONSTANT")
            (constants "CONSTANTS") (variable "VARIABLE")
            (variables "VARIABLES") (theorem "THEOREM"))
  (parser-entrypoints (source-file parse pure))
  (recoveries (module "GERBIL-PARSER-TLA-PLUS-1-5" preserve-source))
  (flow (source lexical) (lexical tla-plus-module) (tla-plus-module cst)))
