;;; Source qualification records one content identity around every real suite.
(import ./process ./products :std/crypto/digest :std/misc/ports)
(export #t)
(def performance-suites
 '(("lalr" . "t/lalr-fixed-point-benchmark-test.ss")
   ("incremental" . "t/incremental-suffix-benchmark-test.ss")
   ("recovery" . "t/recovery-frontier-benchmark-test.ss")
   ("glr" . "t/selective-glr-benchmark-test.ss")
   ("hot-path" . "t/benchmark-test.ss")
   ("gql" . "t/gql/runtime-benchmark-test.ss")
   ("opencypher" . "t/opencypher-large-query-benchmark-test.ss")
   ("languages" . "t/versioned-language-benchmark-test.ss")))
(def (source-identity)
 (let ((files '("gerbil.pkg" "justfile")) (digest (Digest::sha256)))
  (def (walk path)
   (when (file-exists? path)
    (if (eq? (file-type path) 'directory)
     (for-each (lambda (name) (unless (string-prefix? "." name) (walk (path-expand name path)))) (directory-files path))
     (set! files (cons path files)))))
  (for-each walk '("src" "languages" "t" "scripts" "tools"))
  (for-each (lambda (name) (when (equal? (path-extension name) ".ss") (set! files (cons name files)))) (directory-files "."))
  (for-each (lambda (path)
    (let* ((bytes (call-with-input-file path read-all-as-u8vector))
           (header (string->utf8 (string-append path (string #\nul) (number->string (u8vector-length bytes)) (string #\nul)))))
     (digest-update! digest header) (digest-update! digest bytes))) (list-sort string<? files))
  (digest-final! digest)))
(def (qualify-performance! selected budget logs continue?)
 (unless (and (> budget 0) (andmap (lambda (name) (assoc name performance-suites)) selected))
  (error "invalid source performance selection" selected budget))
 (let ((root (path-expand ".")) (identity (source-identity)) (failures '()))
  (with-product-directory "parser-source-"
   (lambda (directory)
    (create-symbolic-link root (path-expand "gerbil-parser" directory))
    (setenv "GERBIL_LOADPATH" directory)
    (setenv "GERBIL_PATH" (path-expand ".gerbil" root))
    (setenv "GAMBOPT" (string-append (getenv "GAMBOPT" "") ",max-heap=1G,debug=q"))
    (displayln "SOURCE ROOT " root) (displayln "SOURCE DIGEST " identity) (force-output)
    (let loop ((rest selected))
     (when (and (pair? rest) (or continue? (null? failures)))
      (let* ((name (car rest)) (suite (cdr (assoc name performance-suites)))
             (result (run-observed-process ["gerbil" "test" "-v" "5" suite]
                         (path-expand (string-append name ".log") logs) timeout: budget idle-timeout: 5))
             (text (utf8->string (process-result-output result))))
       (unless (equal? identity (source-identity)) (error "source changed during performance qualification" name))
       (unless (and (zero? (process-result-status result)) (not (process-result-reason result))
                    (andmap (lambda (pattern) (receipt-present? pattern text)) '("^CASE-OK " "^MODULE-OK " "^HARNESS-OK " "^OK$")))
        (set! failures (cons name failures)))
       (loop (cdr rest)))))))
  (unless (null? failures) (error "source performance qualification failed" failures))
  (displayln (if (and (= (length selected) (length performance-suites))
                     (andmap (lambda (row) (member (car row) selected)) performance-suites))
                 "PERFORMANCE-SOURCE-OK " "PERFORMANCE-SOURCE-SUBSET-OK ") (string-join selected ",")) (force-output)))
