;;; Source command grammar elaborates to the admitted command core.
;;; FIRST and continuations are local to calls, never a global guessed stop set.
(import (only-in :std/list/list delete-duplicates/hash))
(export lower-command-grammar command-grammar-entrypoints)
;;; Entry positions are semantic capabilities, independent of private rule names.
(def (command-grammar-entrypoints rules (diagnose #f))
  (filter-map (lambda (row)
    (let (expression (cadr row))
      (and (pair? expression) (eq? (car expression) 'at)
           (begin
             (unless (and (= (length expression) 3)
                          (memq (cadr expression) '(assignment-tail pipeline-head)))
               (if diagnose (diagnose "unknown command entry position" expression) (error "unknown command entry position" expression)))
             (list (cadr expression) (car row)))))) rules))
(def (lower-command-grammar rules (diagnose #f))
  (def (fail message value)
    (if diagnose (diagnose message value) (error message value)))
  (def (unique values) (delete-duplicates/hash values))
  (unless (and (list? rules) (pair? rules)
               (andmap (lambda (row) (and (list? row) (= (length row) 2) (symbol? (car row)))) rules)
               (= (length rules) (length (unique (map car rules)))))
    (fail "source grammar requires distinct named command rules" rules))
  (def entries (command-grammar-entrypoints rules fail))
  (unless (= (length entries) (length (unique (map car entries))))
    (fail "duplicate command entry position" entries))
  (set! rules (map (lambda (row)
    (let (expression (cadr row))
      (list (car row) (if (and (pair? expression) (eq? (car expression) 'at))
                        (caddr expression) expression)))) rules))
  (def (arity expression n)
    (unless (= (length expression) n) (fail "invalid source grammar constructor arity" expression)))
  (def (union triggers)
    (def (flatten trigger)
      (if (and trigger (eq? (car trigger) 'or)) (apply append (map flatten (cdr trigger)))
          (if trigger (list trigger) '())))
    (let* ((items (unique (apply append (map flatten triggers))))
           (groups '()))
      (for-each (lambda (item)
        (let (prior (find (lambda (row) (and (eq? (car row) (car item)) (memq (car row) '(word operator)))) groups))
          (if prior
            (set-cdr! prior (if (or (null? (cdr prior)) (null? (cdr item))) '() (unique (append (cdr prior) (cdr item)))))
            (set! groups (append groups (list (map values item))))))) items)
      (cond ((null? groups) #f) ((null? (cdr groups)) (car groups)) (else (cons 'or groups)))))
  (def (nullable? expression)
    (and (pair? expression)
         (case (car expression)
           ((optional repeat) #t)
           ((seq) (andmap nullable? (cdr expression)))
           ((choice) (ormap nullable? (cdr expression)))
           ((field) (nullable? (caddr expression))) (else #f))))
  (def (sequence expression)
    (if (and (pair? expression) (eq? (car expression) 'seq)) (cdr expression) (list expression)))
  (def (first-sequence body seen)
    (if (null? body) #f
      (union (list (first (car body) seen)
                   (and (nullable? (car body)) (first-sequence (cdr body) seen))))))
  (def (first expression (seen '()))
    (cond ((string? expression) (list 'word expression))
          ((symbol? expression)
           (case expression
             ((word command command-list) '(word))
             (else (fail "unresolved source grammar reference" expression))))
          ((not (and (list? expression) (pair? expression))) (fail "invalid source grammar expression" expression))
          (else
           (case (car expression)
             ((word operator role newline) expression)
             ((adjacent) expression)
             ((field) (arity expression 3) (first (caddr expression) seen))
             ((node) (first-sequence (cddr expression) seen))
             ((seq) (first-sequence (cdr expression) seen))
             ((choice) (union (map (lambda (child) (first child seen)) (cdr expression))))
             ((optional repeat empty-allowed) (arity expression 2) (first (cadr expression) seen))
             ((balanced) (arity expression 4) (first (cadr expression) seen))
             ((reference)
              (arity expression 2)
              (let* ((name (cadr expression)) (rule (assq name rules)))
                (unless rule (fail "unresolved source grammar reference" expression))
                (when (memq name seen) (fail "source grammar FIRST cycle" name))
                (first (cadr rule) (cons name seen))))
             (else (fail "unknown source grammar constructor" expression))))))
  (def (overlap? left right)
    (and left right
      (cond ((eq? (car left) 'or) (ormap (lambda (child) (overlap? child right)) (cdr left)))
            ((eq? (car right) 'or) (overlap? right left))
            ((and (eq? (car left) (car right)) (memq (car left) '(word operator)))
             (or (null? (cdr left)) (null? (cdr right))
                 (ormap (lambda (value) (member value (cdr right))) (cdr left))))
            ((eq? (car left) 'role) #t)
            ((eq? (car right) 'role) #t)
            (else (equal? left right)))))
  (def (continuation rest follow)
    (union (list (first-sequence rest '()) (and (andmap nullable? rest) follow))))
  (def (lower-body body follow)
    (if (null? body) '()
      (append (lower (car body) (continuation (cdr body) follow))
              (lower-body (cdr body) follow))))
  (def (lower-field field expression follow)
    (unless (symbol? field) (fail "source field requires an identifier" field))
    (cond
      ((string? expression) (list (list 'take field (list 'word expression))))
      ((symbol? expression)
       (case expression
         ((word command) (list (list expression field)))
         ((command-list)
          (unless follow (fail "command-list requires an explicit continuation" expression))
          (list (list 'list field follow #f)))
         (else (fail "unresolved source grammar reference" expression))))
      ((not (and (list? expression) (pair? expression))) (fail "invalid source field expression" expression))
      (else
       (case (car expression)
         ((word operator role newline)
          (if (and (memq (car expression) '(word operator role newline))
                   (null? (cdr expression)))
            (list (list 'raw field))
            (list (list 'take field expression))))
         ((reference) (arity expression 2) (first expression) (list (list 'call field (cadr expression))))
         ((empty-allowed)
          (arity expression 2)
          (unless (and (eq? (cadr expression) 'command-list) follow)
            (fail "empty-allowed requires a command-list with a continuation" expression))
          (list (list 'list field follow #t)))
         ((node) (list (append (list 'node field (cadr expression)) (lower-body (cddr expression) follow))))
         ((adjacent) (apply append (map (lambda (item) (lower-field field item follow)) (cdr expression))))
         (else (fail "unsupported source field expression" expression))))))
  (def (lower expression follow)
    (unless (and (list? expression) (pair? expression))
      (fail "command grammar requires field-labelled expressions" expression))
    (case (car expression)
      ((field) (arity expression 3) (lower-field (cadr expression) (caddr expression) follow))
      ((seq) (lower-body (cdr expression) follow))
      ((node) (append (list (list 'as (cadr expression))) (lower-body (cddr expression) follow)))
      ((optional repeat)
       (arity expression 2)
       (let* ((child (cadr expression)) (trigger (first child)))
         (unless (and trigger (not (nullable? child)))
           (fail "source repetition/optional body must consume input" expression))
         (if (eq? (car expression) 'optional)
           (list (cons 'optional (cons trigger (lower child follow))))
           (let (stops? (overlap? trigger follow))
             (list (cons (if stops? 'until 'many)
                         (cons (if stops? follow trigger) (lower child (if stops? follow (union (list trigger follow)))))))))))
      ((choice)
       (unless (pair? (cdr expression)) (fail "source choice requires alternatives" expression))
       (let (alternatives (cdr expression))
         (when (ormap nullable? alternatives) (fail "source choice requires consuming alternatives" expression))
         (if (and (= (length alternatives) 2) (pair? (car alternatives)) (eq? (caar alternatives) 'node))
           (list (list 'branch (first (car alternatives))
                       (lower (car alternatives) follow) (lower (cadr alternatives) follow)))
           (list (cons 'choose (map (lambda (child) (cons (first child) (lower child follow))) alternatives))))))
      ((balanced)
       (arity expression 4)
       (let ((open (cadr expression)) (close (caddr expression)) (body (cadddr expression)))
         (unless (and (pair? open) (eq? (car open) 'field) (pair? close) (eq? (car close) 'field)
                      (pair? (caddr open)) (eq? (caaddr open) 'adjacent)
                      (pair? (caddr close)) (eq? (caaddr close) 'adjacent))
           (fail "balanced grammar requires field-labelled adjacent delimiters" expression))
         (let ((opens (cdaddr open)) (closes (cdaddr close)))
           (unless (and (pair? opens) (= (length opens) (length closes))
                        (andmap (lambda (item) (equal? item (car opens))) opens)
                        (andmap (lambda (item) (equal? item (car closes))) closes))
             (fail "balanced grammar requires repeated matching delimiter tokens" expression))
           (append (lower open follow)
                   (list (append (list 'balance (car opens) (car closes) (length opens) (cadr open) (cadr close))
                                 (lower body follow)))))))
      (else (fail "unknown source grammar constructor" expression))))
  (map (lambda (row)
    (let* ((name (car row)) (expression (cadr row)))
      (when (getenv "GERBIL_PARSER_SOURCE_TRACE" #f)
        (displayln "SOURCE-COMMAND-LOWER " name) (force-output))
      (unless (and (list? expression) (>= (length expression) 3) (eq? (car expression) 'node))
        (fail "command rule requires a node constructor" row))
      (let* ((kind (cadr expression)) (body (cddr expression))
             ;; Infer a token prefix up to the first contextual operation.
             (prefix (let loop ((remaining body) (result '()))
               (if (null? remaining) (reverse result)
                 (let* ((item (car remaining))
                        (leaf (and (pair? item) (eq? (car item) 'field)
                                   (begin (arity item 3) (caddr item))))
                        (selector (and leaf
                          (cond ((string? leaf) (list 'word leaf))
                                ((eq? leaf 'word) '(word))
                                ((and (pair? leaf) (memq (car leaf) '(word operator))) leaf)
                                (else #f)))))
                   (if selector (loop (cdr remaining) (cons selector result)) (reverse result))))))
             (position (find (lambda (entry) (eq? (cadr entry) name)) entries))
             (trigger (cond
                        (position (if (eq? (car position) 'assignment-tail)
                                    (list 'manual (first-sequence body '())) '(manual)))
                        ((> (length prefix) 1) (cons 'lookahead prefix))
                        (else (first-sequence body '()))))
             (_prefix (unless trigger (fail "source entry requires a token prefix" expression)))
             ;; Numeric encoding of (specific head, prefix width), never a field
             ;; or rule-name policy. Prefix length is bounded by admission.
             (head (if (memq (car trigger) '(lookahead adjacent)) (cadr trigger) trigger))
             (width (if (memq (car trigger) '(lookahead adjacent)) (length (cdr trigger)) 1))
             (rank (if position 0 (+ (if (and (memq (car head) '(word operator)) (pair? (cdr head))) 33 0) width))))
        (append (list name trigger rank kind) (lower-body body #f))))) rules))
