;;; Common source-library frontend. Language packages declare intent, not plans.
(import (only-in :clan/poo/object .o)
        (only-in :std/list/list delete-duplicates/hash)
        (only-in ./command-grammar lower-command-grammar)
        (only-in ../src/language/command-profile CommandProfile. command-node-schemas)
        (only-in ../src/language/part-profile BindingProfile. PartProfile.)
        (only-in ../src/language/result-profile ResultProfile.)
        (only-in ../src/language/scanner-profile ScannerProfile.)
        (only-in ../src/runtime/region-scanner prepare-region-plan region-plan-specification)
        (only-in ../src/runtime/source-engines ShellSourceStrategy.))
(export compile-shell-grammar)
(def (trace step)
  (when (getenv "GERBIL_PARSER_SOURCE_TRACE" #f)
    (displayln "SOURCE-LOWER " step) (force-output)))
(def (compile-shell-grammar declaration)

  (trace "declaration")
  (let ()
    (def (distinct? values) (= (length values) (length (delete-duplicates/hash values))))
    (def (section key)
      (let (row (assq key declaration))
        (unless row (error "missing shell grammar section" key)) (cdr row)))
    (unless (and (list? declaration)
                 (andmap (lambda (row) (and (list? row) (pair? row) (memq (car row) '(operators regions bindings words commands)))) declaration)
                 (= (length declaration) 5) (distinct? (map car declaration)))
      (error "shell grammar requires operators, regions, bindings, words and commands exactly once"))
    (let* ((operators (section 'operators)) (region-rows (section 'regions))
           (binding-rows (section 'bindings)) (word-rows (section 'words))
           (command-rows (section 'commands)))
      (unless (and (pair? operators) (distinct? operators)
                   (andmap (lambda (value) (and (string? value) (> (string-length value) 0))) operators))
        (error "shell operators must be distinct nonempty strings"))
      (unless (and (list? region-rows)
                   (andmap (lambda (row) (and (list? row) (>= (length row) 5)
                                              (memq (car row) '(quote pair)) (symbol? (cadr row)) (symbol? (caddr row))
                                              (string? (cadddr row)) (> (string-length (cadddr row)) 0))) region-rows)
                   (distinct? (map cadr region-rows)))
        (error "shell regions require distinct names and semantic delimiters"))
      (def (region name)
        (or (find (lambda (row) (eq? (cadr row) name)) region-rows) (error "unknown shell region" name)))
      (def (opening row) (cadddr row))
      (def (closing row)
        (if (eq? (car row) 'quote)
          (string (string-ref (opening row) (- (string-length (opening row)) 1)))
          (list-ref row 4)))
      (for-each (lambda (row)
        (if (eq? (car row) 'quote)
          (unless (memq (list-ref row 4) '(opaque escaped)) (error "unknown quote policy" row))
          (unless (and (= (length row) 5) (string? (closing row)) (> (string-length (closing row)) 0)
                       (andmap (lambda (ch) (char=? ch (string-ref (closing row) 0))) (string->list (closing row))))
            (error "pair closing delimiter must repeat one character" row)))) region-rows)
      (let* ((quotes (foldl (lambda (row result)
                       (if (eq? (car row) 'quote)
                         (let (quote-row (list (string-ref (closing row) 0)
                                              (eq? (list-ref row 4) 'escaped) (list-tail row 5)))
                           (let (prior (assv (car quote-row) result))
                             (when (and prior (not (equal? prior quote-row))) (error "conflicting quote region" row))
                             (if prior result (append result (list quote-row))))) result)) '() region-rows))
             (pairs (filter-map (lambda (row)
                      (and (eq? (car row) 'pair)
                           (list (opening row) (string-ref (opening row) (- (string-length (opening row)) 1))
                                 (string-ref (closing row) 0) (string-length (closing row))))) region-rows))
             (region-plan-value (prepare-region-plan (list operators quotes pairs #t)))
             (binding-profile-values
              (map (lambda (row)
                (unless (and (list? row) (= (length row) 5) (symbol? (car row)))
                  (error "binding requires name, prefixes, operators and subscript semantics" row))
                (cons (car row) (.o (:: self BindingProfile.) name: (cadr row)
                                     prefixes: (caddr row) operators: (cadddr row) subscript: (list-ref row 4)))) binding-rows)))
        (trace "regions-and-bindings")
        (unless (and (distinct? (map car binding-profile-values))
                     (equal? (map car binding-profile-values) '(simple parameter assignment)))
          (error "shell grammar requires simple, parameter and assignment binding semantics"))
        (def (part row)
          (unless (and (list? row) (= (length row) 2) (list? (car row)) (pair? (car row))
                       (distinct? (car row)) (andmap symbol? (car row)) (list? (cadr row)) (pair? (cadr row)))
            (error "word grammar requires contexts and a semantic constructor" row))
          (let* ((form (cadr row)) (op (car form)))
            (case op
              ((quoted substitution parameter)
               (unless (= (length form) 2) (error "invalid word region reference" form))
               (let* ((r (region (cadr form))) (prefix (opening r)) (kind (caddr r))
                      (action (case op
                                ((quoted)
                                 (unless (eq? (car r) 'quote) (error "quoted word requires a quote region" form))
                                 (list 'quote kind (string-length prefix) 1 (string-ref (closing r) 0)))
                                ((substitution)
                                 (if (eq? (car r) 'quote)
                                   (list 'quoted-body kind (string-length prefix) 1 (string-ref (closing r) 0))
                                   (list 'pair kind (string-length prefix) (string-length (closing r)))))
                                (else
                                 (unless (and (eq? kind 'ParameterExpansion) (equal? prefix "${") (equal? (closing r) "}"))
                                   (error "parameter word requires the admitted parameter delimiters" form)) '(parameter)))))
                 (list (car row) (list 'prefix prefix 'any) action)))
              ((name)
               (unless (and (= (length form) 4) (string? (caddr form))) (error "invalid name word" form))
               (list (car row) (list 'prefix (caddr form) 'next) (list 'name (cadr form) (cadddr form))))
              ((escape)
               (unless (and (= (length form) 3) (or (eq? (caddr form) 'any) (string? (caddr form))))
                 (error "invalid escape word" form))
               (list (car row) (list 'prefix "\\" (caddr form)) (list 'escape (cadr form))))
              (else (error "unknown word grammar constructor" form)))))
        (let* ((part-rules (map part word-rows))
               (context-values (append '(word) (filter (lambda (kind) (not (eq? kind 'CommandSubstitution)))
                                             (delete-duplicates/hash (filter-map (lambda (row) (and (eq? (car row) 'quote) (caddr row))) region-rows))) '(HereDocument)))
               (part-profile-value (.o (:: self PartProfile.) contexts: context-values bindings: binding-profile-values rules: part-rules literal: 'LiteralPart))
               (region-spec (region-plan-specification region-plan-value))
               (word-matcher (list 'region-word (append (take region-spec 3) '(#t))))
               (scanner-profile-value (.o (:: self ScannerProfile.) modes: '(command marker body) initial-mode: 'command
                 tokens: '(horizontal-whitespace newline line-continuation comment word operator heredoc-marker heredoc-content heredoc-end)
                 rules: (list
                  '(space command horizontal-whitespace (horizontal-whitespace+) 0 keep)
                  '(newline command newline (literal "\n") 0 (activate-next body))
                  '(continuation command line-continuation (literal "\\\n") 10 keep)
                  '(comment command comment (line-prefix "#" "\n") 0 keep)
                  '(strip command operator (literal "<<-") 30 (expect-marker-in #t marker))
                  '(plain command operator (literal "<<") 30 (expect-marker-in #f marker))
                  (list 'operator 'command 'operator (list 'literals (filter (lambda (op) (not (member op '("<<" "<<-")))) operators)) 0 'keep)
                  (list 'word 'command 'word (list 'unless-prefix '(" " "\t" "\n" "#" "\\\n" ";" "&" "|" "(" ")" "<" ">") '("<(" ">(") word-matcher) 0 'keep)
                  '(marker-space marker horizontal-whitespace (horizontal-whitespace+) 0 keep)
                  '(marker-continuation marker line-continuation (literal "\\\n") 10 keep)
                  '(marker-newline marker newline (literal "\n") 10 (activate-next body))
                  (list 'marker-word 'marker 'heredoc-marker (list 'unless-prefix '(" " "\t" "\n" "\\\n") '() word-matcher) 0 '(enqueue-marker-in shell-quote-removal command))
                  '(end body heredoc-end (marker-line-at "\n") 10 (finish-marker command body))
                  '(body body heredoc-content (body-line-at "\n") 0 keep))))
               (projection-rows '()))
          (trace "scanner-and-parts")
          ;; Capture signatures are properties of the source executor operations.
          ;; The frontend derives programs; authors do not allocate capture frames.
          (def (projection id fields)
            (append (list id id (map (lambda (field) (list (car field) (cadr field))) fields))
              (map (lambda (field)
                (case (cadr field)
                  ((span) (list 'token (caddr field) (cadddr field) (car field) (list-ref field 4)))
                  ((node) (list 'one (caddr field) (car field) (cadddr field)))
                  ((parts) (list 'many (caddr field) (car field))))) fields)))
          (def (add! id fields)
            (let (row (projection id fields))
              (let (prior (assq id projection-rows))
                (when (and prior (not (equal? prior row))) (error "conflicting word result kind" id))
                (unless prior (set! projection-rows (append projection-rows (list row)))))))
          (add! 'LiteralPart '((text span text LiteralPart required)))
          (for-each (lambda (op)
            (for-each (lambda (row)
              (let (form (caddr row))
                (when (eq? (car form) op)
                  (let (kind (cadr form)) (add! kind (list (list 'text 'span 'text kind 'required))))))) part-rules)) '(escape name))
          (add! 'Word '((parts parts part))) (add! 'HereDocumentLine '((parts parts part)))
          (for-each (lambda (r)
            (when (and (eq? (car r) 'quote) (not (eq? (caddr r) 'CommandSubstitution)))
              (add! (caddr r) '((open span open quote-open required) (parts parts part) (close span close quote-close required))))) region-rows)
          (for-each (lambda (row)
            (let (form (caddr row))
              (when (memq (car form) '(pair quoted-body))
                (add! (cadr form) '((open span open substitution-open required) (body span body substitution-body optional) (close span close substitution-close required)))))) part-rules)
          (add! 'ArraySubscript '((open span open subscript-open required) (parts parts index) (close span close subscript-close required)))
          (add! 'ParameterExpansion '((open span open parameter-open required) (prefix span prefix parameter-prefix optional)
            (name span name parameter-name optional) (subscript node subscript optional) (operator span operator parameter-operator optional)
            (parts parts operand) (close span close parameter-close required)))
          (add! 'Assignment '((name span name assignment-name required) (operator span operator assignment-operator required) (parts parts value)))
          (unless (and (= (length command-rows) 3)
                       (equal? (map car command-rows) '(roles descriptor rules)))
            (error "commands require roles, descriptor and rules exactly once"))
          (trace "result-projections")
          (let* ((result-profile-value (.o (:: self ResultProfile.) scanner: scanner-profile-value nodes: (command-node-schemas)
                              tokens: '(unparsed-source) projections: projection-rows))
                 (command-profile-value (.o (:: self CommandProfile.) roles: (cdar command-rows)
                              texts: (list (cons 'descriptor (cdadr command-rows)))
                              forms: (lower-command-grammar (cdr (assq 'rules command-rows))))))
            (trace "command-plans")
            (.o (:: self ShellSourceStrategy.) regions: region-plan-value scanner: scanner-profile-value parts: part-profile-value results: result-profile-value commands: command-profile-value)))))))
