(import :std/encoding/json :std/io/tempfile :std/misc/ports)
(load "tools/ci/bootstrap.ss")
(let (metadata (string->json "{\"schema\":\"gerbil-bazel.toolchain-release.v1\",\"upstreamRevision\":\"2591dcd9b7c6d2c4e9dd8611a17c5b1a5d82bbdb\",\"platform\":{\"os\":\"darwin\",\"arch\":\"aarch64\"}}" (JSONReadOptions object-as-hash: #t)))
 (admit-release! metadata "darwin" "aarch64")
 (unless (with-catch (lambda (_) #t) (lambda () (admit-release! metadata "linux" "x86_64") #f)) (error "platform mismatch admitted")))
(displayln "BOOTSTRAP-SCHEMA-CONTROLS-OK")
(let (file (make-temporary-file-name "parser-bootstrap-env-"))
 (try
  (append-lines! file '("FIRST=one" "SECOND=two"))
  (append-lines! file '("THIRD=three"))
  (unless (equal? (call-with-input-file file read-all-as-string) "FIRST=one\nSECOND=two\nTHIRD=three\n")
   (error "GitHub environment publication changed bytes"))
  (finally (when (file-exists? file) (delete-file file)))))
(displayln "BOOTSTRAP-ENVIRONMENT-CONTROL-OK")
(exit 0)
