;;; Host archive extraction precedes Scheme; activation and release admission do not.
(import :std/encoding/json :std/string/misc :std/misc/process :std/misc/ports)
(export main admit-release! append-lines!)
(def (admit-release! metadata os arch)
 (unless (and (equal? (hash-ref metadata "schema" #f) "gerbil-bazel.toolchain-release.v1")
              (equal? (hash-ref metadata "upstreamRevision" #f) "2591dcd9b7c6d2c4e9dd8611a17c5b1a5d82bbdb")
              (let (platform (hash-ref metadata "platform" #f))
               (and (hash-table? platform) (equal? (hash-ref platform "os" #f) os)
                    (equal? (hash-ref platform "arch" #f) arch))))
  (error "immutable Gerbil release identity mismatch" os arch)))
(def (append-lines! file lines)
 (let (port (open-output-file [path: file append: #t]))
  (try (for-each (lambda (line) (display line port) (newline port)) lines) (finally (close-port port)))))
(def (main root os arch)
 (let* ((prefix (path-expand root)) (home (path-expand "current" prefix))
        (options (string-append "~~=" home ",~~bin=" (path-expand "bin" home) ",~~lib=" (path-expand "lib" home)))
        (cores (string-trim (run-process (if (equal? os "darwin") '("sysctl" "-n" "hw.ncpu") '("getconf" "_NPROCESSORS_ONLN"))))))
  (admit-release! (string->json (call-with-input-file (path-expand "gerbil-toolchain-release.json" prefix) read-all-as-string) (JSONReadOptions object-as-hash: #t)) os arch)
  (unless (and (string->number cores) (> (string->number cores) 0)) (error "invalid native build capacity" cores))
  (setenv "GERBIL_PREFIX" prefix) (setenv "GERBIL_HOME" home) (setenv "GAMBOPT" options)
  (setenv "PATH" (string-append (path-expand "bin" prefix) ":" (getenv "PATH")))
  (append-lines! (getenv "GITHUB_PATH") [(path-expand "bin" prefix)])
  (append-lines! (getenv "GITHUB_ENV") [(string-append "GERBIL_PREFIX=" prefix) (string-append "GERBIL_HOME=" home)
                                      (string-append "GAMBOPT=" options) (string-append "GERBIL_BUILD_CORES=" cores)])
  (run-process/batch [(path-expand "bin/gerbil" prefix) "--version"])
  (run-process/batch [(path-expand "bin/gerbil" prefix) "interactive" "-e" "(displayln \"gerbil-ready\") (exit 0)"])
  (displayln "GERBIL-RELEASE-BOOTSTRAP-OK cores=" cores) (force-output))
 (exit 0))
